// Shared browser/static positioning. Geographic reach is confirmed per shipment.
export const positioning = {
 en: {homeTitle:'China Sourcing & International Freight Forwarding | DDNZ Global',homeHeading:'Source in China. Connect every step to international freight.',homeDescription:'Source products, inspect supplier orders and consolidate cargo in China with DDNZ. Heaven Born handles international freight within the agreed shipment scope.',insightsTitle:'China Sourcing & Shipping Guides | DDNZ Global',insightsHeading:'China sourcing and shipping guides for importers.',insightsDescription:'Compare products and supplier quotations, plan order costs, and review packing and shipping decisions before importing from China.'},
 zh: {homeTitle:'中国采购与国际货运代理 | DDNZ Global',homeHeading:'中国采购与国际货运，从需求到出运衔接。',homeDescription:'DDNZ 协调中国产品采购、供应商验货和集货；华正邦泰按确认的运输范围执行国际货运。',insightsTitle:'中国采购与国际运输指南 | DDNZ Global',insightsHeading:'面向进口商的中国采购与运输指南。',insightsDescription:'比较产品与供应商报价，规划订单成本，在从中国进口前核对包装与运输安排。'},
 es: {homeTitle:'Compras en China y transporte internacional | DDNZ Global',homeHeading:'Compre en China. Conecte cada paso con el transporte internacional.',homeDescription:'DDNZ coordina compras, inspección de proveedores y consolidación en China. Heaven Born ejecuta el transporte internacional dentro del alcance acordado.',insightsTitle:'Guías de compras y envíos desde China | DDNZ Global',insightsHeading:'Guías de compras y envíos desde China para importadores.',insightsDescription:'Compare productos y ofertas, planifique costes y revise embalaje y transporte antes de importar desde China.'},
 ar: {homeTitle:'التوريد من الصين والشحن الدولي | DDNZ Global',homeHeading:'توريد من الصين. اربط كل خطوة بالشحن الدولي.',homeDescription:'تنسق DDNZ شراء المنتجات وفحص طلبات الموردين وتجميع البضائع في الصين. تتولى Heaven Born الشحن الدولي ضمن النطاق المتفق عليه.',insightsTitle:'أدلة التوريد والشحن من الصين | DDNZ Global',insightsHeading:'أدلة التوريد والشحن من الصين للمستوردين.',insightsDescription:'قارن المنتجات وعروض الموردين وخطط تكاليف الطلب وراجع التغليف والشحن قبل الاستيراد من الصين.'},
 fr: {homeTitle:'Sourcing en Chine et fret international | DDNZ Global',homeHeading:'Sourcer en Chine. Relier chaque étape au fret international.',homeDescription:'DDNZ coordonne achats, inspection des commandes et consolidation en Chine. Heaven Born exécute le fret international selon le périmètre convenu.',insightsTitle:'Guides sourcing et transport depuis la Chine | DDNZ Global',insightsHeading:'Guides sourcing et transport de Chine pour importateurs.',insightsDescription:'Comparez produits et offres fournisseurs, préparez les coûts et vérifiez emballage et transport avant d’importer de Chine.'},
 ru: {homeTitle:'Закупки в Китае и международные перевозки | DDNZ Global',homeHeading:'Закупки в Китае. Связь каждого этапа с международной перевозкой.',homeDescription:'DDNZ координирует закупки, инспекции и консолидацию в Китае. Heaven Born выполняет международную перевозку в согласованных пределах.',insightsTitle:'Руководства по закупкам и доставке из Китая | DDNZ Global',insightsHeading:'Закупки и доставка из Китая: руководства для импортеров.',insightsDescription:'Сравнивайте товары и предложения, планируйте затраты и проверяйте упаковку и перевозку до импорта из Китая.'},
 pt: {homeTitle:'Compras na China e frete internacional | DDNZ Global',homeHeading:'Compras na China e frete internacional para sua importação.',homeDescription:'A DDNZ coordena compras, inspeções e consolidação na China. A Heaven Born executa o frete internacional no escopo acordado.',insightsTitle:'Guias de compras e transporte da China | DDNZ Global',insightsHeading:'Guias de compras e transporte da China para importadores.',insightsDescription:'Compare produtos e propostas, planeje custos e confira embalagem e transporte antes de importar da China.'},
 tr: {homeTitle:'Çin’den tedarik ve uluslararası taşımacılık | DDNZ Global',homeHeading:'Çin’den tedarik edin. Her adımı uluslararası taşımaya bağlayın.',homeDescription:'DDNZ Çin’de satın alma, denetim ve konsolidasyonu koordine eder. Heaven Born, uluslararası taşımayı kararlaştırılan kapsamda yürütür.',insightsTitle:'Çin’den tedarik ve nakliye rehberleri | DDNZ Global',insightsHeading:'İthalatçılar için Çin’den tedarik ve nakliye rehberleri.',insightsDescription:'Çin’den ithalat öncesinde ürün ve teklifleri karşılaştırın, maliyetleri planlayın, ambalaj ve nakliye kararlarını inceleyin.'},
};
