import { additionalStartupRoutes, additionalStartupCopy } from './startup-extra.mjs';
// Practical buying plans, not promises of the lowest market price or guaranteed profit.
export const startupRoutes = [
 ['/sourcing/restaurant-project-equipment/', 'restaurant-startup'],
 ['/sourcing/restaurant-project-equipment/', 'kitchen-budget'],
 ['/screen-protectors/wholesale-for-stores/', 'retail-privacy'],
 ['/sourcing/mobile-accessories-from-china/', 'accessory-startup'],
];
export const startupCopy = {
 en: {heading:'Plan your first order around the business you want to start',cta:'Prepare a buying brief',items:[
  ['Low-budget restaurant startup: essential equipment from China','Build the first equipment list around a short opening menu, expected portions per service and the space available. A lower starting budget begins with a smaller, workable scope.', ['Start with the cooking, safe cold storage, preparation and washing functions your menu needs. Match capacity and utilities before selecting models.','Separate opening-day essentials from equipment for later menu expansion. Share functions only where capacity, cleaning and food separation allow.','Send the menu, site dimensions, utility details, destination and equipment budget. Compare a basic configuration with an expansion list.'], 'Can I start a small takeaway or cloud kitchen with fewer machines?','Request a menu-based equipment review. Fewer machines can reduce the initial order only if they still meet production and site requirements; refrigeration, ventilation and local installation needs must be checked.','Compare takeaway and cloud-kitchen packages'],
  ['What is the cheapest workable commercial kitchen equipment package?','Compare equipment from China on the same menu, capacity, configuration and delivery scope. The lowest unit price is not necessarily the lowest opening cost.', ['Basic plan: equipment required for the opening menu. Expansion plan: extra capacity or additional menu items, quoted separately.','List goods, packing, sourcing or inspection, freight and destination costs separately. Check site works, utilities and installation outside the equipment quotation.','Compare electrical requirements, cleaning access, spare parts and packing before choosing a lower-priced model. Do not reduce required safety or site provisions to meet a target price.'], 'Can you quote an affordable kitchen package against my budget?','Send your budget currency and state whether it covers equipment only or delivery and installation too. We can request comparable configurations; no global lowest-price or fixed opening-cost promise is implied.','Compare commercial kitchen equipment'],
  ['Privacy screen protector sourcing from China for retailers','Choose a supplier and protector configuration around the phones your shop serves, your installation method and the first-order cash commitment.', ['Select exact phone models and quantities. Compare privacy glass, front-view clarity, touch response, fit and case compatibility on samples.','Compare loose or retail-packed protectors with installation kits. Confirm cleaning accessories, package contents and the cost of replacement stock.','Current OG28 terms: at least 1,000 pieces per order and 100 per phone model. 001 and Titan references require at least 500 per phone model; confirm current availability and terms before ordering.'], 'Which privacy screen protector supplier suits a new phone shop?','Evaluate samples, model coverage, minimums, packaging and replenishment consistency together. A lower unit price can require more starting inventory. Request a review of the listed options against your model list and budget.','Compare privacy protectors and minimum orders'],
  ['Starting a phone accessories business: a first-order plan from China','Build a focused starter assortment of phone cases, straps and screen protectors for your sales channel. This is a purchasing plan, not a fixed-price business kit.', ['Choose your channel: a phone shop, repair counter or online store. Start with phone models and products relevant to that channel rather than a broad untested assortment.','Separate samples, stock products and custom packaging. Limit colours and styles first; suppliers must confirm minimums for every order line.','Budget for goods, samples, packing, inspection if requested, freight and destination costs. Retain working capital for replenishment rather than allocating everything to the first order.'], 'Can I combine phone cases, straps and privacy protectors in a small starter order?','Submit one mixed-product brief with quantities and destination. Minimums still apply by supplier, product and phone model; a combined enquiry does not guarantee lower minimums or that all goods can ship together.','Plan screen protectors for stores'],
 ]},
 zh: {heading:'按创业用途规划第一批采购',cta:'准备采购需求',items:[
  ['餐饮创业低成本起步：从中国采购开业必需设备','先围绕精简的开业菜单、每餐出品量和可用空间列设备清单。降低起步投入，应从缩小且可执行的经营范围开始。',['先覆盖菜单需要的烹饪、安全冷藏、备料和清洗功能，确认产能与水电条件后再选型号。','区分开业必需设备和扩充菜单后再买的设备。共用设备须满足产能、清洁及食材分隔要求。','提交菜单、场地尺寸、水电条件、目的地和设备预算，比较基础配置与后续扩充清单。'],'小型外卖店或云厨房能否少买几台设备起步？','可以按菜单评估设备需求。减少设备只有在仍满足出品和场地要求时才能降低首批采购投入；冷藏、通风及当地安装条件仍需核对。','比较外卖店与云厨房设备组合'],
  ['怎样选择预算内最省钱、又能实际使用的厨房设备方案？','比较中国厨房设备时，应统一菜单、产能、配置和交付范围。单台价格最低，不代表开业总投入最低。',['基础方案只列开业菜单必需设备；扩充方案的额外产能和新品类设备单独报价。','分别列出货值、包装、采购或验货、运费和目的地费用。核对设备报价之外的场地改造、水电和安装。','选择低价型号前，比较供电要求、清洁空间、备件和包装，不为达到预算而省略必要的安全及场地配置。'],'可以按预算报价低成本厨房设备组合吗？','请说明预算币种，以及预算仅覆盖设备还是也包含运输和安装。可据此申请可比配置报价，不承诺全网最低价或固定开业总成本。','比较商用厨房设备与配置'],
  ['适合零售商的手机防窥膜：中国采购与供应商选择','围绕门店服务的机型、贴膜方式和首批资金投入，选择供应商与防窥膜配置。',['列明准确手机机型和数量，通过样品比较防窥效果、正面清晰度、触控、贴合和手机壳兼容性。','比较普通包装、零售独立包装和安装器套装，确认清洁附件、包装内容及补货成本。','当前 OG28 每单至少 1,000 片、每机型至少 100 片；001 与 Titan 参考条件为每机型至少 500 片，下单前确认现货与最新条件。'],'哪种防窥膜供应方案适合新开的手机店？','同时评估样品、机型覆盖、起订量、包装和补货一致性。低单价可能对应更大的首批库存投入，可提交机型清单与预算比较现有方案。','比较防窥膜配置与起订量'],
  ['手机配件创业方案：从中国规划首批选品','按销售渠道搭配手机壳、挂绳和保护膜，形成聚焦的首批采购清单。这是采购规划，并非固定价格的创业礼包。',['先确定手机店、维修柜台或线上销售渠道，按渠道需求选机型和产品，避免首单铺开大量未经验证的款式。','区分样品、现货和定制包装，先控制颜色与款式数量，每个订单明细的起订量须由供应商确认。','分别预留货款、样品、包装、按需验货、运输和目的地费用，并为后续补货保留周转资金。'],'能否把手机壳、挂绳和防窥膜组合成小额创业订单？','可以提交含数量和目的地的混合采购需求。供应商、产品和机型起订条件仍分别适用；合并询价不代表可以降低起订量或保证所有货物同批出运。','规划手机门店保护膜采购'],
 ]},
 es: {heading:'Planifique su primer pedido según el negocio que quiere abrir',cta:'Preparar solicitud de compra',items:[
  ['Empezar un restaurante con poco presupuesto: equipos esenciales de China','Prepare la lista inicial según un menú reducido, las raciones por servicio y el espacio disponible. Limitar el alcance inicial ayuda a definir una inversión viable.',['Cubra cocción, conservación en frío, preparación y lavado según el menú. Compruebe capacidad e instalaciones antes de elegir modelos.','Separe lo imprescindible para abrir de lo necesario para ampliar el menú. Comparta equipos solo si permiten la capacidad, limpieza y separación de alimentos requeridas.','Envíe menú, dimensiones, instalaciones, destino y presupuesto. Compare una configuración básica con una lista de ampliación.'],'¿Puede una cocina de comida para llevar o una cocina de reparto empezar con menos máquinas?','Solicite una revisión basada en el menú. Menos máquinas solo reducen la compra inicial si siguen cubriendo producción y condiciones del local; deben revisarse refrigeración, ventilación e instalación.','Comparar conjuntos para comida para llevar y cocinas de reparto'],
  ['¿Cuál es el conjunto de equipos de cocina más económico que cumple mis necesidades?','Compare equipos de China con el mismo menú, capacidad, configuración y alcance de entrega. El menor precio unitario no siempre supone el menor coste de apertura.',['Plan básico: equipos del menú inicial. Plan de ampliación: capacidad o platos adicionales, cotizados por separado.','Separe productos, embalaje, compras o inspección, flete y costes en destino. Revise obras, instalaciones y montaje fuera de la cotización de equipos.','Compare alimentación eléctrica, limpieza, repuestos y embalaje antes de elegir un modelo más barato. Mantenga los requisitos de seguridad y del local.'],'¿Pueden cotizar un conjunto asequible según mi presupuesto?','Indique moneda y si el presupuesto cubre solo equipos o también entrega e instalación. Podemos solicitar configuraciones comparables; no prometemos el menor precio del mercado ni un coste fijo de apertura.','Comparar equipos de cocina profesional'],
  ['Proveedores de protectores de privacidad de China para minoristas','Elija proveedor y configuración según los teléfonos que atiende su tienda, la instalación y el capital del primer pedido.',['Enumere modelos exactos y cantidades. Revise en muestras privacidad, claridad frontal, respuesta táctil, ajuste y compatibilidad con fundas.','Compare protectores con embalaje básico, presentación individual y kits de instalación. Confirme accesorios de limpieza, contenido y reposición.','Referencias actuales: OG28 exige 1.000 unidades por pedido y 100 por modelo; 001 y Titan, 500 por modelo. Confirme disponibilidad y condiciones antes de comprar.'],'¿Qué proveedor de protectores de privacidad conviene a una tienda nueva?','Compare muestras, cobertura de modelos, mínimos, embalaje y uniformidad de reposición. Un precio unitario menor puede exigir más inventario inicial. Envíe modelos y presupuesto para revisar las opciones.','Comparar protectores de privacidad y pedidos mínimos'],
  ['Emprender con accesorios para teléfonos: primer pedido desde China','Prepare un surtido inicial de fundas, correas y protectores según su canal. Es un plan de compras, no un paquete empresarial a precio fijo.',['Defina tienda, taller de reparación o venta en línea. Priorice modelos y productos relevantes, sin abrir demasiadas referencias no probadas.','Separe muestras, existencias y embalaje personalizado. Limite colores y diseños; confirme los mínimos de cada línea con el proveedor.','Presupueste mercancía, muestras, embalaje, inspección solicitada, transporte y destino. Reserve capital para reponer productos.'],'¿Puedo combinar fundas, correas y protectores de privacidad en un pedido inicial pequeño?','Envíe una solicitud mixta con cantidades y destino. Siguen vigentes los mínimos por proveedor, producto y modelo; una consulta conjunta no garantiza mínimos menores ni un único embarque.','Planificar protectores para tiendas'],
 ]},
 ar: {heading:'خطط لأول طلب بحسب المشروع الذي تريد بدءه',cta:'جهز طلب الشراء',items:[
  ['بدء مشروع مطعم بميزانية محدودة: معدات أساسية من الصين','ابدأ بقائمة طعام مختصرة وعدد الوجبات في كل فترة خدمة والمساحة المتاحة. يساعد نطاق افتتاح أصغر وقابل للتنفيذ على ضبط الاستثمار الأولي.',['حدد وظائف الطهي والتبريد الآمن والتحضير والغسل المطلوبة، ثم طابق الإنتاجية والمرافق قبل اختيار الطرازات.','افصل معدات يوم الافتتاح عن معدات التوسع اللاحق. لا تشارك المعدات بين الوظائف إلا إذا سمحت القدرة والتنظيف وفصل الأغذية بذلك.','أرسل قائمة الطعام وأبعاد الموقع والمرافق والوجهة وميزانية المعدات لمقارنة التجهيز الأساسي وخطة التوسع.'],'هل يمكن بدء مطبخ سحابي أو مشروع وجبات خارجية بعدد أقل من الآلات؟','اطلب مراجعة المعدات وفق القائمة. يقلل العدد الأقل قيمة الطلب الأول فقط إذا استوفى الإنتاج وظروف الموقع؛ ويجب مراجعة التبريد والتهوية والتركيب المحلي.','قارن مجموعات المطابخ السحابية والوجبات الخارجية'],
  ['ما أقل مجموعة معدات مطبخ تكلفةً وتلبي احتياجات التشغيل؟','قارن معدات الصين على أساس قائمة طعام وإنتاجية ومواصفات ونطاق تسليم موحد. أقل سعر للوحدة لا يعني بالضرورة أقل تكلفة للافتتاح.',['الخطة الأساسية لمعدات قائمة الافتتاح، وخطة التوسع لطاقة إضافية أو أطباق جديدة بعرض منفصل.','افصل البضائع والتغليف والشراء أو الفحص والشحن وتكاليف الوجهة. راجع أعمال الموقع والمرافق والتركيب خارج عرض المعدات.','قارن الكهرباء وسهولة التنظيف وقطع الغيار والتغليف قبل اختيار طراز أرخص، مع الحفاظ على متطلبات السلامة والموقع.'],'هل يمكن تقديم مجموعة معدات اقتصادية وفق ميزانيتي؟','حدد العملة وما إذا كانت الميزانية للمعدات فقط أو تشمل النقل والتركيب. يمكن طلب تجهيزات قابلة للمقارنة دون وعد بأقل سعر في السوق أو تكلفة افتتاح ثابتة.','قارن معدات المطابخ التجارية'],
  ['توريد واقيات شاشة للخصوصية من الصين لتجار التجزئة','اختر المورد والتجهيز بحسب طرازات الهواتف التي تخدمها وطريقة التركيب ورأس مال الطلب الأول.',['حدد الطرازات الدقيقة والكميات، واختبر الخصوصية ووضوح الرؤية الأمامية واللمس والملاءمة والتوافق مع الغطاء على العينات.','قارن التغليف الأساسي والعبوات الفردية وأطقم التركيب، وأكد أدوات التنظيف والمحتويات وتكلفة إعادة التوريد.','الشروط المرجعية الحالية: OG28 بحد أدنى 1,000 قطعة للطلب و100 لكل طراز؛ و001 وTitan بحد أدنى 500 لكل طراز. أكد التوفر والشروط قبل الشراء.'],'أي مورد واقيات خصوصية يناسب متجر هواتف جديدًا؟','قيّم العينات وتغطية الطرازات والحد الأدنى والتغليف وثبات إعادة التوريد معًا. قد يتطلب سعر الوحدة الأقل مخزونًا أوليًا أكبر. أرسل الطرازات والميزانية لمراجعة الخيارات.','قارن واقيات الخصوصية والحد الأدنى للطلب'],
  ['بدء تجارة ملحقات الهواتف: خطة أول طلب من الصين','كوّن تشكيلة مركزة من الأغطية والحبال وواقيات الشاشة لقناة البيع. هذه خطة شراء وليست حزمة مشروع بسعر ثابت.',['حدد متجر هواتف أو محل إصلاح أو بيعًا عبر الإنترنت، ثم اختر الطرازات والمنتجات المناسبة بدل تشكيلة واسعة غير مختبرة.','افصل العينات والمنتجات الجاهزة والتغليف المخصص. قلل الألوان والتصاميم أولًا، وأكد الحد الأدنى لكل بند مع المورد.','خصص مبالغ للبضائع والعينات والتغليف والفحص عند طلبه والنقل وتكاليف الوجهة، واحتفظ بسيولة لإعادة التوريد.'],'هل يمكن جمع الأغطية والحبال وواقيات الخصوصية في طلب بداية صغير؟','أرسل طلبًا مختلطًا بالكميات والوجهة. تبقى حدود المورد والمنتج وطراز الهاتف سارية؛ ولا تضمن مقارنة موحدة تخفيض الحدود أو شحن جميع البضائع معًا.','خطط لواقيات الشاشة للمتاجر'],
 ]},
 ru: {heading:'Спланируйте первую закупку под свой новый бизнес',cta:'Подготовить запрос на закупку',items:[
  ['Открытие ресторана с небольшим бюджетом: необходимое оборудование из Китая','Составьте первую закупку под короткое стартовое меню, количество порций за смену и доступную площадь. Ограниченный, но рабочий формат помогает снизить начальные вложения.',['Определите необходимые функции приготовления, безопасного охлаждения, подготовки и мойки. До выбора моделей проверьте производительность и коммуникации.','Отделите оборудование для открытия от последующего расширения меню. Совмещайте функции только при достаточной мощности, возможности очистки и разделения продуктов.','Пришлите меню, размеры помещения, данные коммуникаций, назначение и бюджет. Сравните базовую комплектацию с перечнем для расширения.'],'Можно ли открыть кухню доставки с меньшим количеством машин?','Запросите подбор по меню. Меньшее число машин снижает первую закупку только при выполнении требований к производству и помещению; охлаждение, вентиляцию и местный монтаж нужно проверить.','Сравнить комплекты для еды навынос и кухни доставки'],
  ['Как выбрать самый недорогой комплект кухни, подходящий для работы?','Сравнивайте оборудование из Китая при одинаковых меню, производительности, комплектации и условиях доставки. Минимальная цена единицы не всегда означает минимальные затраты на открытие.',['Базовый план включает стартовое меню; дополнительная производительность и новые блюда рассчитываются отдельно.','Разделите стоимость товара, упаковки, закупочных услуг или инспекции, перевозки и назначения. Уточните работы в помещении, коммуникации и монтаж вне сметы оборудования.','До выбора дешёвой модели сравните питание, доступ для очистки, запчасти и упаковку. Сохраните обязательные требования безопасности и помещения.'],'Можно ли подобрать бюджетный комплект под мою сумму?','Укажите валюту и состав бюджета: только оборудование или также доставка и монтаж. Можно запросить сопоставимые комплектации без обещания самой низкой рыночной цены или фиксированной стоимости открытия.','Сравнить оборудование для профессиональной кухни'],
  ['Поставщики защитных стёкол антишпион из Китая для розничных магазинов','Выбирайте поставщика и комплектацию под модели телефонов в вашем магазине, способ установки и бюджет первой партии.',['Укажите точные модели и количество. На образцах проверьте защиту от бокового просмотра, чёткость спереди, сенсор, посадку и совместимость с чехлами.','Сравните обычную упаковку, индивидуальную розничную и комплекты установки. Уточните чистящие принадлежности, состав и стоимость пополнения.','Текущие ориентиры: OG28 — от 1 000 штук в заказе и 100 на модель; 001 и Titan — от 500 на модель. Перед заказом подтвердите наличие и условия.'],'Какой поставщик стёкол антишпион подойдёт новому магазину?','Оцените образцы, охват моделей, минимумы, упаковку и стабильность повторных партий. Низкая цена единицы может потребовать большего стартового запаса. Пришлите модели и бюджет для сравнения вариантов.','Сравнить стёкла антишпион и минимальные партии'],
  ['Бизнес на аксессуарах для телефонов: первая закупка из Китая','Соберите целевой стартовый ассортимент чехлов, ремешков и защитных стёкол под канал продаж. Это план закупки, а не готовый бизнес-набор с фиксированной ценой.',['Определите формат: магазин, ремонтная точка или онлайн-продажи. Начните с подходящих моделей, не расширяя сразу непроверенный ассортимент.','Разделите образцы, складской товар и индивидуальную упаковку. Ограничьте цвета и варианты; подтвердите минимумы по каждой позиции.','Учтите товар, образцы, упаковку, инспекцию при заказе, перевозку и расходы в пункте назначения. Оставьте оборотные средства на пополнение.'],'Можно ли объединить чехлы, ремешки и стёкла антишпион в небольшую первую закупку?','Отправьте смешанный запрос с количеством и назначением. Минимумы поставщика, товара и модели остаются в силе; общий запрос не гарантирует их снижения или совместной отправки всех товаров.','Спланировать защитные стёкла для магазина'],
 ]},
 fr: {heading:'Préparez votre première commande selon votre projet d’entreprise',cta:'Préparer une demande d’achat',items:[
  ['Ouvrir un restaurant avec un petit budget : équipements essentiels de Chine','Établissez la première liste selon une carte courte, les portions par service et la surface disponible. Un périmètre de départ réduit et exploitable aide à maîtriser l’investissement.',['Couvrez cuisson, conservation au froid, préparation et lavage selon la carte. Vérifiez capacité et raccordements avant de choisir les modèles.','Distinguez les indispensables à l’ouverture des équipements d’extension. Mutualisez seulement si capacité, nettoyage et séparation des aliments le permettent.','Envoyez carte, dimensions, raccordements, destination et budget pour comparer configuration de base et extension.'],'Une cuisine de livraison peut-elle démarrer avec moins de machines ?','Demandez une étude fondée sur la carte. Moins de machines réduit l’achat initial seulement si la production et le local restent adaptés ; froid, ventilation et installation locale sont à vérifier.','Comparer les ensembles pour vente à emporter et cuisines de livraison'],
  ['Quel ensemble de cuisine professionnelle est le moins cher tout en étant adapté ?','Comparez les équipements de Chine à carte, capacité, configuration et livraison identiques. Le prix unitaire le plus bas ne signifie pas le coût d’ouverture le plus bas.',['Le plan de base couvre la carte initiale ; capacité supplémentaire et nouveaux plats sont chiffrés séparément.','Séparez marchandises, emballage, achats ou inspection, fret et coûts à destination. Vérifiez travaux, raccordements et installation hors devis matériel.','Comparez alimentation électrique, accès de nettoyage, pièces et emballage avant de choisir un modèle moins cher, sans supprimer les exigences de sécurité ou du local.'],'Pouvez-vous chiffrer un ensemble économique selon mon budget ?','Indiquez la devise et si le budget couvre seulement le matériel ou aussi livraison et installation. Des configurations comparables peuvent être demandées, sans garantie du prix le plus bas du marché ni d’un coût d’ouverture fixe.','Comparer les équipements de cuisine professionnelle'],
  ['Fournisseurs de protections d’écran anti-espion de Chine pour détaillants','Choisissez le fournisseur et la configuration selon les téléphones servis, le mode de pose et le financement de la première commande.',['Précisez modèles et quantités. Testez confidentialité, netteté de face, réponse tactile, ajustement et compatibilité avec les coques sur échantillons.','Comparez emballage simple, présentation individuelle et kits de pose. Confirmez accessoires de nettoyage, contenu et coût du réassort.','Conditions indicatives actuelles : OG28, 1 000 pièces par commande et 100 par modèle ; 001 et Titan, 500 par modèle. Confirmez disponibilité et conditions avant commande.'],'Quel fournisseur de protections anti-espion convient à une nouvelle boutique ?','Évaluez échantillons, modèles couverts, minimums, emballage et régularité des réassorts. Un prix unitaire inférieur peut exiger plus de stock initial. Envoyez modèles et budget pour étudier les options.','Comparer les protections anti-espion et les minimums'],
  ['Créer un commerce d’accessoires de téléphone : premier achat en Chine','Préparez un assortiment ciblé de coques, cordons et protections d’écran selon votre canal. Il s’agit d’un plan d’achat, pas d’un kit d’entreprise à prix fixe.',['Choisissez boutique, comptoir de réparation ou vente en ligne. Privilégiez les modèles adaptés au canal plutôt qu’un assortiment large non testé.','Séparez échantillons, stock et emballages personnalisés. Limitez couleurs et styles ; faites confirmer les minimums de chaque ligne.','Prévoyez marchandises, échantillons, emballage, inspection demandée, transport et coûts à destination. Gardez de la trésorerie pour le réassort.'],'Puis-je regrouper coques, cordons et protections anti-espion dans une petite première commande ?','Transmettez une demande mixte avec quantités et destination. Les minimums par fournisseur, produit et téléphone restent applicables ; une demande commune ne garantit ni leur baisse ni un envoi unique.','Préparer les protections d’écran pour boutiques'],
 ]},
 pt: {heading:'Planeje o primeiro pedido para o negócio que quer abrir',cta:'Preparar solicitação de compra',items:[
  ['Empreender na alimentação com pouco dinheiro: equipamentos essenciais da China','Monte a primeira lista com base em um cardápio enxuto, porções por turno e espaço disponível. Um escopo inicial menor e viável ajuda a controlar o investimento.',['Cubra cocção, conservação refrigerada segura, preparo e lavagem conforme o cardápio. Confira capacidade e instalações antes de escolher modelos.','Separe o essencial para abrir dos equipamentos para ampliar o cardápio. Compartilhe funções apenas quando capacidade, limpeza e separação de alimentos permitirem.','Envie cardápio, medidas, instalações, destino e orçamento para comparar configuração básica e lista de expansão.'],'Uma operação de entrega ou cozinha exclusiva para delivery pode começar com menos máquinas?','Solicite uma análise baseada no cardápio. Menos máquinas reduz a primeira compra somente se atender à produção e ao local; refrigeração, ventilação e instalação precisam ser conferidas.','Comparar conjuntos para delivery e cozinhas de produção'],
  ['Qual é o conjunto de equipamentos de cozinha mais barato que atende à operação?','Compare equipamentos da China com o mesmo cardápio, capacidade, configuração e entrega. O menor preço por unidade nem sempre gera o menor custo de abertura.',['Plano básico: equipamentos do cardápio inicial. Expansão: capacidade extra ou novos pratos, cotados separadamente.','Separe produtos, embalagem, compras ou inspeção, frete e custos no destino. Confira obras, instalações e montagem fora da cotação dos equipamentos.','Compare alimentação elétrica, acesso para limpeza, peças e embalagem antes de escolher um modelo mais barato. Mantenha os requisitos de segurança e do local.'],'Vocês podem cotar uma cozinha econômica de acordo com meu orçamento?','Informe moeda e se o orçamento cobre apenas equipamentos ou também entrega e instalação. Podemos solicitar configurações comparáveis, sem promessa de menor preço do mercado ou custo fixo de abertura.','Comparar equipamentos de cozinha profissional'],
  ['Fornecedores de películas de privacidade da China para lojistas','Escolha fornecedor e configuração conforme os aparelhos atendidos, a forma de aplicação e o investimento no primeiro pedido.',['Liste modelos exatos e quantidades. Confira nas amostras privacidade, clareza frontal, resposta ao toque, encaixe e compatibilidade com capas.','Compare embalagem básica, individual de varejo e kits com aplicador. Confirme itens de limpeza, conteúdo e custo de reposição.','Referências atuais: OG28 exige 1.000 peças por pedido e 100 por modelo; 001 e Titan, 500 por modelo. Confirme disponibilidade e condições antes da compra.'],'Qual fornecedor de película de privacidade atende uma loja nova?','Avalie amostras, cobertura de modelos, mínimos, embalagem e consistência da reposição. Um preço unitário menor pode exigir mais estoque inicial. Envie modelos e orçamento para comparar as opções.','Comparar películas de privacidade e pedidos mínimos'],
  ['Começar um negócio de acessórios para celular: primeiro pedido da China','Monte um mix focado de capas, cordões e películas para seu canal. Trata-se de planejamento de compra, não de um kit de negócio com preço fixo.',['Defina loja, assistência técnica ou venda online. Priorize modelos e produtos adequados ao canal, evitando um mix amplo ainda não testado.','Separe amostras, produtos de estoque e embalagem personalizada. Limite cores e estilos; confirme o mínimo de cada item com o fornecedor.','Orce mercadorias, amostras, embalagem, inspeção solicitada, frete e custos no destino. Reserve capital de giro para reposição.'],'Posso juntar capas, cordões e películas de privacidade em um pequeno pedido inicial?','Envie uma solicitação mista com quantidades e destino. Os mínimos por fornecedor, produto e aparelho continuam válidos; a cotação conjunta não garante mínimos menores nem embarque de tudo junto.','Planejar películas para lojas'],
 ]},
 tr: {heading:'İlk siparişinizi kurmak istediğiniz işe göre planlayın',cta:'Satın alma talebi hazırlayın',items:[
  ['Düşük bütçeyle restoran açmak: Çin’den temel ekipman tedariki','İlk listeyi sınırlı bir açılış menüsü, servis başına porsiyon ve mevcut alan üzerine kurun. Küçük ama uygulanabilir bir başlangıç kapsamı yatırımı kontrol etmeye yardımcı olur.',['Menünün gerektirdiği pişirme, güvenli soğutma, hazırlık ve yıkama işlevlerini belirleyin. Model seçiminden önce kapasite ve tesisatı kontrol edin.','Açılış için zorunlu ekipmanı sonraki menü genişlemesinden ayırın. İşlevleri yalnızca kapasite, temizlik ve gıda ayrımı uygunsa birleştirin.','Menü, alan ölçüleri, tesisat, varış yeri ve bütçeyi göndererek temel yapılandırma ile genişleme listesini karşılaştırın.'],'Paket servis veya bulut mutfak daha az makineyle başlayabilir mi?','Menüye göre ekipman incelemesi isteyin. Daha az makine, üretim ve alan gereksinimleri karşılanıyorsa ilk alımı azaltabilir; soğutma, havalandırma ve yerel kurulum kontrol edilmelidir.','Paket servis ve bulut mutfak paketlerini karşılaştırın'],
  ['İhtiyacı karşılayan en ucuz endüstriyel mutfak ekipman paketi nasıl seçilir?','Çin’den ekipmanı aynı menü, kapasite, yapılandırma ve teslimat kapsamında karşılaştırın. En düşük birim fiyat, en düşük açılış maliyeti demek değildir.',['Temel plan açılış menüsünü kapsar; ek kapasite ve yeni ürünler ayrı fiyatlandırılır.','Ürün, ambalaj, satın alma veya denetim, nakliye ve varış maliyetlerini ayırın. Tadilat, tesisat ve montajın ekipman teklifi dışında olup olmadığını kontrol edin.','Daha ucuz model seçmeden elektrik, temizleme erişimi, yedek parça ve ambalajı karşılaştırın. Güvenlik ve alan gereksinimlerini koruyun.'],'Bütçeme uygun ekonomik mutfak paketi için teklif alabilir miyim?','Para birimini ve bütçenin yalnızca ekipmanı mı, teslimat ve montajı da mı kapsadığını belirtin. Karşılaştırılabilir teklifler istenebilir; piyasadaki en düşük fiyat veya sabit açılış maliyeti vaat edilmez.','Endüstriyel mutfak ekipmanlarını karşılaştırın'],
  ['Perakendeciler için Çin’den hayalet ekran koruyucu tedariki','Tedarikçiyi ve yapılandırmayı mağazanızdaki telefon modellerine, uygulama yöntemine ve ilk sipariş yatırımına göre seçin.',['Tam telefon modellerini ve miktarları listeleyin. Numunede yandan gizlilik, önden netlik, dokunma tepkisi, uyum ve kılıf uyumluluğunu kontrol edin.','Standart ambalajı, tekli perakende paketini ve uygulama aparatlı setleri karşılaştırın. Temizlik aksesuarlarını, içeriği ve yeniden sipariş maliyetini teyit edin.','Mevcut referans koşullar: OG28 sipariş başına en az 1.000, model başına 100 adet; 001 ve Titan model başına 500 adet. Stok ve koşulları sipariş öncesi teyit edin.'],'Yeni telefon mağazası için hangi hayalet ekran koruyucu tedarikçisi uygundur?','Numune, model kapsamı, asgari miktar, ambalaj ve tekrar sipariş tutarlılığını birlikte değerlendirin. Düşük birim fiyat daha fazla başlangıç stoku gerektirebilir. Seçenekleri incelemek için model listesi ve bütçe gönderin.','Hayalet ekran koruyucuları ve asgari siparişleri karşılaştırın'],
  ['Telefon aksesuarı işine başlamak: Çin’den ilk sipariş planı','Satış kanalınıza göre kılıf, askı ve ekran koruyucudan odaklı bir başlangıç seçkisi oluşturun. Bu bir satın alma planıdır; sabit fiyatlı iş kurma paketi değildir.',['Mağaza, tamir tezgâhı veya online satış kanalını belirleyin. Geniş ve denenmemiş bir seçki yerine kanala uygun modellere odaklanın.','Numune, stok ürün ve özel ambalajı ayırın. Renk ve çeşitleri sınırlayın; her kalemin asgari miktarını tedarikçiye teyit ettirin.','Ürün, numune, ambalaj, talep edilen denetim, nakliye ve varış masraflarını bütçeleyin. Yeniden sipariş için işletme sermayesi ayırın.'],'Kılıf, askı ve hayalet ekran koruyucuları küçük bir başlangıç siparişinde birleştirebilir miyim?','Miktarlar ve varış yeriyle karma talep gönderin. Tedarikçi, ürün ve telefon modeli minimumları geçerlidir; ortak teklif daha düşük minimumları veya tüm malların birlikte taşınmasını garanti etmez.','Mağazalar için ekran koruyucu planlayın'],
 ]},
};

startupRoutes.push(...additionalStartupRoutes);
for (const [locale, items] of Object.entries(additionalStartupCopy)) startupCopy[locale].items.push(...items);
