export const additionalStartupRoutes = [
 ['/sourcing/restaurant-project-equipment/','small-cafe-budget'],
 ['/sourcing/restaurant-project-equipment/','bar-equipment-budget'],
 ['/sourcing/audio-speakers-from-china/','party-speaker-budget'],
 ['/phone-cases/','marketplace-seller-startup'],
];
export const additionalStartupCopy = {
 en:[
  ['Small café startup: low-cost equipment sourcing from China','Start with your drinks menu and peak cups per hour. Buy capacity for the opening offer rather than copying the equipment list of a larger café.',['Prioritise the coffee machine and grinder configuration, water treatment, milk refrigeration, washing and preparation space required by your menu. Confirm model availability and utility needs.','Add an ice machine, blender, display refrigerator or light-meal equipment only where the opening menu requires it. Request essential and expansion items as separate quotations.','Compare equipment, packing and delivery costs separately from plumbing, electrical work, drainage and installation. Send the budget currency, space and expected peak demand.'],'Can I open a small café with an entry-level equipment package?','Request a menu-based shortlist and sample or specification review. The existing café layout is a reference concept, not a minimum-cost bill of equipment; final models and included items need a quotation.','Explore the café equipment concept'],
  ['Low-budget bar and cocktail bar equipment from China','Build the equipment plan around drinks served, ice demand and service speed. A compact drinks menu can narrow the first purchase without assuming every bar needs the same machines.',['List ice production and storage, under-counter refrigeration, glass washing, sinks and preparation surfaces. Confirm which functions and models are included in the sourcing scope.','Request blenders, juicers, cocktail tools and display equipment only where required. These are items to source and confirm, not a pre-approved complete bar kit.','Check drainage, water quality, electrical supply, noise, cleaning and local installation. Separate opening essentials from later capacity upgrades.'],'How can I reduce the initial cost of a cocktail bar?','Compare fewer drink categories and an essential-equipment plan with the expansion option. Check ice and refrigeration capacity before choosing cheaper machines; send destination, menu and budget for an itemised quotation.','Compare commercial ice-machine options'],
  ['Finding the cheapest suitable Bluetooth party speaker supplier in China','Compare suppliers against one approved speaker specification. The lowest advertised price may describe a different driver, battery, accessories or packing scope.',['Use the same driver configuration, continuous-output test basis, battery capacity, playback conditions and included microphones when comparing offers. Do not equate peak wattage with tested continuous output.','Review samples for sound at the intended volume, connection stability, battery operation and microphone use. Request available evidence for the exact model and destination.','Compare minimum order, sample cost, packaging, branding, spare parts and freight as separate lines. Ask for a stock configuration and an upgraded option.'],'Can you find the cheapest Bluetooth party speakers for resale?','We can coordinate comparable supplier quotations around your target price and quantity. No market-wide lowest-price claim is made; select after checking samples, the agreed specification and the total purchase scope.','Request a supplier and quotation comparison'],
  ['Low-cost phone-case ecommerce startup: sourcing for Noon, Amazon and Jumia sellers','Build a focused China sourcing plan for your chosen marketplace and country. This is a product-purchasing plan, not platform account management or a guaranteed sales package.',['Choose exact phone models, case materials and a limited colour assortment. Compare stock cases with custom branding; confirm minimums for each variant before committing inventory.','Inspect fit, cut-outs, buttons, finish and package protection. Confirm usable product photos, accurate compatibility descriptions and any requested labels against the approved sample.','Check current listing, packaging, labelling and fulfilment requirements in your own Noon, Amazon or Jumia seller account. Budget separately for platform costs, returns, advertising, freight and replenishment.'],'Can I start selling phone cases on Noon, Amazon or Jumia with a small order?','Send the platform, country, fulfilment method, phone models, quantities and budget. We can request supplier options; minimums, custom packaging and shipment scope require confirmation. Sourcing does not guarantee listing approval, brand authorisation or profit.','Compare case materials and purchase costs'],
 ],
 zh:[
  ['小型咖啡店低成本起步：从中国采购基础设备','先确定饮品菜单与高峰每小时出杯量，按开业需求购买产能，不直接照搬大型咖啡店的设备清单。',['优先核对菜单所需的咖啡机与磨豆机配置、水处理、牛奶冷藏、清洗及备料空间，并确认可采购型号与水电要求。','只有开业菜单需要时才加入制冰机、搅拌机、展示冷柜或轻食设备，将必需设备和扩充项目分开报价。','设备、包装与运输费用，和给排水、电路改造及安装分别核算。提交预算币种、空间与预计高峰客流。'],'小咖啡店能否用入门设备组合开业？','可以按菜单申请型号清单并核对样品或规格。现有咖啡店布局属于参考概念，不是最低成本设备清单；最终型号与包含项目须逐项报价确认。','查看咖啡店设备参考方案'],
  ['低成本酒吧与调酒吧设备采购方案','根据饮品种类、用冰量和出杯速度规划设备，先用精简饮品菜单控制首批投入，不默认所有酒吧都需要同一套机器。',['列出制冰与储冰、台下冷藏、洗杯、水槽和备料台需求，确认采购范围中包含哪些功能与型号。','按菜单申请搅拌机、榨汁机、调酒工具和展示设备。这些属于待寻源确认的项目，不是已经定型的整套酒吧套装。','核对排水、水质、供电、噪声、清洁及当地安装条件，将开业必需项与后续扩容分开。'],'怎样降低调酒吧的第一批设备投入？','比较精简饮品种类的基础配置和后期扩充配置。选择便宜型号前核对制冰与冷藏能力，提交目的地、菜单和预算获取分项报价。','比较商用制冰机选项'],
  ['怎样寻找价格更低、配置合适的中国蓝牙派对音箱供应商？','以同一份已确认的音箱规格比较供应商。最低展示价格可能对应不同单元、电池、附件或包装范围。',['统一扬声器单元、持续输出测试口径、电池容量、播放条件和麦克风配置，不把峰值功率当作实测持续输出。','通过样品核对目标音量下的声音、连接稳定性、电池使用和麦克风表现，索取具体型号及目的地适用的现有资料。','分别比较起订量、样品、包装、品牌定制、备件和运输费用，申请现货基础配置与升级配置报价。'],'能否找到最便宜的蓝牙派对音箱用于转售？','可以按目标价格与数量协调可比供应商报价，但不承诺全市场最低价。确认样品、约定规格和完整采购范围后再选择。','申请供应商搜索与报价比较'],
  ['手机壳电商低成本启动：面向 Noon、Amazon、Jumia 卖家的采购方案','按目标平台与销售国家规划从中国采购手机壳。这是产品采购方案，不包含店铺代运营或保证销量的创业套餐。',['先确定准确机型、壳体材质和少量颜色，比较现货款与品牌定制款，投入库存前逐款确认起订量。','检查贴合、开孔、按键、表面处理与包装保护；根据确认样品核对可用产品图片、机型描述及所需标签。','在自己的 Noon、Amazon 或 Jumia 卖家账户核对当前上架、包装、标签和履约要求，另列平台费用、退货、广告、运输与补货预算。'],'小批量采购手机壳，可以用于在 Noon、Amazon 或 Jumia 开店吗？','请提交平台、国家、履约方式、机型、数量和预算以申请供应商选项。起订量、定制包装和出运范围须确认；采购服务不保证上架批准、品牌授权或利润。','比较手机壳材质与采购成本'],
 ],
 es:[
  ['Cafetería pequeña con poco presupuesto: equipos básicos de China','Defina el menú de bebidas y las tazas por hora punta. Compre capacidad para la apertura, sin copiar una cafetería mayor.',['Priorice cafetera y molino, tratamiento de agua, refrigeración de leche, lavado y preparación según el menú. Confirme modelos e instalaciones.','Añada hielo, batidora, vitrina fría o equipos de comida ligera solo si son necesarios. Cotice por separado lo esencial y la ampliación.','Separe equipos, embalaje y entrega de fontanería, electricidad, desagüe e instalación. Indique moneda, espacio y demanda máxima.'],'¿Puedo abrir una cafetería pequeña con equipos de entrada?','Solicite una selección según el menú y revise muestras o especificaciones. El plano existente es un concepto de referencia, no una lista de coste mínimo; confirme modelos e inclusiones en la cotización.','Ver el concepto de equipos para cafetería'],
  ['Equipos económicos de China para bares y coctelerías','Planifique según bebidas, demanda de hielo y velocidad de servicio. Un menú reducido permite acotar la primera compra.',['Enumere producción y almacenamiento de hielo, refrigeración bajo mostrador, lavado de vasos, fregaderos y preparación. Confirme lo incluido.','Solicite batidoras, exprimidores, utensilios de coctelería y exposición según necesidad. Son artículos por buscar y confirmar, no un kit completo ya aprobado.','Revise desagüe, agua, electricidad, ruido, limpieza e instalación local. Separe apertura y ampliación de capacidad.'],'¿Cómo reduzco la inversión inicial de una coctelería?','Compare un menú corto y equipos esenciales con una opción de ampliación. Revise hielo y refrigeración antes de elegir máquinas más baratas; envíe destino, menú y presupuesto para cotizar por partidas.','Comparar máquinas de hielo comerciales'],
  ['Cómo encontrar proveedores económicos de altavoces Bluetooth para fiestas en China','Compare proveedores con una misma especificación. El menor precio anunciado puede incluir componentes, batería o embalaje distintos.',['Iguale configuración de altavoces, prueba de potencia continua, batería, condiciones de reproducción y micrófonos. La potencia máxima no equivale a la salida continua ensayada.','Pruebe sonido al volumen previsto, conexión, batería y micrófonos. Solicite documentación del modelo exacto para el destino.','Separe mínimos, muestras, embalaje, marca, repuestos y flete. Solicite una configuración de stock y una mejorada.'],'¿Pueden encontrar los altavoces Bluetooth para fiestas más baratos para reventa?','Podemos coordinar cotizaciones comparables según precio objetivo y cantidad, sin garantizar el menor precio del mercado. Elija tras revisar muestras, especificación y alcance completo de compra.','Solicitar comparación de proveedores y cotizaciones'],
  ['Empezar a vender fundas online con poco presupuesto: Noon, Amazon y Jumia','Prepare compras de China para su plataforma y país. Es un plan de producto, no gestión de cuentas ni una garantía de ventas.',['Elija modelos exactos, materiales y pocos colores. Compare existencias y personalización; confirme mínimos por variante antes de comprar inventario.','Revise ajuste, recortes, botones, acabado y protección. Confirme imágenes utilizables, compatibilidad descrita y etiquetas según la muestra aprobada.','Consulte requisitos vigentes de publicación, embalaje, etiquetas y logística en su cuenta de Noon, Amazon o Jumia. Reserve costes de plataforma, devoluciones, publicidad, transporte y reposición.'],'¿Puedo empezar en Noon, Amazon o Jumia con un pedido pequeño de fundas?','Envíe plataforma, país, método logístico, modelos, cantidades y presupuesto. Mínimos, personalización y envío requieren confirmación. Las compras no garantizan aprobación del anuncio, autorización de marca ni beneficio.','Comparar materiales y costes de fundas'],
 ],
 ar:[
  ['معدات منخفضة التكلفة لمقهى صغير من الصين','حدد قائمة المشروبات وعدد الأكواب في ساعة الذروة. اشترِ قدرة تناسب الافتتاح بدل نسخ تجهيز مقهى أكبر.',['راجع آلة القهوة والمطحنة ومعالجة المياه وتبريد الحليب والغسل والتحضير بحسب القائمة، وأكد الطرازات والمرافق.','أضف آلة الثلج أو الخلاط أو العرض المبرد أو معدات الوجبات الخفيفة عند الحاجة فقط. اطلب عرضين للأساسيات والتوسع.','افصل المعدات والتغليف والنقل عن السباكة والكهرباء والتصريف والتركيب. حدد العملة والمساحة والطلب المتوقع.'],'هل يمكن افتتاح مقهى صغير بمعدات اقتصادية أساسية؟','اطلب قائمة طرازات حسب المشروبات وراجع العينات أو المواصفات. مخطط المقهى الحالي تصور مرجعي وليس قائمة بأقل تكلفة؛ أكد المعدات والمحتويات بعرض سعر.','استعرض تصور معدات المقهى'],
  ['معدات اقتصادية للبارات ومحطات تحضير الكوكتيلات من الصين','حدد التجهيز بحسب المشروبات وطلب الثلج وسرعة الخدمة. تساعد قائمة قصيرة على تقليل نطاق الشراء الأول.',['حدد إنتاج الثلج وتخزينه والتبريد أسفل الطاولة وغسل الكؤوس والأحواض والتحضير، وأكد الوظائف والطرازات المشمولة.','اطلب الخلاطات والعصارات وأدوات الكوكتيل والعرض عند الحاجة. هذه بنود للبحث والتأكيد وليست مجموعة جاهزة معتمدة.','راجع التصريف وجودة المياه والكهرباء والضوضاء والتنظيف والتركيب المحلي. افصل أساسيات الافتتاح عن زيادة القدرة لاحقًا.'],'كيف أخفض الاستثمار الأولي لمعدات تحضير الكوكتيلات؟','قارن قائمة مشروبات محدودة وتجهيزًا أساسيًا بخيار التوسع. تحقق من قدرة الثلج والتبريد قبل اختيار آلات أرخص، وأرسل القائمة والوجهة والميزانية لعرض مفصل.','قارن آلات الثلج التجارية'],
  ['البحث عن مورد سماعات حفلات بلوتوث اقتصادية من الصين','قارن الموردين وفق مواصفات موحدة. قد يخص أقل سعر معلن وحدات صوت أو بطارية أو ملحقات أو تغليفًا مختلفًا.',['وحّد وحدات الصوت وأساس اختبار القدرة المستمرة والبطارية وظروف التشغيل والميكروفونات. قدرة الذروة ليست قدرة مستمرة مختبرة.','اختبر الصوت بالمستوى المطلوب واستقرار الاتصال والبطارية والميكروفون، واطلب ملفات الطراز المحدد والوجهة.','افصل الحد الأدنى والعينة والتغليف والعلامة وقطع الغيار والنقل. اطلب خيارًا جاهزًا وآخر مطورًا.'],'هل يمكن العثور على أرخص سماعات حفلات بلوتوث لإعادة البيع؟','يمكن تنسيق عروض قابلة للمقارنة حسب السعر المستهدف والكمية دون ضمان أقل سعر في السوق. اختر بعد مراجعة العينات والمواصفات ونطاق الشراء الكامل.','اطلب مقارنة الموردين وعروض الأسعار'],
  ['بدء تجارة أغطية الهواتف إلكترونيًا بميزانية محدودة: Noon وAmazon وJumia','خطط للشراء من الصين بحسب المنصة والبلد. هذه خدمة شراء منتجات وليست إدارة حسابات أو ضمانًا للمبيعات.',['اختر طرازات دقيقة ومواد وألوانًا محدودة. قارن الجاهز بالعلامة المخصصة وأكد الحد الأدنى لكل صنف قبل شراء المخزون.','افحص الملاءمة والفتحات والأزرار والتشطيب والحماية. أكد الصور القابلة للاستخدام ووصف التوافق والملصقات وفق العينة المعتمدة.','راجع متطلبات الإدراج والتغليف والملصقات والتنفيذ الحالية في حسابك على Noon أو Amazon أو Jumia. خصص تكاليف المنصة والمرتجعات والإعلانات والنقل وإعادة التوريد.'],'هل يمكن البدء بكمية صغيرة من الأغطية على Noon أو Amazon أو Jumia؟','أرسل المنصة والبلد وطريقة التنفيذ والطرازات والكميات والميزانية. الحدود والتخصيص والشحن تحتاج إلى تأكيد؛ الشراء لا يضمن قبول الإدراج أو تفويض العلامة أو الربح.','قارن مواد الأغطية وتكلفة الشراء'],
 ],
 ru:[
  ['Недорогое оборудование из Китая для небольшой кофейни','Определите меню напитков и чашки в пиковый час. Покупайте мощность под открытие, не копируя большую кофейню.',['Проверьте кофемашину и кофемолку, подготовку воды, охлаждение молока, мойку и рабочую зону по меню. Подтвердите модели и коммуникации.','Добавляйте лёдогенератор, блендер, витрину и оборудование для закусок только при необходимости. Базу и расширение рассчитывайте отдельно.','Разделите оборудование, упаковку и доставку с сантехникой, электрикой, сливом и монтажом. Укажите валюту, площадь и пиковый спрос.'],'Можно ли открыть небольшую кофейню с базовым комплектом?','Запросите подбор под меню и проверку образца или характеристик. Существующий план — концепция, а не минимальная смета; модели и состав требуют подтверждения.','Посмотреть концепцию оборудования кофейни'],
  ['Бюджетное оборудование из Китая для бара и коктейльной стойки','Планируйте оснащение по напиткам, расходу льда и скорости обслуживания. Короткое меню помогает ограничить первую закупку.',['Перечислите производство и хранение льда, подстольное охлаждение, мойку стаканов, раковины и рабочие поверхности. Подтвердите включённые функции.','Запрашивайте блендеры, соковыжималки, барный инвентарь и витрины по необходимости. Это позиции для поиска и проверки, не готовый подтверждённый комплект.','Проверьте слив, воду, питание, шум, очистку и местный монтаж. Разделите открытие и последующее увеличение мощности.'],'Как снизить первые затраты на коктейльный бар?','Сравните короткое меню и необходимый комплект с расширением. До выбора дешёвых машин проверьте лёд и охлаждение; пришлите меню, назначение и бюджет для постатейного расчёта.','Сравнить коммерческие лёдогенераторы'],
  ['Как найти недорогого поставщика Bluetooth-колонок для вечеринок в Китае?','Сравнивайте поставщиков по одной спецификации. Минимальная цена объявления может относиться к другим динамикам, батарее или упаковке.',['Уравняйте динамики, метод проверки длительной мощности, батарею, условия воспроизведения и микрофоны. Пиковая мощность не равна проверенной длительной.','Проверьте образцы на нужной громкости, устойчивость связи, батарею и микрофоны. Запросите документы на точную модель и рынок назначения.','Разделите минимальную партию, образцы, упаковку, брендирование, запчасти и перевозку. Запросите складскую и улучшенную комплектации.'],'Можно ли найти самые дешёвые Bluetooth-колонки для перепродажи?','Можно организовать сопоставимые предложения под целевую цену и количество без гарантии минимума на всём рынке. Выбирайте после проверки образцов, характеристик и полного состава закупки.','Запросить сравнение поставщиков и предложений'],
  ['Недорогой старт продаж чехлов на Noon, Amazon и Jumia','Составьте план закупки в Китае под площадку и страну. Это закупка товара, не управление аккаунтом или гарантия продаж.',['Выберите точные модели телефонов, материалы и немного цветов. Сравните складской товар и брендирование; подтвердите минимум каждого варианта.','Проверьте посадку, вырезы, кнопки, отделку и защиту упаковки. Согласуйте доступные фото, описание совместимости и маркировку по образцу.','Проверьте действующие требования к карточкам, упаковке, маркировке и исполнению заказов в аккаунте Noon, Amazon или Jumia. Отдельно заложите комиссии, возвраты, рекламу, доставку и пополнение.'],'Можно ли начать продажи на Noon, Amazon или Jumia с небольшой партии чехлов?','Пришлите площадку, страну, схему исполнения, модели, количество и бюджет. Минимумы, упаковка и доставка согласуются отдельно; закупка не гарантирует одобрение карточки, разрешение бренда или прибыль.','Сравнить материалы чехлов и закупочные цены'],
 ],
 fr:[
  ['Petit café à budget réduit : équipements essentiels de Chine','Définissez la carte et les tasses à l’heure de pointe. Achetez la capacité nécessaire à l’ouverture sans copier un grand café.',['Vérifiez machine à café, moulin, traitement de l’eau, froid du lait, lavage et préparation selon la carte. Confirmez modèles et raccordements.','Ajoutez machine à glaçons, blender, vitrine ou petite restauration uniquement si nécessaire. Chiffrez séparément base et extension.','Séparez matériel, emballage et livraison de plomberie, électricité, évacuation et pose. Précisez devise, espace et demande maximale.'],'Un petit café peut-il démarrer avec un équipement d’entrée de gamme ?','Demandez une sélection selon la carte et vérifiez échantillons ou caractéristiques. Le plan existant est un concept, pas une nomenclature au coût minimum ; modèles et inclusions doivent être chiffrés.','Voir le concept d’équipement de café'],
  ['Équipements économiques de Chine pour bar et bar à cocktails','Préparez la liste selon les boissons, les besoins en glace et la vitesse de service. Une carte courte réduit le périmètre initial.',['Listez production et stockage de glace, froid sous comptoir, lavage des verres, éviers et préparation. Confirmez les fonctions incluses.','Demandez blenders, extracteurs, ustensiles de cocktail et présentation selon besoin. Ce sont des articles à sourcer et confirmer, pas un kit complet déjà validé.','Vérifiez évacuation, eau, alimentation, bruit, nettoyage et pose locale. Séparez ouverture et augmentation de capacité.'],'Comment réduire l’investissement initial d’un bar à cocktails ?','Comparez une carte réduite et les essentiels à une option d’extension. Vérifiez glace et froid avant de retenir des machines moins chères ; envoyez destination, carte et budget pour un devis détaillé.','Comparer les machines à glaçons professionnelles'],
  ['Trouver un fournisseur économique d’enceintes de soirée Bluetooth en Chine','Comparez les fournisseurs sur une spécification commune. Le prix affiché le plus bas peut correspondre à d’autres haut-parleurs, batterie ou accessoires.',['Alignez haut-parleurs, méthode de test de puissance continue, batterie, conditions de lecture et microphones. Une puissance de crête ne remplace pas une mesure continue.','Testez son au volume prévu, stabilité de connexion, batterie et microphones. Demandez les documents du modèle exact pour la destination.','Séparez minimums, échantillons, emballage, marque, pièces et fret. Demandez une configuration en stock et une version améliorée.'],'Pouvez-vous trouver les enceintes Bluetooth de soirée les moins chères à revendre ?','Nous pouvons coordonner des devis comparables selon votre prix cible et quantité, sans garantir le minimum du marché. Choisissez après contrôle des échantillons, caractéristiques et périmètre d’achat.','Demander une comparaison de fournisseurs et devis'],
  ['Démarrer la vente de coques à petit budget sur Noon, Amazon et Jumia','Préparez l’achat en Chine selon la plateforme et le pays. Il s’agit d’achats produits, pas de gestion de compte ni de ventes garanties.',['Choisissez modèles précis, matières et peu de couleurs. Comparez stock et personnalisation ; confirmez les minimums par variante.','Vérifiez ajustement, découpes, boutons, finition et protection. Confirmez photos utilisables, descriptions de compatibilité et étiquettes selon l’échantillon.','Vérifiez les exigences actuelles de fiche, emballage, étiquetage et traitement des commandes dans votre compte Noon, Amazon ou Jumia. Prévoyez frais, retours, publicité, fret et réassort.'],'Puis-je commencer sur Noon, Amazon ou Jumia avec une petite commande de coques ?','Envoyez plateforme, pays, mode logistique, modèles, quantités et budget. Minimums, emballage et expédition restent à confirmer ; le sourcing ne garantit ni validation des fiches, ni autorisation de marque, ni bénéfice.','Comparer matières et coûts d’achat des coques'],
 ],
 pt:[
  ['Cafeteria pequena com pouco investimento: equipamentos básicos da China','Defina o cardápio e as xícaras por hora de pico. Compre capacidade para abrir, sem copiar uma cafeteria maior.',['Confira máquina de café, moedor, tratamento de água, refrigeração do leite, lavagem e preparo conforme o cardápio. Confirme modelos e instalações.','Inclua máquina de gelo, liquidificador, vitrine ou equipamentos de refeições leves apenas se necessários. Cote base e expansão separadamente.','Separe equipamentos, embalagem e entrega de hidráulica, elétrica, drenagem e instalação. Informe moeda, espaço e demanda máxima.'],'Posso abrir uma cafeteria pequena com equipamentos de entrada?','Peça uma seleção conforme o cardápio e confira amostras ou especificações. O projeto existente é um conceito de referência, não uma lista de menor custo; modelos e itens precisam de cotação.','Ver o conceito de equipamentos para cafeteria'],
  ['Equipamentos econômicos da China para bares e coquetelarias','Planeje conforme bebidas, consumo de gelo e velocidade de serviço. Um cardápio enxuto reduz o escopo da primeira compra.',['Liste produção e armazenamento de gelo, refrigeração sob bancada, lavagem de copos, pias e preparo. Confirme funções e modelos incluídos.','Solicite liquidificadores, extratores, utensílios de coquetelaria e exposição conforme a necessidade. São itens a buscar e confirmar, não um kit completo aprovado.','Confira drenagem, água, energia, ruído, limpeza e instalação local. Separe o essencial da abertura dos aumentos de capacidade.'],'Como reduzir o investimento inicial de uma coquetelaria?','Compare cardápio reduzido e equipamentos essenciais com uma opção de expansão. Confira gelo e refrigeração antes de escolher máquinas mais baratas; envie destino, cardápio e orçamento para cotação discriminada.','Comparar máquinas de gelo comerciais'],
  ['Como encontrar fornecedores econômicos de caixas de som Bluetooth para festas na China','Compare fornecedores com a mesma especificação. O menor preço anunciado pode ter outros alto-falantes, bateria, acessórios ou embalagem.',['Iguale componentes, método de teste de potência contínua, bateria, reprodução e microfones. Potência de pico não equivale a potência contínua testada.','Teste som no volume previsto, estabilidade da conexão, bateria e microfones. Peça documentos do modelo exato para o destino.','Separe mínimos, amostras, embalagem, marca, peças e frete. Solicite configuração de estoque e opção superior.'],'Vocês encontram as caixas Bluetooth para festas mais baratas para revenda?','Podemos coordenar cotações comparáveis conforme preço-alvo e quantidade, sem garantir o menor preço do mercado. Escolha após conferir amostras, especificação e escopo completo da compra.','Solicitar comparação de fornecedores e cotações'],
  ['Começar um ecommerce de capas com baixo investimento: Noon, Amazon e Jumia','Planeje a compra da China para sua plataforma e país. É uma compra de produtos, não gestão de conta ou garantia de vendas.',['Escolha modelos exatos, materiais e poucas cores. Compare estoque e personalização; confirme os mínimos por variante.','Confira encaixe, recortes, botões, acabamento e proteção. Confirme fotos utilizáveis, descrição de compatibilidade e etiquetas conforme a amostra.','Consulte as regras atuais de anúncio, embalagem, etiquetas e processamento de pedidos na sua conta Noon, Amazon ou Jumia. Reserve taxas, devoluções, publicidade, frete e reposição.'],'Posso começar na Noon, Amazon ou Jumia com um pedido pequeno de capas?','Envie plataforma, país, método logístico, modelos, quantidades e orçamento. Mínimos, embalagem e envio exigem confirmação; a compra não garante aprovação do anúncio, autorização de marca ou lucro.','Comparar materiais e custos de compra de capas'],
 ],
 tr:[
  ['Küçük kafe için düşük maliyetli ekipman: Çin’den temel tedarik','Menüyü ve yoğun saatteki fincan sayısını belirleyin. Büyük kafe listesini kopyalamak yerine açılış kapasitesini satın alın.',['Menüye göre kahve makinesi ve değirmen, su arıtma, süt soğutma, yıkama ve hazırlığı değerlendirin. Modelleri ve tesisatı teyit edin.','Buz makinesi, blender, soğutmalı vitrin veya hafif yemek ekipmanını yalnızca gerekiyorsa ekleyin. Temel ve genişleme tekliflerini ayırın.','Ekipman, ambalaj ve teslimatı su, elektrik, gider ve kurulumdan ayırın. Para birimi, alan ve yoğun saat talebini belirtin.'],'Küçük bir kafe giriş seviyesi ekipmanla açılabilir mi?','Menüye göre kısa liste ve numune veya özellik incelemesi isteyin. Mevcut kafe planı referans konsepttir, en düşük maliyet listesi değildir; model ve içerik teklif gerektirir.','Kafe ekipman konseptini inceleyin'],
  ['Bar ve kokteyl barı için Çin’den ekonomik ekipman','Listeyi içecek, buz ihtiyacı ve servis hızına göre hazırlayın. Sınırlı menü ilk alım kapsamını daraltır.',['Buz üretimi ve depolama, tezgâh altı soğutma, bardak yıkama, evye ve hazırlık alanını listeleyin. Dahil işlev ve modelleri teyit edin.','Blender, meyve sıkacağı, kokteyl araçları ve teşhir ekipmanını ihtiyaca göre isteyin. Bunlar aranıp teyit edilecek kalemlerdir; hazır onaylı bar seti değildir.','Gider, su kalitesi, elektrik, gürültü, temizlik ve yerel kurulumu kontrol edin. Açılış ihtiyaçlarını sonraki kapasite artışından ayırın.'],'Kokteyl barının ilk ekipman maliyeti nasıl azaltılır?','Sınırlı menü ve temel planı genişleme seçeneğiyle karşılaştırın. Ucuz model seçmeden buz ve soğutma kapasitesini kontrol edin; kalemli teklif için varış, menü ve bütçe gönderin.','Ticari buz makinelerini karşılaştırın'],
  ['Çin’de uygun fiyatlı Bluetooth parti hoparlörü tedarikçisi nasıl bulunur?','Tedarikçileri aynı teknik özelliklerle karşılaştırın. En düşük ilan fiyatı farklı sürücü, batarya, aksesuar veya ambalajı kapsayabilir.',['Sürücü, sürekli güç test yöntemi, batarya, çalma koşulları ve mikrofonları eşitleyin. Tepe güç test edilmiş sürekli güç değildir.','Numunede hedef ses düzeyi, bağlantı kararlılığı, batarya ve mikrofonu kontrol edin. Tam model ve hedef ülke için belgeleri isteyin.','Minimum sipariş, numune, ambalaj, marka, yedek parça ve nakliyeyi ayırın. Stok yapılandırması ve geliştirilmiş seçenek isteyin.'],'Yeniden satış için en ucuz Bluetooth parti hoparlörlerini bulabilir misiniz?','Hedef fiyat ve miktara göre karşılaştırılabilir teklifler koordine edilebilir; piyasanın en düşük fiyatı garanti edilmez. Numune, özellikler ve toplam satın alma kapsamını kontrol ederek seçin.','Tedarikçi ve teklif karşılaştırması isteyin'],
  ['Düşük bütçeyle telefon kılıfı e-ticareti: Noon, Amazon ve Jumia satıcıları','Çin’den alımı platform ve ülkeye göre planlayın. Bu ürün satın alma planıdır; hesap yönetimi veya satış garantisi değildir.',['Tam telefon modelleri, malzemeler ve az sayıda renk seçin. Stok ile markalı üretimi karşılaştırın; varyant minimumlarını teyit edin.','Uyum, kesikler, tuşlar, yüzey ve paket korumasını inceleyin. Kullanılabilir fotoğraf, uyumluluk açıklaması ve etiketleri numuneye göre onaylayın.','Noon, Amazon veya Jumia hesabınızda güncel listeleme, ambalaj, etiket ve sipariş karşılama koşullarını kontrol edin. Platform, iade, reklam, nakliye ve yeniden sipariş bütçesini ayırın.'],'Noon, Amazon veya Jumia’da küçük bir kılıf siparişiyle başlayabilir miyim?','Platform, ülke, lojistik yöntem, modeller, miktarlar ve bütçeyi gönderin. Minimumlar, ambalaj ve sevkiyat teyit gerektirir; tedarik, listeleme onayı, marka izni veya kâr garantisi sağlamaz.','Kılıf malzemelerini ve satın alma maliyetini karşılaştırın'],
 ],
};
