// Fixed reviewed values from the 2026-09-28 inventory and existing form routes.
// Free destination text belongs in the local brief, never in an enum or href.
export const QUOTE_ENUMS = Object.freeze({
  "leadGoal": [
    "Freight Export",
    "Freight Only",
    "Product Sourcing",
    "Supplier Inspection & Consolidation"
  ],
  "source": [
    "air_freight",
    "amazon_fba",
    "article",
    "audio_assortments",
    "audio_category",
    "audio_speakers",
    "brazil_pt_freight",
    "central_asia_route_builder",
    "commercial_kitchen_product",
    "consolidation_export_service",
    "country_cargo_planning",
    "dangerous_goods_shipping",
    "film_guide",
    "food_processing",
    "footer_primary",
    "freight_region_latin-america",
    "freight_region_middle-east",
    "freight_region_west-africa",
    "ghana_country",
    "homepage_faq_bottom",
    "homepage_navigation",
    "homepage_sourcing_selector",
    "homepage_v2",
    "homepage_v2_freight",
    "how_we_work",
    "international_country",
    "kitchen_catalogue",
    "kitchen_category",
    "lcl_shipping",
    "market_sourcing_handoff",
    "mexico_country",
    "nigeria_country",
    "outdoor_products",
    "phone_cases",
    "products_index",
    "quality_control_service",
    "quote_page",
    "refrigeration_equipment_product",
    "refrigeration_product",
    "restaurant_kitchen_package",
    "restaurant_kitchen_packages",
    "restaurant_kitchen_scenario",
    "screen_protector_localized",
    "screen_protector_localized_manual",
    "screen_protector_planner",
    "sea_freight_fieldwork",
    "sourcing_decisions",
    "sourcing_services",
    "sourcing_services_turkiye_case",
    "startup_plan",
    "supplier_search_service",
    "uae_country",
    "warehouse_services"
  ],
  "dest": [
    "Arabia Saudita",
    "Arabie Saoudite",
    "Argentina",
    "Argentine",
    "Arjantin",
    "Arábia Saudita",
    "Asia Central y Rusia",
    "Asie centrale et Russie",
    "Bahrain",
    "Bahreyn",
    "Bahreïn",
    "Barein",
    "Batı Afrika",
    "Birleşik Arap Emirlikleri",
    "Brasil",
    "Brazil",
    "Brezilya",
    "Brésil",
    "Catar",
    "Cazaquistão",
    "Central Asia & Russia",
    "Chile",
    "Chili",
    "EAU",
    "Emirados Árabes Unidos",
    "Gana",
    "Ghana",
    "Istanbul, Turkey",
    "Katar",
    "Kazajistán",
    "Kazakhstan",
    "Kazakistan",
    "Kirghizistan",
    "Kirguistán",
    "Koweït",
    "Kuveyt",
    "Kuwait",
    "Kyrgyzstan",
    "Kırgızistan",
    "Latin America",
    "Latin Amerika",
    "Latinoamérica",
    "Meksika",
    "Mexico",
    "Mexique",
    "México",
    "Nigeria",
    "Nigéria",
    "Nijerya",
    "Oman",
    "Omã",
    "Oriente Medio",
    "Orta Asya ve Rusya",
    "Orta Doğu",
    "Other",
    "Ouzbékistan",
    "Peru",
    "Perú",
    "Poland",
    "Pérou",
    "Qatar",
    "Quirguistão",
    "Rusia",
    "Russia",
    "Russie",
    "Rusya",
    "Rússia",
    "Saudi Arabia",
    "Suudi Arabistan",
    "Tacikistan",
    "Tadjikistan",
    "Tadjiquistão",
    "Tajikistan",
    "Tayikistán",
    "Turcomenistão",
    "Turkey",
    "Turkmenistan",
    "Turkmenistán",
    "Turkménistan",
    "Türkiye",
    "Türkmenistan",
    "UAE",
    "Umman",
    "Uzbekistan",
    "Uzbekistán",
    "Uzbequistão",
    "West Africa",
    "a América Latina",
    "a África Ocidental",
    "le Moyen-Orient",
    "l’Afrique de l’Ouest",
    "l’Amérique latine",
    "o Oriente Médio",
    "the Middle East",
    "África Occidental",
    "Ásia Central e Rússia",
    "Özbekistan",
    "Şili",
    "Аргентина",
    "Бахрейн",
    "Ближний Восток",
    "Бразилия",
    "Гана",
    "Западную Африку",
    "Казахстан",
    "Катар",
    "Кувейт",
    "Кыргызстан",
    "Латинскую Америку",
    "Мексика",
    "Нигерия",
    "ОАЭ",
    "Оман",
    "Перу",
    "Россия",
    "Саудовская Аравия",
    "Таджикистан",
    "Туркменистан",
    "Узбекистан",
    "Центральная Азия и Россия",
    "Чили",
    "آسيا الوسطى وروسيا",
    "أمريكا اللاتينية",
    "أوزبكستان",
    "الأرجنتين",
    "الإمارات",
    "البحرين",
    "البرازيل",
    "السعودية",
    "الشرق الأوسط",
    "الكويت",
    "المكسيك",
    "بيرو",
    "تركمانستان",
    "تشيلي",
    "روسيا",
    "طاجيكستان",
    "عُمان",
    "غانا",
    "غرب أفريقيا",
    "قطر",
    "قيرغيزستان",
    "كازاخستان",
    "نيجيريا",
    "中东",
    "中亚五国及俄罗斯",
    "乌兹别克斯坦",
    "俄罗斯",
    "卡塔尔",
    "吉尔吉斯斯坦",
    "哈萨克斯坦",
    "土库曼斯坦",
    "塔吉克斯坦",
    "巴林",
    "巴西",
    "拉美",
    "智利",
    "沙特",
    "科威特",
    "秘鲁",
    "西非",
    "阿曼",
    "阿根廷"
  ],
  "subcategory": [
    "Bar and Beverage",
    "Commercial Cooking",
    "Commercial Cooking, Commercial Refrigeration",
    "Commercial Refrigeration",
    "Food processing equipment",
    "Insulated Coolers",
    "Mixed-SKU Retail Packing",
    "Outdoor and Portable Refrigeration, Accessories and Power",
    "Protection and Mounting",
    "Protection and Mounting, Supplier Verification and Control",
    "Screen protectors",
    "Stainless and Turnkey Kitchen",
    "accessory-startup",
    "bar-equipment-budget",
    "kitchen-budget",
    "marketplace-seller-startup",
    "party-speaker-budget",
    "restaurant-startup",
    "retail-privacy",
    "small-cafe-budget"
  ],
  "phoneLocale": [
    "ar",
    "en",
    "es",
    "fr",
    "pt",
    "ru",
    "tr",
    "zh",
    "zh-cn"
  ],
  "cargo": [
    "Carga general",
    "Carga geral",
    "Fret général",
    "Genel yük",
    "General cargo",
    "Обычный груз",
    "بضاعة عامة",
    "普货"
  ],
  "mode": [
    "Comparar carretera y tren",
    "Comparar rodovia e ferrovia",
    "Compare road and rail",
    "Comparer route et rail",
    "Kara ve demiryolunu karşılaştır",
    "Сравнить авто и ЖД",
    "قارن البر والسكك",
    "比较汽运与铁路"
  ],
  "model": [
    "CK-129",
    "CK-136",
    "KB-D55-4",
    "ZH-101V",
    "ZH-102V",
    "ZH-818",
    "ZH-820",
    "ZH-8A",
    "cold-13",
    "cold-15",
    "cold-2",
    "cold-3",
    "cold-4",
    "cold-42",
    "cold-5",
    "cold-6",
    "cold-7",
    "cold-8",
    "eboom-lxyt24",
    "ecoflow-classic",
    "ecoflow-max",
    "ice-39",
    "ice-49",
    "ice-58",
    "ice-61",
    "ice-64",
    "ice-69",
    "juice-1200",
    "juice-500",
    "sanhe-bg",
    "sanhe-st",
    "tieding-51"
  ]
});
