import React, { useState } from 'react';
import { ArrowRight, Plus, Check, Minus, Trash2 } from 'lucide-react';
import { machines, packages, machineById, money, sourceDate, selectionTotals, packageSelection, inquiryUrl, foodProcessingPath } from './catalog.mjs';
import { categoryPages, categoryPath, packagePath } from './pages.mjs';

export function FoodPackageLinks({ compact = false }) {
  return <div className={`fp-package-grid${compact ? ' fp-package-grid-compact' : ''}`}>
    {packages.map((p,index)=>{const totals=selectionTotals(packageSelection(p));return <a className="fp-package-link" href={`${packagePath(p)}/`} key={p.id}>
      <span className="fp-overline">0{index+1} / {p.items.length} machines</span><h3>{p.title}</h3><p>{p.description}</p>
      <strong>{money(totals.equipment)} <small>equipment</small></strong><span className="fp-package-bottom">View equipment & costs <ArrowRight size={17}/></span>
    </a>;})}
  </div>;
}
function PriceNote(){return <p className="fp-price-note">DDNZ indicative supply prices in CNY, updated <time dateTime="2026-09-24">24 September 2026</time>. Equipment and listed packing are shown separately. Confirm current availability, tax treatment, optional parts, export packing, freight and service fees in your quotation. Catalogue images represent model families.</p>;}
export default function FoodProcessingContent({ page }) {
  const [family,setFamily]=useState('all');
  const [selection,setSelection]=useState(()=>page.bundle?packageSelection(page.bundle):{});
  const [destination,setDestination]=useState('');
  const [requirement,setRequirement]=useState('');
  const [notice,setNotice]=useState('');
  const totals=selectionTotals(selection);
  const visible=page.machines.filter(m=>family==='all'||m.family===family);
  const localFamilies=[...new Set(page.machines.map(m=>m.family))];
  const familyNames={dough:'Dough & noodles',bakery:'Bakery',meat:'Meat',vegetables:'Vegetables',grain:'Bean, rice & juice',poultry:'Poultry'};
  const setQuantity=(id,value)=>{const q=Math.max(0,Math.min(99,Math.floor(Number(value)||0)));setSelection(current=>{const next={...current};if(q)next[id]=q;else delete next[id];return next;});};
  const add=(m)=>{setQuantity(m.id,(selection[m.id]||0)+1);setNotice(`${m.model} added to your equipment list.`);};
  const hero=page.bundle?page.machines:page.kind==='hub'?[machineById.h20,machineById['jr-gg22'],machineById['dq-ps300-copper']]:page.machines.slice(0,3);
  return <main className="fp-page" id="main-content">
    <div className="fp-wrap">
      <nav className="fp-breadcrumb" aria-label="Breadcrumb"><a href="/products/">Products</a><span>/</span>{page.kind==='hub'?<span>Food processing</span>:<><a href={`${foodProcessingPath}/`}>Food processing</a><span>/</span><span>{page.title}</span></>}</nav>
      <section className="fp-hero" aria-labelledby="fp-title">
        <div><p className="fp-overline">CHINA SOURCING / FOOD PREPARATION</p><h1 id="fp-title">{page.title}</h1><p className="fp-lead">{page.intro}</p><div className="fp-actions"><a className="fp-primary" href="#equipment">Compare equipment <ArrowRight size={17}/></a><a className="fp-secondary" href={page.kind==='package'?'#your-list':'#packages'}>{page.kind==='package'?'Review this package':'Explore equipment packages'}</a></div><div className="fp-facts"><span><b>{page.machines.length}</b> selected models</span><span><b>CNY</b> wholesale prices</span><span><b>01</b> combined enquiry</span></div></div>
        <div className="fp-hero-media"><div className="fp-machine-stage">{hero.map(m=><img key={m.id} src={`/food-processing-media/${m.image}.webp`} alt={`${m.name}, ${m.model} model family`} width="500" height="500"/>)}</div><p>Equipment for your next preparation step.<span>Supplier catalogue imagery · configuration confirmed per model</span></p></div>
      </section>
      <PriceNote/>
      {page.kind==='hub'&&<section className="fp-section" aria-labelledby="family-heading"><p className="fp-overline">EXPLORE THE RANGE</p><h2 id="family-heading">Choose a preparation function.</h2><div className="fp-family-grid">{categoryPages.map((c,i)=><a href={`${categoryPath(c)}/`} key={c.slug}><span>0{i+1}</span><h3>{c.title}</h3><p>{c.intro}</p><strong>Compare this range <ArrowRight size={16}/></strong></a>)}</div><p className="fp-caption">Poultry pluckers are also included in the equipment catalogue below.</p></section>}
      {page.category&&<section className="fp-section fp-guide"><p className="fp-overline">BEFORE YOU COMPARE</p><h2>Match the machine to the job.</h2><ol>{page.category.checks.map(t=><li key={t}>{t}</li>)}</ol></section>}
      {page.bundle&&<section className="fp-section fp-workflow"><p className="fp-overline">PACKAGE SCOPE</p><h2>From ingredient to preparation step.</h2><ol>{page.bundle.steps.map((step,i)=><li key={step}><span>0{i+1}</span>{step}</li>)}</ol><p>{page.bundle.extra}</p><p className="fp-caption">A proposed equipment selection, with one of each machine. Quantities can be changed below. Recipe trials and capacity matching are required before confirming a working process.</p></section>}
      {page.kind==='hub'&&<section className="fp-section" id="packages"><p className="fp-overline">BUILD BY APPLICATION</p><h2>Start with a practical combination.</h2><p className="fp-lead-small">Each package has a machine list, separate packing costs and a clear scope. Adjust quantities to match your project.</p><FoodPackageLinks/></section>}
      {page.category&&<section className="fp-section" id="packages"><p className="fp-overline">RELATED EQUIPMENT PACKAGES</p><h2>Bring the machines together.</h2><div className="fp-related">{page.bundles.map(p=><a href={`${packagePath(p)}/`} key={p.id}>{p.title} <ArrowRight size={16}/></a>)}</div></section>}
      <section className="fp-section" id="equipment" aria-labelledby="equipment-heading"><div className="fp-section-heading"><div><p className="fp-overline">MODELS / CONFIGURATIONS / PRICES</p><h2 id="equipment-heading">{page.bundle?'The machines in this package.':'Compare the equipment.'}</h2></div><a href="#your-list">Your list ({totals.units}) ↓</a></div>
        {localFamilies.length>1&&<div className="fp-filters" aria-label="Filter equipment"><button type="button" aria-pressed={family==='all'} onClick={()=>setFamily('all')}>All ({page.machines.length})</button>{localFamilies.map(f=><button type="button" aria-pressed={family===f} key={f} onClick={()=>setFamily(f)}>{familyNames[f]}</button>)}</div>}
        <div className="fp-equipment-grid">{visible.map(m=><article className="fp-machine" id={`machine-${m.id}`} key={m.id}>
          <div className="fp-machine-image"><img src={`/food-processing-media/${m.image}.webp`} alt={`${m.model} ${m.name} model-family catalogue image`} width="420" height="360" loading="lazy"/></div><div className="fp-machine-copy"><p className="fp-overline">{m.model}</p><h3>{m.name}</h3><p className="fp-variant">{m.variant}</p><div className="fp-machine-price"><strong>{money(m.price)}</strong><span>per machine</span></div><p className="fp-packing">{m.packing?`${m.packingType}: +${money(m.packing)}`:m.packingType}</p><details><summary>Specifications & buying notes</summary><dl><dt>Power</dt><dd>{m.power}</dd><dt>Machine size</dt><dd>{m.dimensions}</dd><dt>Listed weight</dt><dd>{m.weight} kg</dd></dl><p>{m.note}</p><p>Confirm voltage, frequency, safeguards, packed dimensions and gross weight before shipment.</p><small>Price list p. {m.pricePage}; catalogue PDF p. {m.catalogPage}. Size and weight follow the price list.</small></details><button className="fp-add" type="button" onClick={()=>add(m)} disabled={(selection[m.id]||0)>=99}>{selection[m.id]?<Check size={16}/>:<Plus size={16}/>} {selection[m.id]?`Add another · ${selection[m.id]} in list`:'Add to equipment list'}</button></div>
        </article>)}</div><p className="fp-live" role="status" aria-live="polite">{notice}</p>
      </section>
      <section className="fp-section fp-list" id="your-list" aria-labelledby="list-heading"><div><p className="fp-overline">YOUR EQUIPMENT LIST</p><h2 id="list-heading">One list. Itemised costs.</h2><p>Bring model, quantity and destination together for a scoped quotation.</p>
        {totals.units>0?<><div className="fp-list-items">{Object.entries(selection).map(([id,q])=>{const m=machineById[id];return <div className="fp-list-item" key={id}><div><strong>{m.model} · {m.name}</strong><small>{m.variant}</small><small>{money(m.price)} each · packing {money(m.packing)} each</small></div><div className="fp-quantity"><button type="button" aria-label={`Decrease ${m.model} quantity`} onClick={()=>setQuantity(id,q-1)}><Minus size={14}/></button><input aria-label={`${m.model} quantity`} type="number" min="1" max="99" step="1" value={q} onChange={e=>setQuantity(id,e.target.value)}/><button type="button" aria-label={`Increase ${m.model} quantity`} disabled={q>=99} onClick={()=>setQuantity(id,q+1)}><Plus size={14}/></button></div><strong>{money(m.price*q)}</strong><button className="fp-remove" type="button" aria-label={`Remove ${m.model}`} onClick={()=>setQuantity(id,0)}><Trash2 size={16}/></button></div>;})}</div><button className="fp-text-button" type="button" onClick={()=>{setSelection({});setNotice('Equipment list cleared.');}}>Clear equipment list</button></>:<p className="fp-empty">Your list is empty. Add individual machines above, or open a package to start with its equipment selection.</p>}
      </div><aside className="fp-summary"><h3>Equipment cost summary</h3><dl><dt>Equipment ({totals.units} units)</dt><dd>{money(totals.equipment)}</dd><dt>Listed packing additions</dt><dd>{money(totals.packing)}</dd><dt className="fp-total">Equipment + listed packing</dt><dd className="fp-total">{money(totals.equipment+totals.packing)}</dd></dl><p>Excludes unconfirmed options, export packing upgrades, freight, tax and service fees.</p><label htmlFor="fp-destination">Destination country / city</label><input id="fp-destination" value={destination} onChange={e=>setDestination(e.target.value)} placeholder="e.g. Almaty, Kazakhstan" maxLength={160}/><label htmlFor="fp-requirements">Recipe, output & power requirements</label><textarea id="fp-requirements" value={requirement} onChange={e=>setRequirement(e.target.value)} placeholder="Ingredients, batch size, voltage, frequency and any required accessories" maxLength={1500}/>{totals.units>0?<a className="fp-primary" href={inquiryUrl(selection,destination,requirement)}>Continue to quotation <ArrowRight size={17}/></a>:<a className="fp-secondary" href="#equipment">Choose equipment first ↑</a>}<small>You will review the details on our enquiry form before submitting.</small></aside></section>
      {page.category&&<section className="fp-section fp-faq"><p className="fp-overline">BUYING QUESTIONS</p><h2>Details worth checking.</h2>{page.category.faq.map(f=><details key={f.q}><summary>{f.q}</summary><p>{f.a}</p></details>)}</section>}
      {page.bundle&&<section className="fp-section"><h2>Compare other configurations.</h2><div className="fp-related">{categoryPages.filter(c=>page.bundle.items.some(id=>c.families.includes(machineById[id].family))).map(c=><a href={`${categoryPath(c)}/`} key={c.slug}>{c.title} <ArrowRight size={16}/></a>)}<a href={`${foodProcessingPath}/#packages`}>All food preparation packages <ArrowRight size={16}/></a></div></section>}
      <section className="fp-section fp-services"><p className="fp-overline">FROM SELECTION TO SHIPMENT</p><h2>Connect your equipment order to the next service.</h2><div className="fp-service-grid"><a href="/sourcing-services/supplier-search/"><h3>Supplier comparison</h3><p>Confirm model, motor, blades, guards and included parts against one buying brief.</p></a><a href="/sourcing-services/inspection-quality-control/"><h3>Pre-shipment inspection</h3><p>Scope functional checks, selected configuration, accessories and packing records.</p></a><a href="/sourcing-services/consolidation-export/"><h3>Consolidation & export</h3><p>Combine equipment orders and confirm packed sizes, gross weights and documents.</p></a><a href="/shipping-from-china-to-central-asia/"><h3>Shipping to Central Asia</h3><p>Plan the route after the destination, packing and cargo details are confirmed.</p></a></div><p>Planning cooking or cold storage too? <a href="/sourcing/commercial-kitchen-equipment-from-china/">Compare commercial kitchen equipment</a>. For a whole bakery fit-out, explore <a href="/sourcing/restaurant-kitchen-packages-from-china/bakery-pastry/">bakery & pastry kitchen packages</a>.</p></section>
    </div>
  </main>;
}
