import React, { useState } from 'react';
import { machines, packages, machineById, money, selectionTotals, packageSelection, foodProcessingPath } from './catalog.mjs';
import { categoryPages, categoryPath, packagePath } from './pages.mjs';
import { foodLocales, foodPrefix, localizedFoodInquiry, type FoodLocale } from './localization';
import { overviewCopy } from '../overview/copy';
import { serviceCopy } from '../sourcing-services/copy';
export default function LocalizedFoodContent({page,locale}:{page:any;locale:FoodLocale}) {
 const c=foodLocales[locale],u=c.ui,o=overviewCopy[locale],prefix=foodPrefix(locale);
 const [selection,setSelection]=useState<Record<string,number>>(()=>page.bundle?packageSelection(page.bundle):{});
 const [family,setFamily]=useState('all');
 const [destination,setDestination]=useState('');
 const [requirement,setRequirement]=useState('');
 const [notice,setNotice]=useState('');
 const totals=selectionTotals(selection);
 const families=['dough','bakery','meat','vegetables','grain','poultry'];
 const quantity=(id:string,value:number)=>{const q=Math.max(0,Math.min(99,Math.floor(value)||0));setSelection(current=>{const next={...current};if(q)next[id]=q;else delete next[id];return next;});};
 const localLink=(path:string)=>`${prefix}${path}/`;
 const bundleCard=(bundle:any)=>{const i=packages.indexOf(bundle),t=selectionTotals(packageSelection(bundle));return <a className="fp-package-link" key={bundle.id} href={localLink(packagePath(bundle))}><h3>{o.packageNames[i]}</h3><p>{o.packageDescriptions[i]}</p><strong dir="ltr">{money(t.equipment)}</strong><span>{u.equipment}</span><p>{u.packing}: <bdi>{money(t.packing)}</bdi></p></a>;};
 return <main id="main-content" className="fp-page" lang={locale==='zh'?'zh-CN':locale} dir={locale==='ar'?'rtl':'ltr'}><div className="fp-wrap">
 <nav className="fp-breadcrumb" aria-label={u.products}><a href={`${prefix}/products/`}>{u.products}</a><span>/</span><a href={localLink(foodProcessingPath)}>{u.catalogueTitle}</a></nav>
 <section className="fp-hero"><div><p className="fp-overline">{u.source}</p><h1>{page.title}</h1><p className="fp-lead">{page.intro}</p><div className="fp-actions"><a className="fp-primary" href="#equipment">{u.compare}</a><a className="fp-secondary" href="#your-list">{u.list}</a></div></div><div className="fp-hero-media"><div className="fp-machine-stage">{page.machines.slice(0,3).map((m:any)=><img key={m.id} src={`/food-processing-media/${m.image}.webp`} alt={`${c.names[machines.indexOf(m)]} ${m.model}`} width="500" height="500"/>)}</div><p>{u.imageNote}</p></div></section>
 <p className="fp-price-note">{o.priceNote}</p>
 {page.kind==='hub'&&<section className="fp-section"><h2>{u.catalogueTitle}</h2><div className="fp-family-grid">{categoryPages.map((category,i)=><a key={category.slug} href={localLink(categoryPath(category))}><h3>{c.categories[i][0]}</h3><p>{c.categories[i][1]}</p></a>)}</div></section>}
 {page.bundle&&<section className="fp-section fp-workflow"><h2>{u.scope}</h2><p>{c.scopes[page.bundleIndex]}</p><p>{u.selectionNote}</p></section>}
 {page.bundles.length>0&&<section id="packages" className="fp-section"><h2>{u.packages}</h2><div className="fp-package-grid">{page.bundles.map(bundleCard)}</div></section>}
 <section id="equipment" className="fp-section"><div className="fp-section-heading"><h2>{u.compare}</h2><a href="#your-list">{u.list} ({totals.units})</a></div>
 <div className="fp-filters" aria-label={u.catalogueTitle}><button type="button" aria-pressed={family==='all'} onClick={()=>setFamily('all')}>{u.all}</button>{families.filter(f=>page.machines.some((m:any)=>m.family===f)).map(f=><button key={f} type="button" aria-pressed={family===f} onClick={()=>setFamily(f)}>{c.families[families.indexOf(f)]}</button>)}</div>
 <div className="fp-equipment-grid">{page.machines.filter((m:any)=>family==='all'||m.family===family).map((m:any)=>{const i=machines.indexOf(m);return <article className="fp-machine" id={`machine-${m.id}`} key={m.id}><div className="fp-machine-image"><img src={`/food-processing-media/${m.image}.webp`} alt={`${m.model} ${c.names[i]}`} width="420" height="360" loading="lazy"/></div><div className="fp-machine-copy"><p className="fp-overline"><bdi>{m.model}</bdi></p><h3>{c.names[i]}</h3><p className="fp-variant">{c.variants[i]}</p><div className="fp-machine-price"><strong dir="ltr">{money(m.price)}</strong><span>{u.unit}</span></div><p className="fp-packing">{c.packingTypes[m.packingType as keyof typeof c.packingTypes]}: <bdi>{money(m.packing)}</bdi></p><details><summary>{u.specs}</summary><dl><dt>{u.power}</dt><dd dir="ltr">{m.power}</dd><dt>{u.size}</dt><dd dir="ltr">{m.dimensions}</dd><dt>{u.weight}</dt><dd dir="ltr">{m.weight} kg</dd></dl><p>{c.notes[i]}</p><p>{u.confirm}</p><small>{u.sourcePages}: {u.priceList} {m.pricePage} · {u.catalogue} {m.catalogPage}</small></details><button type="button" className="fp-add" disabled={selection[m.id]>=99} onClick={()=>{quantity(m.id,(selection[m.id]||0)+1);setNotice(`${m.model}: ${u.added}`);}}>{u.add}{selection[m.id]?` (${selection[m.id]})`:''}</button></div></article>;})}</div><p role="status" aria-live="polite">{notice}</p></section>
 <section id="your-list" className="fp-section fp-list"><div><h2>{u.list}</h2>{totals.units>0?<><div className="fp-list-items">{Object.entries(selection).map(([id,q])=>{const m=machineById[id],i=machines.indexOf(m);return <div className="fp-list-item" key={id}><div><strong><bdi>{m.model}</bdi> · {c.names[i]}</strong><small>{c.variants[i]}</small><small>{u.unit}: <bdi>{money(m.price)}</bdi> · {u.packing}: <bdi>{money(m.packing)}</bdi></small></div><div className="fp-quantity"><button type="button" aria-label={`${u.decrease} ${m.model}`} onClick={()=>quantity(id,q-1)}>−</button><input type="number" min="1" max="99" step="1" aria-label={`${m.model} ${u.quantity}`} value={q} onChange={e=>quantity(id,Number(e.target.value))}/><button type="button" disabled={q>=99} aria-label={`${u.increase} ${m.model}`} onClick={()=>quantity(id,q+1)}>+</button></div><strong dir="ltr">{money(m.price*q)}</strong><button type="button" className="fp-remove" aria-label={`${u.remove} ${m.model}`} onClick={()=>quantity(id,0)}>×</button></div>;})}</div><button type="button" className="fp-text-button" onClick={()=>{setSelection({});setNotice(u.cleared);}}>{u.clear}</button></>:<p className="fp-empty">{u.empty}</p>}</div>
 <aside className="fp-summary"><h3>{u.total}</h3><dl><dt>{u.equipment} ({totals.units})</dt><dd dir="ltr">{money(totals.equipment)}</dd><dt>{u.packing}</dt><dd dir="ltr">{money(totals.packing)}</dd><dt className="fp-total">{u.total}</dt><dd className="fp-total" dir="ltr">{money(totals.equipment+totals.packing)}</dd></dl><p>{u.exclude}</p><label htmlFor="fp-destination">{u.destination}</label><input id="fp-destination" value={destination} onChange={e=>setDestination(e.target.value)} maxLength={160}/><label htmlFor="fp-requirements">{u.requirements}</label><textarea id="fp-requirements" value={requirement} onChange={e=>setRequirement(e.target.value)} maxLength={1500}/>{totals.units>0?<a className="fp-primary" href={localizedFoodInquiry(selection,destination,requirement,locale)}>{u.continue}</a>:<a className="fp-secondary" href="#equipment">{u.compare}</a>}<small>{u.review}</small></aside></section>
 <section className="fp-section"><h2>{u.related}</h2><div className="fp-related"><a href={localLink(foodProcessingPath)}>{u.catalogueTitle}</a>{categoryPages.filter(category=>page.machines.some((m:any)=>category.families.includes(m.family))).map(category=><a key={category.slug} href={localLink(categoryPath(category))}>{c.categories[categoryPages.indexOf(category)][0]}</a>)}</div></section>
 <section className="fp-section fp-services"><h2>{u.services}</h2><div className="fp-service-grid">{(['supplier-search','inspection-quality-control','consolidation-export'] as const).map(id=><a key={id} href={`${prefix}/sourcing-services/${id}/`}><h3>{serviceCopy[id][locale].eyebrow}</h3><p>{serviceCopy[id][locale].intro}</p></a>)}</div></section>
 </div></main>;
}
