import { foodProcessingPath as root, foodProcessingMeta, machines, packages, machineById } from './catalog.mjs';
export const categoryPages = [
  { slug: 'dough-and-bakery-machinery', title: 'Dough & bakery machinery', keyword: 'commercial dough and bakery machinery', families: ['dough','bakery'], intro: 'Compare kneaders, spiral mixers, planetary mixers, dough rollers and bread slicers by the job they perform. Select a motor and guard configuration before comparing prices.', checks: ['Kneaders and spiral mixers handle dough; a planetary mixer provides a different attachment-based mixing function.', 'A bowl volume is not a flour capacity. Supply recipe, batch weight and hydration when requesting a working trial.', 'Confirm guard and interlock configuration, speed control, available electrical supply and the selected roller or cutter.'], faq: [{q:'Does the H20 model mean 20 kg of flour?',a:'No. The catalogue lists a 20 L bowl and a maximum flour capacity of 8 kg for H20. Confirm recipe and operating conditions before sizing a batch.'},{q:'Does the YH-GT300 price include a noodle cutter?',a:'No. The May 8 price list excludes the cutter. A standard 1.5–6 mm flat cutter is listed at CNY 150 each before tax; other cutters are priced separately.'}], bundles: ['noodles','bakery'] },
  { slug: 'meat-processing-machinery', title: 'Meat processing machinery', keyword: 'commercial meat processing machinery', families: ['meat'], intro: 'Compare dedicated meat slicers, grinders, paste mixers and meatball formers. Each stage has different material, blade and batch requirements.', checks: ['Specify fresh, chilled or frozen material and whether bones are present. Do not assume a general-purpose slicer can handle frozen blocks.', 'Choose grinding plate and slicing dimensions for the finished product; confirm included attachments and spare sets.', 'Balance grinding, paste preparation and forming around the same recipe. A combined equipment price does not establish line throughput.'], faq: [{q:'Are JR-G22 and JR-GG22 the same price?',a:'No. The price list distinguishes their grinding-part configurations. This selection uses JR-GG22, listed with all-steel grinding parts at CNY 1,120.'},{q:'Does the meatball package include cooking?',a:'No. It contains a grinder, paste mixer and former. Cooking, chilling, storage and packing must be scoped separately.'}], bundles: ['meat-prep','meatballs'] },
  { slug: 'vegetable-processing-machinery', title: 'Vegetable processing machinery', keyword: 'commercial vegetable processing machines', families: ['vegetables'], intro: 'Match peeling, slicing, shredding and chopping to the ingredient and the finished cut. Compare the selected copper-motor slicer with dedicated peeling and chopping machines.', checks: ['Confirm root vegetables, leaf vegetables or other ingredients and their incoming sizes.', 'Provide a sample or dimensions of the required cut, then confirm the blade set included in the quote.', 'Plan water, drainage, cleaning access and manual transfers between machines.'], faq: [{q:'Does DQ-PS300 include every cutting blade?',a:'The supplied price list describes slicing and shredding with a one-way blade. It does not establish a complete multi-blade set. Specify and confirm the required blades in the quotation.'},{q:'Is the three-machine package an automatic processing line?',a:'No. The peeler, slicer and chopper are individual machines. Transfers, washing, drainage and working layout need separate planning.'}], bundles: ['vegetables'] },
  { slug: 'bean-rice-and-juice-machinery', title: 'Bean, rice & juice machinery', keyword: 'bean rice and sugarcane processing machines', families: ['grain'], intro: 'Compare pulp separation, wet rice grinding and sugarcane pressing as distinct preparation functions. Choose equipment around the ingredient and the next step in your process.', checks: ['Specify soaked ingredients, desired fineness and how pulp or residue will be handled.', 'Match the machine to its preparation function. Pulp separation and wet rice grinding are not interchangeable.', 'For sugarcane, choose mains, battery or dual power explicitly; the listed GZ-TC uses mains power.'], faq: [{q:'Does GZ-TC include a battery?',a:'No. GZ-TC is the mains-powered tabletop model. The price list separately names GZ-TD as the battery model and GZ-TS as dual power.'},{q:'Is the bean and rice package a complete beverage line?',a:'No. It combines preparation functions. Soaking, cooking, filtering, filling and storage equipment are outside this package.'}], bundles: ['bean-rice'] },
];
export const categoryPath = category => `${root}/${category.slug}`;
export const packagePath = bundle => `${root}/packages/${bundle.id}`;
export const foodProcessingRoutes = [root, ...categoryPages.map(categoryPath), ...packages.map(packagePath)];
export function foodPage(pathname) {
  const path=pathname.replace(/\/+$/,'');
  const category=categoryPages.find(c=>categoryPath(c)===path);
  const bundle=packages.find(p=>packagePath(p)===path);
  if(category)return {kind:'category',path,category,title:category.title,intro:`Source ${category.title.toLowerCase()} from China for your equipment range or food business. ${category.intro}`,machines:machines.filter(m=>category.families.includes(m.family)),bundles:packages.filter(p=>category.bundles.includes(p.id))};
  if(bundle)return {kind:'package',path,bundle,title:bundle.title+' equipment package',intro:`Buy a ${bundle.title.toLowerCase()} equipment package from China, with models and quantities selected for your operation. ${bundle.description}`,machines:bundle.items.map(id=>machineById[id]),bundles:[]};
  if(path===root)return {kind:'hub',path:root,title:'Food processing machinery from China. Selected for your operation.',intro:'Source food processing machinery from China for dough, bakery, meat and vegetable preparation. Compare individual machines or buy a coordinated equipment package, with model-level wholesale prices and packing costs shown separately.',machines,bundles:packages};
  return null;
}
export function foodPageMeta(page) {
  if(page.kind==='hub')return foodProcessingMeta;
  return {title:`${page.title} from China | DDNZ Global`,description:`${page.intro} Compare CNY wholesale prices, configurations and packing costs.`,image:`/food-processing-media/${page.machines[0].image}.webp`};
}
export function foodPageSchema(page) {
  const site='https://www.ddnzglobal.com';
  const crumbs=[{name:'Products',item:site+'/products/'},{name:'Food processing machinery',item:site+root+'/'}];
  if(page.kind!=='hub')crumbs.push({name:page.title,item:site+page.path+'/'});
  return {'@context':'https://schema.org','@graph':[
    {'@type':'CollectionPage','@id':site+page.path+'/#page',name:foodPageMeta(page).title,url:site+page.path+'/',description:foodPageMeta(page).description},
    {'@type':'BreadcrumbList',itemListElement:crumbs.map((c,i)=>({'@type':'ListItem',position:i+1,...c}))},
    {'@type':'ItemList',name:'Equipment selection',itemListElement:page.machines.map((m,i)=>({'@type':'ListItem',position:i+1,name:`${m.model} ${m.name} — ${m.variant}`,url:site+page.path+'/#machine-'+m.id}))}
  ]};
}
