export { outdoorPath as OUTDOOR_PATH } from '../../lib/productLocalization.mjs';
export const L = (en, es, ar) => ({en, es, ar});
export const copy = (value, locale = 'en') => typeof value === 'string' ? value : value?.[locale] || value?.en || '';
export const FX = Object.freeze({date:'2026-09-11',cnyPerJpy:7.7762/178.56,cnyPerUsd:7.7762/1.1592,url:'https://www.ecb.europa.eu/stats/policy_and_exchange_rates/euro_reference_exchange_rates/html/index.en.html'});
const cny = value => Math.round((value * FX.cnyPerJpy + Number.EPSILON) * 100) / 100;
export const sources = {
 ecoflow6:'/outdoor-sourcing-media/ecoflow-spec-6.webp',
 ecoflow7:'/outdoor-sourcing-media/ecoflow-spec-7.webp',
 eboom20:'/outdoor-sourcing-media/eboom-spec-20.webp',
 sanhe: L('3Hz-Solar model specifications', 'Especificaciones del modelo 3Hz-Solar', 'مواصفات طراز 3Hz-Solar'),
 tieding: L('Tieding product catalogue', 'Catálogo de productos Tieding', 'كتالوج منتجات Tieding'),
 glory: 'https://germany.alibaba.com/product-detail/Custom-Outdoor-ETFE-100w-Portable-Folding_1600976800647.html',
 colku: 'https://www.alibaba.com/product-detail/Factory-Price-20L-Single-Zone-Camping_1601112589604.html',
};
const sanhe = {
 category:'power', supplier:'Guangzhou 3Hz-Solar Technology Co., Ltd.', source:'sanhe',wh:198.4,watts:300,
 price:450,priceKind:'reference',date:'2026-09-14',
 metrics:['198.4 Wh','300 W','LiFePO₄'],
 shared: L('12.8V / 15.5Ah battery. 300W continuous, 500W peak. One 220V AC outlet; six 12V DC5521 outputs; two USB-A and two USB-C, each listed at 5V/2A.', 'Batería de 12,8V / 15,5Ah. 300W continuos y pico de 500W. Una toma CA de 220V; seis salidas DC5521 de 12V; dos USB-A y dos USB-C, indicadas a 5V/2A cada una.', 'بطارية 12.8V / 15.5Ah. قدرة مستمرة 300W وذروة 500W. مخرج AC واحد 220V؛ ستة مخارج DC5521 بجهد 12V؛ منفذا USB-A ومنفذا USB-C بقدرة 5V/2A لكل منفذ.'),
 charging:L('AC charging: 3h claimed. Solar: 18V/100W, 3h claimed; panel inclusion is unspecified. Confirm PV voltage limits, connector and charge test conditions.', 'Carga CA: 3h declaradas. Solar: 18V/100W, 3h declaradas; no se indica si incluye panel. Confirmar límites de tensión FV, conector y condiciones de ensayo.', 'الشحن المتردد: 3 ساعات بحسب المورد. الشمسي: 18V/100W و3 ساعات معلنة؛ إدراج اللوح غير محدد. يلزم تأكيد حدود الجهد والموصل وظروف اختبار الشحن.'),
 conditions:L('Supply reference: CNY 450 per unit. Confirm quantity, selected configuration, freight and tax in your quotation. A two-year portable-unit warranty is listed; agree the service arrangements.', 'Referencia de suministro: CNY 450 por unidad. Confirmar cantidad, configuración, flete e impuestos en la oferta. Garantía indicada de dos años; acordar el servicio.', 'سعر توريد مرجعي: CNY 450 للوحدة. أكد الكمية والتكوين والشحن والضرائب في العرض. ضمان معلن لسنتين؛ اتفق على ترتيبات الخدمة.'),
};
export const outdoorProducts = [
 {...sanhe,id:'sanhe-st',model:'3HZ-300ST',image:'sanhe-st.webp',name:L('Carry-handle power station','Estación con asa de transporte','محطة طاقة بمقبض حمل'),
  use:L('A compact first power SKU for lights, phones and small loads.', 'Una primera referencia compacta para luces, teléfonos y cargas pequeñas.', 'خيار مدمج للإضاءة والهواتف والأحمال الصغيرة.'),
  packing:L('Unit: 160 × 246 × 241mm. Four units per carton; carton 600 × 420 × 298mm, 14.3kg gross. Carton weight is not unit weight.', 'Unidad: 160 × 246 × 241mm. Cuatro unidades por caja; 600 × 420 × 298mm, peso bruto de caja 14,3kg. No es el peso de una unidad.', 'الوحدة: 160 × 246 × 241mm. أربع وحدات بالكرتون؛ أبعاده 600 × 420 × 298mm ووزنه الإجمالي 14.3kg، وليس وزن الوحدة.')},
 {...sanhe,id:'sanhe-bg',model:'3HZ-300BG',image:'sanhe-bg.webp',name:L('Wall-mount power unit','Unidad de energía mural','وحدة طاقة للتثبيت الجداري'),
  use:L('The same listed energy and output, in a fixed-installation format.', 'La misma energía y potencia declaradas, en formato de instalación fija.', 'نفس الطاقة والقدرة المعلنتين، بتصميم للتثبيت الدائم.'),
  packing:L('Unit: 300 × 220 × 120mm. Four units per carton; carton 550 × 340 × 415mm, 15.55kg gross. Confirm mounting hardware and installation instructions.', 'Unidad: 300 × 220 × 120mm. Cuatro por caja; 550 × 340 × 415mm y 15,55kg brutos. Confirmar herrajes e instrucciones de instalación.', 'الوحدة: 300 × 220 × 120mm. أربع وحدات بالكرتون؛ 550 × 340 × 415mm ووزن إجمالي 15.55kg. يلزم تأكيد أدوات وتعليمات التثبيت.')},
 {id:'tieding-51',model:'Tieding · p.51',category:'power',supplier:'Tieding',source:'tieding',page:51,image:'tieding-51.webp',retouched:true,wh:577,watts:600,metrics:['577 Wh','600 W','12.6 V / 8 A'],
  name:L('Step up to a 600W format','Formato de 600W','فئة قدرة 600W'),
  use:L('A catalogue option for a larger energy budget. Battery configuration needs clarification before a sample order.', 'Opción de catálogo con más energía. Aclarar la configuración de batería antes de pedir muestras.', 'خيار كتالوج بسعة طاقة أكبر. يجب توضيح تكوين البطارية قبل طلب العينة.'),
  shared:L('Page 51 states 52Ah / 11.1V / 577Wh and 600W continuous AC. It also labels the battery LiFePO₄: obtain the cell chemistry, series configuration and model-specific datasheet to resolve this mismatch.', 'La página 51 indica 52Ah / 11,1V / 577Wh y 600W CA continuos, pero también etiqueta LiFePO₄. Pedir química de celdas, configuración en serie y ficha del modelo para aclararlo.', 'تذكر الصفحة 51 سعة 52Ah / 11.1V / 577Wh وقدرة مستمرة 600W، مع وصف البطارية LiFePO₄. اطلب كيمياء الخلايا وترتيبها التسلسلي وورقة بيانات الطراز لحل هذا التعارض.'),
  charging:L('Listed input: DC12.6V/8A (100.8W). 577Wh ÷ 100.8W ≈ 5.7h is an ideal energy-only lower bound; actual charging takes longer. Solar input limits are not stated.', 'Entrada indicada: CC12,6V/8A (100,8W). 577Wh ÷ 100,8W ≈ 5,7h es un mínimo ideal, sin pérdidas; la carga real tarda más. No se indican límites solares.', 'الدخل المعلن DC12.6V/8A أي 100.8W. قسمة 577Wh على 100.8W تعطي نحو 5.7 ساعات كحد أدنى مثالي دون خسائر؛ الشحن الفعلي أطول. حدود الدخل الشمسي غير مذكورة.'),
  packing:L('Unit: 298 × 129 × 250mm. Two USB, two Type-C, three 12V DC outputs and one AC outlet listed. Port ratings, socket, net weight and carton data require confirmation.', 'Unidad: 298 × 129 × 250mm. Dos USB, dos Type-C, tres salidas CC de 12V y una CA. Confirmar potencias de puertos, toma, peso neto y embalaje.', 'الوحدة: 298 × 129 × 250mm. منفذا USB ومنفذا Type-C وثلاثة مخارج DC بجهد 12V ومخرج AC. يلزم تأكيد قدرات المنافذ والمقبس والوزن وبيانات الكرتون.')},
 {id:'tieding-45',model:'Tieding · p.45',category:'power',supplier:'Tieding',source:'tieding',page:45,image:'tieding-45.webp',retouched:true,metrics:['499.5–1,110 Wh','600 / 1,000 W','3 options'],
  name:L('A family of larger power options','Familia de mayor capacidad','مجموعة خيارات طاقة أكبر'),
  use:L('Compare the exact version. Capacity and inverter options are grouped together in the catalogue.', 'Comparar la versión exacta: el catálogo agrupa opciones de capacidad e inversor.', 'قارن النسخة المحددة؛ يعرض الكتالوج خيارات السعة والعاكس معاً.'),
  shared:L('135,000 / 240,000 / 300,000mAh at 3.7V convert to 499.5 / 888 / 1,110Wh. The page lists 600W / 1,000W continuous AC without mapping each capacity to an inverter. These are options, not one specification.', '135.000 / 240.000 / 300.000mAh a 3,7V equivalen a 499,5 / 888 / 1.110Wh. La página indica 600W / 1.000W continuos sin vincular cada capacidad al inversor. Son opciones, no una única especificación.', 'سعات 135,000 / 240,000 / 300,000mAh عند 3.7V تعادل 499.5 / 888 / 1,110Wh. تسرد الصفحة 600W / 1,000W مستمرة دون ربط السعات بالعاكس. هذه خيارات وليست مواصفة موحدة.'),
  charging:L('DC12.6V/10A input listed. Two AC, two USB, two Type-C, two DC12V/10A GX16 and one DC12V/10A vehicle outlet listed. Confirm the actual battery configuration and each port rating.', 'Entrada CC12,6V/10A. Dos CA, dos USB, dos Type-C, dos CC12V/10A GX16 y una toma de vehículo CC12V/10A. Confirmar configuración real y potencia de cada puerto.', 'دخل DC12.6V/10A معلن. مخرجان AC ومنفذا USB ومنفذا Type-C ومخرجا GX16 بجهد DC12V/10A ومقبس سيارة DC12V/10A. أكد تكوين البطارية وقدرة كل منفذ.'),
  packing:L('Catalogue dimensions: 260 × 190 × 190mm. Request a model code, version-specific dimensions, net weight and carton specification for the selected capacity.', 'Dimensiones del catálogo: 260 × 190 × 190mm. Pedir código de modelo, dimensiones, peso neto y caja de la capacidad seleccionada.', 'أبعاد الكتالوج: 260 × 190 × 190mm. اطلب رمز الطراز وأبعاد ووزن وتغليف النسخة المختارة.')},
 {id:'ecoflow-classic',model:'EcoFlow DELTA 3 Classic',category:'power',supplier:'EcoFlow',source:'ecoflow6',image:'ecoflow-classic.webp',wh:1024,watts:1800,metrics:['1,024 Wh','1,800 W','16.5 kg'],
  name:L('More output for a compact work kit','Más potencia para un equipo compacto','قدرة أكبر لتجهيزات عمل مدمجة'),
  use:L('A 1kWh reference for work lights, electronics and selected AC appliances. Compare charging speed as well as energy.', 'Referencia de 1kWh para iluminación de trabajo, electrónica y aparatos CA seleccionados. Compare también la velocidad de carga.', 'مرجع بسعة 1kWh لإنارة العمل والإلكترونيات وأجهزة AC المختارة. قارن سرعة الشحن إلى جانب الطاقة.'),
  shared:L('Supplied China catalogue: 1,024Wh LiFePO₄, 1,800W rated AC, 220V. Three AC sockets; one 12W USB-A; USB-C at 30W and 100W. The 2,200W X-Boost figure is a separate operating mode, not the rated output used in this guide.', 'Catálogo chino suministrado: 1.024Wh LiFePO₄, 1.800W CA nominales, 220V. Tres tomas CA; USB-A de 12W; USB-C de 30W y 100W. X-Boost de 2.200W es otro modo, no la potencia nominal usada aquí.', 'الكتالوج الصيني المقدم: 1,024Wh وLiFePO₄ وقدرة AC اسمية 1,800W عند 220V. ثلاثة مقابس AC؛ USB-A بقدرة 12W؛ USB-C بقدرتي 30W و100W. وضع X-Boost بقدرة 2,200W منفصل عن القدرة الاسمية المستخدمة هنا.'),
  charging:L('Catalogue: 220–240V AC input up to 1,400W, full charge about 1.5h. PV input 11–60V, up to 500W; about 4.5h with two 220W panels under the listed setup. Charge times vary with conditions.', 'Catálogo: entrada CA 220–240V hasta 1.400W, carga completa aprox. 1,5h. FV 11–60V, hasta 500W; aprox. 4,5h con dos paneles de 220W. Los tiempos dependen de las condiciones.', 'الكتالوج: دخل AC بجهد 220–240V حتى 1,400W، وشحن كامل نحو 1.5 ساعة. دخل شمسي 11–60V حتى 500W؛ نحو 4.5 ساعات بلوحين 220W وفق التكوين المذكور. المدة تتغير حسب الظروف.'),
  packing:L('Catalogue unit: 400 × 212 × 282mm, 16.5kg. Specify the destination voltage, sockets, accessories and carton separately.', 'Unidad de catálogo: 400 × 212 × 282mm, 16,5kg. Especificar tensión, tomas, accesorios y caja para el destino.', 'الوحدة في الكتالوج: 400 × 212 × 282mm و16.5kg. حدد جهد الوجهة والمقابس والملحقات والكرتون منفصلة.')},
 {id:'ecoflow-max',model:'EcoFlow DELTA 3 Max',category:'power',supplier:'EcoFlow',source:'ecoflow7',image:'ecoflow-max.webp',wh:2048,watts:2400,metrics:['2,048 Wh','2,400 W','20.3 kg'],
  name:L('A larger energy reserve for longer jobs','Más reserva para trabajos largos','احتياطي طاقة أكبر للعمل الأطول'),
  use:L('Twice the energy of the Classic reference, with a higher rated AC output. Useful to compare for field work or a longer portable setup.', 'El doble de energía que la referencia Classic y mayor salida CA nominal. Compare para trabajo de campo o usos portátiles más largos.', 'ضعف طاقة مرجع Classic مع خرج AC اسمي أعلى. قارن لتجهيزات العمل الميداني أو الاستخدام المتنقل الأطول.'),
  shared:L('Supplied China catalogue: 2,048Wh LiFePO₄, 2,400W rated AC at 220V. Four AC sockets; one 18W USB-A; USB-C: one 100W and two 30W ports. Confirm shared USB power limits. X-Boost 3,200W is not used as continuous rated power.', 'Catálogo chino: 2.048Wh LiFePO₄, CA nominal 2.400W a 220V. Cuatro tomas CA; USB-A de 18W; USB-C: uno de 100W y dos de 30W. Confirmar límites USB compartidos. X-Boost 3.200W no se usa como potencia nominal continua.', 'الكتالوج الصيني: 2,048Wh وLiFePO₄ وقدرة AC اسمية 2,400W عند 220V. أربعة مقابس AC؛ USB-A بقدرة 18W؛ USB-C واحد 100W واثنان 30W. أكد حدود USB المشتركة. لا تستخدم قيمة X-Boost البالغة 3,200W كقدرة اسمية مستمرة.'),
  charging:L('Catalogue: AC input up to 2,200W; about 1.2h full charge. Solar input 11–60V / 13A / 500W maximum per port; two ports, 1,000W total maximum. The catalogue lists about 6.6h with one 400W panel.', 'Catálogo: entrada CA hasta 2.200W; carga completa aprox. 1,2h. FV 11–60V / 13A / 500W por puerto; dos puertos, máximo total 1.000W. Un panel de 400W: aprox. 6,6h declaradas.', 'الكتالوج: دخل AC حتى 2,200W وشحن كامل نحو 1.2 ساعة. دخل شمسي 11–60V / 13A / 500W لكل منفذ؛ منفذان بإجمالي أقصى 1,000W. يذكر الكتالوج نحو 6.6 ساعات بلوح واحد 400W.'),
  packing:L('Catalogue unit: 494 × 239 × 305mm, 20.3kg. Confirm the regional version and supplied cables before ordering.', 'Unidad de catálogo: 494 × 239 × 305mm, 20,3kg. Confirmar versión regional y cables incluidos.', 'الوحدة في الكتالوج: 494 × 239 × 305mm و20.3kg. أكد النسخة الإقليمية والكابلات المشمولة قبل الطلب.')},
 {id:'eboom-lxyt24',model:'EBOOM LXYT-24',category:'power',supplier:'Jiangxi Lixiang Technology Co., Ltd.',source:'eboom20',image:'eboom-lxyt.webp',familyImage:true,wh:3500,watts:2400,metrics:['3.5 kWh','2.4 kW','220 V AC'],
  name:L('A trolley format for a larger reserve','Formato con ruedas y mayor reserva','تصميم بعجلات واحتياطي أكبر'),
  use:L('The LXYT-24 option pairs 3.5kWh with 2.4kW output. A heavier wheeled format to assess for a stall, workshop or mobile service.', 'La opción LXYT-24 combina 3,5kWh y 2,4kW. Formato más pesado con ruedas para evaluar en un puesto, taller o servicio móvil.', 'يجمع خيار LXYT-24 سعة 3.5kWh وقدرة 2.4kW. تصميم أثقل بعجلات لتقييمه للكشك أو الورشة أو الخدمة المتنقلة.'),
  shared:L('Catalogue printed p.20: LXYT-24, LiFePO₄ (16S1P), 3.5kWh and 2.4kW; 220V AC, 50–60Hz. The adjacent 5.3kWh / 5kW option belongs to another model. Three AC outlets and USB / Type-C outputs are listed for the family.', 'Página impresa 20: LXYT-24, LiFePO₄ (16S1P), 3,5kWh y 2,4kW; CA 220V, 50–60Hz. La opción contigua de 5,3kWh / 5kW es otro modelo. La familia indica tres tomas CA y salidas USB / Type-C.', 'الصفحة المطبوعة 20: LXYT-24 وLiFePO₄ ‏(16S1P) وسعة 3.5kWh وقدرة 2.4kW؛ AC بجهد 220V وتردد 50–60Hz. الخيار المجاور 5.3kWh / 5kW يخص طرازاً آخر. ثلاثة مقابس AC ومخارج USB / Type-C مذكورة للمجموعة.'),
  charging:L('Family table: MPPT solar input 12–45V, 500W maximum, and an XT90 mains-charging connection. AC input power and full-charge time are not given. Obtain the charger specification and exact port ratings.', 'Tabla de familia: entrada solar MPPT 12–45V, máximo 500W, y conexión de carga de red XT90. No indica potencia de entrada CA ni tiempo de carga completa. Pedir ficha del cargador y límites de puertos.', 'جدول المجموعة: دخل شمسي MPPT بجهد 12–45V وحتى 500W ووصلة شحن XT90. قدرة دخل AC وزمن الشحن الكامل غير مذكورين. اطلب مواصفات الشاحن وحدود المنافذ.'),
  packing:L('The family lists 41kg / 56.4kg bare-unit weights; confirm the selected version. Body 410 × 320 × 490mm; height with handle 1,010mm. Outer pack 620 × 460 × 400mm is listed: reconcile packing orientation and dimensions before booking freight.', 'La familia indica 41kg / 56,4kg sin embalaje; confirmar versión. Cuerpo 410 × 320 × 490mm; altura con asa 1.010mm. Embalaje indicado 620 × 460 × 400mm: verificar orientación y dimensiones antes del transporte.', 'تعرض المجموعة وزني 41kg / 56.4kg؛ أكد النسخة المختارة. الجسم 410 × 320 × 490mm؛ الارتفاع بالمقبض 1,010mm. العبوة المذكورة 620 × 460 × 400mm؛ طابق اتجاه التغليف والأبعاد قبل حجز الشحن.')},
 {id:'glory-100',model:'GSSP-100W',category:'solar',supplier:'Shenzhen Glory Industries Co., Ltd.',source:'glory',image:'glory-100.webp',metrics:['100 W','20 V / 5 A','4.2 kg'],date:'2026-09-14',priceKind:'listing',tiers:[[2,cny(12317)],[20,cny(11693)],[50,cny(11148)]],sample:cny(12473),
  name:L('ETFE folding solar panel','Panel solar plegable ETFE','لوح شمسي قابل للطي ETFE'),
  use:L('Add charging capacity after checking the power station’s PV input window.', 'Añadir carga solar tras comprobar el rango de entrada FV de la estación.', 'أضف الشحن الشمسي بعد التحقق من نطاق دخل المحطة الشمسي.'),
  shared:L('100W at 20V/5A. ETFE laminate with sewn fabric. USB-A and USB-C listed at 5V/3A, 9V/2A or 12V/1.5A maximum; confirm supported protocols.', '100W a 20V/5A. Laminado ETFE con tejido cosido. USB-A y USB-C: 5V/3A, 9V/2A o 12V/1,5A máximos; confirmar protocolos.', '100W عند 20V/5A. تغليف ETFE مع قماش مخيط. USB-A وUSB-C بحدود 5V/3A أو 9V/2A أو 12V/1.5A؛ أكد البروتوكولات المدعومة.'),
  charging:L('The listing describes a 3m lead with MC4 and Anderson connectors. Confirm open-circuit voltage, polarity and the included adapter set before pairing; a matching connector alone is insufficient.', 'Se describe cable de 3m con MC4 y Anderson. Confirmar tensión en circuito abierto, polaridad y adaptadores incluidos; el mismo conector no garantiza compatibilidad.', 'يصف العرض كابل 3m بموصلي MC4 وAnderson. أكد جهد الدائرة المفتوحة والقطبية والمحوّلات المشمولة؛ تشابه الموصل لا يضمن التوافق.'),
  packing:L('Open: 1195 × 525 × 5mm. Folded: 595 × 525 × 35mm. Unit 4.2kg; package 582 × 65 × 659mm, 4.51kg gross.', 'Abierto: 1195 × 525 × 5mm. Plegado: 595 × 525 × 35mm. Unidad 4,2kg; caja 582 × 65 × 659mm, 4,51kg brutos.', 'مفتوح: 1195 × 525 × 5mm. مطوي: 595 × 525 × 35mm. الوحدة 4.2kg؛ العبوة 582 × 65 × 659mm و4.51kg إجمالي.'),
  conditions:L('First displayed tier: 2 units. Logo, graphics and packaging customization from 200 units. One-year warranty listed. Confirm selected panel, accessories, tax, freight and lead time.', 'Primer tramo mostrado: 2 unidades. Logo, gráficos y embalaje personalizados desde 200. Garantía indicada de un año. Confirmar panel, accesorios, impuestos, flete y plazo.', 'أول شريحة سعرية معروضة: وحدتان. تخصيص الشعار والرسومات والتغليف من 200 وحدة. ضمان معلن لسنة. أكد اللوح والملحقات والضرائب والشحن والمهلة.')},
 {id:'colku-20',model:'TF20',category:'cold',supplier:'Foshan Sanshui Colku Electrical Appliance Limited',source:'colku',image:'colku-20.webp',metrics:['20 L','12 / 24 V DC','45 W'],date:'2026-09-14',priceKind:'listing',tiers:[[10,cny(19021)],[50,cny(18085)],[200,cny(16370)]],sample:cny(19956),
  name:L('Single-zone compressor refrigerator','Nevera compresora de una zona','ثلاجة ضاغط بمنطقة واحدة'),
  use:L('Vehicle-powered cold storage. Measure daily energy use in the destination climate.', 'Frío alimentado por vehículo. Medir el consumo diario en el clima de destino.', 'تبريد يعمل بطاقة السيارة. قِس الاستهلاك اليومي في مناخ الوجهة.'),
  shared:L('20L; 12V/24V DC; 45W rated input. Listed set-temperature range −18°C to +10°C. The 45W rating is not a measured 24-hour energy figure or a guaranteed pull-down time.', '20L; CC12V/24V; entrada nominal de 45W. Rango de ajuste declarado −18°C a +10°C. 45W no es un consumo medido de 24h ni garantiza el tiempo de enfriamiento.', '20L؛ DC12V/24V؛ دخل اسمي 45W. نطاق الضبط المعلن من −18°C إلى +10°C. قيمة 45W ليست قياس استهلاك 24 ساعة ولا ضماناً لزمن التبريد.'),
  charging:L('Confirm compressor starting demand, vehicle low-voltage cut-off and DC cable. The listing gives R134a/R600a refrigerant alternatives: confirm the selected version and its transport file.', 'Confirmar arranque del compresor, corte por baja tensión y cable CC. Se mencionan refrigerantes R134a/R600a: confirmar versión elegida y documentación de transporte.', 'أكد تيار بدء الضاغط وحد فصل الجهد المنخفض وكابل DC. يعرض المورد بدائل تبريد R134a/R600a؛ أكد النسخة المحددة ووثائق نقلها.'),
  packing:L('Unit: 600 × 335 × 300mm, 10kg net. Package: 640 × 370 × 330mm, 11kg gross. PP/HIPS housing listed.', 'Unidad: 600 × 335 × 300mm, 10kg netos. Caja: 640 × 370 × 330mm, 11kg brutos. Carcasa PP/HIPS declarada.', 'الوحدة: 600 × 335 × 300mm و10kg صافي. العبوة: 640 × 370 × 330mm و11kg إجمالي. هيكل PP/HIPS بحسب العرض.'),
  conditions:L('First displayed tier: 10 units. Logo and colour customization from 100; packaging from 500. One-year warranty listed. Freight, tax, configuration and stock require a fresh quote.', 'Primer tramo mostrado: 10 unidades. Logo y color desde 100; embalaje desde 500. Garantía indicada de un año. Pedir nueva oferta de flete, impuestos, configuración y stock.', 'أول شريحة معروضة: 10 وحدات. الشعار واللون من 100 وحدة؛ التغليف من 500. ضمان معلن لسنة. يلزم عرض محدث للشحن والضرائب والتكوين والمخزون.')},
];
export const getProduct = id => outdoorProducts.find(p=>p.id===id);
export const priceAt = (product, quantity) => {
 if(!product || !Number.isInteger(quantity) || quantity<1 || quantity>1000000)return null;
 if(product.priceKind==='reference')return product.price;
 const tier=product.tiers?.filter(([min])=>quantity>=min).at(-1);
 return tier?.[1]??null;
};
export const retailExamples = [
 {country:L('Türkiye','Turquía','تركيا'),model:'SolarWise E500LFP',spec:'576 Wh / 600 W',price:'TRY 18,149',store:'Amazon Türkiye',url:'https://www.amazon.com.tr/dp/B0H7Z3GZRQ'},
 {country:L('Mexico','México','المكسيك'),model:'EcoFlow RIVER 2 Max 500',spec:'499 Wh / 500 W',price:'MXN 7,399',store:'EcoFlow Mexico',url:'https://mx.ecoflow.com/products/river-2-max-500-portable-power-station'},
 {country:L('Brazil','Brasil','البرازيل'),model:'BLUETTI AC50P',spec:'504 Wh / 700 W',price:'BRL 2,899',store:'Amazon Brasil',url:'https://www.amazon.com.br/dp/B0DWKBK88K'},
];
