import React, { useEffect, useRef, useState } from 'react';
import { ArrowDown, ArrowUpRight, Check, Plus, BatteryCharging, Sun, Snowflake } from 'lucide-react';
import { outdoorProducts, getProduct, priceAt, copy, sources, retailExamples, FX, L } from './catalog.mjs';
import { readGuideHandoff, POWER_HANDOFF_KEYS } from './power-guide.mjs';
import { outdoorCategories } from './navigation.mjs';
import { localizedProductPath, powerGuidePath } from '../../lib/productLocalization.mjs';
import { ui } from './copy.mjs';
import { runtime, numberInput, quantityInput, trialDefaults, changeCurrency, referenceInCurrency, trialEconomics, emptyBrief, normalizeBrief, validBrief, buildOutdoorPayload } from './buying.mjs';
import { submitInquiry } from '../commercial-kitchen/data/inquiry.mjs';

const media='/outdoor-sourcing-media/';
const navIds=['outdoor-range','power-matching','supply-prices','trial-economics','supplier-checks'];
const storageKey='ddnz:outdoor-brief:v1';
const priced=outdoorProducts.filter(p=>p.priceKind);
export default function OutdoorContent({locale='en',category='all',onCategoryChange,onPrivacy=()=>{},onAction=(_action)=>{}}){
 const t=key=>copy(ui[key],locale),c=value=>copy(value,locale),tr=(en,es,ar)=>c(L(en,es,ar));
 const format=value=>Number(value).toLocaleString(locale,{minimumFractionDigits:2,maximumFractionDigits:2});
 const money=(value,currency='CNY')=>`${currency} ${format(value)}`;
 const [localFilter,setLocalFilter]=useState(category),[comparisonQty,setComparisonQty]=useState('10'),[load,setLoad]=useState('60'),[efficiency,setEfficiency]=useState('85');
 const filter=onCategoryChange?category:localFilter;
 const setFilter=(value,hash='#outdoor-range')=>onCategoryChange?onCategoryChange(value,hash):setLocalFilter(value);
 const [trial,setTrial]=useState(trialDefaults),[calcResult,setCalcResult]=useState(null),[calcNotice,setCalcNotice]=useState('');
 const [brief,setBrief]=useState(emptyBrief),[consent,setConsent]=useState(false),[review,setReview]=useState(false),[sendState,setSendState]=useState('');
 const restored=useRef(false),sending=useRef(false);
 useEffect(()=>{let draft=emptyBrief();try{const saved=sessionStorage.getItem(storageKey);if(saved)draft=normalizeBrief(JSON.parse(saved));}catch{}const incoming=readGuideHandoff(window.location.search,locale);if(incoming){if(!draft.rows.some(r=>r.id===incoming.id))draft.rows.push({id:incoming.id,quantity:'10'});draft.guideNote=incoming.note;const clean=new URL(window.location.href);for(const key of POWER_HANDOFF_KEYS)clean.searchParams.delete(key);window.history.replaceState(window.history.state,'',clean.pathname+clean.search+clean.hash);}setBrief(draft);restored.current=true;},[]);
 useEffect(()=>{if(restored.current)try{sessionStorage.setItem(storageKey,JSON.stringify(brief));}catch{}},[brief]);
 const editBrief=fn=>{setBrief(fn);setReview(false);setSendState('');};
 const addProduct=id=>{editBrief(d=>d.rows.some(r=>r.id===id)?d:{...d,rows:[...d.rows,{id,quantity:'10'}]});onAction('add_product');};
 const toggleCheck=(id,enabled)=>editBrief(d=>({...d,checks:enabled?[...new Set([...d.checks,id])]:d.checks.filter(x=>x!==id)}));
 const updateTrial=(key,value)=>{setTrial(d=>({...d,[key]:value,...(key==='id'?{goods:''}:{})}));setCalcResult(null);setCalcNotice('');};
 const updateForm=(key,value)=>editBrief(d=>({...d,form:{...d.form,[key]:value}}));
 const payload=buildOutdoorPayload(brief,locale);
 const input=(key,label,extra={})=><label className="ods-field"><span>{label}</span><input id={'outdoor-cost-'+key} value={trial[key]} onChange={e=>updateTrial(key,e.target.value)} inputMode="decimal" autoComplete="off" {...extra}/></label>;
 async function send(event){event.preventDefault();if(sending.current)return;if(!validBrief(brief,consent)){setSendState('missing');return;}sending.current=true;setSendState('sending');try{const result=await submitInquiry(payload);setSendState(result.mode==='preview'?'preview':'success');if(result.mode==='production')onAction('submit_success');}catch{setSendState('failure');onAction('submit_error');}finally{sending.current=false;}}
 return <main id="main-content" className="ods" lang={locale} dir={locale==='ar'?'rtl':'ltr'}>
  <div className="ods-wrap">
   <nav className="ods-breadcrumb" aria-label={tr('Breadcrumb','Ruta de navegación','مسار التصفح')}><a href={locale==='en'?'/':`/${locale}/`}>{t('home')}</a><span>/</span><a href="/products/">{t('products')}</a><span>/</span><span>{tr('Outdoor sourcing','Compras outdoor','توريد المنتجات الخارجية')}</span></nav>
   <section className="ods-hero">
    <div className="ods-hero-copy"><p className="ods-eyebrow">{t('eyebrow')}</p><h1>{t('heading')}</h1><p className="ods-lead">{t('intro')}</p><div className="ods-actions"><a className="ods-button" href="#outdoor-range">{t('browse')}<ArrowDown size={18}/></a><a className="ods-text-link" href="#buying-brief">{t('brief')}<ArrowUpRight size={18}/></a></div></div>
    <figure className="ods-hero-image"><img src={media+'outdoor-camp.webp'} alt={tr('A power station and folding solar panel in a mountain campsite catalogue scene','Estación de energía y panel plegable en una escena de camping del catálogo','محطة طاقة ولوح قابل للطي في مشهد تخييم جبلي من الكتالوج')} width="1356" height="763" fetchPriority="high"/></figure>
   </section>
   <a className="ods-guide-entry" href={localizedProductPath(powerGuidePath,locale)} aria-labelledby="outdoor-guide-title">
    <div className="ods-guide-copy"><span className="ods-guide-kicker">{tr('Interactive power guide','Guía interactiva de energía','دليل الطاقة التفاعلي')}</span><h2 id="outdoor-guide-title">{tr('Which power station fits your day?','¿Qué estación se adapta a su día?','أي محطة طاقة تناسب يومك؟')}</h2><p>{tr('Compare six models. Try your appliances. See how long they could run.','Compare seis modelos. Pruebe sus aparatos y estime cuánto durarían.','قارن ستة طرازات. جرّب أجهزتك وقدّر مدة تشغيلها.')}</p><span className="ods-guide-cta">{tr('Find your power station','Encuentre su estación','اختر محطة الطاقة المناسبة')}<ArrowUpRight size={21}/></span></div>
    <div className="ods-guide-preview" aria-hidden="true"><BatteryCharging size={68} strokeWidth={1.4}/><div className="ods-guide-numbers"><span><strong>Wh</strong><small>{tr('Capacity','Capacidad','السعة')}</small></span><span><strong>W</strong><small>{tr('Power','Potencia','القدرة')}</small></span><span><strong>h</strong><small>{tr('Runtime','Autonomía','مدة التشغيل')}</small></span></div></div>
   </a><div className="ods-start-points"><div><BatteryCharging/><span>{tr('Select the energy & output','Elija energía y potencia','حدد الطاقة والقدرة')}<strong>Wh · W · AC / DC</strong></span></div><div><Sun/><span>{tr('Match the charging chain','Compatibilice la carga','طابق سلسلة الشحن')}<strong>V · A · {tr('connector','conector','الموصل')}</strong></span></div><div><Snowflake/><span>{tr('Measure cold performance','Mida el rendimiento del frío','قِس أداء التبريد')}<strong>°C · Wh / 24h</strong></span></div></div>
   <nav className="ods-section-nav" aria-label={tr('Outdoor guide sections','Secciones de la guía','أقسام الدليل')}>{navIds.map((id,i)=><a key={id} href={'#'+id}>{c(ui.nav[i])}</a>)}<a href="#buying-brief">{t('brief')} <span className="ods-count">{brief.rows.length}</span></a></nav>

   <section id="outdoor-range" className="ods-section"><span id="range-atlas"/><header className="ods-section-header"><div><p className="ods-eyebrow">01 / {t('products')}</p><h2>{t('range')}</h2><p>{t('rangeIntro')}</p></div></header>
    <div className="ods-filters" aria-label={t('products')}>{outdoorCategories.map(f=><button key={f} type="button" aria-pressed={filter===f} onClick={()=>setFilter(f)}>{t(f)}</button>)}</div>
    <div className="ods-product-grid">{outdoorProducts.filter(p=>filter==='all'||p.category===filter).map(p=>{
     const selected=brief.rows.some(r=>r.id===p.id),firstPrice=p.price??p.tiers?.[0][1];
     return <article id={'product-'+p.id} key={p.id} className="ods-product">
      <figure className="ods-product-image"><img src={media+p.image} alt={c(p.name)+' · '+p.model} loading="lazy" width="1000" height="1000"/></figure>
      <div className="ods-product-body"><div className="ods-product-code"><span>{p.model}</span><span>{t(p.category)}</span></div><h3>{c(p.name)}</h3><p className="ods-use">{c(p.use)}</p><ul className="ods-metrics">{p.metrics.map((v,i)=><li key={v} dir="ltr">{v==='3 options'?tr('3 capacity options','3 capacidades','3 خيارات سعة'):v}</li>)}</ul>
       <div className="ods-price"><span>{t(p.priceKind==='reference'?'reference':p.priceKind==='listing'?'listing':'quoteOnly')}</span>{firstPrice!==undefined?<strong><bdi>{money(firstPrice)}</bdi><small> / {t('unit')}</small></strong>:<p>{t('quoteOnlyNote')}</p>}{p.tiers?<small>{p.tiers[0][0]}+ {tr('units at this tier','unidades en este tramo','وحدات في هذه الشريحة')}</small>:p.priceKind==='reference'?<small>{t('referenceBasis')}</small>:null}</div>
       <details><summary>{t('details')}</summary><div className="ods-detail-copy"><p>{c(p.shared)}</p><h4>{t('charging')}</h4><p>{c(p.charging)}</p><h4>{t('pack')}</h4><p>{c(p.packing)}</p>{p.conditions?<><h4>{tr('Quotation conditions','Condiciones de oferta','شروط العرض')}</h4><p>{c(p.conditions)}</p></>:null}{p.tiers?<dl className="ods-tier-list">{p.tiers.map(([min,price],i)=><React.Fragment key={min}><dt>{min}{p.tiers[i+1]?'–'+(p.tiers[i+1][0]-1):'+'}</dt><dd><bdi>{money(price)}</bdi></dd></React.Fragment>)}</dl>:null}{p.sample?<p>{t('sample')}: <bdi>{money(p.sample)}</bdi></p>:null}<p className="ods-source">{t('source')}: {p.source==='sanhe'?c(sources.sanhe):p.source==='tieding'?`${c(sources.tieding)} · p.${p.page}`:<a href={sources[p.source]} target="_blank" rel="noopener noreferrer">{p.source.startsWith('ecoflow')||p.source==='eboom20'?tr('View catalogue specifications','Ver especificaciones del catálogo','عرض مواصفات الكتالوج'):t('viewSource')} ↗</a>}<br/>{p.supplier}</p></div></details>
       {p.wh&&p.watts?<a className="ods-model-guide" href={localizedProductPath(powerGuidePath,locale)+'?model='+p.id}>{tr('Explore power & runtime','Explore potencia y autonomía','استكشف القدرة ومدة التشغيل')} ↗</a>:null}<button type="button" className={'ods-add' +(selected?' is-added':'')} onClick={()=>addProduct(p.id)} aria-pressed={selected}>{selected?<Check size={18}/>:<Plus size={18}/>} {t(selected?'added':'add')}</button>
      </div>
     </article>;
    })}</div>
   </section>

   <section id="power-matching" className="ods-section"><header className="ods-section-header"><div><p className="ods-eyebrow">02 / Wh ≠ W</p><h2>{t('capacityHeading')}</h2><p>{t('capacityIntro')}</p></div></header>
    <div className="ods-runtime"><div className="ods-runtime-controls"><h3>{t('runtime')}</h3><label className="ods-field"><span>{t('load')}</span><input id="outdoor-runtime-load" value={load} onChange={e=>setLoad(e.target.value)} inputMode="decimal"/></label><label className="ods-field"><span>{t('efficiency')}</span><input id="outdoor-runtime-efficiency" value={efficiency} onChange={e=>setEfficiency(e.target.value)} inputMode="decimal"/></label></div>
     <div className="ods-runtime-results" aria-live="polite">{[getProduct('sanhe-st'),getProduct('tieding-51')].map(p=>{const r=runtime(p,load,efficiency);return <article key={p.id}><p>{p.model}</p><h4><bdi>{p.wh} Wh / {p.watts} W</bdi></h4>{r.status==='complete'?<><strong>{format(r.hours)}</strong><span>{t('hours')}</span><div className="ods-runtime-bar" aria-hidden="true"><i style={{width:`${p.wh/577*100}%`}}/></div></>:<p className="ods-alert">{t(r.status==='overload'?'overload':'completeNumbers')}</p>}{p.source==='tieding'?<small>{t('flagged')}</small>:null}</article>;})}</div>
    </div><p className="ods-note">{t('runtimeNote')}</p>
    <p><a className="ods-text-link" href={localizedProductPath(powerGuidePath,locale)}>{tr('Compare six models in the visual power guide','Compare seis modelos en la guía visual','قارن ستة طرازات في الدليل المرئي')}<ArrowUpRight size={18}/></a></p><h3 className="ods-subheading">{t('pairing')}</h3><div className="ods-chain">{ui.chain.map(([heading,body],i)=><article key={i}><h4>{c(heading)}</h4><p>{c(body)}</p></article>)}</div>
   </section>

   <section id="supply-prices" className="ods-section"><header className="ods-section-header"><div><p className="ods-eyebrow">03 / CNY</p><h2>{t('prices')}</h2><p>{t('pricesIntro')}</p></div><label className="ods-field ods-quantity"><span>{t('qty')}</span><input id="outdoor-compare-quantity" inputMode="numeric" value={comparisonQty} onChange={e=>setComparisonQty(e.target.value)}/></label></header>
    <div className="ods-table-scroll" tabIndex="0" role="region" aria-label={t('prices')}><table><thead><tr><th scope="col">{t('products')}</th><th scope="col">{t('basis')}</th><th scope="col">{t('unitPrice')}</th><th scope="col">{t('goods')}</th></tr></thead><tbody>{priced.map(p=>{const q=quantityInput(comparisonQty),v=priceAt(p,q),activeTier=p.tiers?.filter(([min])=>q>=min).at(-1)||p.tiers?.[0],nextTier=p.tiers?.find(([min])=>min>(activeTier?.[0]??0));return <tr key={p.id}><th scope="row"><a href={'#product-'+p.id} onClick={e=>{if(onCategoryChange){e.preventDefault();setFilter('all','#product-'+p.id);}else setFilter('all');}}>{p.model}</a><small>{c(p.name)}</small></th><td><span className="ods-price-basis">{t(p.priceKind==='reference'?'reference':'tierBasis')}</span><small>{p.priceKind==='reference'?t('referenceBasis'):`${activeTier[0]}${nextTier?'–'+(nextTier[0]-1):'+'}`}</small></td><td>{v===null?<span>{q?t('below'):t('completeNumbers')}</span>:<bdi>{money(v)}</bdi>}</td><td>{v===null?'—':<bdi>{money(v*q)}</bdi>}</td></tr>;})}</tbody></table></div><p className="ods-note">{t('priceNote')} <a href={FX.url} target="_blank" rel="noopener noreferrer">{t('fx')} ↗</a></p>
   </section>

   <section id="market-context" className="ods-section"><header className="ods-section-header"><div><p className="ods-eyebrow">04 / {tr('CHANNEL CONTEXT','CONTEXTO DEL CANAL','سياق قناة البيع')}</p><h2>{t('marketHeading')}</h2><p>{t('marketIntro')}</p></div></header>
    <div className="ods-market-grid">{retailExamples.map(m=><article key={m.country.en}><div className="ods-market-country">{c(m.country)}<span>{t('retail')}</span></div><h3>{m.model}</h3><p dir="ltr">{m.spec}</p><strong dir="ltr">{m.price}</strong><a href={m.url} target="_blank" rel="noopener noreferrer">{m.store}<ArrowUpRight size={16}/></a><small>{t('marketDate')}</small></article>)}</div><p className="ods-note">{t('marketNote')}</p>
   </section>

   <section id="trial-economics" className="ods-section"><header className="ods-section-header"><div><p className="ods-eyebrow">05 / {tr('TRIAL ORDER','PEDIDO DE PRUEBA','طلب تجريبي')}</p><h2>{t('economics')}</h2><p>{t('economicsIntro')}</p></div></header>
    <form className="ods-calculator" onSubmit={e=>{e.preventDefault();setCalcResult(trialEconomics(trial));setCalcNotice('');onAction('calculate');}}>
     <div className="ods-calc-fields"><div className="ods-form-grid"><label className="ods-field ods-wide"><span>{t('choose')}</span><select id="outdoor-cost-product" value={trial.id} onChange={e=>updateTrial('id',e.target.value)}>{priced.map(p=><option key={p.id} value={p.id}>{p.model} · {c(p.name)}</option>)}</select></label>{input('quantity',t('qty'),{inputMode:'numeric'})}<label className="ods-field"><span>{t('currency')}</span><select id="outdoor-cost-currency" value={trial.currency} onChange={e=>{setTrial(d=>changeCurrency(d,e.target.value));setCalcResult(null);setCalcNotice('fxReset');}}><option value="CNY">CNY</option><option value="USD">USD</option></select></label>{trial.currency==='USD'?<div className="ods-wide">{input('rate',t('currencyRate'))}<p className="ods-note">ECB · {FX.date} · {tr('Used when importing the reference price.','Se usa al importar el precio de referencia.','يستخدم عند إدراج السعر المرجعي.')}</p></div>:null}
       <div className="ods-wide ods-reference-use"><button type="button" className="ods-text-link" onClick={()=>{const value=referenceInCurrency(trial);updateTrial('goods',value===null?'':String(value));setCalcNotice(value===null?'below':getProduct(trial.id).priceKind==='reference'?'reference':'listing');}}>{t('useReference')} <ArrowDown size={16}/></button><span>{referenceInCurrency(trial)===null?t('below'):money(referenceInCurrency(trial),trial.currency)} · {t(getProduct(trial.id).priceKind==='reference'?'reference':'listing')}</span></div>
       {input('goods',`${t('goodsInput')} (${trial.currency})`)}{input('freight',`${t('freightInput')} (${trial.currency})`)}{input('fees',`${t('feesInput')} (${trial.currency})`)}{input('tax',`${t('taxInput')} (${trial.currency})`)}{input('prep',`${t('prepInput')} (${trial.currency})`)}{input('vat',`${t('vatInput')} (${trial.currency})`)}{input('sale',`${t('saleInput')} (${trial.currency})`)}{input('channel',t('channelInput'))}
      </div><p className="ods-note">{t('enterCosts')}</p><button className="ods-button" type="submit">{t('calc')}<ArrowUpRight size={18}/></button>{calcNotice?<p className="ods-note" role="status">{t(calcNotice)}</p>:null}</div>
     <aside className="ods-calc-result" aria-live="polite"><p className="ods-eyebrow">{tr('YOUR SCENARIO','SU ESCENARIO','سيناريو طلبك')}</p>{calcResult?.status==='complete'?<><dl><dt>{t('landed')}</dt><dd><bdi>{money(calcResult.landed,trial.currency)}</bdi></dd><dt>{t('cash')}</dt><dd><bdi>{money(calcResult.cash,trial.currency)}</bdi></dd><dt>{t('contribution')} / {t('unit')}</dt><dd className={calcResult.contribution<0?'ods-loss':''}><bdi>{money(calcResult.contribution,trial.currency)}</bdi><small>{format(calcResult.margin)}%</small></dd></dl></>:<><h3>{tr('Keep the cash and the margin in view.','Vea el efectivo y el margen juntos.','تابع السيولة والهامش معاً.')}</h3><p>{t(calcResult?'enterCosts':'economicsIntro')}</p></>}<p>{t('calcNote')}</p><a href="#buying-brief" className="ods-text-link">{t('brief')}<ArrowDown size={18}/></a></aside>
    </form>
   </section>

   <section id="supplier-checks" className="ods-section"><header className="ods-section-header"><div><p className="ods-eyebrow">06 / {tr('SUPPLIER CAPABILITY','CAPACIDAD DEL PROVEEDOR','قدرات المورد')}</p><h2>{t('supplierHeading')}</h2><p>{t('supplierIntro')}</p></div></header><div className="ods-supplier-cards">{ui.evidenceLevels.map(([title,body],i)=><article key={i}><span className="ods-index">0{i+1}</span><h3>{c(title)}</h3><p>{c(body)}</p></article>)}</div>
    <div className="ods-dimensions">{ui.dimensions.map(([title,body],i)=><div key={i}><h3>{c(title)}</h3><p>{c(body)}</p></div>)}</div>
   </section>
   <section id="order-checkpoints" className="ods-section"><header className="ods-section-header"><div><p className="ods-eyebrow">DDNZ / {tr('FROM BRIEF TO BATCH','DE LA SOLICITUD AL LOTE','من الموجز إلى الدفعة')}</p><h2>{t('processHeading')}</h2><p>{t('processIntro')}</p></div></header><div className="ods-process">{ui.steps.map((s,i)=><article key={s.id}><span className="ods-step-number">0{i+1}</span><h3>{c(s.title)}</h3><p>{c(s.body)}</p><a href="#buying-brief" className="ods-text-link" onClick={()=>{toggleCheck(s.id,true);onAction('request_check');}}>{t('requestCheck')}<Plus size={16}/></a></article>)}</div><p className="ods-note">{t('documentNote')} <a href="https://www.iata.org/contentassets/05e6d8742b0047259bf3a700bc9d42b9/lithium-battery-guidance-document.pdf" target="_blank" rel="noopener noreferrer">{t('iata')} ↗</a></p></section>

   <section id="buying-brief" className="ods-section ods-brief"><div className="ods-brief-intro"><p className="ods-eyebrow">07 / {tr('LET’S SPECIFY YOUR ORDER','DEFINAMOS SU PEDIDO','لنحدد مواصفات طلبك')}</p><h2>{t('brief')}</h2><p>{t('briefIntro')}</p><fieldset><legend>{t('checks')}</legend>{ui.steps.map(s=><label key={s.id} className="ods-checkbox"><input type="checkbox" checked={brief.checks.includes(s.id)} onChange={e=>toggleCheck(s.id,e.target.checked)}/><span>{c(s.title)}</span></label>)}</fieldset><p className="ods-note">{t('requestNote')}</p></div>
    <form className="ods-brief-form" onSubmit={send} noValidate><h3>{t('selected')}</h3>{brief.rows.length?<div className="ods-brief-products">{brief.rows.map(row=>{const p=getProduct(row.id);return <div key={row.id} className="ods-brief-row"><div><strong>{p.model}</strong><span>{c(p.name)}</span></div><label className="ods-field"><span>{t('qty')}</span><input inputMode="numeric" aria-label={p.model+' · '+t('qty')} value={row.quantity} onChange={e=>editBrief(d=>({...d,rows:d.rows.map(r=>r.id===row.id?{...r,quantity:e.target.value}:r)}))}/></label><button type="button" className="ods-remove" aria-label={t('remove')+' '+p.model} onClick={()=>editBrief(d=>({...d,rows:d.rows.filter(r=>r.id!==row.id)}))}>{t('remove')}</button></div>;})}</div>:<p className="ods-empty">{t('empty')}</p>}
     {brief.guideNote?<label className="ods-field ods-guide-brief-note"><span>{tr('Your load plan (editable)','Su plan de consumo (editable)','خطة أحمالك (قابلة للتعديل)')}</span><textarea id="outdoor-guide-plan" rows="6" maxLength="2400" value={brief.guideNote} onChange={e=>editBrief(d=>({...d,guideNote:e.target.value}))}/></label>:null}<div className="ods-form-grid">{['name' ,'email','company','destination','voltage'].map(key=><label className={'ods-field'+(key==='voltage'?' ods-wide':'')} key={key}><span>{t(key)}{key!=='company'?' *':''}</span><input id={'outdoor-brief-'+key} name={key} required={key!=='company'} type={key==='email'?'email':'text'} autoComplete={key==='name'?'name':key==='email'?'email':key==='company'?'organization':'off'} maxLength={key==='email'?254:160} value={brief.form[key]} onChange={e=>updateForm(key,e.target.value)}/></label>)}<label className="ods-field ods-wide"><span>{t('notes')}</span><textarea id="outdoor-brief-notes" rows="4" maxLength="1200" value={brief.form.notes} onChange={e=>updateForm('notes',e.target.value)}/></label></div>
     <label className="ods-checkbox"><input type="checkbox" id="outdoor-brief-consent" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>{t('consent')}</span></label><button type="button" className="ods-text-link ods-privacy" onClick={onPrivacy}>{t('privacy')}</button>
     <div className="ods-actions"><button type="button" className="ods-secondary" onClick={()=>{setReview(v=>!v);onAction('review_brief');}} aria-expanded={review}>{t('review')}</button><button type="submit" className="ods-button" disabled={sendState==='sending'}>{t(sendState==='sending'?'sending':'send')}<ArrowUpRight size={18}/></button></div>{review?<label className="ods-field ods-review"><span>{t('review')}</span><textarea readOnly rows="12" value={payload.message}/></label>:null}{sendState&&sendState!=='sending'?<p className={'ods-status '+(['missing','failure'].includes(sendState)?'ods-error':'')} role="status">{t(sendState)}</p>:null}
    </form>
   </section>
  </div>
 </main>;
}
