import React, {useEffect,useState,useRef} from 'react';
import {ArrowDown,ArrowUpRight,ArrowRight,BatteryFull,Plug,Sun,Usb,Cable,Check,Info,Tent,Laptop,Store} from 'lucide-react';
import {copy,L,sources} from './catalog.mjs';
import {guideUI} from './guide-copy.mjs';
import PowerSceneHero from './PowerSceneHero.jsx';
import PowerDeviceCards, {PowerSourceVisual} from './PowerDeviceLab.jsx';
import PowerModelMatches from './PowerModelMatches.jsx';
import {emptyPowerDraft,readPowerDraft,savePowerDraft} from './power-draft.mjs';
import {launchCopy} from './power-launch-copy.mjs';
import {sceneCopy} from './power-scenes.mjs';
import {powerModels,powerModel,devices,presets,loadPreset,analysePlan,capacityPercent,chargeFloor,guideHandoff} from './power-guide.mjs';
import {localizedProductPath,outdoorPath} from '../../lib/productLocalization.mjs';
const sections=['appliance-plan','power-numbers','energy-flow','charging-guide','buying-checks'];
const navOrder=[2,0,1,3,4];
const uniqueModels=powerModels.filter(p=>p.id!=='sanhe-bg');
const ports={
 'sanhe-st':['AC × 1 · 220 V','DC5521 × 6 · 12 V','USB-A × 2 + USB-C × 2 · 5 V / 2 A'],
 'sanhe-bg':['AC × 1 · 220 V','DC5521 × 6 · 12 V','USB-A × 2 + USB-C × 2 · 5 V / 2 A'],
 'tieding-51':['AC × 1','DC × 3 · 12 V','USB × 2 + Type-C × 2'],
 'ecoflow-classic':['AC × 3 · 220 V',null,'USB-A · 12 W / USB-C · 30 W + 100 W'],
 'ecoflow-max':['AC × 4 · 220 V','12.6 V · 10 A / 126 W','USB-A · 18 W / USB-C · 100 W + 30 W × 2'],
 'eboom-lxyt24':['AC × 3 · 220 V',null,'USB × 4 / Type-C × 2'],
};
export default function PowerGuideContent({locale='en',onAction=(_action,_details={})=>{}}){
 const t=k=>copy(guideUI[k],locale),c=v=>copy(v,locale),tr=(en,es,ar)=>c(L(en,es,ar));
 const [modelId,setModelId]=useState('sanhe-st'),[port,setPort]=useState('ac'),[scenario,setScenario]=useState('camp'),[sceneId,setSceneId]=useState('camp'),[plan,setPlan]=useState(()=>loadPreset()),[eff,setEff]=useState('85'),[panel,setPanel]=useState('100'),[yieldPct,setYield]=useState('70');
 const [ready,setReady]=useState(false),[saveStatus,setSaveStatus]=useState('saved');
 const actionRef=useRef(onAction);actionRef.current=onAction;
 const applyDraft=d=>{setModelId(d.modelId);setSceneId(d.sceneId);setScenario(d.scenario);setPlan(d.plan);setEff(d.eff);setPort(d.port);setPanel(d.panel);setYield(d.yieldPct);};
 useEffect(()=>{let saved=null;try{saved=readPowerDraft(window.sessionStorage);}catch{}const d=saved||emptyPowerDraft(),id=new URLSearchParams(window.location.search).get('model');if(powerModels.some(m=>m.id===id)){d.modelId=id;const clean=new URL(window.location.href);clean.searchParams.delete('model');window.history.replaceState(window.history.state,'',clean.pathname+clean.search+clean.hash);}applyDraft(d);setSaveStatus(saved?'restored':'saved');setReady(true);},[]);
 const draft={version:1,modelId,sceneId,scenario,plan,eff,port,panel,yieldPct};
 useEffect(()=>{if(!ready)return;let saved=false;try{saved=savePowerDraft(window.sessionStorage,draft);}catch{}if(!saved)setSaveStatus('unavailable');},[ready,modelId,sceneId,scenario,plan,eff,port,panel,yieldPct]);
 useEffect(()=>{if(!ready||typeof IntersectionObserver==='undefined')return;const target=document.getElementById('power-plan-result');const observer=new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting)){actionRef.current('result_view');observer.disconnect();}},{threshold:.15});if(target)observer.observe(target);return()=>observer.disconnect();},[ready]);
 const chooseModel=(id,action='model_select')=>{setModelId(id);onAction(action,{modelId:id});};
 const resetDraft=()=>{applyDraft(emptyPowerDraft());setSaveStatus('resetDone');onAction('draft_reset');};
 const enterBrief=()=>onAction('brief_open',{modelId});
 const m=powerModel(modelId),result=analysePlan(m,plan.rows,plan.hours,eff),f=(n,d=1)=>Number(n).toLocaleString(locale,{maximumFractionDigits:d}),catalogue=localizedProductPath(outdoorPath,locale),handoff=guideHandoff(m,result,locale,catalogue,draft),floor=m.pvMax?chargeFloor(m,panel,yieldPct):null;
 const editRow=(id,key,value)=>{setPlan(p=>({...p,rows:p.rows.map(r=>r.id===id?{...r,[key]:value}:r)}));setScenario('');if(key==='on')onAction('device_toggle',{deviceId:id});};
 const choosePreset=id=>{setSceneId(id);setScenario(id);setPlan(loadPreset(id));onAction('scene_select',{sceneId:id});};
 const meter=(ratio,kind)=><div className={'opg-meter '+(ratio>1?'is-over':'')} role="img" aria-label={`${kind}: ${f(ratio*100)}%`}><span style={{width:`${Math.min(100,ratio*100)}%`}}/></div>;
 const selectedPort=ports[m.id][['ac','dc','usb'].indexOf(port)];
 return <main id="main-content" className="ods opg" lang={locale} dir={locale==='ar'?'rtl':'ltr'}><div className="ods-wrap">
  <nav className="ods-breadcrumb" aria-label={tr('Breadcrumb','Ruta de navegación','مسار التصفح')}><a href={catalogue}>{tr('Outdoor products','Productos outdoor','المنتجات الخارجية')}</a><span>/</span><span>{tr('Power guide','Guía de energía','دليل الطاقة')}</span></nav>
  <PowerSceneHero locale={locale} sceneId={sceneId} model={m} rows={plan.rows} onScenario={choosePreset} onModel={chooseModel} onAction={onAction} onEditRow={editRow} catalogue={catalogue}/>
  <nav className="ods-section-nav" aria-label={t('eyebrow')}>{sections.map((id,i)=><a key={id} href={'#'+id}><small>0{i+1}</small> {c(guideUI.nav[navOrder[i]])}</a>)}</nav>
  <div className="opg-mobile-shortcuts"><a href="#appliance-plan">{c(launchCopy.appliances)}</a><a href="#power-plan-result">{c(launchCopy.result)} <ArrowDown size={15}/></a></div>
  <section id="appliance-plan" className="ods-section"><header className="ods-section-header"><div><p className="ods-eyebrow">01 / Wh ÷ W = h</p><h2>{c(sceneCopy.lab)}</h2><p>{c(sceneCopy.labIntro)}</p></div></header>
   <div className="opg-draft-tools"><p role="status">{ready?c(launchCopy[saveStatus]):''}</p><button type="button" onClick={resetDraft}>{c(launchCopy.reset)}</button></div>
   <div className="opg-presets">{presets.map((p,i)=>{const Icon=[Tent,Laptop,Store][i];return <button type="button" key={p.id} aria-pressed={scenario===p.id} onClick={()=>choosePreset(p.id)}><Icon/><span>{c(p.name)}</span><small>{p.hours} h</small></button>;})}</div>{scenario?<p className="ods-note">{c(presets.find(p=>p.id===scenario).note)}</p>:<p className="ods-note">{c(sceneCopy.custom)}</p>}
   <p className="ods-note opg-lab-assumptions">{t('applianceNote')}</p>
   <div className="opg-planner opg-device-planner"><div className="opg-lab-main"><div className={'opg-lab-status'+(result.status==='complete'?(result.overload?' is-over':result.shortfall?' is-short':''):'')}><span>{t('runtime')}<strong>{result.status==='complete'&&!result.overload?f(result.hours)+' '+t('hours'):result.status==='complete'?t('overload'):'—'}</strong>{result.status==='complete'?<small>{t('duration')}: {f(result.targetHours)} h</small>:null}</span><bdi>{result.status==='complete'?f(result.watts)+' / '+f(m.watts)+' W':'—'}</bdi></div><PowerDeviceCards rows={plan.rows} locale={locale} onEdit={editRow}/>
<div className="opg-plan-controls"><label className="ods-field"><span>{t('duration')}</span><input id="power-target-hours" inputMode="decimal" value={plan.hours} onChange={e=>{setPlan(p=>({...p,hours:e.target.value}));setScenario('');}}/><small>0–168 h</small></label><label className="ods-field"><span>{t('efficiency')}</span><input id="power-usable-percent" inputMode="decimal" value={eff} onChange={e=>setEff(e.target.value)}/><small>50–95%</small></label></div></div>
   <aside id="power-plan-result" className={'opg-plan-result opg-lab-result'+(result.status==='complete'&&result.overload?' is-over':'')} aria-live="polite"><p className="ods-eyebrow">{t('result')}</p><label className="ods-field opg-result-model"><span>{t('choose')}</span><select id="power-plan-model" value={modelId} onChange={e=>chooseModel(e.target.value)}>{powerModels.map(p=><option key={p.id} value={p.id}>{p.model}</option>)}</select></label><PowerSourceVisual model={m} rows={plan.rows} result={result} locale={locale}/>{result.status==='complete'?<><div className="opg-runtime-number"><span>{t('runtime')}</span><strong>{result.overload?'—':f(result.hours)} <small>{result.overload?'':t('hours')}</small></strong></div><div className="opg-result-metric"><span>{t('load')}</span><bdi>{f(result.watts)} / {f(m.watts)} W</bdi>{meter(result.powerRatio,t('load'))}<p className={result.overload?'opg-bad':'opg-ok'}>{result.overload?t('overload'):t('within')}</p></div><div className="opg-result-metric"><span>{t('energy')}</span><bdi>{f(result.energy)} / {f(result.usable)} Wh</bdi>{meter(result.energyRatio,t('energy'))}<p className={result.shortfall?'opg-bad':'opg-ok'}>{result.shortfall?t('shortfall'):t('enough')}</p></div><a className="opg-compare-link" href="#power-model-matches">{c(launchCopy.comparisonLink)} <ArrowDown size={15}/></a><small>{t('usable')}: <bdi>{f(result.usable)} Wh</bdi></small>{result.starting?<p className="opg-result-note">{t('startCheck')}</p>:null}<a className="ods-button" href={handoff} onClick={enterBrief}>{t('send')}<ArrowUpRight size={18}/></a></>:<p className="opg-result-note">{t('incomplete')}</p>}</aside></div><p className="ods-note">{t('formula')}</p><PowerModelMatches rows={plan.rows} hours={plan.hours} eff={eff} modelId={modelId} onChoose={id=>chooseModel(id,'compare_select')} locale={locale}/>
  </section>
  <section id="power-numbers" className="ods-section"><header className="ods-section-header"><div><p className="ods-eyebrow">02 / {m.model}</p><h2>{t('numbers')}</h2></div></header>
   <div className="opg-number-grid"><article><BatteryFull/><p>{t('stored')}</p><strong><bdi>{f(m.wh)} <small>Wh</small></bdi></strong><span className="opg-equivalent"><bdi>{f(m.wh/1000,4)} kWh</bdi></span><p>{t('storedNote')}</p></article><article><Plug/><p>{t('output')}</p><strong><bdi>{f(m.watts,0)} <small>W</small></bdi></strong><span className="opg-equivalent">{tr('Continuous rating','Potencia continua','قدرة مستمرة')}</span><p>{t('outputNote')}</p></article><article><BatteryFull/><p>{t('fullCharge')}</p><strong>{m.acHours?<bdi>~{f(m.acHours)} <small>h</small></bdi>:<span className="opg-unknown">{t('unknown')}</span>}</strong><span className="opg-equivalent">{tr('According to source','Según la fuente','وفق المصدر')}</span><p>{t('chargeNote')}</p></article></div>
   <div className="opg-capacity"><div><h3>{t('capacity')}</h3><p>{t('capacityNote')}</p></div><div className="opg-bars">{[{label:t('phone'),wh:18.5,id:'phone'},{label:t('powerbank'),wh:37,id:'pack'},...uniqueModels.map(p=>({label:p.model,wh:p.wh,id:p.id}))].map(p=><div className={'opg-bar-row'+((p.id===m.id||m.id==='sanhe-bg'&&p.id==='sanhe-st')?' is-selected':'')} key={p.id}><span>{p.label}</span><div className="opg-bar-track"><i style={{width:capacityPercent(p.wh)+'%'}}/></div><bdi>{f(p.wh)} Wh</bdi></div>)}</div></div><p className="ods-note opg-inset"><Info size={18}/>{t('voltageNote')}</p>
  </section>
  <section id="energy-flow" className="ods-section"><header className="ods-section-header"><div><p className="ods-eyebrow">03 / AC · DC · USB</p><h2>{t('flow')}</h2><p>{t('flowNote')}</p></div></header>
   <div className="opg-flow"><div className="opg-inputs"><div><Plug/><span>{t('mains')}</span></div><div><Sun/><span>{t('sun')}</span></div></div><ArrowRight className="opg-flow-arrow" aria-hidden="true"/><div className="opg-battery"><BatteryFull size={42}/><strong dir="ltr">{f(m.wh)} Wh</strong><span>{t('battery')}</span></div><ArrowRight className="opg-flow-arrow" aria-hidden="true"/><div className="opg-outputs" role="group" aria-label={tr('Select an output','Seleccione salida','اختر المخرج')}>{[['ac',Plug],['dc',Cable],['usb',Usb]].map(([key,Icon])=><button key={key} type="button" aria-pressed={port===key} onClick={()=>setPort(key)}><Icon size={24}/><span>{t(key)}</span><ArrowRight size={16}/></button>)}</div></div>
   <div className="opg-port-detail" aria-live="polite"><div className="opg-port-symbol">{port==='ac'?<Plug size={36}/>:port==='dc'?<Cable size={36}/>:<Usb size={36}/>}<span>{port.toUpperCase()}</span></div><div><p className="ods-eyebrow">{m.model}</p><h3 dir={selectedPort?'ltr':undefined}>{selectedPort||(m.id==='eboom-lxyt24'?tr('Confirm the DC configuration','Confirme la configuración CC','أكد تكوين DC'):tr('No dedicated DC output specified for this model','Sin salida CC dedicada especificada para este modelo','لا يوجد خرج DC مخصص محدد لهذا الطراز'))}</h3><p>{t(port+'Tip')}</p>{port==='usb'&&m.id.startsWith('sanhe')?<p className="opg-port-callout">{tr('Listed USB-C: 5V × 2A = 10W per port. Do not assume laptop PD charging from the connector alone.','USB-C indicado: 5V × 2A = 10W por puerto. No asuma carga PD de portátil solo por el conector.','USB-C المعلن: 5V × 2A = 10W لكل منفذ. لا تفترض دعم شحن الحاسوب PD اعتماداً على شكل الموصل.')}</p>:null}{port==='dc'&&m.id==='eboom-lxyt24'?<p>{tr('The family table lists a 24V / 100A output without a clear model-specific connector. Request its pinout and protection limits before using it.','La tabla de familia indica salida 24V / 100A sin conector definido por modelo. Pedir conexión y límites de protección antes de usar.','يذكر جدول المجموعة خرج 24V / 100A دون موصل محدد للطراز. اطلب توصيلاته وحدود الحماية قبل استخدامه.')}</p>:null}</div></div>
   <details className="opg-source-details"><summary>{t('source')} · {m.model}</summary><p>{c(m.shared)}</p>{sources[m.source]?.startsWith?.('/')?<a href={sources[m.source]} target="_blank" rel="noopener noreferrer">{t('source')} ↗</a>:<a href={catalogue+'#product-'+m.id}>{tr('View product details','Ver detalles del producto','عرض تفاصيل المنتج')} ↗</a>}</details>
  </section>
  <section id="charging-guide" className="ods-section"><header className="ods-section-header"><div><p className="ods-eyebrow">04 / {tr('THE RETURN JOURNEY','EL CAMINO DE VUELTA','رحلة الشحن')}</p><h2>{t('charging')}</h2><p>{t('chargingIntro')}</p></div></header>
   <div className="opg-charging"><div><p className="ods-eyebrow">{m.model}</p><h3>{t('source')}</h3><p>{c(m.charging)}</p><div className="opg-charge-limit"><Sun/><span>{tr('Listed PV input ceiling','Límite de entrada FV indicado','الحد الأعلى لدخل PV المذكور')}<strong>{m.pvMax?<bdi>{f(m.pvMax)} W</bdi>:t('unknown')}</strong></span></div></div><div className="opg-solar-lab">{m.pvMax?<>{m.id==='ecoflow-max'?<p className="ods-note">{tr('The 1,000W total requires both inputs, each limited to 500W. Match each panel string to its input voltage and current limits.','El total de 1.000W requiere ambas entradas, cada una limitada a 500W. Ajuste tensión y corriente de cada grupo de paneles.','يتطلب إجمالي 1,000W استخدام المدخلين، بحد 500W لكل منهما. طابق جهد وتيار كل مجموعة ألواح مع حدود مدخلها.')}</p>:null}<label className="ods-field"><span>{t('solarWatts')}</span><input id="power-panel-watts" inputMode="decimal" value={panel} onChange={e=>setPanel(e.target.value)}/></label><label className="ods-field"><span>{t('solarYield')} <bdi>{yieldPct}%</bdi></span><input id="power-solar-yield" type="range" min="10" max="100" step="5" value={yieldPct} onChange={e=>setYield(e.target.value)}/></label><div className="opg-solar-result" aria-live="polite"><span>{t('floor')}</span><strong>{floor===null?'—':f(floor)} <small>h</small></strong></div></>:<><p>{t('solarUnknown')}</p>{m.id.startsWith('sanhe')?<p>{tr('For the 3Hz models, the 100W figure describes the quoted panel setup, not a verified input ceiling.','En los modelos 3Hz, 100W describe el panel de la oferta, no un límite de entrada verificado.','لطرازات 3Hz، تصف قيمة 100W اللوح المذكور في العرض وليست حداً أعلى مؤكداً للدخل.')}</p>:null}<label className="ods-field"><span>{t('choose')}</span><select id="power-charge-model" value={modelId} onChange={e=>chooseModel(e.target.value)}>{powerModels.map(p=><option key={p.id} value={p.id}>{p.model}</option>)}</select></label></>}</div></div><p className="ods-note">{t('floorNote')}</p>
  </section>
  <section id="buying-checks" className="ods-section"><header className="ods-section-header"><div><p className="ods-eyebrow">05 / {tr('SPECIFY · TEST · REPEAT','DEFINIR · PROBAR · REPETIR','حدد · اختبر · كرر')}</p><h2>{t('before')}</h2><p>{t('beforeIntro')}</p></div></header><div className="opg-checks">{guideUI.checks.map(([title,body],i)=><article key={i}><span>0{i+1}</span><h3>{c(title)}</h3><p>{c(body)}</p></article>)}</div><p className="opg-boundary"><Info/>{t('boundary')}</p><p className="ods-note">{t('referenceNote')}</p><div className="opg-source-links"><a href="/outdoor-sourcing-media/ecoflow-spec-6.webp" target="_blank" rel="noopener noreferrer">EcoFlow · PDF 6 ↗</a><a href="/outdoor-sourcing-media/ecoflow-spec-7.webp" target="_blank" rel="noopener noreferrer">EcoFlow · PDF 7 ↗</a><a href="/outdoor-sourcing-media/eboom-spec-20.webp" target="_blank" rel="noopener noreferrer">EBOOM · p.20 ↗</a><a href="https://manuals.ecoflow.com/eu/product/delta-3-classic?lang=en_US" target="_blank" rel="noopener noreferrer">{tr('EcoFlow operating manual','Manual de uso EcoFlow','دليل تشغيل EcoFlow')} ↗</a></div><div className="ods-actions"><a className="ods-button" href={handoff||catalogue+'#buying-brief'} onClick={enterBrief}>{t('send')}<ArrowUpRight size={18}/></a><a className="ods-text-link" href={catalogue}>{t('catalogue')}<ArrowUpRight size={18}/></a></div></section>
 </div></main>;
}
