import React from 'react';
import {Headphones,MonitorSpeaker,Speaker,Mic2,Radio,CheckCircle2,PackageCheck,Truck} from 'lucide-react';
import {categoryCopy,audioCategoryPaths,audioCategoryRoot,audioCategoryProducts,type CategoryLanguage} from './categories';
import {buyerCopy,bundleSelections,extraBundleIndices,criterionIndices} from './buyer-guide';
import {foodPrefix} from '../food-processing/localization';
const icons=[Headphones,MonitorSpeaker,Speaker,Mic2,Radio];
// Each image is a category example, explicitly separate from the requested configurations.
const gallery=[
 [{image:'tws-earbuds-reference',product:0},{image:'folding-headphones-reference',product:6},{image:'wireless-gaming-headset-reference',product:11}],
 [{image:'desktop-usb-reference',product:0},{image:'active-bookshelf-reference',product:6}],
 [{image:'mini-black-product-v1',product:0},{image:'bts07-shower-reference',product:3}],
 [{image:'k12-karaoke-reference',product:1},{image:'trolley-party-reference',product:6}],
 [{image:'active-bookshelf-reference',product:0},{image:'passive-bookshelf-reference',product:5},{image:'vintage-range-hero-v1',product:7}],
];
export function AudioCategoryLinks({locale='en',current=-1}:{locale?:CategoryLanguage,current?:number}){
 const c=categoryCopy[locale];
 return <nav aria-label={c.ui[7]} className="mx-auto max-w-7xl px-6 py-10"><h2 className="text-2xl font-bold">{current<0?c.ui[7]:c.ui[4]}</h2><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{c.names.map((name,i)=>i!==current&&<a key={name} className="rounded-xl border border-purple-200 bg-white p-5 font-semibold text-purple-800" href={`${foodPrefix(locale)}${audioCategoryPaths[i]}/`}>{name} →</a>)}</div></nav>;
}
export default function AudioCategoryContent({index,locale='en'}:{index:number,locale?:CategoryLanguage}){
 const c=categoryCopy[locale],b=buyerCopy[locale],prefix=foodPrefix(locale),Icon=icons[index],products=audioCategoryProducts(index,locale);
 const quote=(name:string,body:string)=>`${prefix}/get-a-quote/?${new URLSearchParams({leadGoal:'Product Sourcing',source:'audio_category',industry:c.names[index],productScope:`${name}\n${body}`,overviewBrief:`${name}\n${body}`})}`;
 const packNames=[...c.packNames[index],...extraBundleIndices[index].map(i=>b.extraPacks[i])];
 return <main id="main-content" lang={locale==='zh'?'zh-CN':locale} dir={locale==='ar'?'rtl':'ltr'} className="bg-slate-50 text-slate-900">
 <div className="mx-auto max-w-7xl space-y-14 px-6 py-10">
  <nav aria-label={c.ui[0]} className="flex flex-wrap gap-3 text-sm"><a className="text-purple-800 underline" href={`${prefix}${audioCategoryRoot}/`}>{c.ui[0]}</a><span>/</span><span>{c.names[index]}</span></nav>
  <header className="max-w-4xl"><Icon size={42} className="mb-5 text-purple-700" aria-hidden="true"/><h1 className="text-4xl font-bold leading-tight md:text-5xl">{c.titles[index]}</h1><p className="mt-6 text-lg leading-8">{c.intros[index]}</p>
   <nav aria-label={b.labels[0]} className="mt-7 flex flex-wrap gap-3">{[['#product-selection',b.labels[15]],['#order-packages',b.labels[16]],['#buying-guide',b.labels[17]]].map(([href,label])=><a key={href} className="rounded-xl border border-purple-300 bg-white px-5 py-3 font-semibold text-purple-800" href={href}>{label} ↓</a>)}</nav>
  </header>
  <section aria-label={b.labels[12]}><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{gallery[index].map(({image,product})=><figure key={image} className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><img src={`/images/product-showcase/audio/${image}.webp`} alt={products[product][0]} width="300" height="300" loading="lazy" className="aspect-[4/3] max-h-72 w-full object-contain p-4"/><figcaption className="border-t border-slate-100 px-5 py-4 font-semibold">{products[product][0]}</figcaption></figure>)}</div><p className="mt-4 max-w-4xl text-sm leading-6 text-slate-600">{b.labels[13]}</p></section>
  <section id="product-selection" className="scroll-mt-32"><h2 className="text-3xl font-bold">{b.labels[11]}</h2><div className="mt-6 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{products.map(([name,body],i)=><article id={`product-${i+1}`} key={name} className="flex scroll-mt-32 flex-col rounded-2xl border border-slate-200 bg-white p-5"><div className="mb-5 flex items-center justify-between text-purple-700"><Icon size={32} aria-hidden="true"/><span className="text-2xl font-light tabular-nums text-slate-400" aria-hidden="true">{String(i+1).padStart(2,'0')}</span></div><h3 className="text-lg font-bold leading-7">{name}</h3><span className="mt-4 text-sm font-semibold text-purple-800">{b.checks[index][criterionIndices[index][i]][0]}</span><p className="mb-6 mt-2 text-sm leading-6 text-slate-600">{body}</p><a className="mt-auto border-t border-slate-100 pt-4 font-semibold text-purple-800 underline" href={quote(name,body)}>{c.ui[5]} →</a></article>)}</div></section>
  <section id="order-packages" className="scroll-mt-32"><h2 className="text-3xl font-bold">{c.ui[2]}</h2><div className="mt-6 grid gap-6 md:grid-cols-2">{packNames.map((name,i)=>{const included=bundleSelections[index][i];const brief=[...included.map(p=>products[p][0]),c.packBodies[index][i]||'',b.packPlan].filter(Boolean).join('\n');return <article data-audio-bundle key={name} className="flex flex-col rounded-2xl border border-purple-100 bg-purple-50 p-7"><h3 className="text-2xl font-bold">{name}</h3><p className="mt-5 text-sm font-semibold text-purple-800">{b.labels[8]}</p><ul className="my-3 space-y-2">{included.map(p=><li key={p}><a className="inline-flex items-start gap-2 text-purple-900 underline" href={`#product-${p+1}`}><CheckCircle2 size={18} className="mt-1 shrink-0" aria-hidden="true"/>{products[p][0]}</a></li>)}</ul>{c.packBodies[index][i]&&<p className="my-3 leading-7">{c.packBodies[index][i]}</p>}<p className="mb-5 text-sm leading-6 text-slate-600">{b.packPlan}</p><a className="mt-auto font-semibold text-purple-800 underline" href={quote(name,brief)}>{b.labels[10]} →</a></article>})}</div></section>
  <section id="buying-guide" className="scroll-mt-32"><h2 className="text-3xl font-bold">{b.labels[1]}</h2><div className="mt-6 overflow-x-auto rounded-2xl border border-slate-200 bg-white"><table className="w-full text-start"><thead className="bg-slate-100"><tr><th scope="col" className="p-5 text-start">{b.labels[2]}</th><th scope="col" className="p-5 text-start">{b.labels[3]}</th></tr></thead><tbody>{b.checks[index].map(([name,body])=><tr key={name} className="border-t border-slate-200"><th scope="row" className="p-5 text-start align-top font-semibold">{name}</th><td className="p-5 leading-7">{body}</td></tr>)}</tbody></table></div></section>
  <section className="grid gap-6 lg:grid-cols-3">{[{title:b.labels[4],body:b.inspection[index],icon:CheckCircle2},{title:b.labels[5],body:b.packaging,icon:PackageCheck},{title:b.labels[6],body:b.freight,icon:Truck}].map(({title,body,icon:SectionIcon})=><article key={title} className="rounded-2xl border border-slate-200 bg-white p-7"><SectionIcon size={30} className="mb-4 text-purple-700" aria-hidden="true"/><h2 className="text-2xl font-bold">{title}</h2><p className="mt-5 leading-7">{body}</p></article>)}<p className="text-sm text-slate-600 lg:col-span-3">{b.evidence}</p></section>
  <section><h2 className="text-3xl font-bold">{b.channelTitle}</h2><p className="mt-5 text-lg leading-8">{c.channel[index]}</p><div className="mt-6 grid gap-5 lg:grid-cols-3">{b.channels.map(([title,body])=><article key={title} className="rounded-2xl border border-slate-200 p-6"><h3 className="text-xl font-bold">{title}</h3><p className="mt-4 leading-7">{body}</p></article>)}</div></section>
  <section><h2 className="text-3xl font-bold">{c.ui[3]}</h2><h3 className="mt-6 text-xl font-bold">{c.questions[index]}</h3><p className="mt-4 max-w-4xl leading-8">{c.answers[index]}</p></section>
  <section className="rounded-2xl bg-slate-900 p-8 text-white"><h2 className="text-3xl font-bold">{b.labels[7]}</h2><p className="my-5 max-w-4xl leading-8">{b.brief}</p><a className="inline-block rounded-xl bg-white px-5 py-3 font-bold text-purple-900" href={quote(c.names[index],b.brief)}>{c.ui[5]} →</a><p className="mt-5 text-sm leading-7 text-slate-300">{c.note}</p><nav className="mt-6 flex flex-wrap gap-5">{['/sourcing-services/','/sourcing-services/inspection-quality-control/','/services/sea-freight/'].map((path,i)=><a className="underline" key={path} href={`${prefix}${path}`}>{b.serviceLinks[i]}</a>)}</nav></section>
 </div><AudioCategoryLinks locale={locale} current={index}/></main>;
}
