import test from 'node:test';
import assert from 'node:assert/strict';
import {existsSync,readFileSync} from 'node:fs';
import products from '../../src/features/commercial-kitchen/data/products.mjs';
import launch from '../../src/features/commercial-kitchen/data/launch.mjs';
import benchmarks from '../../src/features/commercial-kitchen/data/benchmarks.mjs';
import {addItems,cleanList,createPriceDraft,makeBrief,quantity,validateBuyingTarget} from '../../src/features/commercial-kitchen/data/model.mjs';
import {buildInquiryMessage,isProductionHost,submitInquiry} from '../../src/features/commercial-kitchen/data/inquiry.mjs';

const root=new URL('../..',import.meta.url);
const product=id=>products.find(item=>item.id===id);

test('keeps all 26 catalog SKUs',()=>assert.equal(products.length,26));
test('keeps exactly eight indicative supply references',()=>assert.equal(products.filter(item=>item.quote).length,8));
test('preserves approved indicative prices, currencies and reference quantities',()=>assert.deepEqual(Object.fromEntries(products.filter(item=>item.quote).map(item=>[item.model,[item.quote.price,item.quote.currency,item.quote.minUnits]])),{'HZB-50/AB':[1318.34,'CNY',1],'ZH-101V':[348.8,'CNY',10],'GN650TNPro':[4534.41,'CNY',1],'GNT2MTNPro':[3170.91,'CNY',1],'ZH-818':[291.1,'CNY',1],'HZB-100FA':[2124.51,'CNY',1],'ZH-102V':[824.44,'CNY',1],'500W variant':[2283.06,'CNY',1]}));
test('every product image is an actually copied commercial-kitchen media file',()=>{for(const item of products){assert.match(item.image,/^\/commercial-kitchen-media\//);assert.ok(existsSync(new URL(`../../public${item.image}`,import.meta.url)),item.image);}});
test('the public product data excludes source and supplier metadata',()=>{for(const item of products){for(const key of ['originalImage','internal_price','supplier_reference_price','source_file','sourceLabel','sourceLocation'])assert.equal(item[key],undefined);}});
test('the eight featured IDs exist and lead the feature data',()=>{assert.equal(launch.featuredProductIds.length,8);for(const id of launch.featuredProductIds)assert.ok(product(id),id);});
test('every assortment item refers to a catalog product',()=>{for(const kit of launch.assortments)for(const item of kit.items)assert.ok(product(item.productId),item.productId);});
test('retail references preserve external HTTPS links and catalog matches',()=>{for(const benchmark of benchmarks){assert.equal(new URL(benchmark.url).protocol,'https:');assert.ok(product(benchmark.productId));}});
test('quantity sanitisation retains the established 0 to 9999 bounds',()=>{assert.equal(quantity(-2),0);assert.equal(quantity(10000),9999);assert.equal(quantity(2.7),2);});
test('cleanList drops unknown and empty entries',()=>assert.deepEqual(cleanList({'ZH-101V':2,missing:8,'cold-2':0},products),{'ZH-101V':2}));
test('addItems preserves the established list merge behavior',()=>assert.deepEqual(addItems({'ZH-101V':2},{'ZH-101V':3,'cold-2':1},products),{'ZH-101V':5,'cold-2':1}));
test('a valid fryer reference retains its 10-unit basis',()=>{const fryer=product('ZH-101V');const draft={...createPriceDraft(fryer),productId:fryer.id,intent:'trial'};assert.equal(validateBuyingTarget(products,draft).units,10);});
test('a fryer below ten units cannot assert the indicative unit reference',()=>{const fryer=product('ZH-101V');const draft={...createPriceDraft(fryer),productId:fryer.id,intent:'trial',units:'1'};assert.equal(validateBuyingTarget(products,draft),null);});
test('the brief asks for a quote when a saved fryer reference is below its basis',()=>{const fryer=product('ZH-101V');const target=validateBuyingTarget(products,{...createPriceDraft(fryer),productId:fryer.id,intent:'trial'});const brief=makeBrief(products,{[fryer.id]:1},{type:'Distributor / dealer',buyingTargets:{[fryer.id]:target}});assert.match(brief,/please quote this smaller quantity/);assert.doesNotMatch(brief,/Indicative buying price:/);});
test('the concise enquiry includes optional company and preferred contact',()=>{const message=buildInquiryMessage({products,list:{'ZH-101V':10},form:{country:'United Arab Emirates',company:'Example Distribution Co.',contact:'WhatsApp +971 50 000 0000'}});assert.match(message,/Company: Example Distribution Co\./);assert.match(message,/Preferred contact: WhatsApp \+971 50 000 0000/);});
test('local enquiry simulation does not invoke fetch',async()=>{let calls=0;const result=await submitInquiry({},{hostname:'localhost',fetchImpl:async()=>{calls++;}});assert.deepEqual(result,{mode:'preview',networked:false});assert.equal(calls,0);});
test('production sending remains restricted to the two approved hostnames',()=>{assert.equal(isProductionHost('ddnzglobal.com'),true);assert.equal(isProductionHost('www.ddnzglobal.com'),true);assert.equal(isProductionHost('preview.ddnzglobal.com'),false);});
test('the module has explicit kitchen prefixes, no preview shell, and accepts the privacy callback',()=>{const source=readFileSync(new URL('../../src/features/commercial-kitchen/KitchenContent.jsx',import.meta.url),'utf8');const css=readFileSync(new URL('../../src/features/commercial-kitchen/styles/kitchen.css',import.meta.url),'utf8');assert.match(source,/export default function KitchenContent\(\{onPrivacy\}\)/);assert.match(source,/className="ddnz-kitchen"/);assert.match(source,/onPrivacy=\{onPrivacy\}/);assert.doesNotMatch(source,/createRoot|CONTENT PREVIEW|className="header"|className="footer"/);assert.doesNotMatch(css,/@scope/);assert.match(css,/\.ddnz-kitchen \.wrap/);assert.match(css,/dialog\.detail-dialog\[open\]/);});
