import FilmVideoContent from './FilmVideoContent';
import FilmGuideDetails from './FilmGuideDetails';
import React,{useState} from 'react';
import {filmGuideCopy,filmGuideText,type FilmGuideKind,type FilmGuideLocale} from './copy';
import {foodPrefix} from '../food-processing/localization';
import {overviewCopy} from '../overview/copy';
export const guideAssets=['001-kit-photo.jpg','curved-glass-cover-v1.png'];
export function filmGuideInquiry(locale:FilmGuideLocale,selected:number[],notes:string,kind:FilmGuideKind='index'){const c=filmGuideCopy[locale];return `${foodPrefix(locale)}/get-a-quote/?`+new URLSearchParams({source:'film_guide',leadGoal:'Product Sourcing',industry:filmGuideText(locale,kind).title,overviewBrief:[filmGuideText(locale,kind).title,...selected.map(i=>c.checks[i]),notes].filter(Boolean).join('\n')});}
export default function FilmGuideContent({locale,kind='index'}:{locale:FilmGuideLocale;kind?:FilmGuideKind}){
 const text=filmGuideText(locale,kind),checkIds=kind==='price-differences'?[0,1,2,3,4,5]:kind==='curved-glass'?[6,7,8,9,10]:Array.from({length:11},(_,i)=>i);
 const c=filmGuideCopy[locale],u=overviewCopy[locale].ui,prefix=foodPrefix(locale),[selected,setSelected]=useState<number[]>([]),[notes,setNotes]=useState(''),[ready,setReady]=useState(false);
 return <main id="main-content" lang={locale==='zh'?'zh-CN':locale} dir={locale==='ar'?'rtl':'ltr'} className="bg-slate-50 text-slate-900"><div className="mx-auto max-w-6xl space-y-12 px-6 py-12"><header><a className="text-purple-800 underline" href={`${prefix}/products/`}>{u.categories}</a><h1 className="mt-5 text-4xl font-bold leading-tight">{text.title}</h1><p className="mt-6 text-lg leading-8">{text.intro}</p></header>
 {kind==='videos'&&<FilmVideoContent locale={locale}/>}
 {kind!=='index'&&kind!=='videos'&&<FilmGuideDetails locale={locale} kind={kind}/>}
 <section><h2 className="text-2xl font-bold">{c.labels[3]}</h2><div className="mt-6 grid gap-6 md:grid-cols-2">{c.cards.map(([title,body],i)=><a className="overflow-hidden rounded-2xl border bg-white" href={`${prefix}/screen-protectors/guides/${i===0?'price-differences':'curved-glass'}/`} key={title}><img src={`/screen-protector-media/assets/${guideAssets[i]}`} width="1200" height="720" alt={title} className="aspect-video w-full object-contain"/><div className="p-6"><h3 className="text-xl font-bold text-purple-800">{title} ↗</h3><p className="mt-4 leading-7">{body}</p></div></a>)}</div></section>
 <section id="guide-brief"><h2 className="text-2xl font-bold">{c.labels[0]}</h2><form onSubmit={e=>{e.preventDefault();setReady(true);}} className="mt-6 space-y-6"><fieldset><legend className="mb-4">{c.labels[2]}</legend><div className="grid gap-4 md:grid-cols-2">{checkIds.map(i=><label className="flex items-start gap-3 rounded-xl border bg-white p-5" key={i}><input className="mt-1 h-5 w-5 shrink-0" type="checkbox" checked={selected.includes(i)} onChange={e=>{setSelected(a=>e.target.checked?[...a,i].sort((a,b)=>a-b):a.filter(v=>v!==i));setReady(false);}}/><span className="leading-7">{c.checks[i]}</span></label>)}</div></fieldset><label className="block">{u.notes}<textarea className="mt-2 block w-full rounded-lg border p-3" maxLength={1500} rows={3} value={notes} onChange={e=>{setNotes(e.target.value);setReady(false);}}/></label><button className="rounded-xl bg-purple-800 px-5 py-3 font-bold text-white" disabled={!selected.length&&!notes.trim()}>{u.prepare}</button></form>{ready&&<div role="status" className="mt-6 rounded-xl bg-purple-50 p-6"><h3 className="text-xl font-bold">{c.labels[1]} · {new Intl.NumberFormat(locale).format(selected.length)}</h3><ul className="my-5 list-inside list-disc space-y-3">{selected.map(i=><li key={i}>{c.checks[i]}</li>)}</ul>{notes&&<p className="mb-5 whitespace-pre-wrap">{notes}</p>}<p className="mb-4">{u.ready}</p><a className="inline-block rounded-xl bg-purple-800 px-5 py-3 font-bold text-white" href={filmGuideInquiry(locale,selected,notes,kind)}>{u.continue}</a></div>}</section>
 <a className="inline-block text-purple-800 underline" href={`${prefix}/screen-protectors/wholesale-for-stores/`}>{u.quote}</a></div></main>;
}
