import React from 'react';
import {filmGuideCopy,type FilmGuideLocale,type FilmGuideKind} from './copy';
const clips=['001-place-9s','titan-install-12s','001-view-6s','factory-fixture-15s','factory-rack-12s','factory-transfer-12s'];
const posters=['001-place-poster','titan-install-poster','001-view-poster','factory-fixture-poster','factory-rack-poster','factory-transfer-poster'];
export default function FilmGuideDetails({locale,kind}:{locale:FilmGuideLocale;kind:FilmGuideKind}){
 const d=filmGuideCopy[locale].details,prices=kind==='price-differences';
 const sections=prices?d.factors:d.processes;
 return <><section className="grid gap-6 md:grid-cols-2">{!prices&&d.shapes.map(([title,body],i)=><article className="rounded-xl border bg-white p-6" key={title}><svg viewBox="0 0 360 160" role="img" aria-label={title} className="w-full"><path d={i===0?'M40 93 Q40 70 63 70 H297 Q320 70 320 93 V100 H40Z':'M40 112 Q43 67 91 67 H269 Q317 67 320 112 L302 118 Q300 85 265 85 H95 Q60 85 58 118Z'} fill="#e4d8f7" stroke="#7e22ce" strokeWidth="3"/></svg><h2 className="text-xl font-bold">{title}</h2><p className="mt-4 leading-7">{body}</p></article>)}{!prices&&<p className="md:col-span-2">{d.notes[2]}</p>}{sections.map(([title,body])=><article className="rounded-xl border bg-white p-6" key={title}><h2 className="text-xl font-bold">{title}</h2><p className="mt-4 leading-7">{body}</p></article>)}</section>
 {prices&&<section className="grid gap-6 md:grid-cols-2">{['001-kit-photo.jpg','titan-kit.jpg'].map((asset,i)=><figure className="rounded-xl bg-white p-5" key={asset}><img src={`/screen-protector-media/assets/${asset}`} alt={d.notes[5+i]} width="1200" height="800" loading="lazy" className="aspect-video w-full object-contain"/><figcaption className="mt-4 leading-7">{d.notes[5+i]}</figcaption></figure>)}</section>}
 <section><h2 className="text-2xl font-bold">{d.heads[5]}</h2><p className="my-5 leading-7">{d.notes[prices?0:3]}</p><div className="grid gap-6 md:grid-cols-3">{(prices?[0,1,2]:[3,4,5]).map(i=><figure className="rounded-xl border bg-white p-4" key={clips[i]}><video controls playsInline preload="none" aria-label={d.videos[i][0]} poster={`/screen-protector-media/media/${posters[i]}.jpg`} className="aspect-video w-full bg-slate-900"><source src={`/screen-protector-media/media/${clips[i]}.mp4`} type="video/mp4"/></video><figcaption className="mt-4"><h3 className="font-bold">{d.videos[i][0]}</h3><p className="mt-3 leading-7">{d.videos[i][1]}</p></figcaption></figure>)}</div><p className="mt-6 leading-7">{d.notes[prices?1:4]}</p></section></>;
}
