import { powerProducts } from './power-products.mjs';
import { alibabaUpdates } from './alibaba-records.mjs';
import { chainProduct } from './chain.mjs';
const tri=(en,es,ar)=>({en,es,ar});
const M='/images/product-showcase/mobile/';
const Q='/mobile-sourcing-media/';
export const observedDate='2026-09-13';
export const mobileProducts=[
 ...powerProducts,
 chainProduct,
 {id:'color-ring',code:'C01',group:'cases',type:'sample',image:Q+'case-colorways-ddnz-v1.webp',original:M+'family-phone-cases-v1.webp',
  name:tri('Colour frame · ring stand','Marco de color · soporte de anillo','إطار ملون وحامل حلقي'),
  detail:tri('Six two-tone samples with a hinged rear ring. Select frame, back and ring colours separately.','Seis muestras bicolor con anillo trasero abatible. Elija por separado marco, trasera y anillo.','ست عينات بلونين مع حلقة خلفية مفصلية. حدد لون الإطار والظهر والحلقة كلًا على حدة.'),
  check:tri('Approve hinge resistance, ring alignment and camera clearance on the exact device. Magnetic holding force is a separate test.','Apruebe resistencia de la bisagra, alineación y espacio de cámara en el dispositivo exacto. La fuerza magnética requiere otra prueba.','اعتمد مقاومة المفصلة ومحاذاة الحلقة وفتحات الكاميرا على الجهاز المحدد. قوة التثبيت المغناطيسي تحتاج اختبارًا منفصلًا.')},
 {id:'textured',code:'C02',group:'cases',type:'sample',image:Q+'textured-clean-v2.webp',
  name:tri('Textured back · covered buttons','Trasera texturizada · botones cubiertos','ظهر بملمس نسيجي وأزرار مغطاة'),
  detail:tri('Close-up sample of a woven-look surface and contrasting button inserts. Choose a finish after handling the sample.','Muestra de una superficie de aspecto tejido y botones en contraste. Elija el acabado tras revisar la muestra.','عينة مقربة لسطح بمظهر منسوج وأزرار بلون متباين. اختر التشطيب بعد فحص العينة.'),
  check:tri('Confirm actual surface composition, edge bonding, stain resistance and colour transfer; appearance alone does not identify the material.','Confirme composición, unión de bordes, manchas y transferencia de color; la apariencia no identifica el material.','أكد تركيب السطح والتصاق الحواف ومقاومة البقع وانتقال اللون؛ المظهر وحده لا يحدد المادة.')},
 {id:'perforated',code:'C03',group:'cases',type:'sample',image:M+'c1s-perforated-case-transparent-v1.webp',
  name:tri('Perforated back','Trasera perforada','ظهر مثقّب'),
  detail:tri('Open-pattern sample for buyers comparing grip, weight and appearance.','Muestra de trama abierta para comparar agarre, peso y aspecto.','عينة بنمط مفتوح لمقارنة القبضة والوزن والمظهر.'),
  check:tri('Check edge finish, rigidity and dust access. Do not infer cooling performance from the holes.','Revise bordes, rigidez y entrada de polvo. Los orificios no demuestran refrigeración.','افحص الحواف والصلابة ودخول الغبار. الثقوب لا تثبت أداء التبريد.')},
 {id:'fold-folio',code:'C04',group:'cases',type:'sample',image:M+'f2-leather-fold-transparent-v1.webp',
  name:tri('Foldable folio · fit sample','Funda plegable · muestra de ajuste','غطاء قابل للطي · عينة للمطابقة'),
  detail:tri('Book-style sample shown open and closed. Device compatibility is confirmed only after a physical fit check.','Muestra tipo libro abierta y cerrada. La compatibilidad se confirma mediante una prueba física.','عينة بتصميم كتاب في الوضعين المفتوح والمغلق. يعتمد توافق الجهاز بعد فحص فعلي.'),
  check:tri('Approve hinge travel, screen clearance and retention through repeated opening. Request the official device name and model number.','Apruebe recorrido de bisagra, espacio de pantalla y sujeción al abrir. Indique nombre oficial y número de modelo.','اعتمد حركة المفصلة وخلوص الشاشة وثبات الغطاء مع الفتح المتكرر. حدد الاسم الرسمي للجهاز ورقم طرازه.')},
 {id:'folio-bida',code:'C05',group:'cases',type:'listing',image:Q+'folio-bida.webp',seller:'Guangzhou Bida Trading Co., Ltd.',url:'https://www.alibaba.com/product-detail/High-Quality-Business-Retro-Skin-Feel_1601492636282.html',tiers:[[5,19.03],[100,18.33],[500,17.68],[1000,16.98]],
  name:tri('PU + TPU flip wallet','Funda cartera abatible de PU + TPU','غطاء محفظة من PU وTPU'),
  detail:tri('Supplier-listed PU outer and TPU holder, card slot and flip cover. Black, red, pink, brown and blue options.','Exterior de PU y soporte de TPU declarados, ranura para tarjeta y tapa. Opciones negro, rojo, rosa, marrón y azul.','وفق المورد: سطح PU وحامل TPU وجيب بطاقة وغطاء أمامي. خيارات الأسود والأحمر والوردي والبني والأزرق.'),
  pack:tri('OPP bag option · graphic / retail-pack customization from 500 pieces.','Opción bolsa OPP · personalización gráfica / embalaje desde 500 unidades.','خيار كيس OPP · تخصيص الرسوم أو التغليف من ٥٠٠ قطعة.'),
  check:tri('Select the exact phone variant; approve closure, card retention and edge finishing. PU is not genuine leather.','Elija la variante exacta; revise cierre, sujeción de tarjeta y bordes. PU no es cuero natural.','حدد طراز الهاتف بدقة وافحص الإغلاق وثبات البطاقة والحواف. PU ليس جلدًا طبيعيًا.')},
 {id:'silicone-jmetec',code:'C06',group:'cases',type:'listing',image:Q+'silicone-ddnz-v1.webp',original:Q+'silicone-jmetec.webp',seller:'Shenzhen Jimijie Technology Co., Ltd.',url:'https://www.alibaba.com/product-detail/Jmetec-Macaron-Inner-Microfiber-Skin-feeling_1601457880520.html',tiers:[[100,11.63],[500,10.89],[3000,10.06],[8000,9.32]],
  name:tri('Silicone finish · inner lining','Acabado de silicona · forro interior','تشطيب سيليكون وبطانة داخلية'),
  detail:tri('JM-MF-1: silicone exterior and microfiber lining described by the seller. Nine numbered colour options.','JM-MF-1: exterior de silicona y forro de microfibra descritos por el vendedor. Nueve colores numerados.','JM-MF-1: يصف المورد سطحًا من السيليكون وبطانة ألياف دقيقة. تسعة خيارات ألوان مرقمة.'),
  pack:tri('Sold as one case. Confirm packaging, magnetic configuration and custom MOQ in the quote.','Venta por funda. Confirme embalaje, configuración magnética y mínimo personalizado en la cotización.','البيع بالقطعة. أكد التغليف والتكوين المغناطيسي وحد التخصيص في العرض.'),
  check:tri('Compare lining coverage, lint pickup, button feel and camera lip on a sample. No drop rating or magnetic force is included in this reference.','Compare cobertura del forro, pelusa, botones y borde de cámara en muestra. La referencia no incluye resistencia a caídas ni fuerza magnética verificadas.','قارن تغطية البطانة والتقاط الوبر والأزرار وحافة الكاميرا بعينة. المرجع لا يتضمن تصنيف سقوط أو قوة مغناطيسية مختبرة.')},
 {id:'rope-bintu',code:'S01',group:'straps',type:'listing',assembly:'set',image:Q+'rope-bintu.webp',seller:'Haikou Bintu Products Co., Ltd.',url:'https://www.alibaba.com/product-detail/Factory-Wholesale-8mm-Polyester-Mobile-Phone_1601263295545.html',tiers:[[50,9.93],[500,9.71],[2000,9.41]],
  name:tri('8 mm cord · 120 cm set','Cordón de 8 mm · conjunto de 120 cm','طقم حبل ٨ مم بطول ١٢٠ سم'),
  detail:tri('Polyester cord with phone-holder patch in the listing title; hook, phone clip and O-ring listed. 18 numbered colour options.','Cordón de poliéster con parche en el título; gancho, clip y anilla declarados. 18 colores numerados.','حبل بوليستر مع رقعة تثبيت في عنوان المنتج؛ خطاف ومشبك وحلقة ضمن الوصف. ١٨ خيار لون مرقم.'),
  pack:tri('50-piece listing minimum · package 12 × 10 × 3 cm / 70 g. Retail pack and custom minimum by quotation.','Mínimo publicado de 50 · paquete 12 × 10 × 3 cm / 70 g. Embalaje comercial y mínimo personalizado por cotizar.','الحد المنشور ٥٠ قطعة · العبوة ١٢ × ١٠ × ٣ سم / ٧٠ غ. التغليف التجاري وحد التخصيص حسب العرض.'),
  check:tri('Approve the complete parts list and finished length before pricing as a set. Test patch seating and charging-port clearance with the selected case.','Apruebe componentes y longitud final antes de cotizar el conjunto. Pruebe parche y espacio del conector con la funda elegida.','اعتمد قائمة الأجزاء والطول النهائي قبل تسعير الطقم. افحص تثبيت الرقعة وخلوص منفذ الشحن مع الغطاء المختار.')},
 {id:'wrist-zimi',code:'S02',group:'straps',type:'listing',assembly:'strap',image:Q+'wrist-zimi.webp',seller:'Hangzhou Zimi Gift Co., Ltd.',url:'https://www.alibaba.com/product-detail/Adjustable-Keychain-Lanyard-Portable-Polyester-Wrist_1600753024298.html',tiers:[[100,5.1],[500,4.92],[5000,4.66],[10000,3.75]],sample:33.97,
  name:tri('Woven wrist strap','Correa de muñeca tejida','سوار هاتف منسوج'),
  detail:tri('Short wrist-lanyard style in blue or black. Order the strap separately from the case and tether patch.','Correa corta de muñeca en azul o negro. Pida correa, funda y parche como componentes separados.','تصميم قصير للمعصم بالأزرق أو الأسود. اطلب السوار منفصلًا عن الغطاء ورقعة التثبيت.'),
  pack:tri('One OPP bag · standard minimum 100; logo from 50, custom pack from 1,000 pieces.','Una bolsa OPP · mínimo estándar 100; logotipo desde 50 y embalaje desde 1.000.','كيس OPP واحد · الحد القياسي ١٠٠؛ الشعار من ٥٠ والتغليف الخاص من ١٠٠٠ قطعة.'),
  check:tri('Ask for confirmed fibre composition, hook type and usable length: supplier fields differ. A short decorative loop is not a tested load-bearing strap.','Confirme fibra, gancho y longitud útil: los campos del proveedor difieren. Un lazo decorativo no equivale a una correa de carga ensayada.','أكد نوع الألياف والخطاف والطول القابل للاستخدام؛ تختلف حقول المورد. الحلقة الزخرفية ليست حزام حمل مختبرًا.')},
 {id:'beads-zimi',code:'S03',group:'straps',type:'listing',assembly:'charm',image:Q+'beads-zimi.webp',seller:'Hangzhou Zimi Gift Co., Ltd.',url:'https://www.alibaba.com/product-detail/Top-Sell-Color-Different-Material-Acrylic_1600838166685.html',tiers:[[50,10.19],[300,8.19],[1000,7.84],[2000,5.44]],sample:33.97,
  name:tri('Colour bead charm','Adorno de cuentas de colores','زينة خرز ملون'),
  detail:tri('Decorative beaded loop with five design types described. Pick the exact bead sequence and attachment as one reference sample.','Lazo decorativo de cuentas con cinco diseños descritos. Elija secuencia y enganche mediante una muestra de referencia.','حلقة خرز للزينة مع خمسة تصاميم موصوفة. حدد تسلسل الخرز ووصلة التثبيت بعينة مرجعية واحدة.'),
  pack:tri('OPP bag · shown tier begins at 50; detail mentions 10. Logo / graphics from 100; custom pack from 5,000.','Bolsa OPP · precio desde 50; detalle menciona 10. Logotipo / gráficos desde 100; embalaje desde 5.000.','كيس OPP · يبدأ السعر عند ٥٠ بينما يذكر الوصف ١٠. الشعار والرسوم من ١٠٠؛ التغليف الخاص من ٥٠٠٠.'),
  check:tri('Confirm bead material: the title says acrylic while attributes say stone. Approve thread, knots and small-part retention; decoration has no load rating.','Confirme material: el título dice acrílico y los atributos piedra. Revise hilo, nudos y piezas pequeñas; no se declara capacidad de carga.','أكد مادة الخرز؛ العنوان يذكر الأكريليك والخصائص تذكر الحجر. افحص الخيط والعقد وثبات القطع الصغيرة؛ لا توجد حمولة معتمدة.')},
 {id:'patch-trendcomm',code:'S04',group:'straps',type:'listing',assembly:'component',image:Q+'patch-clean-v2.webp',seller:'Guangzhou Trend Comm Electronic Company Limited',url:'https://www.alibaba.com/product-detail/Universal-Crossbody-Phone-Strap-Custom-TPU_1600976545458.html',tiers:[[20,5.79],[1000,5.31],[10000,3.57]],sample:33.97,
  name:tri('TPU tether patch · component','Parche de sujeción TPU · componente','رقعة تثبيت TPU · مكوّن منفصل'),
  detail:tri('60 × 40 mm patch described by the supplier. This price is for the tether component; add the cord, clips and case separately.','Parche de 60 × 40 mm según proveedor. Precio del componente; cordón, clips y funda se cotizan aparte.','رقعة ٦٠ × ٤٠ مم وفق المورد. السعر للمكوّن فقط؛ أضف الحبل والمشابك والغطاء بشكل منفصل.'),
  pack:tri('OPP bag · price tiers from 20, supplier MOQ 100 per colour. Logo / packaging from 500 pieces, extra charge.','Bolsa OPP · precio desde 20, mínimo del proveedor 100 por color. Logo / embalaje desde 500, con recargo.','كيس OPP · شرائح السعر من ٢٠ وحد المورد ١٠٠ لكل لون. الشعار والتغليف من ٥٠٠ مع تكلفة إضافية.'),
  check:tri('Confirm the per-colour minimum. Check patch width, closed case bottom, connector access and pull testing on the assembled set.','Confirme mínimo por color. Revise ancho, base cerrada de funda, acceso al conector y tracción del conjunto.','أكد الحد لكل لون. افحص عرض الرقعة وقاعدة الغطاء المغلقة ومنفذ الشحن واختبار الشد للطقم المركّب.')},
];
for(const [id,update] of Object.entries(alibabaUpdates)){const existing=mobileProducts.find(p=>p.id===id);if(existing)Object.assign(existing,update);else mobileProducts.push(update);}
export const productById=id=>mobileProducts.find(p=>p.id===id);
export const copyFor=(map,locale='en')=>map?.[locale]??map?.en??'';
export function referencePrice(product,qty){
 if(!Number.isInteger(qty)||qty<1||qty>1000000||!product?.tiers)return null;
 return [...product.tiers].reverse().find(([min])=>qty>=min)?.[1]??null;
}
export function formatNumber(value,locale='en',digits=0){return new Intl.NumberFormat(locale==='es'?'es-MX':locale==='ar'?'ar-AE':'en-US',{maximumFractionDigits:digits,minimumFractionDigits:digits}).format(value);}
export function formatMoney(value,locale='en',currency='CNY'){return new Intl.NumberFormat(locale==='es'?'es-MX':locale==='ar'?'ar-AE':'en-US',{style:'currency',currency,currencyDisplay:'code',minimumFractionDigits:2,maximumFractionDigits:2}).format(value);}
