const t=(en,es,ar)=>({en,es,ar});
export const inspectionCopy={
 inspectionOnly:t('Inspection request selected. Add the supplier or product details below; a catalogue selection is optional.','Inspección seleccionada. Añada los datos del proveedor o producto abajo; elegir del catálogo es opcional.','تم اختيار طلب الفحص. أضف بيانات المورد أو المنتج أدناه؛ اختيار منتج من المجموعة اختياري.'),
 title:t('Look beyond the unit price. Meet the operation behind it.','Mire más allá del precio. Conozca quién lo fabrica.','تجاوز سعر الوحدة. تعرّف على الجهة التي تصنعها.'),
 intro:t('Suppliers can differ in experience, funding, design, materials, capacity and service. Choose the strengths your order needs, then verify them with records, a site visit and product checks.','Los proveedores difieren en experiencia, financiación, diseño, materiales, capacidad y servicio. Elija lo que necesita su pedido y verifíquelo con documentos, visita e inspecciones.','يختلف الموردون في الخبرة والتمويل والتصميم والمواد والطاقة والخدمة. حدد ما يحتاجه طلبك ثم تحقّق بالوثائق والزيارة وفحص المنتجات.'),
 compare:t('What changes the buying decision','Qué cambia la decisión de compra','ما الذي يؤثر في قرار الشراء'),verify:t('What we can help verify','Qué podemos ayudar a verificar','ما يمكننا المساعدة في التحقق منه'),
 dimensions:t('Supplier comparison criteria','Criterios para comparar proveedores','معايير مقارنة الموردين'),
 actual:t('Starting points for your shortlist','Opciones para su selección inicial','خيارات لبدء قائمة الموردين'),
 listingNote:t('These are listing-level comparisons. The factory, inspection scope and order terms are confirmed for your project.','Comparación basada en fichas. Se confirman fábrica, alcance de inspección y condiciones para su proyecto.','هذه مقارنة لبيانات الصفحات. نؤكد المصنع ونطاق الفحص وشروط الطلب لمشروعك.'),
 request:t('Discuss factory & product checks','Consultar verificación e inspecciones','ناقش التحقق من المصنع وفحص المنتج'),
 processPhoto:t('Phone-case production example','Ejemplo de producción de fundas','مثال لإنتاج أغطية الهواتف'),
 workflow:t('Four checkpoints. One reference for your next order.','Cuatro controles. Una referencia para volver a pedir.','أربع نقاط فحص. مرجع واحد لطلبك التالي.'),
 workflowIntro:t('Start with an approved sample, follow the agreed process, inspect the shipment and keep the reference for reorders. Explore each stage to see what to check.','Apruebe la muestra, siga el proceso acordado, inspeccione el envío y conserve la referencia para reposición. Explore qué revisar en cada etapa.','اعتمد العينة، وتابع العملية المتفق عليها، وافحص الشحنة، واحتفظ بالمرجع لإعادة الطلب. استكشف ما يُفحص في كل مرحلة.'),
 examples:t('Images and production footage illustrate the checkpoints. Your inspection plan uses the selected SKU, its approved sample and its own batch records.','Las imágenes y el vídeo ilustran los controles. El plan usa su SKU, muestra aprobada y registros del lote.','توضح الصور ولقطة الإنتاج نقاط الفحص. تعتمد خطة طلبك على الصنف المختار وعينته المعتمدة وسجلات دفعته.'),
 deliverable:t('Keep for the order file','Conservar en el expediente','احتفظ به في ملف الطلب'),
 checksLabel:t('Checks you want to discuss','Controles que desea consultar','الفحوصات التي تريد مناقشتها'),
 inspectionHint:t('For an inspection request, include the supplier or product link and the checks needed.','Para una inspección, incluya enlace del proveedor o producto y controles necesarios.','لطلب الفحص، أدرج رابط المورد أو المنتج والفحوصات المطلوبة.'),
};
export const supplierDimensions=[
 {id:'history',name:t('Operating history','Trayectoria','تاريخ النشاط'),compare:t('Years in business, ownership continuity and experience with similar orders. Platform membership and company establishment are separate dates.','Años de actividad, continuidad y pedidos similares. Antigüedad en la plataforma y fecha de constitución son datos distintos.','سنوات النشاط واستمرارية الإدارة وخبرة الطلبات المماثلة. تاريخ عضوية المنصة يختلف عن تاريخ تأسيس الشركة.'),verify:t('Match the business licence, operating address, manufacturing entity and recent customer references.','Contrastar licencia, dirección, entidad fabricante y referencias recientes.','طابق الترخيص والعنوان والجهة المصنّعة ومراجع العملاء الحديثة.')},
 {id:'funding',name:t('Financial capacity','Capacidad financiera','القدرة المالية'),compare:t('Ability to fund raw materials, hold stock and handle a larger batch through a busy season.','Capacidad para financiar materias primas, mantener stock y atender lotes mayores en temporada alta.','القدرة على تمويل المواد والاحتفاظ بالمخزون وتنفيذ دفعة أكبر في موسم الذروة.'),verify:t('Review available financial records and trade references; agree the material-purchase plan and payment milestones.','Revisar documentación financiera y referencias comerciales; acordar compras de material e hitos de pago.','راجع الوثائق المالية والمراجع التجارية المتاحة، واتفق على شراء المواد ومراحل الدفع.')},
 {id:'design',name:t('Design & development','Diseño y desarrollo','التصميم والتطوير'),compare:t('Stock catalogue, artwork adaptation or original mould development each need a different design team and budget.','Catálogo, adaptación gráfica y molde original requieren equipos y presupuestos distintos.','تحتاج التصاميم الجاهزة وتعديل الرسوم وتطوير القوالب الأصلية فرقًا وميزانيات مختلفة.'),verify:t('Review drawings, prototype changes, tooling ownership and the team responsible for sample revisions.','Revisar planos, cambios de prototipo, propiedad del molde y responsables de revisar muestras.','راجع الرسومات وتعديلات النموذج وملكية القالب والفريق المسؤول عن تعديل العينات.')},
 {id:'materials',name:t('Materials & quality','Materiales y calidad','المواد والجودة'),compare:t('Layer structure, lining, coating and consistent incoming materials determine what can be repeated in the next batch.','Capas, forro, recubrimiento y consistencia de materias primas influyen en la repetición del lote.','يحدد تركيب الطبقات والبطانة والطلاء وثبات المواد ما يمكن تكراره في الدفعة التالية.'),verify:t('Approve the material specification and reference sample; agree fit, finish, wear and functional checks with acceptance criteria.','Aprobar especificación y muestra; acordar ajuste, acabado, desgaste y función con criterios de aceptación.','اعتمد مواصفات المواد والعينة، واتفق على فحوص المطابقة والتشطيب والتآكل والوظيفة ومعايير القبول.')},
 {id:'scale',name:t('Factory & capacity','Fábrica y capacidad','المصنع والطاقة'),compare:t('Equipment, production lines, subcontracting and current order load affect the promised lead time.','Equipos, líneas, subcontratación y carga actual afectan al plazo prometido.','تؤثر المعدات والخطوط والتعاقد الفرعي وحجم الطلبات الحالية في مهلة التسليم.'),verify:t('Check the actual production site, machinery, bottlenecks and capacity reserved for your order.','Verificar planta real, maquinaria, cuellos de botella y capacidad reservada para el pedido.','افحص موقع الإنتاج الفعلي والآلات ومواطن التعطل والطاقة المخصصة لطلبك.')},
 {id:'team',name:t('Team & execution','Equipo y ejecución','الفريق والتنفيذ'),compare:t('Engineering, purchasing, production and QC must work from the same approved specification.','Ingeniería, compras, producción y calidad deben trabajar con la misma especificación aprobada.','يجب أن تعمل فرق الهندسة والمشتريات والإنتاج والجودة وفق المواصفات المعتمدة نفسها.'),verify:t('Identify responsible people, escalation contacts, sample sign-off and inspection record ownership.','Identificar responsables, contactos de escalado, aprobación de muestra y registros de inspección.','حدد المسؤولين وجهات التصعيد واعتماد العينات ومسؤولية سجلات الفحص.')},
 {id:'service',name:t('Service & follow-through','Servicio y seguimiento','الخدمة والمتابعة'),compare:t('Useful answers, early issue reporting and agreed corrective action matter throughout production and after delivery.','Respuestas útiles, avisos tempranos y medidas correctivas acordadas importan durante y después de producir.','تهم الإجابات المفيدة والإبلاغ المبكر والإجراءات التصحيحية أثناء الإنتاج وبعد التسليم.'),verify:t('Compare response quality with sample enquiries; agree update frequency, defect handling and reorder control.','Comparar respuestas a consultas de muestra; acordar actualizaciones, gestión de defectos y reposición.','قارن جودة الرد على استفسارات العينة، واتفق على التحديثات ومعالجة العيوب وضبط إعادة الطلب.')},
];
export const inspectionOptions=[
 {id:'factory',label:t('Factory verification','Verificación de fábrica','التحقق من المصنع')},
 {id:'sample',label:t('Sample approval','Aprobación de muestra','اعتماد العينة')},
 {id:'production',label:t('During-production checks','Control durante producción','الفحص أثناء الإنتاج')},
 {id:'shipment',label:t('Pre-shipment inspection','Inspección antes del envío','الفحص قبل الشحن')},
 {id:'reorder',label:t('Reorder consistency','Consistencia de reposición','ثبات إعادة الطلب')},
];
const M='/images/product-showcase/mobile/';
export const orderCheckSteps=[
 {id:'sample',title:t('Approve the sample','Aprobar la muestra','اعتمد العينة'),image:M+'phone-case-finish-samples-v1.webp',text:t('Confirm the exact device, material layers, colour and finish. Sign off the physical reference before the production specification is frozen.','Confirme dispositivo, capas, color y acabado. Apruebe la referencia física antes de cerrar la especificación.','أكد الجهاز وطبقات المواد واللون والتشطيب. اعتمد المرجع الفعلي قبل تثبيت مواصفات الإنتاج.'),record:t('Approved sample + material / colour specification','Muestra aprobada + especificación de material y color','عينة معتمدة ومواصفات المواد والألوان')},
 {id:'production',title:t('Check during production','Revisar durante producción','افحص أثناء الإنتاج'),image:M+'phone-case-machine-proof-v1.webp',video:M+'phone-case-factory.mp4',text:t('This clip shows a phone-case moulding operation. Review agreed material and process checkpoints, compare output with the sample and record corrective action.','El vídeo muestra el moldeo de una funda. Revise materiales y proceso acordados, compare con la muestra y registre correcciones.','تعرض اللقطة عملية قولبة غطاء هاتف. راجع نقاط المواد والعملية، وقارن الإنتاج بالعينة وسجّل التصحيح.'),record:t('Batch checkpoints + production issue log','Controles del lote + registro de incidencias','نقاط فحص الدفعة وسجل مشكلات الإنتاج')},
 {id:'shipment',title:t('Release the shipment','Autorizar el envío','اعتمد الشحنة'),image:M+'phone-case-packout-proof-v2.webp',text:t('Check quantities, model and colour mix, workmanship, labels and retail packaging against the order. Agree defect limits and the inspection sample size in advance.','Revise cantidades, modelos, colores, acabados, etiquetas y embalaje frente al pedido. Acuerde límites de defectos y tamaño de muestra.','راجع الكميات والطرازات والألوان والتشطيب والملصقات والتغليف مقابل الطلب. اتفق مسبقًا على حدود العيوب وحجم عينة الفحص.'),record:t('Inspection report + packing and SKU reconciliation','Informe de inspección + conciliación de embalaje y SKU','تقرير الفحص ومطابقة التغليف والأصناف')},
 {id:'reorder',title:t('Control the next order','Controlar la reposición','اضبط الطلب التالي'),image:M+'phone-case-colorway-proof-v1.webp',text:t('Keep the approved sample, colour codes and defect feedback. Confirm material, tooling or packing changes before the next batch starts.','Conserve muestra, códigos de color y fallos detectados. Confirme cambios de material, molde o embalaje antes del nuevo lote.','احتفظ بالعينة وأكواد الألوان وملاحظات العيوب. أكد تغييرات المواد أو القوالب أو التغليف قبل بدء الدفعة التالية.'),record:t('Reference sample + revision history + reorder brief','Muestra de referencia + cambios + solicitud de reposición','عينة مرجعية وسجل تعديلات وطلب إعادة الشراء')},
];
