export const shenzhenCopy = {
  "en": [
    "Shenzhen · Huaqiangbei sourcing",
    "From a style reference to your retail range.",
    "Sourcing mobile accessories in Shenzhen or comparing styles from Huaqiangbei? Start with the phones your customers use, the finishes they prefer and the quantities you need for each model.",
    "DDNZ brings your references into one sourcing brief: phone cases, tempered glass and privacy screen protectors, straps and charging accessories. We compare supplier quotations against the same model mix, materials and packaging, then coordinate samples and order follow-up.",
    "A market price is a starting point. For a factory quotation or custom packaging, specify quantities by model and colour, the pack you want and your delivery timing. Before shipment, agree which fit, appearance, quantity and packing checks you need.",
    "Phone case finish samples",
    "Retail packaging examples",
    "Explore phone cases",
    "Explore screen protectors",
    "Plan quality checks",
    "Build your sourcing request"
  ],
  "zh": [
    "深圳 · 华强北采购",
    "把款式参考，变成适合门店的产品组合。",
    "想在深圳采购手机配件，或比较华强北的不同款式？先从客户使用的手机型号、偏好的材质与外观，以及各型号的采购数量入手。",
    "DDNZ 将手机壳、钢化膜与防窥膜、挂绳及充电配件整理进同一份采购需求，按一致的型号组合、材质和包装要求比较供应商报价，再跟进样品与订单。",
    "市场价格只是起点。需要工厂报价或定制包装时，请列出各型号与颜色的数量、包装形式和交期；出货前，再约定适配、外观、数量与包装的检查项目。",
    "手机壳外观与表面效果样品",
    "零售包装示例",
    "查看手机壳",
    "查看屏幕保护膜",
    "安排质量检查",
    "整理采购需求"
  ],
  "es": [
    "Compras en Shenzhen · Huaqiangbei",
    "De una referencia de estilo a una selección para su tienda.",
    "¿Busca accesorios para móviles en Shenzhen o compara diseños de Huaqiangbei? Empiece por los modelos de teléfono de sus clientes, los acabados que prefieren y las cantidades por modelo.",
    "DDNZ reúne sus referencias en una solicitud de compra: fundas, protectores de vidrio templado y de privacidad, correas y accesorios de carga. Comparamos ofertas con los mismos modelos, materiales y embalajes, y coordinamos las muestras y el seguimiento del pedido.",
    "El precio de mercado es un punto de partida. Para una oferta de fábrica o un embalaje personalizado, indique cantidades por modelo y color, presentación y plazo. Antes del envío, acuerde las comprobaciones de ajuste, aspecto, cantidades y embalaje.",
    "Muestras de acabados de fundas",
    "Ejemplos de embalaje para venta minorista",
    "Ver fundas",
    "Ver protectores de pantalla",
    "Planificar controles de calidad",
    "Preparar su solicitud de compra"
  ],
  "fr": [
    "Approvisionnement à Shenzhen · Huaqiangbei",
    "D’un modèle repéré à une gamme pour votre boutique.",
    "Vous recherchez des accessoires pour téléphones à Shenzhen ou comparez des modèles de Huaqiangbei ? Partez des téléphones de vos clients, des finitions souhaitées et des quantités par modèle.",
    "DDNZ rassemble vos références dans une même demande : coques, protections en verre trempé et filtres de confidentialité, cordons et accessoires de charge. Nous comparons les devis sur les mêmes modèles, matériaux et emballages, puis coordonnons les échantillons et le suivi de commande.",
    "Un prix de marché est un point de départ. Pour un devis usine ou un emballage personnalisé, précisez les quantités par modèle et couleur, la présentation et les délais. Avant expédition, convenez des contrôles d’ajustement, d’aspect, de quantité et d’emballage.",
    "Échantillons de finitions de coques",
    "Exemples d’emballages pour la vente au détail",
    "Voir les coques",
    "Voir les protections d’écran",
    "Préparer les contrôles qualité",
    "Préparer votre demande"
  ],
  "pt": [
    "Compras em Shenzhen · Huaqiangbei",
    "De uma referência de estilo à seleção para sua loja.",
    "Quer comprar acessórios para celular em Shenzhen ou comparar modelos de Huaqiangbei? Comece pelos aparelhos dos seus clientes, os acabamentos preferidos e as quantidades de cada modelo.",
    "A DDNZ reúne suas referências em uma única solicitação: capas, películas de vidro temperado e de privacidade, alças e acessórios de carregamento. Comparamos cotações com os mesmos modelos, materiais e embalagens e acompanhamos as amostras e o pedido.",
    "O preço de mercado é um ponto de partida. Para uma cotação de fábrica ou embalagem personalizada, indique quantidades por modelo e cor, apresentação e prazo. Antes do embarque, combine as verificações de encaixe, aparência, quantidade e embalagem.",
    "Amostras de acabamentos de capas",
    "Exemplos de embalagens para varejo",
    "Ver capas",
    "Ver películas",
    "Planejar o controle de qualidade",
    "Preparar sua solicitação"
  ],
  "tr": [
    "Shenzhen · Huaqiangbei tedariki",
    "Beğendiğiniz tasarımdan mağazanızın ürün seçkisine.",
    "Shenzhen’den telefon aksesuarı mı tedarik ediyorsunuz, yoksa Huaqiangbei’deki tasarımları mı karşılaştırıyorsunuz? Müşterilerinizin telefon modelleri, tercih ettikleri yüzeyler ve model başına adetlerle başlayın.",
    "DDNZ; telefon kılıfları, temperli cam ve gizlilik ekran koruyucuları, askılar ve şarj aksesuarlarını tek bir tedarik talebinde toplar. Tedarikçi tekliflerini aynı model dağılımı, malzeme ve ambalaj koşullarına göre karşılaştırır, ardından numuneleri ve siparişi takip ederiz.",
    "Piyasa fiyatı bir başlangıç noktasıdır. Fabrika teklifi veya özel ambalaj için model ve renk başına adetleri, ambalajı ve teslim süresini belirtin. Sevkiyattan önce uyum, görünüm, adet ve ambalaj kontrollerini kararlaştırın.",
    "Telefon kılıfı yüzey örnekleri",
    "Perakende ambalaj örnekleri",
    "Telefon kılıflarını inceleyin",
    "Ekran koruyucuları inceleyin",
    "Kalite kontrolünü planlayın",
    "Tedarik talebinizi hazırlayın"
  ],
  "ru": [
    "Закупки в Шэньчжэне · Хуацянбэй",
    "От понравившегося образца к ассортименту магазина.",
    "Ищете аксессуары для телефонов в Шэньчжэне или сравниваете варианты из Хуацянбэй? Начните с моделей телефонов ваших покупателей, нужных материалов и отделки, а также количества для каждой модели.",
    "DDNZ объединяет чехлы, защитные и антишпионские стёкла, ремешки и зарядные аксессуары в одну заявку. Мы сравниваем предложения поставщиков при одинаковом наборе моделей, материалах и упаковке, затем координируем образцы и сопровождаем заказ.",
    "Рыночная цена — отправная точка. Для запроса цены у фабрики или индивидуальной упаковки укажите количество по моделям и цветам, упаковку и сроки. Перед отправкой согласуйте проверки совместимости, внешнего вида, количества и упаковки.",
    "Образцы отделки чехлов",
    "Примеры розничной упаковки",
    "Посмотреть чехлы",
    "Посмотреть защитные стёкла",
    "Запланировать проверку качества",
    "Подготовить заявку на закупку"
  ],
  "ar": [
    "التوريد من شنتشن · هوا تشيانغ بي",
    "من تصميم يعجبك إلى تشكيلة تناسب متجرك.",
    "هل تبحث عن إكسسوارات الهواتف في شنتشن أو تقارن تصاميم من هوا تشيانغ بي؟ ابدأ بطرازات هواتف عملائك، والتشطيبات التي يفضلونها، والكميات المطلوبة لكل طراز.",
    "تجمع DDNZ مراجعك في طلب توريد واحد: أغطية الهواتف، وواقيات الزجاج المقسّى والخصوصية، والأحزمة وإكسسوارات الشحن. نقارن عروض الموردين وفق الطرازات والخامات والتغليف نفسها، ثم ننسّق العينات ونتابع الطلب.",
    "سعر السوق نقطة بداية. لطلب عرض سعر من مصنع أو تغليف مخصص، حدّد الكميات حسب الطراز واللون، ونوع التغليف وموعد التسليم. وقبل الشحن، اتفق على فحوص الملاءمة والمظهر والكميات والتغليف المطلوبة.",
    "عينات تشطيبات أغطية الهواتف",
    "أمثلة على عبوات البيع بالتجزئة",
    "استعرض أغطية الهواتف",
    "استعرض واقيات الشاشة",
    "خطّط لفحص الجودة",
    "جهّز طلب التوريد"
  ]
};
