// Shared English purchase navigation for static HTML and interactive pages.
const esc = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const link = (href, label) => `<a href="${esc(href)}">${esc(label)} <span aria-hidden="true">→</span></a>`;
export const cards = rows => `<div class="buyer-entry-grid">${rows.map(([title, text, href, label, extraLinks = []]) => `<article><h3>${esc(title)}</h3><p>${esc(text)}</p>${link(href,label)}${extraLinks.map(([url,text])=>link(url,text)).join('')}</article>`).join('')}</div>`;
const style = `<style>.buyer-entry{margin:2rem auto;padding:clamp(20px,3vw,36px);max-width:1200px;border:1px solid #dce2e5;border-radius:16px;background:#f7f9fa;color:#243448;text-align:left}.buyer-entry h2{font-size:clamp(24px,3vw,34px);line-height:1.2;margin:0 0 16px;letter-spacing:-.02em}.buyer-entry h3{font-size:18px;line-height:1.4;margin:0 0 8px}.buyer-entry p{font-size:16px;line-height:1.65;margin:0 0 16px;max-width:80ch}.buyer-entry-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,230px),1fr));gap:20px;margin:24px 0}.buyer-entry article{min-width:0;padding:16px;background:white;border:1px solid #e2e6e9;border-radius:10px}.buyer-entry a{color:#174968;text-decoration:underline;text-underline-offset:4px;font-size:16px;font-weight:600;overflow-wrap:anywhere;display:inline-block;padding:6px 0}.buyer-entry a:focus-visible{outline:3px solid #18577a;outline-offset:4px}.buyer-entry-links{display:flex;flex-wrap:wrap;gap:8px 24px}</style>`;
export const wrap = (id,title,body) => `${style}<section class="buyer-entry" id="${id}" aria-labelledby="${id}-heading"><h2 id="${id}-heading">${title}</h2>${body}</section>`;
export function renderCaseEntry(){
  const context = esc(JSON.stringify({leadGoal:'Product Sourcing',source:'phone_cases',industry:'Mobile Accessories',productScope:'Phone cases'}));
  return wrap('case-materials','Find a material. Build your phone-model mix.',
  `<style>#case-materials .buyer-entry-grid{grid-template-columns:repeat(2,minmax(0,1fr))}#case-materials article a{display:block}#case-materials .case-request{display:flex;align-items:center;gap:24px;border-top:1px solid #dce2e5;margin-top:28px;padding-top:28px}#case-materials .case-request-copy{flex:1;min-width:0}#case-materials .case-request p{margin-bottom:0}#case-materials .case-request .case-request-button{flex-shrink:0;display:inline-flex;align-items:center;justify-content:center;gap:10px;min-height:48px;padding:12px 18px;border-radius:8px;background:#174968;color:white;text-decoration:none;line-height:1.4}#case-materials .case-request-button:hover{background:#123950}@media(min-width:1200px){#case-materials .buyer-entry-grid{grid-template-columns:repeat(4,minmax(0,1fr))}}@media(max-width:760px){#case-materials .case-request{align-items:flex-start;flex-direction:column;gap:16px}}@media(max-width:520px){#case-materials .buyer-entry-grid{grid-template-columns:1fr}#case-materials .case-request-button{width:100%}}</style>`+
  '<p>Source wholesale phone cases from China by material, finish and the models your customers use. Browse the existing styles below, then add your quantities to one sourcing request.</p>'+cards([
    ['Silicone cases','Soft-touch cases with an inner lining.','#style-silicone-jmetec','Browse silicone cases'],
    ['Clear TPU cases','A clear everyday style for a simple retail range.','#style-clear-trendcomm','Browse clear TPU cases'],
    ['PC cases','A mesh PC case for Samsung.','#style-mesh-longan','Browse PC cases'],
    ['PU / leather-style cases','Choose a flip wallet or a textured PU back.','#style-folio-bida','Browse flip-wallet cases', [['#style-fabric-feishile','Browse textured PU cases']]],
  ])+`<div class="case-request"><div class="case-request-copy"><h3>Need a different model or style?</h3><p>Looking for phone cases for iPhone, Samsung, Xiaomi / Redmi, OPPO or vivo? Share the models, preferred styles and quantities you need.</p></div><a class="case-request-button" href="/get-a-quote/" data-quote-context="${context}">Request matching cases <span aria-hidden="true">→</span></a></div>`);
}
export function renderFilmEntry(){return wrap('film-buying-options','Choose the screen protector your customers ask for.',
  '<p>Source screen protectors from China for shop replenishment or your own brand. Start with the viewing finish and phone model, then compare the current products below.</p>'+cards([
    ['HD / clear','For buyers who want a clear view of the screen. Compare clear versions alongside the installation kit.','/screen-protectors/wholesale-for-stores/','Plan a store assortment'],
    ['Privacy / anti-spy','For customers who prefer to limit side viewing. Consider how the privacy effect looks during everyday use.','/screen-protectors/videos/','Watch the product demonstrations'],
    ['9H tempered glass','Use this buying term when requesting a glass screen protector. Choose the finish, phone model and packing as part of the same request.','/screen-protectors/private-label/','Explore own-brand orders'],
    ['2.5D / 3D curved','Compare the edge shape and screen coverage for the exact phone, including use with a case.','/screen-protectors/guides/curved-glass/','Compare 2.5D and 3D'],
  ])+'<h3>Build the brand and model mix</h3><p>Include iPhone, Samsung, Xiaomi / Redmi, OPPO or vivo with the exact model name and quantity you need. Add HD, privacy, 9H tempered glass or curved-edge preferences to your request, together with the packing you want.</p><div class="buyer-entry-links">'+link('/screen-protectors/wholesale-for-stores/','Wholesale for phone stores')+link('/screen-protectors/private-label/','Private-label screen protectors')+link('/sourcing/mobile-accessories-from-china/#buying-brief','Build one combined sourcing request')+'</div>');}
export function renderVegetableEntry(){return wrap('vegetable-jobs','Peel, slice, shred or chop.',
  '<p>Choose a single vegetable preparation machine for one job, or bring three machines together for a small kitchen preparation area.</p>'+cards([
    ['Potato peeling','Start root-vegetable preparation with the TP-350 peeler.','#machine-tp-350','View TP-350'],
    ['Slicing and julienne / shredding','Use the DQ-PS300 cutting options for slices or strips. Include the ingredient and preferred cut size in your request.','#machine-dq-ps300-copper','View DQ-PS300'],
    ['Vegetable chopping','Choose the SC-R22 for the chopping stage.','#machine-sc-r22','View SC-R22'],
  ])+'<p>The three-machine package combines separate peeling, slicing / shredding and chopping machines. It is a preparation set, not an automatic production line.</p><div class="buyer-entry-links">'+link('/sourcing/food-processing-machinery-from-china/packages/vegetables/','Explore the three-machine package')+link('#your-list','Review selected machines and quantities')+'</div>');}
