// Shared English purchase navigation for static HTML and interactive pages.
const esc = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const link = (href, label) => `<a href="${esc(href)}">${esc(label)} <span aria-hidden="true">→</span></a>`;
export const cards = rows => `<div class="buyer-entry-grid">${rows.map(([title, text, href, label, extraLinks = []]) => `<article><h3>${esc(title)}</h3><p>${esc(text)}</p>${link(href,label)}${extraLinks.map(([url,text])=>link(url,text)).join('')}</article>`).join('')}</div>`;
const style = `<style>.buyer-entry{margin:2rem auto;padding:clamp(20px,3vw,36px);max-width:1200px;border:1px solid #dce2e5;border-radius:16px;background:#f7f9fa;color:#243448;text-align:left}.buyer-entry h2{font-size:clamp(24px,3vw,34px);line-height:1.2;margin:0 0 16px;letter-spacing:-.02em}.buyer-entry h3{font-size:18px;line-height:1.4;margin:0 0 8px}.buyer-entry p{font-size:16px;line-height:1.65;margin:0 0 16px;max-width:80ch}.buyer-entry-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,230px),1fr));gap:20px;margin:24px 0}.buyer-entry article{min-width:0;padding:16px;background:white;border:1px solid #e2e6e9;border-radius:10px}.buyer-entry a{color:#174968;text-decoration:underline;text-underline-offset:4px;font-size:16px;font-weight:600;overflow-wrap:anywhere;display:inline-block;padding:6px 0}.buyer-entry a:focus-visible{outline:3px solid #18577a;outline-offset:4px}.buyer-entry-links{display:flex;flex-wrap:wrap;gap:8px 24px}</style>`;
export const wrap = (id,title,body) => `${style}<section class="buyer-entry" id="${id}" aria-labelledby="${id}-heading"><h2 id="${id}-heading">${title}</h2>${body}</section>`;
export function renderCaseEntry(){
  const context = esc(JSON.stringify({leadGoal:'Product Sourcing',source:'phone_cases',industry:'Mobile Accessories',productScope:'Phone cases'}));
  return wrap('case-materials','Find a material. Build your phone-model mix.',
  `<style>#case-materials .buyer-entry-grid{grid-template-columns:repeat(2,minmax(0,1fr))}#case-materials article a{display:block}#case-materials .case-request{display:flex;align-items:center;gap:24px;border-top:1px solid #dce2e5;margin-top:28px;padding-top:28px}#case-materials .case-request-copy{flex:1;min-width:0}#case-materials .case-request p{margin-bottom:0}#case-materials .case-request .case-request-button{flex-shrink:0;display:inline-flex;align-items:center;justify-content:center;gap:10px;min-height:48px;padding:12px 18px;border-radius:8px;background:#174968;color:white;text-decoration:none;line-height:1.4}#case-materials .case-request-button:hover{background:#123950}@media(min-width:1200px){#case-materials .buyer-entry-grid{grid-template-columns:repeat(4,minmax(0,1fr))}}@media(max-width:760px){#case-materials .case-request{align-items:flex-start;flex-direction:column;gap:16px}}@media(max-width:520px){#case-materials .buyer-entry-grid{grid-template-columns:1fr}#case-materials .case-request-button{width:100%}}</style>`+
  '<p>Source wholesale phone cases from China by material, finish and the models your customers use. Browse the existing styles below, then add your quantities to one sourcing request.</p>'+cards([
    ['Silicone cases','Soft-touch cases with an inner lining.','#style-silicone-jmetec','Browse silicone cases'],
    ['Clear TPU cases','A clear everyday style for a simple retail range.','#style-clear-trendcomm','Browse clear TPU cases'],
    ['PC cases','A mesh PC case for Samsung.','#style-mesh-longan','Browse PC cases'],
    ['PU / leather-style cases','Choose a flip wallet or a textured PU back.','#style-folio-bida','Browse flip-wallet cases', [['#style-fabric-feishile','Browse textured PU cases']]],
  ])+`<div class="case-request"><div class="case-request-copy"><h3>Need a different model or style?</h3><p>Looking for phone cases for iPhone, Samsung, Xiaomi / Redmi, OPPO or vivo? Share the models, preferred styles and quantities you need.</p></div><a class="case-request-button" href="/get-a-quote/" data-quote-context="${context}">Request matching cases <span aria-hidden="true">→</span></a></div>`);
}

export const entryStyle = `<style>.buyer-entry .entry-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:20px;margin:24px 0}.buyer-entry .entry-grid article{min-width:0;display:flex;flex-direction:column;gap:8px}.buyer-entry .entry-grid article p{margin:0 0 8px}.buyer-entry .entry-media{width:100%;height:170px;object-fit:contain;background:#fff;border-radius:6px;margin-bottom:8px}.buyer-entry .entry-brief-preview{height:170px;display:flex;flex-direction:column;justify-content:center;gap:10px;padding:20px;background:#edf2f4;border-radius:6px;margin-bottom:8px;color:#334b60}.buyer-entry .entry-brief-preview strong{font-size:28px}.buyer-entry .entry-card-links{margin-top:auto;display:flex;flex-direction:column;align-items:flex-start}.buyer-entry .entry-request{display:flex;align-items:center;gap:24px;border-top:1px solid #dce2e5;margin-top:28px;padding-top:24px}.buyer-entry .entry-request>div{flex:1;min-width:0}.buyer-entry .entry-request p{margin-bottom:0}.buyer-entry .entry-request .entry-request-button{display:inline-flex;align-items:center;justify-content:center;min-height:48px;flex-shrink:0;padding:12px 18px;border-radius:8px;background:#174968;color:#fff;text-decoration:none}.buyer-entry .entry-reading{border-top:1px solid #dce2e5;padding-top:24px;margin-top:24px}.buyer-entry .entry-reading-links{display:flex;flex-wrap:wrap;gap:8px 24px}.rkp-planner-details{max-width:1200px;margin:32px auto;border:1px solid #dce2e5;border-radius:12px;padding:20px}.rkp-planner-details>summary{cursor:pointer;font-size:20px;font-weight:700;min-height:40px}.rkp-planner-details .rkp-scenarios{margin-top:24px}#refrigeration-categories .entry-grid{grid-template-columns:repeat(6,minmax(0,1fr))}#refrigeration-categories .entry-grid article{grid-column:span 2}#refrigeration-categories .entry-grid article:nth-last-child(-n+2){grid-column:span 3}[id^="film-product-"]{scroll-margin-top:110px}@media(max-width:900px){.buyer-entry .entry-grid,#refrigeration-categories .entry-grid{grid-template-columns:repeat(2,minmax(0,1fr))}#refrigeration-categories .entry-grid article,#refrigeration-categories .entry-grid article:nth-last-child(-n+2){grid-column:auto}#refrigeration-categories .entry-grid article:last-child{grid-column:1/-1}.buyer-entry .entry-request{flex-direction:column;align-items:flex-start;gap:16px}}@media(max-width:600px){.buyer-entry .entry-grid,#refrigeration-categories .entry-grid{grid-template-columns:1fr}.buyer-entry .entry-request-button{width:100%}.rkp-planner-details{margin:24px 16px}}</style>`;
export const entryCards = rows => `<div class="entry-grid">${rows.map(({title,text,image,alt,brief,briefLabel = 'Scenario brief',links})=>`<article>${image?`<img class="entry-media" src="${esc(image)}" alt="${esc(alt||title)}" width="480" height="340" loading="lazy">`:`<div class="entry-brief-preview"><strong>${esc(brief)}</strong><span>${esc(briefLabel)}</span></div>`}<h3>${esc(title)}</h3><p>${esc(text)}</p><div class="entry-card-links">${links.map(([href,label])=>link(href,label)).join('')}</div></article>`).join('')}</div>`;
export const requestEntry = (title,text,label,industry,scope,source,quotePath = '/get-a-quote/') => `<div class="entry-request"><div><h3>${esc(title)}</h3><p>${esc(text)}</p></div><a class="entry-request-button" href="${esc(quotePath)}" data-quote-context="${esc(JSON.stringify({leadGoal:'Product Sourcing',industry,productScope:scope,source}))}">${esc(label)} <span aria-hidden="true">→</span></a></div>`;
export function renderFilmEntry(){return wrap('film-buying-options','Find your viewing finish or installation kit.',entryStyle+
  '<p>Source screen protectors from China for store replenishment or your own brand. Explore the current clear and privacy products, including versions with an installation tool.</p>'+entryCards([
    {title:'HD / clear screen protectors',text:'Titan HD combines a clear protector with an enclosed installation tool.',image:'/screen-protector-media/assets/titan-hd.jpg',links:[['/screen-protectors/compare/#film-product-titan-hd','View Titan HD']]},
    {title:'Privacy / anti-spy screen protectors',text:'Compare OG28, individually packed 001 and Titan privacy with an installation tool.',image:'/screen-protector-media/assets/og28-privacy.jpg',links:[['/screen-protectors/compare/#film-product-og28','View OG28 privacy'],['/screen-protectors/compare/#film-product-001','View 001 privacy'],['/screen-protectors/compare/#film-product-titan-privacy','View Titan privacy']]},
    {title:'Screen protector installation kits',text:'The Titan range offers clear and privacy versions with an enclosed installation tool.',image:'/screen-protector-media/assets/titan-kit.jpg',links:[['/screen-protectors/compare/#film-product-titan-hd','View the clear kit'],['/screen-protectors/compare/#film-product-titan-privacy','View the privacy kit']]},
  ])+'<div class="entry-reading"><h3>Choosing glass and edge coverage</h3><p>Looking for 9H tempered glass or a 2.5D / 3D curved screen protector? Include the phone model, viewing finish and edge coverage you want. Clear or privacy describes the viewing finish; the edge shape is a separate choice.</p><div class="entry-reading-links">'+link('/screen-protectors/guides/curved-glass/','Read the 2.5D and 3D guide')+link('/screen-protectors/videos/','Watch product demonstrations')+'</div></div>'+requestEntry('Looking for other models or your own packaging?','For iPhone, Samsung, Xiaomi / Redmi, OPPO or vivo orders, share the phone models, protector styles and quantities, along with any logo or packaging requirements.','Request matching screen protectors','Mobile Accessories','Screen protectors','screen_protector_planner'));}
export function renderVegetableEntry(){return wrap('vegetable-jobs','Choose the machine for your preparation step.',entryStyle+
  '<p>Compare vegetable preparation machines from China for potato peeling, slicing, shredding and chopping. Choose a single machine or explore a small preparation set.</p>'+entryCards([
    {title:'Potato peelers',text:'TP-350 for the root-vegetable peeling stage.',image:'/food-processing-media/potato-peeler.webp',links:[['#machine-tp-350','View the TP-350 potato peeler']]},
    {title:'Vegetable slicers & shredders',text:'DQ-PS300 for slices or julienne strips, with cutting options for the result you need.',image:'/food-processing-media/vegetable-slicer.webp',links:[['#machine-dq-ps300-copper','View the DQ-PS300 slicer']]},
    {title:'Vegetable choppers',text:'SC-R22 for the chopping stage of ingredient preparation.',image:'/food-processing-media/chopper.webp',links:[['#machine-sc-r22','View the SC-R22 chopper']]},
  ])+'<div class="entry-reading"><h3>Putting a preparation area together?</h3><p>The three-machine set brings peeling, slicing / shredding and chopping into one equipment selection. Each machine works separately; choose the quantities for your kitchen.</p>'+link('/sourcing/food-processing-machinery-from-china/packages/vegetables/','Explore the three-machine preparation set')+'</div>'+requestEntry('Working with other ingredients or cuts?','Share the ingredients, preferred cut, required output and quantities. We can review a single-machine request or a preparation package.','Request preparation equipment','Commercial Kitchen Equipment','Vegetable preparation machinery','food_processing'));}
