import { kitchenModelHref } from '../commercial-kitchen/data/categories.mjs';
import { allScenarios, libraryOrder } from '../commercial-kitchen/data/restaurant-scenarios.mjs';
import { link, wrap, entryStyle, entryCards, requestEntry } from './content.mjs';
const modelEntry = id => kitchenModelHref(id).replace('#commercial-kitchen-trade-pricing', '#commercial-kitchen-equipment');
export function renderRefrigerationEntry(){return wrap('refrigeration-categories','Choose refrigeration by the job it does.',entryStyle+
  '<p>Source commercial refrigeration equipment from China for chilled storage, frozen stock, food preparation, display or ice service. Open a model to compare its buying price and add it to your equipment list.</p>'+entryCards([
    {title:'Commercial refrigerators',text:'Upright cabinets for chilled ingredients, with two model sizes to compare.',image:'/commercial-kitchen-media/cold-2.webp',alt:'GN650TNPro upright refrigerator',links:[[modelEntry('cold-2'),'View refrigerator GN650TNPro'],[modelEntry('cold-3'),'View larger refrigerator GN1410TNPro']]},
    {title:'Commercial freezers',text:'Upright cabinets for frozen stock, with two model sizes to compare.',image:'/commercial-kitchen-media/cold-4.webp',alt:'GN650BTPro upright freezer',links:[[modelEntry('cold-4'),'View freezer GN650BTPro'],[modelEntry('cold-5'),'View larger freezer GN1410BTPro']]},
    {title:'Refrigerated prep counters',text:'A work surface with chilled storage beneath.',image:'/commercial-kitchen-media/cold-7.webp',alt:'GNT2MTNPro refrigerated workbench',links:[[modelEntry('cold-7'),'View prep counter GNT2MTNPro']]},
    {title:'Display coolers',text:'Glass-door cooling for displaying chilled products.',image:'/commercial-kitchen-media/cold-42.webp',alt:'LC-615M1F glass-door display cooler',links:[[modelEntry('cold-42'),'View display cooler LC-615M1F']]},
    {title:'Commercial ice makers',text:'Compare the existing ice-machine range for drinks and service.',image:'/commercial-kitchen-media/ice-49-studio-v2.png',alt:'HZB-50/AB commercial ice maker',links:[['/sourcing/commercial-ice-machines-from-china/#model-ice-49','View HZB-50/AB and other ice makers']]},
  ])+requestEntry('Need other sizes or a mixed equipment order?','Tell us what you need to chill, freeze or display, along with the cabinet sizes, quantities and destination.','Request refrigeration equipment','Commercial Kitchen Equipment','Commercial refrigeration equipment','refrigeration_equipment_product'));}
export function renderKitchenEntry(){return wrap('kitchen-buying-paths','Start with your restaurant format.',entryStyle+
  '<p>Source a restaurant kitchen package from China around your menu, working space and service flow. Explore the existing concepts and briefs below.</p>'+entryCards(libraryOrder.map(slug=>{const s=allScenarios[slug];return {title:s.tab,text:s.title,image:s.isometric,alt:`${s.tab} kitchen planning concept`,brief:s.footprint,links:[[`/sourcing/restaurant-kitchen-packages-from-china/${slug}/`,s.isometric?'Explore the kitchen concept':'Read the kitchen brief']]};}))+
  '<div class="entry-reading"><h3>Buying individual equipment?</h3><p>Browse equipment for a replacement purchase or a wholesale range.</p><nav class="entry-reading-links" aria-label="Individual kitchen equipment">'+link('/sourcing/commercial-electric-fryers-from-china/','Electric fryers')+link('/sourcing/commercial-electric-griddles-from-china/','Electric griddles')+link('/refrigeration-equipment/','Refrigerators, freezers and ice makers')+link('/sourcing/food-processing-machinery-from-china/','Food preparation machinery')+'</nav></div>'+requestEntry('Planning a complete kitchen?','Share your restaurant format, menu, floor plan and destination so the equipment request can be considered as one project.','Request a kitchen package','Commercial Kitchen Equipment','Restaurant kitchen package','restaurant_kitchen_packages'));}
