const copy = {
"zh":["001／冲击测试", "观看落球测试。", "连续录像展示钢球准备、释放及测试后样品检查。", "001 落球冲击测试演示", "1 分 46 秒 · 完整录像", "请为您的订单确认钢球质量、落下高度、样品支撑及验收标准。本录像不代表经过认证的抗冲击等级。"],"ru":["001 / ИСПЫТАНИЕ НА УДАР", "Посмотрите испытание падающим шаром.", "Непрерывная запись показывает подготовку стального шара, его сброс и проверку образца.", "Демонстрация испытания 001 падающим шаром", "1 мин 46 с · Полная запись", "Согласуйте массу шара, высоту падения, опору образца и критерии приёмки. Эта запись не подтверждает сертифицированный класс ударостойкости."],"fr":["001 / ESSAI DE CHOC", "Regardez l’essai de chute de bille.", "L’enregistrement continu montre la préparation de la bille d’acier, sa chute et l’inspection finale de l’échantillon.", "Démonstration de chute de bille sur le modèle 001", "1 min 46 s · Enregistrement complet", "Confirmez la masse de la bille, la hauteur de chute, le support et les critères d’acceptation. Cet enregistrement ne prouve pas un niveau certifié de résistance aux chocs."],"pt":["001 / TESTE DE IMPACTO", "Veja o teste de queda da esfera.", "O vídeo contínuo mostra a preparação da esfera de aço, a queda e a inspeção final da amostra.", "Demonstração do teste de impacto com esfera no modelo 001", "1 min 46 s · Gravação completa", "Confirme massa da esfera, altura de queda, suporte da amostra e critérios de aceitação. Esta gravação não comprova uma classificação certificada de resistência ao impacto."],"tr":["001 / DARBE TESTİ", "Bilye düşürme testini izleyin.", "Kesintisiz kayıt; çelik bilyenin hazırlanmasını, bırakılmasını ve numunenin son kontrolünü gösterir.", "001 bilye düşürme darbe testi gösterimi", "1 dk 46 sn · Tam kayıt", "Siparişiniz için bilye kütlesini, düşme yüksekliğini, numune desteğini ve kabul kriterlerini doğrulayın. Bu kayıt sertifikalı bir darbe dayanım sınıfı kanıtlamaz."],
 en: ['001 / IMPACT TEST', 'See the drop-ball test.', 'Watch the steel-ball setup, release and final sample inspection in one continuous recording.', '001 drop-ball impact test demonstration', '1 min 46 sec · Full recording', 'Confirm ball mass, drop height, sample support and acceptance criteria for your order. This recording does not establish a certified impact rating.'],
 es: ['001 / PRUEBA DE IMPACTO', 'Observe la prueba de caída de bola.', 'Vea la preparación de la bola de acero, su liberación y la inspección final de la muestra en una grabación continua.', 'Demostración de impacto por caída de bola de 001', '1 min 46 s · Grabación completa', 'Confirme la masa de la bola, la altura, el soporte de la muestra y los criterios de aceptación. Esta grabación no acredita una clasificación de impacto certificada.'],
 ar: ['001 / اختبار الصدمات', 'شاهد اختبار سقوط الكرة.', 'شاهد تجهيز الكرة الفولاذية وإطلاقها وفحص العينة النهائي في تسجيل متواصل.', 'عرض اختبار سقوط الكرة على 001', 'دقيقة و46 ثانية · التسجيل الكامل', 'تأكد من كتلة الكرة وارتفاع السقوط ودعم العينة ومعايير القبول لطلبك. هذا التسجيل لا يثبت تصنيف مقاومة صدمات معتمدًا.']
};
export function renderImpact001(locale = 'en') {
 const [label,title,body,alt,duration,note]=copy[locale==='zh-cn'?'zh':locale] || copy.en;
 return `<section class="impact001"><div><p class="eyebrow">${label}</p><h2>${title}</h2><p>${body}</p><p class="small">${duration}</p><p class="small">${note}</p></div><figure><video controls playsinline preload="none" poster="/screen-protector-media/assets/001-impact-poster.webp" aria-label="${alt}" width="720" height="1280"><source src="/screen-protector-media/media/001-drop-ball-impact.mp4" type="video/mp4"><a href="/screen-protector-media/media/001-drop-ball-impact.mp4">${alt}</a></video></figure></section>`;
}
