import React,{useEffect,useState} from 'react';
import {EN} from './locales/en.mjs';
import {PRODUCTS,BASIS,preset,estimate,economics,makeBrief} from './model.mjs';
import {DRAFT_KEY,saveHandoff} from './handoff.mjs';
import {translatedText,translatedTree,localeCode,localePrefix} from '../site-localization/translate.mjs';
import {localizedProductPath,productAlternates} from '../../lib/productLocalization.mjs';
const initial={rows:[],packing:'product',charging:'shipment',route:'sea',price:'',monthly:'',feeRate:'',requests:[]};
export function calculatorMeta(locale){return {title:translatedText('Screen protector sourcing and landed cost from China',locale)+' | DDNZ',description:translatedText('Confirm your phone models, quantities and China sourcing plan. The calculator uses the Istanbul freight reference; other destinations require a separate quote.',locale),path:localizedProductPath('/screen-protectors/calculator',locale),alternateUrls:productAlternates('/screen-protectors/calculator')};}
export default function LocalizedCalculator({locale='pt'}){
 const l=localeCode(locale),copy=translatedTree(EN,l),c=copy.calc,q=copy.quote,T=s=>translatedText(s,l),f=(s,p={})=>s.replace(/\{(\w+)\}/g,(_,k)=>String(p[k]??`{${k}}`));
 const n=(v,d=0)=>new Intl.NumberFormat(l==='zh'?'zh-CN':l,{maximumFractionDigits:d}).format(v),money=v=>new Intl.NumberFormat(l==='zh'?'zh-CN':l,{style:'currency',currency:'CNY',currencyDisplay:'code'}).format(v);
 const [state,setState]=useState(initial),[loaded,setLoaded]=useState(false),[saved,setSaved]=useState(true);
 useEffect(()=>{try{const raw=JSON.parse(sessionStorage.getItem(DRAFT_KEY)||'null');if(raw&&Array.isArray(raw.rows)&&raw.rows.length<=100)setState({...initial,rows:raw.rows.map(r=>({product:Object.hasOwn(PRODUCTS,r.product)?r.product:'001',qty:typeof r.qty==='number'||typeof r.qty==='string'?r.qty:'',model:String(r.model||'').slice(0,80)})),packing:['product','model'].includes(raw.packing)?raw.packing:'product',charging:['shipment','carton'].includes(raw.charging)?raw.charging:'shipment',route:raw.route==='air'?'air':'sea',...Object.fromEntries(['price','monthly','feeRate'].map(k=>[k,['string','number'].includes(typeof raw[k])?raw[k]:'']))});}catch{setSaved(false)}setLoaded(true)},[]);
 useEffect(()=>{if(loaded)try{sessionStorage.setItem(DRAFT_KEY,JSON.stringify(state));setSaved(true)}catch{setSaved(false)}},[state,loaded]);
 const set=(key,value)=>setState(s=>({...s,[key]:value})),row=(i,key,value)=>setState(s=>({...s,rows:s.rows.map((r,j)=>j===i?{...r,[key]:value}:r)}));
 const result=estimate(state.rows,state.packing,state.charging),sales=economics(result,state.route,state);
 const date=new Intl.DateTimeFormat(l==='zh'?'zh-CN':l,{year:'numeric',month:'long',day:'numeric',timeZone:'UTC'}).format(new Date(BASIS.date+'T00:00:00Z'));
 // Model names and user-entered phone models remain literal; translate templates before insertion.
 const brief=result.valid?[q.heading,f(q.reference,{date}),q.destination,...result.rows.map((r,i)=>f(q.line,{row:n(i+1),product:copy.product.names[r.product],model:r.model||q.modelMissing,qty:n(r.qty),price:money(PRODUCTS[r.product].price)})),f(q.totalQty,{qty:n(result.qty),goods:money(result.goods)}),f(q.packing,{packing:c.packingOptions[state.packing]}),f(q.airBilling,{charging:c.chargingOptions[state.charging]}),f(q.shipment,{cartons:n(result.cartons),volume:n(result.cbm,5),gross:n(result.actualKg,3),dim:n(result.dimensionalKg,3),charge:n(result.chargeKg,3)}),f(q.route,{route:c[state.route],fee:money(result[state.route].fee),total:money(result[state.route].total),unit:money(result[state.route].unit)}),q.moq,c.formulaSea,c.scope,c.timing,c.limits,c.classification,q.final].join('\n'):'';
 const meta=calculatorMeta(l),href=localePrefix(l)+'/get-a-quote/?'+new URLSearchParams({source:'screen_protector_planner',leadGoal:'Product Sourcing',industry:'Mobile Accessories'}).toString();
 return <main className="phone-film phone-localized mx-auto max-w-7xl px-4 py-10 sm:px-6" lang={l==='zh'?'zh-CN':l} dir={l==='ar'?'rtl':'ltr'} data-localized-calculator={l}>
  <nav aria-label={copy.nav.crumb}><a href={localePrefix(l)+'/'}>{copy.nav.home}</a> / <a href={localizedProductPath('/screen-protectors',l)}>{copy.pages.home}</a></nav>
  <header className="page-heading"><p className="eyebrow">{T('ISTANBUL / LANDED COST')}</p><h1>{meta.title.replace(' | DDNZ','')}</h1><p className="lede">{c.intro}</p><p>{f(c.basis,{date})}</p><a href={localizedProductPath('/screen-protectors/compare',l)}>{copy.pages.products} →</a></header>
  <div className="planner-layout"><section className="planner"><h2>{c.mix}</h2><div className="presets" role="group" aria-label={c.replace}>{[1000,5000,10000].map(v=><button key={v} type="button" onClick={()=>set('rows',preset(v))}>{n(v)}</button>)}</div><p>{c.presetNote}</p>
  {state.rows.map((r,i)=><fieldset key={i} className="sku-row"><legend>{f(c.row,{row:n(i+1)})}</legend><label>{c.product}<select value={r.product} onChange={e=>row(i,'product',e.target.value)}>{Object.keys(PRODUCTS).map(id=><option key={id} value={id}>{copy.product.names[id]}</option>)}</select></label><label>{c.qty}<input type="number" min={PRODUCTS[r.product].minQty} max="1000000" step="1" value={r.qty} onChange={e=>row(i,'qty',e.target.value)}/></label><label>{c.model}<input maxLength={80} placeholder={c.modelPlaceholder} value={r.model} onChange={e=>row(i,'model',e.target.value)}/></label><p>{f(c.rowSummary,{price:money(PRODUCTS[r.product].price),qty:n(PRODUCTS[r.product].unitsPerCarton),min:n(PRODUCTS[r.product].minQty)})}</p><button type="button" onClick={()=>set('rows',state.rows.filter((_,j)=>j!==i))}>{c.remove}</button></fieldset>)}
  <button className="button secondary" disabled={state.rows.length>=BASIS.maxRows} onClick={()=>set('rows',[...state.rows,{product:'001',qty:500,model:''}])}>{c.add} +</button><p role="status">{saved?c.draft:c.draftFailed}</p>
  {!result.valid&&<div role="alert">{result.errors.map((s,i)=><p key={i}>{T(s)}</p>)}</div>}
  <h2>{c.pack}</h2><div className="packing-fields">{[['packing',c.packingOptions],['charging',c.chargingOptions]].map(([key,options])=><label key={key}>{c[key]}<select value={state[key]} onChange={e=>set(key,e.target.value)}>{Object.entries(options).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label>)}</div><p>{c.notMix}</p>
  {result.valid&&<><p>{result.missingModels?f(c.missing,{count:n(result.missingModels)}):c.modelsComplete}</p><dl className="packing-summary">{[['cartons',result.cartons],['cbm',result.cbm],['gross',result.actualKg],['charge',result.chargeKg]].map(([key,value])=><div key={key}><dt>{c[key]}</dt><dd>{n(value,key==='cartons'?0:3)} {key==='cbm'?'m³':['gross','charge'].includes(key)?'kg':''}</dd></div>)}</dl>{result.warnings.map((w,i)=><p key={i}>{T(w)}</p>)}</>}
  <details className="formula"><summary>{c.details}</summary>{result.valid&&result.groups.map((g,i)=><p key={i}>{copy.product.names[g.product]}: {f(c.cartonLine,{qty:n(g.qty),full:n(g.full),tail:n(g.tail?1:0),pieces:n(g.tail),cartons:n(g.cartons)})}<br/>{f(c.groupMeta,{dimensions:PRODUCTS[g.product].cartonCm.join(' × '),volume:n(g.cbm,5),weight:n(g.actualKg,3)})}</p>)}{['formulaCbm','formulaDim','formulaBill','formulaSea'].map(k=><p key={k}>{c[k]}</p>)}{result.valid&&<p>{f(c.compareWeights,{shipment:n(result.shipmentChargeKg,3),carton:n(result.cartonChargeKg,3)})}</p>}</details>
  <details className="sales-panel"><summary>{c.optional}</summary><div className="sales-fields">{[['price','price'],['monthly','monthly'],['feeRate','fee']].map(([key,label])=><label key={key}>{c[label]}<input type="number" min="0" max={key==='price'?100000:key==='monthly'?1000000:100} step={key==='monthly'?'1':'any'} value={state[key]} onChange={e=>set(key,e.target.value)}/></label>)}</div><p>{c.salesNote}</p>{sales&&<><p>{f(c.salesBasis,{route:c[state.route]})}</p>{[['price','priceOK','priceError'],['monthly','monthlyOK','monthlyError'],['feeRate','feeOK','feeError']].filter(([key,valid])=>state[key]!==''&&!sales[valid]).map(([key,,error])=><p role="alert" key={key}>{c[error]}</p>)}<dl>{['revenue','spread','contribution','months'].map(k=><div key={k}><dt>{c[k]}</dt><dd>{sales[k]===null?(k==='months'&&sales.monthlyZero?c.zeroMonthly:c.empty):k==='months'?f(c.monthValue,{months:n(sales[k],1)}):money(sales[k])}</dd></div>)}</dl></>}</details></section>
  <aside>{result.valid?['sea','air'].map(route=><section key={route} className="route-card"><h2>{c[route]}</h2><p>{f(c.days,{days:n(result[route].days)})}</p><strong>{money(result[route].unit)} / {c.unit}</strong><dl>{[['goods',result.goods],['freight',result[route].fee],['total',result[route].total]].map(([k,v])=><div key={k}><dt>{c[k]}</dt><dd>{money(v)}</dd></div>)}</dl><p>{route==='sea'?f(c.seaBasis,{volume:n(result.seaBillableCbm,5)}):f(c.airBasis,{weight:n(result.chargeKg,3)})}</p><button type="button" aria-pressed={state.route===route} onClick={()=>set('route',route)}>{state.route===route?c.selected:c.select}</button></section>):<p>{c.invalid}</p>}<h2>{c.scopeTitle}</h2>{['scope','timing','limits','classification'].map(k=><p key={k}>{c[k]}</p>)}{result.valid&&<><details><summary>{q.label}</summary><pre className="whitespace-pre-wrap">{brief}</pre></details><a className="button" href={href} onClick={e=>{if(!saveHandoff(sessionStorage,state).ok){e.preventDefault();setSaved(false)}}}>{c.quote} →</a></>}</aside></div>
 </main>;
}

export function calculatorSchema(locale){const m=calculatorMeta(locale);return {'@context':'https://schema.org','@type':'WebPage','name':m.title,'description':m.description,'url':'https://www.ddnzglobal.com'+m.path,'inLanguage':localeCode(locale)==='zh'?'zh-CN':localeCode(locale)};}
