import { renderImpact001 } from './impact001.mjs';
export function renderPrivacy001(locale = 'en') {
 const localized = {
"zh":["近看 001。", ["零售包装", "橙色包装用于识别 001 防窥系列，下单前请确认每份包装内的实际配件。"], ["28° 侧向防窥", "设计用于限制侧面观看。请在选定手机上比较正面亮度及不同视角。"], ["听筒网细节", "示意图展示听筒开口上的网层。请通过样品检查机型适配、粘合和通话清晰度。"]],"ru":["Подробнее о 001.", ["Розничная упаковка", "Оранжевая упаковка обозначает серию 001 с защитой от бокового просмотра. Уточните комплектацию каждой упаковки."], ["Боковая приватность 28°", "Конструкция ограничивает боковой просмотр. Сравните яркость и углы обзора на выбранном телефоне."], ["Сетка динамика", "На иллюстрации сетка закрывает отверстие разговорного динамика. Проверьте посадку, приклеивание и слышимость на образце."]],"fr":["Le modèle 001 en détail.", ["Présentation en magasin", "L’emballage orange identifie la gamme 001 de confidentialité. Confirmez le contenu de chaque emballage avant commande."], ["Confidentialité latérale à 28°", "Conçu pour limiter la vision latérale. Comparez la luminosité et les angles de vue sur le téléphone choisi."], ["Grille de l’écouteur", "L’illustration montre une grille sur l’ouverture de l’écouteur. Vérifiez l’ajustement, l’adhérence et la clarté des appels sur un échantillon."]],"pt":["Conheça o modelo 001.", ["Embalagem de varejo", "A embalagem laranja identifica a linha de privacidade 001. Confirme o conteúdo de cada embalagem antes do pedido."], ["Privacidade lateral de 28°", "Projetado para limitar a visão lateral. Compare o brilho e os ângulos de visão no telefone escolhido."], ["Tela do alto-falante", "A ilustração mostra uma tela sobre a abertura do alto-falante de chamadas. Verifique encaixe, adesão e clareza das chamadas na amostra."]],"tr":["001 modelini yakından inceleyin.", ["Perakende ambalajı", "Turuncu ambalaj 001 gizlilik serisini tanımlar. Siparişten önce her paketin içeriğini doğrulayın."], ["28° yandan gizlilik", "Yandan görüntülemeyi sınırlamak için tasarlanmıştır. Seçtiğiniz telefonda parlaklığı ve görüş açılarını karşılaştırın."], ["Ahize ızgarası", "Görselde ahize açıklığı üzerinde bir ızgara gösterilir. Numunede model uyumunu, yapışmayı ve arama sesinin netliğini kontrol edin."]],
 es: ['001 en detalle.', ['Presentación de venta','El embalaje naranja identifica la gama 001. Confirme el contenido de cada paquete.'], ['Privacidad lateral de 28°','Diseñado para limitar la visión lateral. Compare brillo y ángulos en el teléfono elegido.'], ['Malla del auricular','La ilustración muestra la malla sobre el auricular. Compruebe ajuste, adhesión y claridad de las llamadas en la muestra.']],
 ar: ['نظرة أقرب على 001.', ['عبوة البيع','تميّز العبوة البرتقالية مجموعة 001. تأكد من محتويات كل عبوة.'], ['خصوصية جانبية بزاوية 28°','مصمم للحد من الرؤية الجانبية. قارن السطوع وزوايا الرؤية على هاتفك المختار.'], ['شبكة سماعة الأذن','يوضح الرسم الشبكة فوق فتحة السماعة. تحقق من الملاءمة والالتصاق ووضوح المكالمات على العينة.']]
 }[locale==='zh-cn'?'zh':locale];
 return `<section class="privacy001" aria-labelledby="privacy001-title"><p class="eyebrow">${({en:'001 / PRIVACY GLASS',zh:'001／防窥玻璃膜','zh-cn':'001／防窥玻璃膜',ru:'001 / СТЕКЛО С ЗАЩИТОЙ ОТ ПРОСМОТРА',fr:'001 / VERRE DE CONFIDENTIALITÉ',pt:'001 / VIDRO DE PRIVACIDADE',tr:'001 / GİZLİLİK CAMI',es:'001 / VIDRIO DE PRIVACIDAD',ar:'001 / زجاج الخصوصية'})[locale] || '001'}</p><h2 id="privacy001-title">${localized?.[0] || 'A closer look at 001.'}</h2><div class="privacy001-grid">${[
 ['001-pack-ddnz.webp','Retail presentation','Orange 001 packaging makes the privacy range easy to identify. Confirm the individual pack contents for your order.'],
 ['001-view-28deg-ddnz.webp','28° side-view privacy','Designed to limit side viewing while keeping the screen visible from the front. Compare brightness and viewing angles on your chosen phone.'],
 ['001-mesh-ddnz.webp','Earpiece mesh detail','The illustrated mesh covers the earpiece opening. Check model fit, adhesion and call clarity on the sample.']
 ].map(([file,title,body],index)=> { if(localized) [title,body]=localized[index+1]; return `<figure><img src="/screen-protector-media/assets/${file}" width="1254" height="1254" loading="lazy" alt="${title}"><figcaption><h3>${title}</h3><p>${body}</p></figcaption></figure>`; }).join('')}</div>${renderImpact001(locale)}</section>`;
}
