import { Link } from 'react-router-dom';
import { ROUTES } from './routes.mjs';
import { canonicalSitePath } from '../../lib/notionArticleRouting';
import { useLanguage } from '../../contexts/LanguageContext';
import type { Language } from '../../i18n/translations';

const copy: Record<Language, { aria: string; altGuide: string; altHome: string; label: string; guideTitle: string; homeTitle: string; guideBody: string; homeBody: string; quote: string; explore: string; curved: string; landed: string }> = {
  en: { aria: 'Screen protector sourcing', altGuide: '2.5D and curved 3D glass profile comparison', altHome: 'Screen protector and retail-pack contents', label: 'Screen protectors · Buyer’s field notes', guideTitle: 'From product questions to an order-ready brief.', homeTitle: 'Compare four screen protectors, then plan your shipment.', guideBody: 'See packaging, glass profiles and factory footage. Carry the checks that matter into your sourcing request.', homeBody: 'Review prices, packaging and minimum quantities. Estimate all-inclusive delivery to Istanbul with your own product mix.', quote: 'Why quotes differ', explore: 'Explore screen protectors', curved: '2.5D & curved glass', landed: 'Plan landed cost' },
  zh: { aria: '屏幕保护膜采购', altGuide: '2.5D 与 3D 曲面玻璃轮廓对比', altHome: '屏幕保护膜及零售包装内容', label: '屏幕保护膜 · 买家实用笔记', guideTitle: '从产品问题整理成可询价采购需求。', homeTitle: '比较四种保护膜，再规划出运。', guideBody: '查看包装、玻璃轮廓与工厂视频，把关键检查项带入采购需求。', homeBody: '比较价格、包装和起订量，并按产品组合规划综合成本。', quote: '报价为什么不同', explore: '查看屏幕保护膜', curved: '2.5D 与曲面玻璃', landed: '规划落地成本' },
  ru: { aria: 'Закупка защитных стекол', altGuide: 'Сравнение профилей 2.5D и изогнутого 3D-стекла', altHome: 'Защитное стекло и содержимое розничной упаковки', label: 'Защитные стекла · Практические заметки покупателя', guideTitle: 'От вопросов о товаре к готовому запросу.', homeTitle: 'Сравните четыре стекла и спланируйте отправку.', guideBody: 'Изучите упаковку, профили и видео фабрики; перенесите важные проверки в запрос.', homeBody: 'Сравните цены, упаковку и минимальные партии, затем оцените полную стоимость.', quote: 'Почему цены различаются', explore: 'Смотреть защитные стекла', curved: '2.5D и изогнутое стекло', landed: 'Рассчитать полную стоимость' },
  fr: { aria: 'Sourcing de protections d’écran', altGuide: 'Comparaison des profils 2.5D et verre 3D incurvé', altHome: 'Protection d’écran et contenu de l’emballage', label: 'Protections d’écran · Notes pratiques acheteur', guideTitle: 'Des questions produit à un brief prêt à chiffrer.', homeTitle: 'Comparez quatre protections puis planifiez l’expédition.', guideBody: 'Voir emballages, profils de verre et vidéos d’usine, puis intégrer les contrôles au brief.', homeBody: 'Comparer prix, emballage et minimums, puis estimer le coût complet.', quote: 'Pourquoi les offres diffèrent', explore: 'Voir les protections', curved: 'Verre 2.5D et incurvé', landed: 'Planifier le coût rendu' },
  es: { aria: 'Compra de protectores de pantalla', altGuide: 'Comparación de perfiles 2.5D y vidrio curvo 3D', altHome: 'Protector de pantalla y contenido del empaque', label: 'Protectores de pantalla · Notas prácticas del comprador', guideTitle: 'De preguntas de producto a un brief listo para cotizar.', homeTitle: 'Compare cuatro protectores y planifique el envío.', guideBody: 'Revise embalaje, perfiles y videos de fábrica; lleve los controles al brief.', homeBody: 'Compare precios, embalaje y mínimos, y estime el costo total.', quote: 'Por qué cambian las cotizaciones', explore: 'Explorar protectores', curved: 'Vidrio 2.5D y curvo', landed: 'Planificar costo puesto' },
  ar: { aria: 'توريد واقيات الشاشة', altGuide: 'مقارنة زجاج 2.5D والزجاج المنحني 3D', altHome: 'واقي شاشة ومحتويات عبوة البيع', label: 'واقيات الشاشة · ملاحظات عملية للمشتري', guideTitle: 'من أسئلة المنتج إلى موجز جاهز للتسعير.', homeTitle: 'قارن أربعة واقيات ثم خطط للشحن.', guideBody: 'راجع التعبئة وأشكال الزجاج وفيديو المصنع وأضف الفحوص إلى طلبك.', homeBody: 'قارن الأسعار والتعبئة والحد الأدنى وقدّر التكلفة الكلية.', quote: 'لماذا تختلف العروض', explore: 'استكشف واقيات الشاشة', curved: 'زجاج 2.5D والمنحني', landed: 'خطط للتكلفة الواصلة' },
  pt: { aria: 'Sourcing de películas de proteção', altGuide: 'Comparação de perfis 2.5D e vidro curvo 3D', altHome: 'Película de proteção e conteúdo da embalagem', label: 'Películas de proteção · Notas práticas do comprador', guideTitle: 'Das dúvidas de produto a um brief pronto para cotação.', homeTitle: 'Compare quatro películas e planeje o envio.', guideBody: 'Veja embalagem, perfis e vídeos da fábrica; leve os controles ao pedido.', homeBody: 'Compare preços, embalagem e mínimos e estime o custo total.', quote: 'Por que as cotações variam', explore: 'Explorar películas', curved: 'Vidro 2.5D e curvo', landed: 'Planejar custo posto' },
  tr: { aria: 'Ekran koruyucu tedariki', altGuide: '2.5D ve kavisli 3D cam profil karşılaştırması', altHome: 'Ekran koruyucu ve perakende paket içeriği', label: 'Ekran koruyucular · Alıcı saha notları', guideTitle: 'Ürün sorularından teklife hazır talebe.', homeTitle: 'Dört koruyucuyu karşılaştırın ve sevkiyatı planlayın.', guideBody: 'Ambalajı, cam profillerini ve fabrika görüntülerini inceleyip kontrolleri talebe ekleyin.', homeBody: 'Fiyat, ambalaj ve minimumları karşılaştırıp toplam maliyeti planlayın.', quote: 'Teklifler neden farklı', explore: 'Ekran koruyucuları inceleyin', curved: '2.5D ve kavisli cam', landed: 'Toplam maliyeti planlayın' },
};

export default function ScreenProtectorEntry({ guides = false }: { guides?: boolean }) {
  const { language } = useLanguage();
  const t = copy[language];
  return <section aria-label={t.aria} className="mx-auto my-10 grid max-w-7xl gap-6 rounded-2xl border border-slate-200 bg-white p-6 text-[#10243f] sm:p-8 md:grid-cols-[180px_1fr] md:items-center">
    <Link to={canonicalSitePath(guides ? ROUTES.curves : ROUTES.home)} className="block overflow-hidden rounded-xl border border-slate-200">
      <img src={`/screen-protector-media/assets/${guides ? 'curved-glass-cover-v1.png' : '001-kit-photo.jpg'}`} width="1672" height="941" loading="lazy" alt={guides ? t.altGuide : t.altHome} className="aspect-video w-full object-cover" />
    </Link>
    <div>
      <p className="mb-3 text-xs font-bold uppercase tracking-widest text-[#763c9c]">{t.label}</p>
      <h2 className="text-2xl font-extrabold leading-tight tracking-tight">{guides ? t.guideTitle : t.homeTitle}</h2>
      <p className="mt-3 max-w-3xl text-base leading-7 text-slate-600">{guides ? t.guideBody : t.homeBody}</p>
      <div className="mt-5 flex flex-wrap gap-x-7 gap-y-4 text-sm font-bold text-[#763c9c]">
        <Link className="min-h-11 py-3 underline underline-offset-4" to={canonicalSitePath(guides ? ROUTES.prices : ROUTES.home)}>{guides ? t.quote : t.explore} ↗</Link>
        <Link className="min-h-11 py-3 underline underline-offset-4" to={canonicalSitePath(guides ? ROUTES.curves : ROUTES.calculator)}>{guides ? t.curved : t.landed} ↗</Link>
      </div>
    </div>
  </section>;
}
