import { FieldStory } from './ServiceMotion';
import { useEffect, useRef } from 'react';
import { Link } from 'react-router-dom';
import type { SourcingServiceKind } from './SourcingServicePage';
import { useLanguage } from '../contexts/LanguageContext';
import type { Language } from '../i18n/translations';

type CaseCopy = { kicker: string; title: string; intro: string; steps: string[][]; result: string; cta: string };
type SharedCaseCopy = { outcome: string; start: string; fullInspection: string; audio: string; capacity: string; complete: string; parts: string; original: string; revised: string; dutyAria: string; packingChoice: string; marginTitle: string; dutyBody: string; finished: string; components: string; difference: string; disclaimer: string };

const shared: Record<Language, SharedCaseCopy> = {
  en: { outcome: 'THE OUTCOME', start: 'Start with your products, approximate quantity and destination. Service arrangements are confirmed per order.', fullInspection: 'Read the full order story', audio: 'Explore audio & speakers', capacity: 'Loading capacity comparison', complete: 'COMPLETE SPEAKERS', parts: 'SHIPPED IN PARTS', original: 'Units per 40HQ · original packaging', revised: 'Speaker sets per 40HQ · revised plan', dutyAria: 'Project import-duty comparison', packingChoice: 'A DIFFERENT PACKING CHOICE · GUANGZHOU TO NHAVA SHEVA', marginTitle: 'Plan around total cost and margin.', dutyBody: 'For another shipment, components were packed separately. DDNZ recorded a project comparison of 44% duty for finished speakers and 18% for components.', finished: 'Finished speakers', components: 'Components', difference: 'Percentage-point difference', disclaimer: 'Project-specific figures supplied by DDNZ. Confirm current classification and rates with the destination customs broker.' },
  zh: { outcome: '项目结果', start: '提交产品、预估数量和目的地。具体服务范围按订单确认。', fullInspection: '查看完整订单案例', audio: '查看音响产品', capacity: '装柜数量对比', complete: '整机装柜', parts: '拆分部件装柜', original: '每 40HQ 台数 · 原包装', revised: '每 40HQ 套数 · 优化方案', dutyAria: '项目进口税率对比', packingChoice: '另一种包装选择 · 广州至那瓦舍瓦', marginTitle: '围绕总成本与利润规划。', dutyBody: '另一票货采用部件分装方案。DDNZ 项目记录显示，整机进口税率为 44%，部件为 18%。', finished: '整机', components: '部件', difference: '百分点差额', disclaimer: '以上为 DDNZ 提供的单项目数据。当前归类和税率需与目的国报关代理确认。' },
  ru: { outcome: 'РЕЗУЛЬТАТ', start: 'Укажите товары, примерный объем и назначение. Условия подтверждаются для каждого заказа.', fullInspection: 'Полная история заказа', audio: 'Аудио и акустика', capacity: 'Сравнение загрузки', complete: 'ГОТОВЫЕ КОЛОНКИ', parts: 'КОМПОНЕНТЫ', original: 'Штук в 40HQ · исходная упаковка', revised: 'Комплектов в 40HQ · новый план', dutyAria: 'Сравнение пошлин проекта', packingChoice: 'ДРУГОЙ ВАРИАНТ УПАКОВКИ · ГУАНЧЖОУ — НАВА-ШЕВА', marginTitle: 'Планируйте полную стоимость и маржу.', dutyBody: 'В другом проекте компоненты упаковали отдельно. DDNZ зафиксировала 44% пошлины для готовых колонок и 18% для компонентов.', finished: 'Готовые колонки', components: 'Компоненты', difference: 'Разница в п.п.', disclaimer: 'Данные относятся к конкретному проекту. Проверьте классификацию и ставки у таможенного брокера.' },
  fr: { outcome: 'RÉSULTAT', start: 'Indiquez produits, quantité approximative et destination. Le périmètre est confirmé par commande.', fullInspection: 'Lire le cas complet', audio: 'Voir audio et enceintes', capacity: 'Comparaison de capacité', complete: 'ENCEINTES COMPLÈTES', parts: 'EXPÉDIÉES EN PIÈCES', original: 'Unités par 40HQ · emballage initial', revised: 'Kits par 40HQ · plan révisé', dutyAria: 'Comparaison des droits du projet', packingChoice: 'AUTRE CHOIX D’EMBALLAGE · GUANGZHOU–NHAVA SHEVA', marginTitle: 'Planifier le coût total et la marge.', dutyBody: 'Sur un autre envoi, les composants ont été emballés séparément. DDNZ a relevé 44 % de droits sur les enceintes finies contre 18 % sur les composants.', finished: 'Enceintes finies', components: 'Composants', difference: 'Écart en points', disclaimer: 'Chiffres propres au projet. Confirmer classement et taux auprès du courtier en douane.' },
  es: { outcome: 'RESULTADO', start: 'Indique productos, cantidad aproximada y destino. El alcance se confirma por pedido.', fullInspection: 'Leer el caso completo', audio: 'Explorar audio y altavoces', capacity: 'Comparación de capacidad', complete: 'ALTAVOCES COMPLETOS', parts: 'ENVIADOS EN PARTES', original: 'Unidades por 40HQ · embalaje original', revised: 'Juegos por 40HQ · plan revisado', dutyAria: 'Comparación de aranceles', packingChoice: 'OTRA OPCIÓN DE EMBALAJE · GUANGZHOU A NHAVA SHEVA', marginTitle: 'Planifique el costo total y el margen.', dutyBody: 'En otro envío se embalaron componentes por separado. DDNZ registró 44 % de arancel para altavoces terminados y 18 % para componentes.', finished: 'Altavoces terminados', components: 'Componentes', difference: 'Diferencia en puntos', disclaimer: 'Cifras específicas del proyecto. Confirme clasificación y tasas con el agente aduanero.' },
  ar: { outcome: 'النتيجة', start: 'أرسل المنتجات والكمية التقريبية والوجهة. يؤكد نطاق الخدمة لكل طلب.', fullInspection: 'اقرأ قصة الطلب', audio: 'استكشف الصوتيات', capacity: 'مقارنة سعة التحميل', complete: 'مكبرات كاملة', parts: 'الشحن كأجزاء', original: 'وحدة لكل 40HQ · التعبئة الأصلية', revised: 'طقم لكل 40HQ · الخطة المعدلة', dutyAria: 'مقارنة رسوم المشروع', packingChoice: 'خيار تعبئة مختلف · قوانغتشو إلى نهافا شيفا', marginTitle: 'خطط وفق التكلفة الكلية والهامش.', dutyBody: 'في شحنة أخرى عُبئت المكونات منفصلة. سجلت DDNZ رسوماً بنسبة 44٪ على المنتج النهائي و18٪ على المكونات.', finished: 'منتج نهائي', components: 'مكونات', difference: 'فرق بالنقاط', disclaimer: 'الأرقام خاصة بالمشروع. أكد التصنيف والمعدل مع وسيط الجمارك.' },
  pt: { outcome: 'RESULTADO', start: 'Informe produtos, quantidade aproximada e destino. O escopo é confirmado por pedido.', fullInspection: 'Ler o caso completo', audio: 'Explorar áudio e caixas', capacity: 'Comparação de capacidade', complete: 'CAIXAS COMPLETAS', parts: 'ENVIADAS EM PEÇAS', original: 'Unidades por 40HQ · embalagem original', revised: 'Conjuntos por 40HQ · plano revisado', dutyAria: 'Comparação de impostos', packingChoice: 'OUTRA ESCOLHA DE EMBALAGEM · GUANGZHOU A NHAVA SHEVA', marginTitle: 'Planeje custo total e margem.', dutyBody: 'Em outro embarque, os componentes foram embalados separadamente. A DDNZ registrou 44% de imposto para caixas prontas e 18% para componentes.', finished: 'Caixas prontas', components: 'Componentes', difference: 'Diferença em pontos', disclaimer: 'Dados específicos do projeto. Confirme classificação e taxas com o despachante.' },
  tr: { outcome: 'SONUÇ', start: 'Ürünleri, yaklaşık miktarı ve varış yerini paylaşın. Kapsam sipariş bazında onaylanır.', fullInspection: 'Sipariş öyküsünü okuyun', audio: 'Ses ürünlerini inceleyin', capacity: 'Yükleme kapasitesi karşılaştırması', complete: 'TAM HOPARLÖRLER', parts: 'PARÇA OLARAK SEVK', original: '40HQ başına adet · ilk ambalaj', revised: '40HQ başına set · yeni plan', dutyAria: 'Proje vergi karşılaştırması', packingChoice: 'FARKLI AMBALAJ SEÇİMİ · GUANGZHOU–NHAVA SHEVA', marginTitle: 'Toplam maliyet ve marja göre planlayın.', dutyBody: 'Başka bir sevkiyatta parçalar ayrı paketlendi. DDNZ proje kaydında bitmiş ürün için %44, parçalar için %18 vergi yer aldı.', finished: 'Bitmiş ürün', components: 'Parçalar', difference: 'Puan farkı', disclaimer: 'Rakamlar projeye özeldir. Güncel sınıflandırmayı ve oranı gümrük müşaviriyle doğrulayın.' },
};
const localePrefix: Record<Language, string> = { en: '', zh: '/zh-cn', ru: '/ru', fr: '/fr', es: '/es', ar: '/ar', pt: '/pt', tr: '/tr' };

const caseCopy: Record<Language, Record<SourcingServiceKind, CaseCopy>> = {
  en: {
    'supplier-search': { kicker: 'IN PRACTICE · GUANGZHOU TO ABIDJAN', title: 'Source around how your business operates.', intro: 'An Abidjan customer asked DDNZ to source dual-8-inch Bluetooth party speakers and design the shipment around local assembly.', steps: [['Understand the operation','The buyer could assemble and make basic repairs locally.'],['Work with engineers','DDNZ and factory engineers produced a loading plan in one day.'],['Improve packing','The first model increased from 637 complete speakers to parts for 740 sets per 40HQ.']], result: 'A sourcing decision aligned with local capability and container capacity.', cta: 'Discuss your sourcing requirements' },
    'inspection-quality-control': { kicker: 'IN PRACTICE · TÜRKİYE PHONE-CASE ORDER', title: 'A defective batch stopped in China.', intro: 'Checks of models, quantities, appearance and packing identified defective products before release.', steps: [['Pause & separate','Packing and release stopped; affected goods were isolated.'],['Establish the facts','The team confirmed the issue, quantity and remedy.'],['Agree & remake','After customer approval, the factory completed the remake in two days.']], result: 'Known defective goods were not shipped to protect the sailing date.', cta: 'Discuss an inspection' },
    'consolidation-export': { kicker: 'IN PRACTICE · GUANGZHOU TO ABIDJAN', title: 'FCL loading case: 103 more speaker sets in one 40HQ.', intro: 'DDNZ and factory engineers designed a parts-based packing and loading plan.', steps: [['Original format','One 40HQ held 637 complete speakers.'],['Revised packing','Drivers, cabinets and circuit boards travelled separately.'],['Revised loading','The same container could hold parts for 740 speaker sets.']], result: '103 additional sets per 40HQ, about 16.2% more for the first model.', cta: 'Discuss a lower-cost shipment plan' },
  },
  zh: {
    'supplier-search': { kicker: '实际案例 · 广州至阿比让', title: '围绕客户的实际经营方式采购。', intro: '阿比让客户委托 DDNZ 采购双 8 英寸蓝牙音响，并结合当地组装能力设计出运方案。', steps: [['理解经营方式','客户可在当地组装并进行基础维修。'],['与工程师协作','DDNZ 与工厂工程师一天内完成装载方案。'],['优化包装','首个型号由 637 台整机提升至 740 套部件。']], result: '采购方案同时匹配客户能力与集装箱容量。', cta: '沟通采购需求' },
    'inspection-quality-control': { kicker: '实际案例 · 土耳其手机壳订单', title: '问题批次在中国被拦截。', intro: '型号、数量、外观与包装检查在放行前发现不良品。', steps: [['暂停并隔离','停止包装和放行，隔离受影响货物。'],['确认事实','核对问题、数量及可行处理方式。'],['确认并返工','客户同意后，工厂两天内完成重做。']], result: '已知不良品没有因为船期紧张而被发出。', cta: '沟通验货需求' },
    'consolidation-export': { kicker: '实际案例 · 广州至阿比让', title: '整柜案例：一个 40HQ 多装 103 套音响。', intro: 'DDNZ 与工厂工程师设计部件分装和装载方案。', steps: [['原方案','一个 40HQ 装 637 台整机。'],['调整包装','喇叭、箱体和电路板分别包装。'],['调整装载','同一柜可装 740 套部件。']], result: '首个型号每柜增加 103 套，约提升 16.2%。', cta: '沟通低成本出运方案' },
  },
  ru: {
    'supplier-search': { kicker: 'ПРАКТИКА · ГУАНЧЖОУ — АБИДЖАН', title: 'Закупка под реальную работу бизнеса.', intro: 'Клиент из Абиджана поручил DDNZ найти акустику и учесть местную сборку.', steps: [['Понять работу','Покупатель мог собирать и ремонтировать товар локально.'],['Подключить инженеров','DDNZ и фабрика создали план за один день.'],['Улучшить упаковку','Объем вырос с 637 готовых единиц до 740 комплектов деталей.']], result: 'Решение учло возможности клиента и вместимость контейнера.', cta: 'Обсудить закупку' },
    'inspection-quality-control': { kicker: 'ПРАКТИКА · ЗАКАЗ ЧЕХЛОВ В ТУРЦИЮ', title: 'Дефектную партию остановили в Китае.', intro: 'Проверка моделей, количества, внешнего вида и упаковки выявила дефекты.', steps: [['Остановить и отделить','Упаковку остановили, товар изолировали.'],['Установить факты','Подтвердили проблему, количество и решение.'],['Согласовать и переделать','После согласования фабрика переделала партию за два дня.']], result: 'Известные дефекты не отправили ради графика судна.', cta: 'Обсудить инспекцию' },
    'consolidation-export': { kicker: 'ПРАКТИКА · ГУАНЧЖОУ — АБИДЖАН', title: 'На 103 комплекта больше в одном 40HQ.', intro: 'DDNZ и инженеры фабрики разработали раздельную упаковку.', steps: [['Исходно','40HQ вмещал 637 готовых колонок.'],['Новая упаковка','Динамики, корпуса и платы упаковали отдельно.'],['Новая загрузка','Контейнер вместил детали для 740 комплектов.']], result: 'На 103 комплекта, или примерно на 16,2%, больше для первой модели.', cta: 'Обсудить экономичную отправку' },
  },
  fr: {
    'supplier-search': { kicker: 'CAS RÉEL · GUANGZHOU–ABIDJAN', title: 'Sourcer selon le fonctionnement du client.', intro: 'Un client d’Abidjan a demandé des enceintes en tenant compte de son assemblage local.', steps: [['Comprendre l’activité','Le client pouvait assembler et réparer localement.'],['Travailler avec les ingénieurs','DDNZ et l’usine ont préparé le plan en une journée.'],['Optimiser l’emballage','Le volume est passé de 637 unités finies à 740 kits.']], result: 'Une décision adaptée aux capacités locales et au conteneur.', cta: 'Discuter du sourcing' },
    'inspection-quality-control': { kicker: 'CAS RÉEL · COMMANDE DE COQUES EN TURQUIE', title: 'Un lot défectueux bloqué en Chine.', intro: 'Le contrôle des modèles, quantités, aspects et emballages a révélé des défauts.', steps: [['Bloquer et séparer','L’emballage a été arrêté et le lot isolé.'],['Établir les faits','Problème, quantité et solution ont été confirmés.'],['Valider et refaire','Après accord, l’usine a refait le lot en deux jours.']], result: 'Les produits défectueux connus n’ont pas été expédiés.', cta: 'Discuter d’une inspection' },
    'consolidation-export': { kicker: 'CAS RÉEL · GUANGZHOU–ABIDJAN', title: '103 kits supplémentaires dans un 40HQ.', intro: 'DDNZ et les ingénieurs ont conçu un plan en composants.', steps: [['Format initial','Le 40HQ contenait 637 enceintes finies.'],['Nouvel emballage','Haut-parleurs, caisses et cartes séparés.'],['Nouveau chargement','Le conteneur a accueilli 740 kits.']], result: '103 kits en plus, soit environ 16,2 % pour le premier modèle.', cta: 'Discuter d’un transport économique' },
  },
  es: {
    'supplier-search': { kicker: 'CASO REAL · GUANGZHOU–ABIDJAN', title: 'Comprar según la operación del cliente.', intro: 'Un cliente de Abiyán pidió altavoces adaptados a su capacidad de montaje local.', steps: [['Entender la operación','El cliente podía montar y reparar localmente.'],['Trabajar con ingenieros','DDNZ y la fábrica crearon el plan en un día.'],['Mejorar el embalaje','Se pasó de 637 unidades completas a 740 juegos.']], result: 'Una decisión alineada con la capacidad local y del contenedor.', cta: 'Hablar de su compra' },
    'inspection-quality-control': { kicker: 'CASO REAL · PEDIDO DE FUNDAS A TURQUÍA', title: 'Un lote defectuoso detenido en China.', intro: 'El control de modelos, cantidades, apariencia y embalaje detectó defectos.', steps: [['Pausar y separar','Se detuvo el embalaje y se aisló la mercancía.'],['Establecer hechos','Se confirmó problema, cantidad y solución.'],['Acordar y rehacer','Tras aprobación, la fábrica rehízo el lote en dos días.']], result: 'No se enviaron defectos conocidos por proteger la salida.', cta: 'Hablar de una inspección' },
    'consolidation-export': { kicker: 'CASO REAL · GUANGZHOU–ABIDJAN', title: '103 juegos más en un 40HQ.', intro: 'DDNZ y la fábrica diseñaron un plan de carga por componentes.', steps: [['Formato original','El 40HQ llevaba 637 altavoces completos.'],['Embalaje revisado','Drivers, cajas y placas viajaron separados.'],['Carga revisada','El contenedor admitió 740 juegos.']], result: '103 juegos adicionales, cerca de 16,2 % para el primer modelo.', cta: 'Hablar de un envío económico' },
  },
  ar: {
    'supplier-search': { kicker: 'حالة فعلية · قوانغتشو إلى أبيدجان', title: 'توريد يناسب طريقة عمل العميل.', intro: 'طلب عميل في أبيدجان مكبرات تناسب قدرته على التجميع المحلي.', steps: [['فهم التشغيل','يمكن للعميل التجميع والإصلاح محلياً.'],['العمل مع المهندسين','أعدت DDNZ والمصنع الخطة في يوم.'],['تحسين التعبئة','ارتفعت السعة من 637 وحدة كاملة إلى 740 طقماً.']], result: 'قرار يطابق القدرة المحلية وسعة الحاوية.', cta: 'ناقش متطلبات التوريد' },
    'inspection-quality-control': { kicker: 'حالة فعلية · طلب أغطية هواتف لتركيا', title: 'إيقاف دفعة معيبة في الصين.', intro: 'كشف فحص الموديلات والكميات والمظهر والتعبئة عن العيوب.', steps: [['الإيقاف والعزل','توقفت التعبئة وعُزلت البضائع.'],['تحديد الحقائق','تم تأكيد المشكلة والكمية والحل.'],['الاتفاق وإعادة الصنع','بعد موافقة العميل أعاد المصنع الدفعة خلال يومين.']], result: 'لم تُشحن العيوب المعروفة للحفاظ على الموعد.', cta: 'ناقش طلب الفحص' },
    'consolidation-export': { kicker: 'حالة فعلية · قوانغتشو إلى أبيدجان', title: '103 أطقم إضافية في حاوية 40HQ.', intro: 'صممت DDNZ والمصنع خطة تعبئة بالأجزاء.', steps: [['الوضع الأصلي','استوعبت الحاوية 637 مكبراً كاملاً.'],['التعبئة المعدلة','شُحنت الأجزاء منفصلة.'],['التحميل المعدل','استوعبت الحاوية أجزاء 740 طقماً.']], result: 'زيادة 103 أطقم، نحو 16.2٪ للموديل الأول.', cta: 'ناقش خطة شحن أقل تكلفة' },
  },
  pt: {
    'supplier-search': { kicker: 'CASO REAL · GUANGZHOU–ABIDJAN', title: 'Comprar conforme a operação do cliente.', intro: 'Um cliente de Abidjan pediu caixas adaptadas à montagem local.', steps: [['Entender a operação','O cliente podia montar e reparar localmente.'],['Trabalhar com engenheiros','DDNZ e fábrica criaram o plano em um dia.'],['Melhorar a embalagem','A capacidade passou de 637 unidades a 740 conjuntos.']], result: 'Uma decisão alinhada à capacidade local e do contêiner.', cta: 'Discutir o sourcing' },
    'inspection-quality-control': { kicker: 'CASO REAL · PEDIDO DE CAPAS PARA A TURQUIA', title: 'Um lote defeituoso parado na China.', intro: 'A verificação de modelos, quantidades, aparência e embalagem encontrou defeitos.', steps: [['Parar e separar','A embalagem parou e os itens foram isolados.'],['Confirmar os fatos','Problema, quantidade e solução foram confirmados.'],['Acordar e refazer','Após aprovação, a fábrica refez o lote em dois dias.']], result: 'Defeitos conhecidos não foram enviados para proteger a data.', cta: 'Discutir uma inspeção' },
    'consolidation-export': { kicker: 'CASO REAL · GUANGZHOU–ABIDJAN', title: '103 conjuntos a mais em um 40HQ.', intro: 'DDNZ e fábrica criaram um plano de peças separadas.', steps: [['Formato original','O 40HQ levava 637 caixas completas.'],['Embalagem revisada','Drivers, gabinetes e placas separados.'],['Carga revisada','O contêiner recebeu 740 conjuntos.']], result: '103 conjuntos adicionais, cerca de 16,2% para o primeiro modelo.', cta: 'Discutir transporte econômico' },
  },
  tr: {
    'supplier-search': { kicker: 'SAHA ÖRNEĞİ · GUANGZHOU–ABIDJAN', title: 'Müşterinin işleyişine göre tedarik.', intro: 'Abidjan’daki müşteri yerel montaja uygun hoparlör tedariki istedi.', steps: [['Operasyonu anla','Müşteri yerelde montaj ve temel onarım yapabiliyordu.'],['Mühendislerle çalış','DDNZ ve fabrika planı bir günde hazırladı.'],['Ambalajı geliştir','Kapasite 637 tam üründen 740 sete çıktı.']], result: 'Yerel yetenek ve konteyner kapasitesine uygun karar.', cta: 'Tedarik ihtiyacını görüşün' },
    'inspection-quality-control': { kicker: 'SAHA ÖRNEĞİ · TÜRKİYE TELEFON KILIFI SİPARİŞİ', title: 'Kusurlu parti Çin’de durduruldu.', intro: 'Model, miktar, görünüm ve ambalaj kontrolü kusurları yakaladı.', steps: [['Durdur ve ayır','Ambalaj durdu, etkilenen ürünler ayrıldı.'],['Gerçeği belirle','Sorun, miktar ve çözüm doğrulandı.'],['Onayla ve yenile','Müşteri onayıyla fabrika iki günde yeniledi.']], result: 'Bilinen kusurlar gemi programı için sevk edilmedi.', cta: 'Kontrol talebini görüşün' },
    'consolidation-export': { kicker: 'SAHA ÖRNEĞİ · GUANGZHOU–ABIDJAN', title: 'Bir 40HQ’da 103 set daha.', intro: 'DDNZ ve fabrika parça bazlı yükleme planı geliştirdi.', steps: [['İlk düzen','40HQ 637 tam hoparlör alıyordu.'],['Yeni ambalaj','Sürücüler, kabinler ve kartlar ayrı paketlendi.'],['Yeni yükleme','Konteyner 740 set parça aldı.']], result: 'İlk model için 103 set, yaklaşık %16,2 artış.', cta: 'Daha düşük maliyetli sevkiyatı görüşün' },
  },
};

export default function ServiceCaseDetail({ kind, quoteHref }: { kind: SourcingServiceKind; quoteHref: string }) {
  const { language } = useLanguage();
  const content = caseCopy[language][kind];
  const t = shared[language];
  const section = useRef<HTMLElement>(null);
  useEffect(() => {
    const nodes = section.current?.querySelectorAll('.sc-capacity,.sc-duty,.sc-inner>ol>li');
    if (!nodes || matchMedia('(prefers-reduced-motion: reduce)').matches) return;
    const observer = new IntersectionObserver(entries => entries.forEach(entry => { if (entry.isIntersecting) { entry.target.classList.add('sc-visible'); observer.unobserve(entry.target); } }), { threshold: 0.15 });
    nodes.forEach(node => { node.classList.add('sc-animate'); observer.observe(node); });
    return () => observer.disconnect();
  }, [kind]);
  return <section ref={section} className="sc-case" id="service-case" aria-labelledby="sc-title">
    <div className="sc-inner"><p className="sc-kicker">{content.kicker}</p><h2 id="sc-title">{content.title}</h2><p className="sc-intro">{content.intro}</p>
      {kind === 'consolidation-export' && <div className="sc-capacity" aria-label={t.capacity}><div><span>{t.complete}</span><strong>637</strong><div style={{ width: '86.1%' }} /><small>{t.original}</small></div><div><span>{t.parts}</span><strong>740</strong><div style={{ width: '100%' }} /><small>{t.revised}</small></div></div>}
      {kind !== 'supplier-search' ? <FieldStory steps={content.steps} inspection={kind === 'inspection-quality-control'} /> : <ol>{content.steps.map(([title, body], index) => <li key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{body}</p></li>)}</ol>}
      {kind === 'consolidation-export' && <aside className="sc-result" style={{ marginBottom: 20 }}><strong>{t.packingChoice}</strong><h3>{t.marginTitle}</h3><p>{t.dutyBody}</p><div className="sc-duty" aria-label={t.dutyAria}><div><strong>44%</strong><span>{t.finished}</span></div><div><strong>18%</strong><span>{t.components}</span></div><div><strong>26 pp</strong><span>{t.difference}</span></div></div><p>{t.disclaimer}</p></aside>}
      <div className="sc-result"><strong>{t.outcome}</strong><p>{content.result}</p></div>
      <div className="sc-actions"><div><Link className="ddnz-button ddnz-button-primary" to={quoteHref}>{content.cta} →</Link><p>{t.start}</p></div>{kind === 'inspection-quality-control' ? <Link to={`${localePrefix[language]}/sourcing-services/?review=candidate#retail-case`}>{t.fullInspection} →</Link> : <Link to="/sourcing/audio-speakers-from-china/">{t.audio} →</Link>}</div>
    </div>
  </section>;
}
