import copy from './locales/planning/cafe';
import React, {useState} from 'react';

export const cafePath='/sourcing/restaurant-kitchen-packages-from-china/cafe-light-meals/';
export const cafeImages=['3d-concept','floor-plan','workflow','espresso-station','back-bar-elevation','equipment-layout'];
export const cafeMeta=Object.fromEntries(Object.entries(copy).map(([lang,c])=>[lang,c.meta]));

export default function CafePlanningContent({locale='en'}:{locale?:string}){
 const c=copy[locale],prefix=locale==='en'?'':locale==='zh'?'/zh-cn':'/'+locale,[destination,setDestination]=useState(''),[requirements,setRequirements]=useState('');
 const quote=prefix+'/get-a-quote/?'+new URLSearchParams({leadGoal:'Product Sourcing',source:'restaurant_kitchen_package',projectNeed:'cafe-light-meals',industry:c.industry,dest:destination,overviewBrief:[c.title,requirements,...c.rows.map(r=>r[0])].join('\n')});
 return <main id="main-content" lang={locale==='zh'?'zh-CN':locale} dir={locale==='ar'?'rtl':'ltr'} className="bg-[#fffdf9] text-[#38253f]">
 <header className="border-b border-purple-100 bg-cover bg-right px-6 py-16" style={{backgroundImage:"linear-gradient(110deg,#fffdf9f5,#faf4f9c9),url('/commercial-kitchen-media/ddnz-ribbon-desktop-v1.webp')"}}><div className="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-2"><div><a className="text-sm text-purple-800 underline" href={`${prefix}/sourcing/restaurant-kitchen-packages-from-china/`}>{c.parent} ↗</a><p className="mt-8 text-sm font-bold tracking-wide text-purple-800">{c.eyebrow}</p><h1 className="mt-5 text-4xl font-bold leading-tight md:text-5xl">{c.title}</h1><p className="mt-6 text-lg leading-8 text-[#65596b]">{c.intro}</p><div className="mt-8 flex flex-wrap items-center gap-6"><a href="#package-rfq" className="rounded-lg bg-[#c2492b] px-6 py-4 font-bold text-white">{c.cta} →</a><a href="#cafe-layout" className="font-bold text-purple-800 underline">{c.explore} ↓</a></div></div><figure><img src="/images/cafe-planning/3d-concept.webp" width="1198" height="1313" fetchPriority="high" alt={c.captions[0]} className="mx-auto max-h-[620px] w-full rounded-2xl object-contain"/><figcaption className="mt-3 text-sm text-[#65596b]">{c.captions[0]}</figcaption></figure></div></header>
 <div className="mx-auto max-w-7xl space-y-20 px-6 py-16">
 <section id="cafe-layout" className="scroll-mt-28"><h2 className="text-3xl font-bold">{c.gallery}</h2><p className="mt-4 leading-8 text-[#65596b]">{c.galleryIntro}</p><div className="mt-8 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{cafeImages.map((name,i)=><figure key={name} className="overflow-hidden rounded-xl border border-purple-100 bg-white"><a href={`/images/cafe-planning/${name}.webp`} target="_blank" rel="noopener noreferrer" aria-label={c.captions[i]}><img src={`/images/cafe-planning/${name}-640.webp`} width="640" height="710" loading="lazy" alt={c.captions[i]} className="aspect-[10/11] w-full object-contain"/></a><figcaption className="p-5"><strong>{String(i+1).padStart(2,'0')} · {c.tabs[i]}</strong><p className="mt-2 text-sm leading-6 text-[#65596b]">{c.captions[i]}</p></figcaption></figure>)}</div><p className="mt-5 max-w-5xl text-sm leading-7 text-[#65596b]">{c.note}</p></section>
 <section><h2 className="text-3xl font-bold">{c.zonesTitle}</h2><div className="mt-8 grid gap-x-12 md:grid-cols-2">{c.zones.map(([title,body],i)=><article key={title} className="border-t border-purple-200 py-7"><span className="text-sm font-bold text-purple-700">0{i+1}</span><h3 className="mt-3 text-xl font-bold">{title}</h3><p className="mt-4 leading-8 text-[#65596b]">{body}</p></article>)}</div></section>
 <section><h2 className="text-3xl font-bold">{c.scheduleTitle}</h2><div className="mt-8 overflow-x-auto rounded-xl border border-purple-100"><table className="w-full min-w-[620px] border-collapse text-start"><thead className="bg-purple-50"><tr>{c.headers.map(v=><th className="p-5 text-start" key={v}>{v}</th>)}</tr></thead><tbody>{c.rows.map(row=><tr className="border-t border-purple-100" key={row[0]}>{row.map((v,i)=>i===0?<th scope="row" className="p-5 text-start leading-7" key={v}>{v}</th>:<td className="p-5 leading-7 text-[#65596b]" key={v}>{v}</td>)}</tr>)}</tbody></table></div></section>
 <section className="grid gap-10 border-y border-purple-100 py-10 md:grid-cols-2"><h2 className="text-3xl font-bold leading-tight">{c.procureTitle}</h2><div><p className="leading-8 text-[#65596b]">{c.procure}</p><p className="mt-5 text-sm leading-7 text-[#65596b]">{c.boundary}</p></div></section>
 <section id="package-rfq" className="scroll-mt-28 rounded-2xl bg-purple-50 p-7 md:p-10"><h2 className="text-3xl font-bold">{c.briefTitle}</h2><p className="mt-4 max-w-4xl leading-8 text-[#65596b]">{c.brief}</p><div className="my-7 grid gap-6 md:grid-cols-2"><label>{c.destination}<input maxLength={160} value={destination} onChange={e=>setDestination(e.target.value)} className="mt-3 block w-full rounded-lg border border-purple-200 bg-white p-4"/></label><label>{c.requirements}<textarea maxLength={1500} value={requirements} onChange={e=>setRequirements(e.target.value)} rows={4} className="mt-3 block w-full rounded-lg border border-purple-200 bg-white p-4"/></label></div><a href={quote} className="inline-block rounded-lg bg-purple-800 px-6 py-4 font-bold text-white">{c.next} →</a><p className="mt-4 text-sm text-[#65596b]">{c.review}</p></section>
 <nav aria-label={c.related}><h2 className="text-xl font-bold">{c.related}</h2><div className="mt-5 flex flex-wrap gap-7">{['/sourcing/commercial-ice-machines-from-china/','/refrigeration-equipment/','/sourcing-services/inspection-quality-control/'].map((path,i)=><a key={path} href={prefix+path} className="font-bold text-purple-800 underline">{c.links[i]} ↗</a>)}</div></nav>
 </div></main>;
}
