import React,{useState} from 'react';
import {categoryCopy,type CategoryLocale} from './categoryLocalization';
import {kitchenCategories,categoryProducts,kitchenModelHref} from './data/categories.mjs';
import {foodLocales,foodPrefix} from '../food-processing/localization';
import {overviewCopy} from '../overview/copy';
export default function LocalizedCategoryContent({category,locale}:{category:any;locale:CategoryLocale}){
 const c=categoryCopy[locale],u=foodLocales[locale].ui,o=overviewCopy[locale],i=kitchenCategories.indexOf(category),prefix=foodPrefix(locale),products=categoryProducts(category),hero=products.find(p=>p.id===category.heroId)!;
 const [selection,setSelection]=useState<Record<string,number>>({});const [destination,setDestination]=useState('');const [notes,setNotes]=useState('');
 const chosen=products.filter(p=>selection[p.id]>0);const amount=(id:string,n:number)=>setSelection(s=>({...s,[id]:Math.max(0,Math.min(999,Math.floor(n)||0))}));
 const brief=[c.titles[i],...chosen.map(p=>`${p.model} × ${selection[p.id]} · ${p.metric} · ${p.dimensions}`),`${u.destination}: ${destination}`,notes,c.ui.priceNote].join('\n');
 const quote=`${prefix}/get-a-quote/?`+new URLSearchParams({leadGoal:'Product Sourcing',source:'kitchen_category',industry:c.titles[i],overviewBrief:brief,dest:destination});
 const keys:Record<string,string>={'Daily output':c.ui.output,'Tank volume':c.ui.volume,'Tanks':c.ui.tanks,'Rated power':u.power,'Cooking plate':c.ui.plate,'Surface':c.ui.surface};
 return <main id="main-content" className="ddnz-kitchen kitchen-category" lang={locale==='zh'?'zh-CN':locale} dir={locale==='ar'?'rtl':'ltr'}>
 <nav className="kitchen-breadcrumb wrap" aria-label={u.products}><a href={`${prefix}/products/`}>{u.products}</a></nav>
 <section className="category-hero wrap"><div><p className="eyebrow">{o.ui.services}</p><h1>{c.titles[i]}</h1><p className="hero-description">{c.intros[i]}</p><div className="actions"><a className="button primary" href="#category-models">{u.compare}</a><a className="text-link" href="#category-buying">{u.scope}</a></div></div><figure className="category-hero-photo"><img src={hero.image} alt={`${hero.model} · ${c.titles[i]}`} width="1200" height="900"/><figcaption><strong dir="ltr">{category.statistic}</strong><span>{i===0?c.ui.output:i===1?c.ui.volume:c.ui.plate}</span></figcaption></figure></section>
 <nav className="category-navigation wrap" aria-label={u.related}>{kitchenCategories.map((cat,index)=><a key={cat.id} href={`${prefix}${cat.path}`} aria-current={index===i?'page':undefined}>{c.titles[index]}</a>)}</nav>
 <section id="category-models" className="section wrap"><h2>{u.compare}</h2><div className="category-model-grid">{products.map(p=><article className="category-model" id={`model-${p.id}`} key={p.id}><div className="category-model-photo"><img src={p.image} alt={`${p.model} · ${c.titles[i]}`} width="1200" height="900" loading="lazy"/></div><div className="category-model-copy"><h3><bdi>{p.model}</bdi></h3><strong className="category-model-metric" dir="ltr">{p.metric}</strong><dl>{category.comparisonKeys.filter((k:string)=>p.specs[k]).map((k:string)=><div key={k}><dt>{keys[k]}</dt><dd>{p.specs[k]==='Flat'?c.ui.flat:<bdi>{p.specs[k]}</bdi>}</dd></div>)}<div><dt>{u.size}</dt><dd><bdi>{p.dimensions}</bdi></dd></div></dl><div className="category-price">{p.quote?<><span>{c.ui.price}</span><strong dir="ltr">CNY {p.quote.price.toFixed(2)}</strong><span>{u.unit} · {c.ui.reference}: {p.quote.minUnits}</span></>:<strong>{c.ui.request}</strong>}</div><button type="button" className="button primary" onClick={()=>{amount(p.id,(selection[p.id]||0)+1);document.getElementById('category-rfq')?.scrollIntoView();}}>{u.add}</button></div></article>)}</div><p className="fine category-price-note">{c.ui.priceNote}</p></section>
 <section id="category-buying" className="section wrap category-buying"><h2>{u.scope}</h2><div className="category-buying-grid">{c.notes[i].map((text,j)=><article key={j}><span className="category-step">0{j+1}</span><p>{text}</p></article>)}</div></section>
 <section id="category-rfq" className="section wrap"><h2>{u.list}</h2><p>{o.ui.formIntro}</p>{chosen.length?chosen.map(p=><div className="my-4 flex flex-wrap items-center gap-5" key={p.id}><strong><bdi>{p.model}</bdi></strong><label>{u.quantity}<input className="mx-3 rounded border border-slate-400 p-3" aria-label={`${p.model} ${u.quantity}`} type="number" min="1" max="999" value={selection[p.id]} onChange={e=>amount(p.id,Number(e.target.value))}/></label><button className="text-link" type="button" onClick={()=>amount(p.id,0)}>{u.remove} {p.model}</button></div>):<p>{u.empty}</p>}<div className="my-6 grid gap-5 md:grid-cols-2"><label>{u.destination}<input className="mt-2 block w-full rounded border border-slate-400 p-3" value={destination} onChange={e=>setDestination(e.target.value)} maxLength={160}/></label><label>{o.ui.notes}<textarea className="mt-2 block w-full rounded border border-slate-400 p-3" value={notes} onChange={e=>setNotes(e.target.value)} maxLength={1500}/></label></div>{chosen.length>0&&<a className="button primary" href={quote}>{u.continue}</a>}<p className="fine">{u.review}</p></section>
 <section className="section wrap"><h2>{u.related}</h2><div className="category-reading"><a href={kitchenModelHref(hero.id)} hrefLang="en">{o.ui.compare} · {c.ui.english}</a>{category.reading.map((article:any)=><a key={article.slug} href={`/blog/${article.slug}/`} hrefLang="en">{c.ui.reading} · {c.ui.english}</a>)}<a href={`${prefix}/sourcing-services/`}>{o.ui.services}</a></div></section>
 </main>;
}
