import React,{useState} from 'react';
import {packageCopy,packageInquiry,type PackageLocale} from './packageLocalization';
import {allScenarios,libraryOrder} from './data/restaurant-scenarios.mjs';
import {kitchenPackagePath} from './routes.mjs';
import {foodPrefix,foodLocales} from '../food-processing/localization';
import {overviewCopy} from '../overview/copy';
function ConceptPlan({base,copy,label}:{base:any;copy:any;label:string}){return <div className="overflow-x-auto"><svg viewBox="0 0 710 540" role="img" aria-label={label} className="mx-auto w-full max-w-3xl" style={{direction:"ltr"}}><rect x="40" y="40" width="630" height="460" fill="#f3f5f5" stroke="#64748b"/><text x="350" y="24" textAnchor="middle" fontSize="16">{base.plan.width}</text><text x="14" y="270" textAnchor="middle" fontSize="16" transform="rotate(-90 14 270)">{base.plan.depth}</text>{base.plan.rooms.map((r:any,i:number)=><g key={i}><rect x={r.x} y={r.y} width={r.w} height={r.h} fill="#e2e8f0" stroke="white" strokeWidth="3"/><text x={r.x+12} y={r.y+r.h-12} fontSize="18" fill="#475569">{i+1}</text></g>)}{base.plan.equipment.map((e:any,i:number)=><g key={i}><rect x={e.x} y={e.y} width={e.w} height={e.h} fill="white" stroke="#334155"/><text x={e.x+e.w/2} y={e.y+e.h/2} textAnchor="middle" fontSize="11">{e.code.replace(' HOOD','').replace('PREP','E')}</text></g>)}</svg><ol className="grid gap-3 md:grid-cols-2">{copy.zones.map((name:string,i:number)=><li key={name}>{i+1}. {name}</li>)}</ol></div>;}
export default function LocalizedPackageContent({locale,slug}:{locale:PackageLocale;slug?:string}){
 const c=packageCopy[locale],u=foodLocales[locale].ui,o=overviewCopy[locale],prefix=foodPrefix(locale),[selected,setSelected]=useState(slug||libraryOrder[0]),[destination,setDestination]=useState(''),[requirements,setRequirements]=useState('');
 const index=libraryOrder.indexOf(selected),s=c.scenarios[index],base=allScenarios[selected],heading=slug?c.ui.template.replace('{name}',s.name):c.ui.title;
 const numeric=(value:string)=>value.match(/\d[\d,]*/g)?.join('–')||value;
 return <main id="main-content" lang={locale==='zh'?'zh-CN':locale} dir={locale==='ar'?'rtl':'ltr'} className="bg-slate-50 text-slate-900"><div className="mx-auto max-w-7xl space-y-16 px-6 py-12">
 <header className="grid items-center gap-10 lg:grid-cols-2"><div><nav className="mb-6 flex flex-wrap gap-4"><a className="text-purple-800 underline" href={`${prefix}/products/`}>{u.products}</a>{slug&&<a className="text-purple-800 underline" href={`${prefix}${kitchenPackagePath}/`}>{c.ui.scenarios}</a>}</nav><h1 className="text-4xl font-bold leading-tight md:text-5xl">{heading}</h1><p className="mt-6 text-lg leading-8">{slug?s.summary:c.ui.intro}</p><a className="mt-6 inline-block rounded-xl bg-purple-800 px-5 py-3 font-bold text-white" href="#package-rfq">{o.ui.quote}</a></div>{base.isometric?<figure><img src={base.isometric} alt={`${s.name} · ${c.ui.concept}`} width="1200" height="900" className="w-full rounded-2xl"/><figcaption className="mt-3 text-sm text-slate-600">{c.ui.concept}</figcaption></figure>:<div className="rounded-2xl bg-slate-900 p-10 text-white"><p>{c.ui.plan}</p><p className="mt-5 text-3xl" dir="ltr">{base.size}</p><p className="mt-5">{c.ui.concept}</p></div>}</header>
 <section aria-labelledby="package-scenarios"><h2 id="package-scenarios" className="text-3xl font-bold">{c.ui.scenarios}</h2><div className="mt-7 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{libraryOrder.map((key:string,i:number)=><a className="rounded-2xl border border-slate-200 bg-white p-6" key={key} href={`${prefix}${kitchenPackagePath}/${key}/`}><h3 className="text-xl font-bold text-purple-800">{c.scenarios[i].name}</h3><p className="mt-3 leading-7">{c.scenarios[i].summary}</p></a>)}</div></section>
 {!slug&&<label className="block text-lg font-bold">{c.ui.scenarios}<select className="mt-3 block w-full rounded-xl border border-slate-400 bg-white p-4" value={selected} onChange={e=>setSelected(e.target.value)}>{libraryOrder.map((key:string,i:number)=><option value={key} key={key}>{c.scenarios[i].name}</option>)}</select></label>}
 <section><h2 className="text-3xl font-bold">{s.name} · {c.ui.workflow}</h2><p className="mt-5 leading-8">{s.summary}</p><dl className="my-7 grid gap-4 sm:grid-cols-3">{[[c.ui.area,`${numeric(base.footprint)} m²`],[c.ui.aisle,`${numeric(base.aisle)} mm`],[c.ui.crew,numeric(base.crew)]].map(([label,value])=><div className="rounded-xl bg-white p-5" key={label}><dt>{label}</dt><dd className="mt-2 text-xl font-bold"><bdi>{value}</bdi></dd></div>)}</dl><ol className="flex flex-wrap gap-3">{s.zones.map((zone,i)=><li className="rounded-xl bg-purple-100 px-4 py-3" key={zone}>{i+1}. {zone}</li>)}</ol></section>
 {base.plan&&<section><h2 className="mb-6 text-3xl font-bold">{c.ui.plan}</h2><ConceptPlan base={base} copy={s} label={`${s.name} · ${c.ui.plan}`}/><p className="mt-4 text-sm leading-7">{c.ui.concept}</p></section>}
 <section className="grid gap-8 lg:grid-cols-2"><div><h2 className="text-3xl font-bold">{c.ui.equipment}</h2><ol className="mt-6 divide-y divide-slate-200 rounded-2xl bg-white p-6">{s.equipment.map((text,j)=><li className="py-4 leading-7" key={text}><bdi className="font-bold">{base.equipment[j][0]}</bdi> · {text}{base.equipment[j].length>3&&<p className="text-sm text-slate-600"><bdi>{base.equipment[j][2]} mm</bdi></p>}</li>)}</ol></div><div><h2 className="text-3xl font-bold">{c.ui.utilities}</h2><ul className="mt-6 list-disc space-y-5 ps-6 leading-7">{s.utilities.map(text=><li key={text}>{text}</li>)}</ul><p className="mt-8 rounded-xl bg-amber-50 p-5 leading-7">{c.ui.boundary}</p></div></section>
 <section id="package-rfq" className="scroll-mt-32 rounded-2xl bg-purple-50 p-7"><h2 className="text-3xl font-bold">{o.ui.quote}</h2><p className="mt-4 leading-7">{c.ui.scope}</p><div className="my-6 grid gap-5 md:grid-cols-2"><label>{u.destination}<input className="mt-2 block w-full rounded-lg border border-slate-400 bg-white p-3" value={destination} onChange={e=>setDestination(e.target.value)} maxLength={160}/></label><label>{c.ui.menu}<textarea className="mt-2 block w-full rounded-lg border border-slate-400 bg-white p-3" value={requirements} onChange={e=>setRequirements(e.target.value)} maxLength={1500}/></label></div><a className="inline-block rounded-xl bg-purple-800 px-5 py-3 font-bold text-white" href={packageInquiry(locale,selected,destination,requirements)}>{u.continue}</a><p className="mt-4 text-sm">{u.review}</p></section>
 <div className="flex flex-wrap gap-5"><a className="text-purple-800 underline" href={`${kitchenPackagePath}/${selected}/`} hrefLang="en">{c.ui.pdf} · {c.ui.english}</a><a className="text-purple-800 underline" href={`${prefix}/sourcing-services/`}>{o.ui.services}</a><a className="text-purple-800 underline" href={`${prefix}/sourcing/food-processing-machinery-from-china/`}>{u.catalogueTitle}</a></div>
 </div></main>;
}
