import smallTranslations from './locales/planning/small';
import React, {useState} from 'react';
export const smallKitchenPath='/sourcing/restaurant-kitchen-packages-from-china/casual-dining/';
export const smallKitchenMeta=Object.fromEntries(Object.entries(smallTranslations).map(([lang,c]:any)=>[lang,c.meta]));
// Transcribed from source image 8. Dimensions and quantities are reference values, not verified specifications.
export const smallKitchenSchedule=[
['A01','单星水池（无靠背）','Single-bowl sink, no upstand','500 × 600 × 800','1'],['A02','水吧台','Beverage counter','1500 × 600 × 1485','1'],['A03','冷藏操作台','Refrigerated work counter','1200 × 600 × 800','1'],
['B01','油网烟罩','Extraction hood with grease filters','900 × 610','2.76 m'],['B02','挂墙双层板','Two-tier wall shelf','1500 × 350 × 600','1'],['B03','三头自动升降煮面炉','Three-basket pasta cooker with automatic lift','400 × 800 × 830','1'],['B04','台式双缸炸炉','Countertop twin-tank fryer','600 × 600 × 435','1'],['B05','单通工作台','Work cabinet, single-side access','1500 × 700 × 800','1'],['B06','双门平台雪柜','Two-door refrigerated prep counter','1500 × 700 × 800','1'],['B07','双通工作台','Pass-through work cabinet','1800 × 600 × 800','1'],['B08','单门玻璃门消毒柜','Single glass-door sanitizing cabinet','600 × 600 × 1800','1'],['B09','单孔收餐工作台','Scraping table with waste opening','500 × 700 × 800','1'],['B10','台式扒炉','Countertop griddle','600 × 600 × 370','1'],['B11','四层栅格层架','Four-tier slatted storage rack','1200 × 600 × 1550','1'],['B12','三星水池','Three-bowl sink','1500 × 700 × 950','2'],['B13','四门高身雪柜','Four-door upright refrigerator','1200 × 700 × 1950','1'],['B14','双层工作台','Worktable with undershelf','700 × 700 × 800','1'],['B15','台式保温炉','Countertop bain-marie','600 × 600 × 350','1'],['B16','单层二盘不锈钢烤箱','Single-deck two-tray stainless steel oven','1225 × 770 × 450','1'],['B17','单星盆水池','Single-bowl sink','500 × 700 × 950','1'],['B18','四头电磁炉连柜座','Four-zone induction range with cabinet base','800 × 800 × 800','1'],['B19','双层工作台','Worktable with undershelf','1600 × 800 × 800','1']];
const images=[['dimensioned-plan',6,1290,1301,'带设备尺寸的厨房平面图','Dimensioned kitchen equipment plan'],['wet-dry-zones',1,1290,1352,'干湿分区','Wet and dry zones'],['functional-zones',2,1290,1268,'烹饪、脏物与洁净分区','Cooking, soiled and clean zones'],['workflow',3,1290,1318,'出品与餐具回收动线','Food preparation and used-ware return'],['area-plan',7,1105,2049,'后厨、水吧与餐区关系','Kitchen, beverage counter and dining areas']] as const;
export default function SmallKitchenPlanningContent({locale='en'}:{locale?:string}){
 const zh=locale==='zh',p=locale==='en'?'':zh?'/zh-cn':'/'+locale;
 const local=smallTranslations[locale]; const tx=(key: keyof typeof local)=>local[key] as string;
 const [dest,setDest]=useState(''),[brief,setBrief]=useState(''),[topic,setTopic]=useState(''),[view,setView]=useState(0);
 const title=tx('s0');
 const quote=p+'/get-a-quote/?'+new URLSearchParams({leadGoal:'Product Sourcing',source:'restaurant_kitchen_package',projectNeed:'casual-dining',industry:tx('s1'),dest,overviewBrief:[title,topic,brief,tx('s2')].join('\n')});
 return <main id="main-content" className="bg-[#fffdf9] text-[#38253f]" lang={zh?'zh-CN':locale} dir={locale==='ar'?'rtl':'ltr'}>
 <header className="border-b border-purple-100 bg-cover bg-right px-6 py-14" style={{backgroundImage:"linear-gradient(110deg,#fffdf9f5,#faf4f9c9),url('/commercial-kitchen-media/ddnz-ribbon-desktop-v1.webp')"}}><div className="mx-auto grid max-w-7xl items-center gap-10 lg:grid-cols-2"><div><a className="text-purple-800 underline" href={p+'/sourcing/restaurant-kitchen-packages-from-china/'}>{tx('s3')} ↗</a><p className="mt-8 font-bold text-purple-800">{tx('s4')}</p><h1 className="mt-5 text-4xl font-bold leading-tight md:text-5xl">{title}</h1><p className="mt-6 text-lg leading-8 text-[#65596b]">{tx('s5')}</p><div className="mt-8 flex flex-wrap gap-6"><a className="rounded-lg bg-[#c2492b] px-6 py-4 font-bold text-white" href="#package-rfq">{tx('s6')} →</a><a className="py-4 font-bold text-purple-800 underline" href="#small-kitchen-layout">{tx('s7')} ↓</a></div></div><figure><img src="/images/small-kitchen/rendering.webp" width="1175" height="1805" fetchPriority="high" alt={tx('s8')} className="max-h-[650px] w-full rounded-xl object-contain"/><figcaption className="mt-3 text-sm text-[#65596b]">{tx('s9')}</figcaption></figure></div></header>
 <div className="mx-auto max-w-7xl space-y-16 px-6 py-14">
 <section id="small-kitchen-layout" className="scroll-mt-28"><h2 className="text-3xl font-bold">{tx('s10')}</h2><p className="mt-4 leading-8 text-[#65596b]">{tx('s11')}</p><div className="mt-8"><div className="mb-5 flex gap-2 overflow-x-auto pb-3" aria-label={local.gallery[0]}>{images.map((image,i)=><button type="button" key={image[0]} aria-pressed={view===i} aria-controls="kitchen-plan-view" onClick={()=>setView(i)} className={'shrink-0 rounded-full px-5 py-3 text-sm font-bold transition-colors focus-visible:outline-2 focus-visible:outline-purple-800 '+(view===i?'bg-purple-800 text-white':'bg-purple-50 text-purple-800 hover:bg-purple-100')}>{local.images[i]}</button>)}</div><figure id="kitchen-plan-view" className="grid items-center gap-8 lg:grid-cols-[minmax(0,3fr)_minmax(220px,1fr)]"><a href={'/images/small-kitchen/'+images[view][0]+'.webp'} target="_blank" rel="noopener noreferrer" aria-label={local.gallery[1]} className="block overflow-hidden rounded-2xl bg-[#080909] p-4 shadow-[0_12px_40px_-22px_#71388955]"><img src={'/images/small-kitchen/'+images[view][0]+'.webp'} width={images[view][2]} height={images[view][3]} loading="lazy" alt={local.images[view]} className="mx-auto h-[min(72vh,760px)] min-h-[340px] w-full object-contain"/></a><figcaption className="py-4"><p className="text-sm font-bold tracking-widest text-purple-700"><bdi>{String(view+1).padStart(2,'0')} / 05</bdi></p><h3 className="mt-4 text-2xl font-bold">{local.images[view]}</h3><p className="mt-4 leading-7 text-[#65596b]">{local.gallery[4]}</p><a href={'/images/small-kitchen/'+images[view][0]+'.webp'} target="_blank" rel="noopener noreferrer" className="mt-5 inline-block font-bold text-purple-800 underline">{local.gallery[1]} ↗</a></figcaption></figure></div><p className="mt-5 text-sm leading-7 text-[#65596b]">{tx('s12')}</p></section>
 <section><h2 className="text-3xl font-bold">{tx('s13')}</h2><div className="mt-7 grid gap-x-10 md:grid-cols-2">{[0,1,2,3].map(i=><article key={i} className="border-t border-purple-200 py-7"><h3 className="text-xl font-bold">{local.zones[i*2]}</h3><p className="mt-4 leading-8 text-[#65596b]">{local.zones[i*2+1]}</p></article>)}</div></section>
 <section id="equipment-schedule"><h2 className="text-3xl font-bold">{tx('s14')}</h2><p className="mt-4 leading-8 text-[#65596b]">{tx('s15')}</p><div className="mt-6 overflow-x-auto rounded-xl border border-purple-100"><table className="w-full min-w-[660px] text-start"><thead className="bg-purple-50"><tr>{[tx('s16'),tx('s17'),tx('s18'),tx('s19')].map(x=><th key={x} className="p-4 text-start">{x}</th>)}</tr></thead><tbody>{smallKitchenSchedule.map(([id,cn,en,dim,qty],i)=><tr key={id} className="border-t border-purple-100"><th scope="row" className="p-4 text-start">{id}</th><td className="p-4">{local.equipment[i]}</td><td className="whitespace-nowrap p-4"><bdi>{dim}</bdi></td><td className="p-4"><bdi>{qty}</bdi></td></tr>)}</tbody></table></div><div className="mt-7 rounded-xl bg-purple-50 p-6"><p className="font-bold">{tx('s20')}</p><div className="mt-4 flex flex-wrap gap-3">{[tx('s21'),tx('s22'),tx('s23')].map(label=><a key={label} href="#package-rfq" onClick={()=>setTopic(label)} className="rounded-lg border border-purple-300 bg-white px-5 py-3 font-bold text-purple-800 hover:bg-purple-100 focus-visible:outline-2 focus-visible:outline-purple-800">{label} →</a>)}</div></div></section>
 <section className="grid gap-8 border-y border-purple-100 py-10 md:grid-cols-2"><h2 className="text-3xl font-bold">{tx('s24')}</h2><p className="leading-8 text-[#65596b]">{tx('s25')}</p></section>
 <section id="package-rfq" className="scroll-mt-28 rounded-xl bg-purple-50 p-7 md:p-10"><h2 className="text-3xl font-bold">{tx('s26')}</h2><p className="mt-4 leading-8">{tx('s27')}</p><p role="status" className="mt-4 font-bold text-purple-800">{topic ? tx('s28')+' '+topic : ''}</p><div className="my-6 grid gap-6 md:grid-cols-2"><label>{tx('s29')}<input value={dest} onChange={e=>setDest(e.target.value)} maxLength={160} className="mt-3 block w-full rounded-lg border border-purple-200 bg-white p-4"/></label><label>{tx('s30')}<textarea value={brief} onChange={e=>setBrief(e.target.value)} maxLength={1500} rows={4} className="mt-3 block w-full rounded-lg border border-purple-200 bg-white p-4"/></label></div><a href={quote} className="inline-block rounded-lg bg-purple-800 px-6 py-4 font-bold text-white">{tx('s31')} →</a><p className="mt-4 text-sm">{tx('s32')}</p></section>
 <nav className="flex flex-wrap gap-7 font-bold text-purple-800 underline" aria-label={tx('s33')}>{[['/sourcing/restaurant-kitchen-packages-from-china/cafe-light-meals/',tx('s34')],['/sourcing/commercial-kitchen-equipment-from-china/',tx('s35')],['/sourcing/commercial-ice-machines-from-china/',tx('s36')]].map(([url,label])=><a href={p+url} key={url}>{label} ↗</a>)}</nav>
 </div></main>;
}
