export const locationCopy = {
en: {
 eyebrow:'Sourcing in China', title:'Start with what you want to buy.',
 intro:'From our base in Guangzhou, we help you turn a product idea or supplier shortlist into a purchasing plan.',
 paragraphs:['A mixed order from Yiwu needs a different approach from a production order in Dongguan or Jinhua. For phone accessories in Shenzhen and Huaqiangbei, start with your model mix; for commercial kitchen equipment in Foshan, start with the equipment your business needs.', 'Whether you are looking for suppliers, comparing factory prices or arranging quality checks, share your product references, quantities and any supplier details. We can then agree the next steps for your order.'],
 links:[["Find suppliers & compare quotations", "Product requirements, samples and like-for-like factory offers."], ["Plan a quality check", "Set the checks and records you need before shipment."], ["Combine orders for export", "Bring supplier orders, packing lists and shipment plans together."]]
},
zh:{eyebrow:'中国采购',title:'从您想采购的产品开始。',intro:'立足广州，我们协助您把产品想法或供应商名单，整理成具体的采购计划。',paragraphs:['在义乌组合多个供应商的订单，与在东莞、金华寻找生产供应商，需要不同的采购安排。在深圳、华强北采购手机配件，可以从机型和款式组合开始；在佛山采购商用厨房设备，则从实际经营所需的设备清单开始。','无论是寻找供应商、比较工厂报价，还是安排质量检查，都可以先提供产品参考、数量及已有供应商信息，再一起确定订单的下一步。'],links:[["寻找供应商与比较报价", "明确产品要求，比较样品及相同条件下的工厂报价。"], ["安排质量检查", "确定出运前的检查项目及所需记录。"], ["安排集货与出口", "汇总供应商订单、装箱资料及出运安排。"]]},
es:{eyebrow:'Compras en China',title:'Empecemos por lo que quiere comprar.',intro:'Desde nuestra sede en Guangzhou, le ayudamos a convertir una idea de producto o una lista de proveedores en un plan de compras.',paragraphs:['Un pedido combinado de Yiwu requiere un enfoque distinto al de un pedido de fabricación en Dongguan o Jinhua. Para accesorios de móvil en Shenzhen y Huaqiangbei, parta de los modelos y estilos; para equipos de cocina profesional en Foshan, de las necesidades de su negocio.','Si busca proveedores, compara precios de fábrica o necesita un control de calidad, envíenos referencias de producto, cantidades y los datos de proveedores que ya tenga. Así podremos acordar los siguientes pasos.'],links:[["Buscar proveedores y comparar ofertas", "Requisitos, muestras y ofertas de fábrica comparables."], ["Organizar una inspección", "Defina los controles y registros necesarios antes del envío."], ["Consolidar pedidos para exportación", "Coordine pedidos, listas de empaque y planes de envío."]]},
fr:{eyebrow:'Achats en Chine',title:'Partons des produits que vous recherchez.',intro:'Depuis Guangzhou, nous vous aidons à transformer une idée de produit ou une liste de fournisseurs en un projet d’achat concret.',paragraphs:['Regrouper des commandes à Yiwu demande une approche différente d’une commande en fabrication à Dongguan ou Jinhua. Pour les accessoires de téléphone à Shenzhen et Huaqiangbei, partez des modèles et des styles ; pour une cuisine professionnelle à Foshan, des équipements nécessaires à votre activité.','Recherche de fournisseurs, comparaison des prix d’usine ou contrôle qualité : transmettez vos références produits, les quantités et les coordonnées des fournisseurs déjà identifiés. Nous pourrons ensuite convenir des prochaines étapes.'],links:[["Trouver des fournisseurs et comparer les devis", "Besoins produits, échantillons et offres d’usine comparables."], ["Préparer un contrôle qualité", "Définissez les vérifications et les documents attendus avant expédition."], ["Regrouper les commandes pour l’export", "Réunissez commandes fournisseurs, listes de colisage et transport."]]},
pt:{eyebrow:'Compras na China',title:'Comece pelo que você quer comprar.',intro:'A partir da nossa base em Guangzhou, ajudamos você a transformar uma ideia de produto ou uma lista de fornecedores em um plano de compras.',paragraphs:['Combinar pedidos de fornecedores em Yiwu exige uma abordagem diferente de encomendar a produção em Dongguan ou Jinhua. Para acessórios de celular em Shenzhen e Huaqiangbei, comece pelos modelos e estilos; para equipamentos de cozinha profissional em Foshan, pelas necessidades do seu negócio.','Para buscar fornecedores, comparar preços de fábrica ou organizar uma inspeção de qualidade, envie referências dos produtos, quantidades e os dados dos fornecedores que já tiver. Assim podemos definir os próximos passos do pedido.'],links:[["Encontrar fornecedores e comparar cotações", "Requisitos, amostras e propostas de fábrica nas mesmas condições."], ["Planejar uma inspeção", "Defina as verificações e os registros necessários antes do embarque."], ["Consolidar pedidos para exportação", "Reúna pedidos, listas de embalagem e planos de embarque."]]},
tr:{eyebrow:'Çin’den tedarik',title:'Almak istediğiniz ürünle başlayalım.',intro:'Guangzhou’daki merkezimizden, ürün fikrinizi veya tedarikçi listenizi bir satın alma planına dönüştürmenize yardımcı oluyoruz.',paragraphs:['Yiwu’daki farklı tedarikçilerden siparişleri birleştirmek, Dongguan veya Jinhua’da üretim siparişi vermekten farklı bir yaklaşım gerektirir. Shenzhen ve Huaqiangbei’de telefon aksesuarları için model ve çeşitlerle; Foshan’da ticari mutfak ekipmanları için işletmenizin ihtiyaçlarıyla başlayın.','Tedarikçi aramak, fabrika fiyatlarını karşılaştırmak veya kalite kontrolü planlamak için ürün örneklerini, miktarları ve varsa tedarikçi bilgilerini paylaşın. Ardından siparişinizin sonraki adımlarını birlikte belirleyebiliriz.'],links:[["Tedarikçi bulun, teklifleri karşılaştırın", "Ürün gereksinimleri, numuneler ve aynı koşullardaki fabrika teklifleri."], ["Kalite kontrolünü planlayın", "Sevkiyat öncesi kontrolleri ve gerekli kayıtları belirleyin."], ["İhracat için siparişleri birleştirin", "Tedarikçi siparişlerini, çeki listelerini ve sevkiyat planını bir araya getirin."]]},
ru:{eyebrow:'Закупки в Китае',title:'Начнём с того, что вы хотите купить.',intro:'Наша команда в Гуанчжоу поможет превратить идею продукта или список поставщиков в конкретный план закупки.',paragraphs:['Сборный заказ у поставщиков в Иу требует иного подхода, чем размещение производства в Дунгуане или Цзиньхуа. При закупке аксессуаров для телефонов в Шэньчжэне и Хуацянбэе начните с моделей и ассортимента, а кухонного оборудования в Фошане — с потребностей вашего предприятия.','Если вы ищете поставщиков, сравниваете заводские цены или планируете проверку качества, пришлите примеры товаров, количества и имеющиеся данные поставщиков. Затем мы согласуем следующие шаги по заказу.'],links:[["Найти поставщиков и сравнить предложения", "Требования, образцы и заводские цены на сопоставимых условиях."], ["Запланировать проверку качества", "Определите проверки и необходимые отчётные материалы до отгрузки."], ["Объединить заказы для экспорта", "Согласуйте заказы поставщиков, упаковочные листы и отправку."]]},
ar:{eyebrow:'الشراء من الصين',title:'لنبدأ بالمنتجات التي تريد شراءها.',intro:'من مقرنا في قوانغتشو، نساعدك على تحويل فكرة المنتج أو قائمة الموردين إلى خطة شراء واضحة.',paragraphs:['يختلف تجميع طلبات من عدة موردين في ييوو عن طلب التصنيع في دونغقوان أو جينهوا. عند شراء إكسسوارات الهواتف من شنتشن وهوا تشيانغ بي، ابدأ بالموديلات والتشكيلات المطلوبة؛ ولتجهيز المطابخ التجارية من فوشان، ابدأ بقائمة المعدات التي يحتاجها مشروعك.','سواء كنت تبحث عن موردين أو تقارن أسعار المصانع أو ترتب فحص الجودة، أرسل مراجع المنتجات والكميات وبيانات الموردين المتوفرة لديك. بعدها نتفق على الخطوات التالية لطلبك.'],links:[["البحث عن الموردين ومقارنة العروض", "متطلبات المنتجات والعينات وعروض المصانع بشروط قابلة للمقارنة."], ["ترتيب فحص الجودة", "حدد الفحوص والسجلات المطلوبة قبل الشحن."], ["تجميع الطلبات للتصدير", "تنسيق طلبات الموردين وقوائم التعبئة وخطة الشحن."]]}
} as const;
