import type { Language } from '../../i18n/translations';

export type SourcingServiceKind = 'supplier-search' | 'inspection-quality-control' | 'consolidation-export';

type ServiceCopy = {
  eyebrow: string;
  title: string;
  intro: string;
  useTitle: string;
  useCases: string[];
  outputTitle: string;
  outputs: string[];
  sequenceTitle: string;
  sequence: Array<{ title: string; body: string }>;
  boundaryTitle: string;
  boundary: string;
  cta: string;
};

export const serviceCopy: Record<SourcingServiceKind, Record<Language, ServiceCopy>> = {
  'supplier-search': {
    en: {
      eyebrow: 'Supplier search & comparison', title: 'Shortlist China suppliers against one comparable buying brief.',
      intro: 'DDNZ turns product references and market requirements into a structured brief, searches suitable manufacturers and normalizes quotations before a buyer chooses whom to sample or audit.',
      useTitle: 'Use this service when', useCases: ['You have a product photo or target model but no verified factory.', 'Supplier quotations use different specifications or inclusions.', 'You need a shortlist before samples, audit or negotiation.'],
      outputTitle: 'What you receive', outputs: ['A clarified product and market brief.', 'A comparable supplier and quotation matrix.', 'Open questions, evidence gaps and recommended next checks.'],
      sequenceTitle: 'From brief to shortlist', sequence: [
        { title: 'Define', body: 'Confirm use, destination, specification, quantity, budget and timing.' },
        { title: 'Search', body: 'Identify candidate manufacturers and check basic business identity and product fit.' },
        { title: 'Normalize', body: 'Align models, materials, accessories, terms and pack-out before comparing price.' },
        { title: 'Recommend', body: 'Present the shortlist, evidence gaps and sample or audit priorities.' },
      ],
      boundaryTitle: 'What the shortlist does not claim', boundary: 'A shortlist is an initial commercial and supplier-fit review. It does not replace a factory audit, sample approval, model-level compliance review or pre-shipment inspection.',
      cta: 'Start a supplier-search brief',
    },
    zh: {
      eyebrow: '供应商搜索与比价', title: '用统一采购需求筛选并比较中国供应商。',
      intro: 'DDNZ 将产品参考与目的市场要求整理成结构化采购需求，搜索适合的制造商，并统一报价口径，帮助买家决定后续打样、验厂或谈判对象。',
      useTitle: '适合以下情况', useCases: ['只有产品图片或目标型号，尚无已核验工厂。', '不同供应商报价的规格或包含项不一致。', '在打样、验厂或谈判前需要形成候选名单。'],
      outputTitle: '您将获得', outputs: ['明确的产品与市场采购需求。', '可横向比较的供应商与报价矩阵。', '待确认问题、证据缺口及下一步检查建议。'],
      sequenceTitle: '从需求到候选名单', sequence: [{ title: '定义', body: '确认用途、目的地、规格、数量、预算和时间。' }, { title: '搜索', body: '寻找候选制造商并初步核对企业身份与产品匹配度。' }, { title: '统一', body: '在比价前统一型号、材料、配件、条款和包装口径。' }, { title: '建议', body: '提交候选名单、证据缺口及打样或验厂优先级。' }],
      boundaryTitle: '候选名单不代表什么', boundary: '候选名单属于初步商务与供应商匹配审核，不能替代验厂、样品确认、具体型号合规审核或出货前验货。', cta: '提交供应商搜索需求',
    },
    ru: {
      eyebrow: 'Поиск и сравнение поставщиков', title: 'Сравните поставщиков из Китая по единому закупочному заданию.', intro: 'DDNZ формирует структурированный бриф, ищет подходящих производителей и приводит предложения к сопоставимому виду до выбора образцов или аудита.',
      useTitle: 'Когда услуга полезна', useCases: ['Есть фото или целевая модель, но нет проверенной фабрики.', 'Предложения поставщиков отличаются по комплектации.', 'Нужен шорт-лист перед образцами, аудитом или переговорами.'], outputTitle: 'Что вы получите', outputs: ['Уточненный продуктовый и рыночный бриф.', 'Сопоставимую матрицу поставщиков и предложений.', 'Открытые вопросы и рекомендуемые проверки.'], sequenceTitle: 'От брифа к шорт-листу', sequence: [{ title: 'Определить', body: 'Согласовать применение, рынок, спецификацию, объем, бюджет и сроки.' }, { title: 'Найти', body: 'Подобрать производителей и проверить базовую идентификацию.' }, { title: 'Сопоставить', body: 'Выровнять модели, материалы, аксессуары, условия и упаковку.' }, { title: 'Рекомендовать', body: 'Представить шорт-лист и приоритеты образцов или аудита.' }], boundaryTitle: 'Границы шорт-листа', boundary: 'Шорт-лист не заменяет аудит фабрики, утверждение образца, проверку соответствия модели или предотгрузочную инспекцию.', cta: 'Начать поиск поставщика',
    },
    fr: {
      eyebrow: 'Recherche et comparaison fournisseurs', title: 'Comparez les fournisseurs chinois sur un brief d’achat commun.', intro: 'DDNZ transforme vos références et exigences marché en brief structuré, recherche des fabricants adaptés et normalise les offres avant les échantillons ou l’audit.',
      useTitle: 'À utiliser lorsque', useCases: ['Vous avez une photo ou un modèle cible, sans usine vérifiée.', 'Les offres fournisseurs ne couvrent pas les mêmes spécifications.', 'Une présélection est nécessaire avant échantillon ou audit.'], outputTitle: 'Livrables', outputs: ['Brief produit et marché clarifié.', 'Matrice comparable fournisseurs et offres.', 'Questions ouvertes et contrôles recommandés.'], sequenceTitle: 'Du brief à la présélection', sequence: [{ title: 'Définir', body: 'Confirmer usage, destination, spécifications, volume, budget et délai.' }, { title: 'Rechercher', body: 'Identifier les fabricants et vérifier leur identité de base.' }, { title: 'Normaliser', body: 'Aligner modèles, matières, accessoires, conditions et emballage.' }, { title: 'Recommander', body: 'Présenter la sélection et les priorités d’échantillon ou d’audit.' }], boundaryTitle: 'Limites de la présélection', boundary: 'La présélection ne remplace pas un audit usine, la validation d’échantillon, la conformité du modèle ou l’inspection avant expédition.', cta: 'Démarrer la recherche fournisseur',
    },
    es: {
      eyebrow: 'Búsqueda y comparación de proveedores', title: 'Compare proveedores chinos con un único brief de compra.', intro: 'DDNZ convierte referencias y requisitos de mercado en un brief estructurado, busca fabricantes adecuados y normaliza las cotizaciones antes de elegir muestras o auditorías.',
      useTitle: 'Utilice este servicio cuando', useCases: ['Tiene una foto o modelo objetivo, pero no una fábrica verificada.', 'Las cotizaciones incluyen especificaciones diferentes.', 'Necesita una lista corta antes de muestras, auditoría o negociación.'], outputTitle: 'Qué recibe', outputs: ['Brief de producto y mercado aclarado.', 'Matriz comparable de proveedores y cotizaciones.', 'Preguntas abiertas y próximos controles recomendados.'], sequenceTitle: 'Del brief a la lista corta', sequence: [{ title: 'Definir', body: 'Confirmar uso, destino, especificaciones, cantidad, presupuesto y plazo.' }, { title: 'Buscar', body: 'Identificar fabricantes y revisar su identidad comercial básica.' }, { title: 'Normalizar', body: 'Alinear modelos, materiales, accesorios, condiciones y embalaje.' }, { title: 'Recomendar', body: 'Presentar la lista y prioridades de muestra o auditoría.' }], boundaryTitle: 'Límites de la lista corta', boundary: 'La lista corta no sustituye una auditoría de fábrica, aprobación de muestras, revisión de conformidad o inspección previa al envío.', cta: 'Iniciar búsqueda de proveedores',
    },
    ar: {
      eyebrow: 'البحث عن الموردين والمقارنة', title: 'قارن موردي الصين وفق موجز شراء واحد قابل للمقارنة.', intro: 'تحول DDNZ مراجع المنتج ومتطلبات السوق إلى موجز منظم، وتبحث عن مصنعين مناسبين وتوحد عروض الأسعار قبل اختيار العينات أو التدقيق.',
      useTitle: 'استخدم الخدمة عندما', useCases: ['لديك صورة أو نموذج مستهدف دون مصنع تم التحقق منه.', 'عروض الموردين تختلف في المواصفات أو الملحقات.', 'تحتاج قائمة مختصرة قبل العينات أو التدقيق أو التفاوض.'], outputTitle: 'ما الذي تستلمه', outputs: ['موجز واضح للمنتج والسوق.', 'مصفوفة قابلة للمقارنة للموردين والعروض.', 'الأسئلة المفتوحة والفحوص التالية المقترحة.'], sequenceTitle: 'من الموجز إلى القائمة', sequence: [{ title: 'التعريف', body: 'تأكيد الاستخدام والوجهة والمواصفات والكمية والميزانية والموعد.' }, { title: 'البحث', body: 'تحديد المصنعين والتحقق الأساسي من الهوية وملاءمة المنتج.' }, { title: 'التوحيد', body: 'مواءمة النماذج والمواد والملحقات والشروط والتعبئة.' }, { title: 'التوصية', body: 'عرض القائمة وأولويات العينات أو التدقيق.' }], boundaryTitle: 'حدود القائمة المختصرة', boundary: 'لا تحل القائمة محل تدقيق المصنع أو اعتماد العينة أو مراجعة امتثال النموذج أو فحص ما قبل الشحن.', cta: 'ابدأ طلب البحث عن مورد',
    },
    pt: { eyebrow: 'Busca e comparação de fornecedores', title: 'Compare fornecedores chineses com um único brief de compra.', intro: 'A DDNZ estrutura as referências e exigências do mercado, busca fabricantes e normaliza as cotações antes da escolha de amostras ou auditorias.', useTitle: 'Use este serviço quando', useCases: ['Você tem uma foto ou modelo, mas não uma fábrica verificada.', 'As cotações usam especificações ou itens diferentes.', 'Você precisa de uma lista curta antes de amostras, auditoria ou negociação.'], outputTitle: 'O que você recebe', outputs: ['Brief claro de produto e mercado.', 'Matriz comparável de fornecedores e cotações.', 'Perguntas abertas, lacunas e próximos controles.'], sequenceTitle: 'Do brief à lista curta', sequence: [{ title: 'Definir', body: 'Confirmar uso, destino, especificação, quantidade, orçamento e prazo.' }, { title: 'Buscar', body: 'Identificar fabricantes e verificar identidade e adequação básica.' }, { title: 'Normalizar', body: 'Alinhar modelos, materiais, acessórios, termos e embalagem.' }, { title: 'Recomendar', body: 'Apresentar a lista e prioridades de amostra ou auditoria.' }], boundaryTitle: 'O que a lista não comprova', boundary: 'A lista curta não substitui auditoria de fábrica, aprovação de amostra, análise de conformidade do modelo ou inspeção antes do embarque.', cta: 'Iniciar busca de fornecedores' },
    tr: { eyebrow: 'Tedarikçi arama ve karşılaştırma', title: 'Çin tedarikçilerini tek bir karşılaştırılabilir talebe göre değerlendirin.', intro: 'DDNZ ürün referanslarını ve pazar gerekliliklerini yapılandırır, uygun üreticileri arar ve numune veya denetim kararından önce teklifleri normalize eder.', useTitle: 'Bu hizmeti ne zaman kullanmalı', useCases: ['Ürün fotoğrafınız veya hedef modeliniz var ancak doğrulanmış fabrikanız yok.', 'Tedarikçi tekliflerinde özellikler veya dahil olanlar farklı.', 'Numune, denetim veya pazarlık öncesi kısa liste gerekiyor.'], outputTitle: 'Neler alırsınız', outputs: ['Netleştirilmiş ürün ve pazar talebi.', 'Karşılaştırılabilir tedarikçi ve teklif matrisi.', 'Açık sorular, kanıt açıkları ve sonraki kontroller.'], sequenceTitle: 'Talepten kısa listeye', sequence: [{ title: 'Tanımla', body: 'Kullanım, varış, özellik, miktar, bütçe ve zamanı onayla.' }, { title: 'Ara', body: 'Üreticileri belirle ve temel kimlik ile ürün uygunluğunu kontrol et.' }, { title: 'Normalize et', body: 'Fiyat öncesi model, malzeme, aksesuar, şart ve ambalajı hizala.' }, { title: 'Öner', body: 'Kısa listeyi ve numune veya denetim önceliklerini sun.' }], boundaryTitle: 'Kısa listenin sınırı', boundary: 'Kısa liste; fabrika denetimi, numune onayı, model düzeyi uygunluk incelemesi veya sevkiyat öncesi denetimin yerine geçmez.', cta: 'Tedarikçi arama talebi başlat' },
  },
  'inspection-quality-control': {
    en: {
      eyebrow: 'Inspection & quality control', title: 'Pre-shipment inspection and quality control in China.',
      intro: 'DDNZ converts approved specifications into an inspection checklist, coordinates on-site checks and returns traceable photo, quantity, function and packing evidence before release.',
      useTitle: 'Use this service when', useCases: ['Production is ready or approaching completion.', 'You need evidence tied to an approved model or sample.', 'Labels, accessories, functions or packing must be checked before release.'],
      outputTitle: 'What you receive', outputs: ['A scope-specific inspection checklist.', 'Photos and findings tied to the inspected model and quantity.', 'A release, rework or buyer-decision summary with open risks.'],
      sequenceTitle: 'From approval to evidence', sequence: [{ title: 'Freeze scope', body: 'Confirm model, approved sample, quantities, specifications and acceptance points.' }, { title: 'Prepare', body: 'Build the checklist and confirm readiness, location and available test conditions.' }, { title: 'Inspect', body: 'Check agreed quantity, identity, appearance, function, accessories, labels and packing.' }, { title: 'Report', body: 'Return findings, photos, exceptions and the decision still required.' }],
      boundaryTitle: 'Inspection has a defined scope', boundary: 'Inspection records what was observed under the agreed checklist and available conditions. It is not a laboratory certification, regulatory approval or guarantee of every unit unless separately specified.', cta: 'Start an inspection brief',
    },
    zh: {
      eyebrow: '验货与质量控制', title: '中国出货前验货与质量控制。', intro: 'DDNZ 将已确认规格转化为验货清单，协调现场检查，并在放货前提供可追溯的照片、数量、功能和包装证据。',
      useTitle: '适合以下情况', useCases: ['生产已完成或接近完成。', '需要与已确认型号或样品对应的证据。', '放货前必须检查标签、配件、功能或包装。'], outputTitle: '您将获得', outputs: ['针对本次订单的验货清单。', '与受检型号和数量对应的照片与发现。', '放货、返工或买家决策摘要及待处理风险。'], sequenceTitle: '从确认到证据', sequence: [{ title: '锁定范围', body: '确认型号、样品、数量、规格和验收点。' }, { title: '准备', body: '制定清单并确认完工状态、地点和可用测试条件。' }, { title: '检查', body: '核对数量、身份、外观、功能、配件、标签和包装。' }, { title: '报告', body: '提交发现、照片、异常及仍需决定的事项。' }], boundaryTitle: '验货具有明确范围', boundary: '验货记录约定清单及现场条件下观察到的情况，不等于实验室认证、法规批准或对每件产品的保证，除非另有明确约定。', cta: '提交验货需求',
    },
    ru: {
      eyebrow: 'Инспекция и контроль качества', title: 'Предотгрузочная инспекция и контроль качества в Китае.', intro: 'DDNZ превращает утвержденные требования в чек-лист, организует инспекцию и предоставляет фото, количество, функции и упаковку до выпуска товара.',
      useTitle: 'Когда услуга полезна', useCases: ['Производство завершено или близко к завершению.', 'Нужны доказательства по утвержденной модели или образцу.', 'До выпуска нужно проверить маркировку, аксессуары, функции или упаковку.'], outputTitle: 'Что вы получите', outputs: ['Чек-лист под конкретный заказ.', 'Фото и результаты по модели и количеству.', 'Резюме для выпуска, доработки или решения покупателя.'], sequenceTitle: 'От утверждения к доказательствам', sequence: [{ title: 'Зафиксировать', body: 'Подтвердить модель, образец, количество и критерии.' }, { title: 'Подготовить', body: 'Составить чек-лист и подтвердить готовность и условия проверки.' }, { title: 'Проверить', body: 'Проверить количество, идентичность, функции, аксессуары и упаковку.' }, { title: 'Отчитаться', body: 'Передать результаты, фото, отклонения и открытые решения.' }], boundaryTitle: 'Определенный объем инспекции', boundary: 'Инспекция фиксирует наблюдения по согласованному чек-листу. Это не лабораторная сертификация, разрешение регулятора или гарантия каждой единицы.', cta: 'Начать заявку на инспекцию',
    },
    fr: {
      eyebrow: 'Inspection et contrôle qualité', title: 'Inspection avant expédition et contrôle qualité en Chine.', intro: 'DDNZ transforme les spécifications approuvées en checklist, coordonne les contrôles sur site et fournit des preuves traçables avant libération.',
      useTitle: 'À utiliser lorsque', useCases: ['La production est terminée ou presque.', 'Les preuves doivent correspondre au modèle approuvé.', 'Étiquettes, accessoires, fonctions ou emballage doivent être contrôlés.'], outputTitle: 'Livrables', outputs: ['Checklist propre à la commande.', 'Photos et constats liés au modèle et à la quantité.', 'Synthèse de libération, reprise ou décision acheteur.'], sequenceTitle: 'De l’approbation aux preuves', sequence: [{ title: 'Figer', body: 'Confirmer modèle, échantillon, quantités et critères.' }, { title: 'Préparer', body: 'Créer la checklist et confirmer disponibilité et conditions de test.' }, { title: 'Inspecter', body: 'Contrôler identité, aspect, fonction, accessoires, étiquettes et emballage.' }, { title: 'Rapporter', body: 'Transmettre constats, photos, écarts et décisions ouvertes.' }], boundaryTitle: 'Un périmètre défini', boundary: 'L’inspection consigne les observations selon la checklist et les conditions disponibles. Elle ne constitue pas une certification laboratoire ou réglementaire.', cta: 'Démarrer un brief inspection',
    },
    es: {
      eyebrow: 'Inspección y control de calidad', title: 'Inspección previa al envío y control de calidad en China.', intro: 'DDNZ convierte las especificaciones aprobadas en una lista de inspección, coordina controles in situ y entrega pruebas trazables antes de liberar la mercancía.',
      useTitle: 'Utilice este servicio cuando', useCases: ['La producción está terminada o casi terminada.', 'Necesita evidencia ligada al modelo aprobado.', 'Debe revisar etiquetas, accesorios, funciones o embalaje.'], outputTitle: 'Qué recibe', outputs: ['Lista de inspección específica.', 'Fotos y hallazgos ligados al modelo y cantidad.', 'Resumen de liberación, retrabajo o decisión del comprador.'], sequenceTitle: 'De la aprobación a la evidencia', sequence: [{ title: 'Fijar', body: 'Confirmar modelo, muestra, cantidades y criterios.' }, { title: 'Preparar', body: 'Crear la lista y confirmar disponibilidad y condiciones de prueba.' }, { title: 'Inspeccionar', body: 'Revisar identidad, aspecto, función, accesorios, etiquetas y embalaje.' }, { title: 'Informar', body: 'Entregar hallazgos, fotos, excepciones y decisiones abiertas.' }], boundaryTitle: 'Alcance definido', boundary: 'La inspección registra lo observado según la lista y las condiciones disponibles. No es certificación de laboratorio, aprobación normativa ni garantía de cada unidad.', cta: 'Iniciar solicitud de inspección',
    },
    ar: {
      eyebrow: 'الفحص ومراقبة الجودة', title: 'فحص ما قبل الشحن ومراقبة الجودة في الصين.', intro: 'تحول DDNZ المواصفات المعتمدة إلى قائمة فحص وتنسق الفحص الميداني وتقدم أدلة قابلة للتتبع قبل الإفراج عن البضائع.',
      useTitle: 'استخدم الخدمة عندما', useCases: ['اكتمل الإنتاج أو اقترب من الاكتمال.', 'تحتاج أدلة مرتبطة بالنموذج أو العينة المعتمدة.', 'يجب فحص الملصقات أو الملحقات أو الوظائف أو التعبئة.'], outputTitle: 'ما الذي تستلمه', outputs: ['قائمة فحص خاصة بالطلب.', 'صور ونتائج مرتبطة بالنموذج والكمية.', 'ملخص للإفراج أو إعادة العمل أو قرار المشتري.'], sequenceTitle: 'من الاعتماد إلى الدليل', sequence: [{ title: 'تثبيت النطاق', body: 'تأكيد النموذج والعينة والكميات والمعايير.' }, { title: 'التحضير', body: 'إعداد القائمة وتأكيد الجاهزية وظروف الاختبار.' }, { title: 'الفحص', body: 'فحص الهوية والمظهر والوظيفة والملحقات والملصقات والتعبئة.' }, { title: 'التقرير', body: 'تقديم النتائج والصور والاستثناءات والقرارات المفتوحة.' }], boundaryTitle: 'نطاق فحص محدد', boundary: 'يسجل الفحص ما تمت ملاحظته وفق القائمة والظروف المتاحة، ولا يعد شهادة مختبر أو موافقة تنظيمية أو ضماناً لكل وحدة.', cta: 'ابدأ طلب الفحص',
    },
    pt: { eyebrow: 'Inspeção e controle de qualidade', title: 'Inspeção pré-embarque e controle de qualidade na China.', intro: 'A DDNZ transforma especificações aprovadas em checklist, coordena verificações no local e devolve evidências rastreáveis antes da liberação.', useTitle: 'Use este serviço quando', useCases: ['A produção está pronta ou quase pronta.', 'Você precisa de evidências ligadas ao modelo ou amostra aprovada.', 'Etiquetas, acessórios, funções ou embalagem precisam ser verificados.'], outputTitle: 'O que você recebe', outputs: ['Checklist específico do pedido.', 'Fotos e resultados ligados ao modelo e quantidade.', 'Resumo de liberação, retrabalho ou decisão do comprador.'], sequenceTitle: 'Da aprovação às evidências', sequence: [{ title: 'Fixar o escopo', body: 'Confirmar modelo, amostra, quantidades e critérios.' }, { title: 'Preparar', body: 'Criar o checklist e confirmar prontidão e condições de teste.' }, { title: 'Inspecionar', body: 'Verificar identidade, aparência, função, acessórios, etiquetas e embalagem.' }, { title: 'Reportar', body: 'Entregar resultados, fotos, exceções e decisões abertas.' }], boundaryTitle: 'A inspeção tem escopo definido', boundary: 'A inspeção registra o observado no checklist e condições disponíveis. Não é certificação de laboratório, aprovação regulatória ou garantia de cada unidade.', cta: 'Iniciar brief de inspeção' },
    tr: { eyebrow: 'Denetim ve kalite kontrol', title: 'Çin’de sevkiyat öncesi denetim ve kalite kontrolü.', intro: 'DDNZ onaylı özellikleri kontrol listesine dönüştürür, yerinde kontrolleri koordine eder ve serbest bırakmadan önce izlenebilir kanıtları sunar.', useTitle: 'Bu hizmeti ne zaman kullanmalı', useCases: ['Üretim tamamlandı veya tamamlanmak üzere.', 'Onaylı model veya numuneye bağlı kanıt gerekiyor.', 'Etiket, aksesuar, işlev veya ambalaj kontrol edilmeli.'], outputTitle: 'Neler alırsınız', outputs: ['Siparişe özel denetim listesi.', 'Denetlenen model ve miktara bağlı fotoğraf ve bulgular.', 'Serbest bırakma, düzeltme veya alıcı kararı özeti.'], sequenceTitle: 'Onaydan kanıta', sequence: [{ title: 'Kapsamı sabitle', body: 'Model, numune, miktar ve kabul noktalarını doğrula.' }, { title: 'Hazırla', body: 'Kontrol listesini oluştur ve hazır olma ile test koşullarını doğrula.' }, { title: 'Denetle', body: 'Kimlik, görünüm, işlev, aksesuar, etiket ve ambalajı kontrol et.' }, { title: 'Raporla', body: 'Bulguları, fotoğrafları, istisnaları ve açık kararları sun.' }], boundaryTitle: 'Denetimin tanımlı kapsamı vardır', boundary: 'Denetim, kararlaştırılan liste ve mevcut koşullarda gözleneni kaydeder. Laboratuvar sertifikası, mevzuat onayı veya her birim garantisi değildir.', cta: 'Denetim talebi başlat' },
  },
  'consolidation-export': {
    en: {
      eyebrow: 'Consolidation & export', title: 'Consolidation and export support in China for multi-supplier orders.',
      intro: 'DDNZ coordinates supplier readiness, receiving, count and packing checks, shipment reconciliation and the handoff to Heaven Born for international freight execution when engaged.',
      useTitle: 'Use this service when', useCases: ['Orders from several suppliers need one shipment.', 'Cartons, quantities and documents must be reconciled before booking.', 'You need one China-origin team to coordinate export readiness.'],
      outputTitle: 'What you receive', outputs: ['A supplier readiness and receiving status record.', 'A consolidated carton, quantity and document reconciliation.', 'A defined freight handoff with open exceptions visible.'],
      sequenceTitle: 'From supplier release to export', sequence: [{ title: 'Plan', body: 'Confirm suppliers, order status, cargo data, destination and required release checks.' }, { title: 'Receive', body: 'Coordinate delivery, count cartons and record visible condition or exceptions.' }, { title: 'Reconcile', body: 'Match orders, packing lists, carton marks, quantities and shipment documents.' }, { title: 'Handoff', body: 'Release the approved cargo scope for booking, loading and export execution.' }],
      boundaryTitle: 'Two accountable roles', boundary: 'DDNZ Global coordinates sourcing, supplier follow-up, receiving and trade-support records. Heaven Born International Freight executes international freight when included in the confirmed scope.', cta: 'Start a consolidation brief',
    },
    zh: {
      eyebrow: '集货与出口交付', title: '中国多供应商订单集货与出口协同。', intro: 'DDNZ 协调供应商完工、收货、数量与包装检查、出货核对；如委托国际货运，则交接给 Heaven Born 执行。',
      useTitle: '适合以下情况', useCases: ['多家供应商订单需要合并出运。', '订舱前必须核对纸箱、数量和单证。', '需要一个中国源头团队统一协调出口准备。'], outputTitle: '您将获得', outputs: ['供应商完工与收货状态记录。', '合并后的箱数、数量及单证核对。', '异常事项清晰可见的货运交接记录。'], sequenceTitle: '从供应商放货到出口', sequence: [{ title: '计划', body: '确认供应商、订单状态、货物数据、目的地和放货检查。' }, { title: '收货', body: '协调送仓、清点箱数并记录外观状态或异常。' }, { title: '核对', body: '匹配订单、装箱单、箱唛、数量与出货单证。' }, { title: '交接', body: '将已确认货物范围交付订舱、装载和出口执行。' }], boundaryTitle: '两个清晰责任主体', boundary: 'DDNZ Global 负责采购、供应商跟进、收货与贸易支持记录；确认范围包含国际货运时，由 Heaven Born International Freight 执行。', cta: '提交集货出口需求',
    },
    ru: {
      eyebrow: 'Консолидация и экспорт', title: 'Консолидация заказов и экспортная координация в Китае.', intro: 'DDNZ координирует готовность поставщиков, приемку, проверку количества и упаковки, сверку отправки и передачу Heaven Born для международной перевозки.',
      useTitle: 'Когда услуга полезна', useCases: ['Заказы нескольких поставщиков нужно объединить.', 'Перед бронированием нужно сверить коробки, количество и документы.', 'Нужна единая команда в Китае для экспортной готовности.'], outputTitle: 'Что вы получите', outputs: ['Статус готовности поставщиков и приемки.', 'Сверку коробок, количества и документов.', 'Определенную передачу перевозчику с открытыми исключениями.'], sequenceTitle: 'От выпуска поставщика к экспорту', sequence: [{ title: 'План', body: 'Подтвердить поставщиков, статус заказов, груз и проверки.' }, { title: 'Приемка', body: 'Координировать доставку, подсчитать коробки и отметить состояние.' }, { title: 'Сверка', body: 'Сопоставить заказы, упаковочные листы, маркировку и документы.' }, { title: 'Передача', body: 'Передать утвержденный груз на бронирование, погрузку и экспорт.' }], boundaryTitle: 'Две ответственные роли', boundary: 'DDNZ Global координирует закупки, поставщиков, приемку и торговые записи. Heaven Born выполняет международную перевозку, если она включена в объем.', cta: 'Начать заявку на консолидацию',
    },
    fr: {
      eyebrow: 'Consolidation et export', title: 'Consolidation des commandes et coordination export en Chine.', intro: 'DDNZ coordonne la disponibilité fournisseurs, la réception, le comptage, l’emballage, le rapprochement et la transmission à Heaven Born lorsque le fret est inclus.',
      useTitle: 'À utiliser lorsque', useCases: ['Plusieurs commandes fournisseurs doivent être regroupées.', 'Cartons, quantités et documents doivent être rapprochés.', 'Une équipe en Chine doit coordonner la préparation export.'], outputTitle: 'Livrables', outputs: ['Statut de disponibilité et réception.', 'Rapprochement cartons, quantités et documents.', 'Transmission fret définie avec exceptions visibles.'], sequenceTitle: 'De la libération fournisseur à l’export', sequence: [{ title: 'Planifier', body: 'Confirmer fournisseurs, commandes, données cargo et contrôles.' }, { title: 'Recevoir', body: 'Coordonner la livraison, compter et consigner l’état visible.' }, { title: 'Rapprocher', body: 'Comparer commandes, listes, marquages, quantités et documents.' }, { title: 'Transmettre', body: 'Libérer le périmètre approuvé pour réservation, chargement et export.' }], boundaryTitle: 'Deux rôles responsables', boundary: 'DDNZ Global coordonne sourcing, suivi fournisseur, réception et dossiers commerciaux. Heaven Born exécute le fret international lorsqu’il est inclus.', cta: 'Démarrer un brief consolidation',
    },
    es: {
      eyebrow: 'Consolidación y exportación', title: 'Consolidación de pedidos y coordinación de exportación en China.', intro: 'DDNZ coordina preparación de proveedores, recepción, recuento, embalaje, conciliación y entrega a Heaven Born cuando se contrata el transporte internacional.',
      useTitle: 'Utilice este servicio cuando', useCases: ['Los pedidos de varios proveedores deben enviarse juntos.', 'Hay que conciliar cajas, cantidades y documentos.', 'Necesita un equipo en China para coordinar la preparación de exportación.'], outputTitle: 'Qué recibe', outputs: ['Registro de preparación y recepción.', 'Conciliación de cajas, cantidades y documentos.', 'Entrega al transporte con excepciones visibles.'], sequenceTitle: 'De la liberación al envío', sequence: [{ title: 'Planificar', body: 'Confirmar proveedores, pedidos, carga y controles.' }, { title: 'Recibir', body: 'Coordinar la entrega, contar cajas y registrar su estado.' }, { title: 'Conciliar', body: 'Cotejar pedidos, listas, marcas, cantidades y documentos.' }, { title: 'Entregar', body: 'Liberar la carga aprobada para reserva, carga y exportación.' }], boundaryTitle: 'Dos funciones responsables', boundary: 'DDNZ Global coordina compras, proveedores, recepción y registros comerciales. Heaven Born ejecuta el transporte internacional cuando está incluido.', cta: 'Iniciar solicitud de consolidación',
    },
    ar: {
      eyebrow: 'التجميع والتصدير', title: 'تجميع الطلبات وتنسيق التصدير في الصين.', intro: 'تنسق DDNZ جاهزية الموردين والاستلام وعدّ الطرود وفحص التعبئة ومطابقة الشحنة والتسليم إلى Heaven Born عند تضمين الشحن الدولي.',
      useTitle: 'استخدم الخدمة عندما', useCases: ['يجب جمع طلبات عدة موردين في شحنة واحدة.', 'يجب مطابقة الطرود والكميات والمستندات قبل الحجز.', 'تحتاج فريقاً واحداً في الصين لتنسيق جاهزية التصدير.'], outputTitle: 'ما الذي تستلمه', outputs: ['سجل جاهزية الموردين والاستلام.', 'مطابقة موحدة للطرود والكميات والمستندات.', 'تسليم محدد للشحن مع إظهار الاستثناءات.'], sequenceTitle: 'من إفراج المورد إلى التصدير', sequence: [{ title: 'التخطيط', body: 'تأكيد الموردين وحالة الطلب وبيانات البضاعة والفحوص.' }, { title: 'الاستلام', body: 'تنسيق التسليم وعدّ الطرود وتسجيل الحالة الظاهرة.' }, { title: 'المطابقة', body: 'مطابقة الطلبات وقوائم التعبئة والعلامات والكميات والمستندات.' }, { title: 'التسليم', body: 'إطلاق نطاق البضاعة المعتمد للحجز والتحميل والتصدير.' }], boundaryTitle: 'دوران بمسؤولية واضحة', boundary: 'تنسق DDNZ Global الشراء ومتابعة الموردين والاستلام وسجلات الدعم التجاري، وتنفذ Heaven Born الشحن الدولي عند إدراجه في النطاق.', cta: 'ابدأ طلب التجميع',
    },
    pt: { eyebrow: 'Consolidação e exportação', title: 'Consolidação de pedidos e coordenação de exportação na China.', intro: 'A DDNZ coordena prontidão dos fornecedores, recebimento, contagem, embalagem, conciliação e entrega à Heaven Born quando o frete internacional está incluído.', useTitle: 'Use este serviço quando', useCases: ['Pedidos de vários fornecedores precisam seguir juntos.', 'Caixas, quantidades e documentos precisam ser conciliados.', 'Uma equipe na China deve coordenar a prontidão para exportação.'], outputTitle: 'O que você recebe', outputs: ['Registro de prontidão e recebimento.', 'Conciliação de caixas, quantidades e documentos.', 'Entrega ao frete com exceções visíveis.'], sequenceTitle: 'Da liberação do fornecedor à exportação', sequence: [{ title: 'Planejar', body: 'Confirmar fornecedores, pedidos, dados da carga e controles.' }, { title: 'Receber', body: 'Coordenar entrega, contar caixas e registrar a condição.' }, { title: 'Conciliar', body: 'Comparar pedidos, listas, marcas, quantidades e documentos.' }, { title: 'Entregar', body: 'Liberar a carga aprovada para reserva, carregamento e exportação.' }], boundaryTitle: 'Duas funções responsáveis', boundary: 'A DDNZ coordena sourcing, fornecedores, recebimento e registros. A Heaven Born executa o frete internacional quando incluído.', cta: 'Iniciar brief de consolidação' },
    tr: { eyebrow: 'Konsolidasyon ve ihracat', title: 'Çin’de sipariş konsolidasyonu ve ihracat koordinasyonu.', intro: 'DDNZ tedarikçi hazırlığını, teslim almayı, sayım ve ambalaj kontrollerini, sevkiyat uzlaştırmasını ve kapsamdaysa Heaven Born teslimini koordine eder.', useTitle: 'Bu hizmeti ne zaman kullanmalı', useCases: ['Birden fazla tedarikçinin siparişleri tek sevkiyatta birleşmeli.', 'Rezervasyon öncesi koli, miktar ve belgeler uzlaştırılmalı.', 'İhracat hazırlığını Çin’de tek ekip koordine etmeli.'], outputTitle: 'Neler alırsınız', outputs: ['Tedarikçi hazırlık ve teslim alma kaydı.', 'Konsolide koli, miktar ve belge uzlaştırması.', 'Açık istisnalarla tanımlı nakliye teslimi.'], sequenceTitle: 'Tedarikçi serbest bırakmadan ihracata', sequence: [{ title: 'Planla', body: 'Tedarikçileri, sipariş durumunu, yük verisini ve kontrolleri onayla.' }, { title: 'Teslim al', body: 'Teslimatı koordine et, kolileri say ve görünür durumu kaydet.' }, { title: 'Uzlaştır', body: 'Sipariş, çeki listesi, koli işareti, miktar ve belgeleri eşleştir.' }, { title: 'Teslim et', body: 'Onaylı yükü rezervasyon, yükleme ve ihracat için serbest bırak.' }], boundaryTitle: 'İki sorumlu rol', boundary: 'DDNZ tedarik, takip, teslim alma ve ticari kayıtları koordine eder. Uluslararası nakliye kapsamdaysa Heaven Born tarafından uygulanır.', cta: 'Konsolidasyon talebi başlat' },
  },
};
