import type { Language } from '../../i18n/translations';
export type AboutCopy = {
 nav: string; title: string; description: string; heading: string; intro: string;
 history: string; years: [string,string,string]; evidence: string;
 visit: string; visitBody: string; loading: string; loadingBody: string;
 trust: string; trustIntro: string; checks: [string,string][];
 caseTitle: string; caseBody: string; caseLink: string;
 process: string; services: string; freight: string; contact: string; final: string;
};
export const aboutCopy: Record<Language, AboutCopy> = {
 en: {
 nav:'About us', title:'About DDNZ Global | China Sourcing & Freight Team',
 description:'Meet the companies behind DDNZ: China product sourcing and export coordination, supported by HB international freight. View company records and real field work.',
 heading:'Your sourcing and freight team in China.',
 intro:'From Guangzhou, DDNZ works with overseas buyers on product sourcing, production coordination and export preparation. HB coordinates international freight. Two generations work across these businesses to connect purchasing decisions with shipment planning.',
 history:'Our background', years:['The team’s freight experience begins.','HB’s company is incorporated in Guangzhou.','DDNZ’s company is incorporated in Guangzhou.'],
 evidence:'A closer look at the work.', visit:'At the supplier’s showroom', visitBody:'Discussing speaker products with buyers and supplier representatives. Product requirements take shape through direct conversations and on-site review.',
 loading:'At the freight handoff', loadingBody:'A field record from a mobile-accessories shipment: checking the container door and seal during the handoff.',
 trust:'What to look for in a reliable China sourcing partner', trustIntro:'A company introduction is a starting point. Before choosing a sourcing agent, ask how the supplier decision, product checks and freight handoff will be handled for your order.',
 checks:[['Comparable supplier offers','Review supplier identity, product fit, included items and terms together. A low price alone does not settle the buying decision.'],['Checks tied to your order','Agree the sample or specification and inspection scope. Record findings, photos and unresolved issues before approving the next step.'],['A clear freight handoff','Connect carton quantities, packing records and the agreed transport scope. DDNZ handles the sourcing side; HB coordinates international freight.']],
 caseTitle:'A packing decision that changed a shipment.', caseBody:'In our Guangzhou–Abidjan speaker case, DDNZ and factory engineers planned shipment as parts for local assembly. For the first model, a 40HQ held 740 sets of parts instead of 637 complete speakers.', caseLink:'Read the speaker shipment case',
 process:'See how we work', services:'Explore sourcing services', freight:'Explore freight services', contact:'Discuss your sourcing needs', final:'Tell us what you are buying and where it needs to go.',
 },
 zh: {
 nav:'关于我们', title:'关于 DDNZ Global | 中国采购与国际货运团队',
 description:'了解 DDNZ 与 HB 的公司背景、中国采购与国际货运分工、登记信息及真实业务现场记录。',
 heading:'在中国，连接产品采购与国际运输。',
 intro:'DDNZ 在广州为海外客户协调产品采购、生产与出口准备，HB 负责国际货运。两代人分别负责贸易与货运业务，把采购决策和出运安排衔接起来。',
 history:'我们的业务背景',years:['团队开始从事货运业务。','HB 公司在广州登记成立。','DDNZ 公司在广州登记成立。'],
 evidence:'看看实际工作现场。',visit:'走进供应商展厅',visitBody:'与采购客户和供应商一起讨论音响产品，通过面对面交流和现场查看明确产品需求。',loading:'货物交接现场',loadingBody:'手机配件出运的现场记录：交接时查看集装箱箱门及封条。',
 trust:'选择可靠的中国采购合作方，需要看什么',trustIntro:'认识公司只是第一步。选择采购代理时，也应了解自己的订单将如何筛选供应商、安排产品检查，以及交接国际运输。',
 checks:[['让供应商报价可比较','把供应商身份、产品适配、包含项目和交易条款放在一起比较。单看低价，无法完成采购判断。'],['围绕具体订单安排检查','明确样品或规格及检查范围，在确认下一步之前记录结果、照片和未解决的问题。'],['明确采购与货运的交接','衔接箱数、包装记录和约定的运输范围。DDNZ 负责采购环节，HB 协调国际货运。']],
 caseTitle:'一个包装决定，改变了一票货的装载量。',caseBody:'在广州至阿比让的音响案例中，DDNZ 与工厂工程师根据客户当地组装条件设计散件出运方案。第一个型号的 40HQ 装载量从 637 台整机变为 740 套散件。',caseLink:'查看音响出运案例',process:'了解我们的工作流程',services:'查看采购服务',freight:'查看货运服务',contact:'讨论您的采购需求',final:'告诉我们您要采购什么，以及货物需要运往哪里。',
 },
 es: {
 nav:'Quiénes somos',title:'Sobre DDNZ Global | Equipo de compras y transporte en China',description:'Conozca DDNZ y HB: compras de productos en China, coordinación de exportaciones y transporte internacional. Consulte registros de empresa y trabajo sobre el terreno.',
 heading:'Su equipo de compras y transporte en China.',intro:'Desde Guangzhou, DDNZ ayuda a compradores internacionales con el abastecimiento, la coordinación de producción y la preparación de exportaciones. HB coordina el transporte internacional. Dos generaciones conectan las decisiones de compra con la planificación de los envíos.',history:'Nuestra trayectoria',years:['Comienza la experiencia del equipo en transporte.','La empresa HB se constituye en Guangzhou.','La empresa DDNZ se constituye en Guangzhou.'],
 evidence:'Nuestro trabajo sobre el terreno.',visit:'En la sala de exposición del proveedor',visitBody:'Conversaciones sobre altavoces con compradores y representantes del proveedor. Las visitas y el diálogo directo ayudan a concretar los requisitos.',loading:'En la entrega al transportista',loadingBody:'Registro de un envío de accesorios móviles: revisión de la puerta y el precinto del contenedor durante la entrega.',
 trust:'Qué buscar en un agente de compras fiable en China',trustIntro:'La presentación de la empresa es un punto de partida. Pregunte cómo se seleccionarán los proveedores, se revisarán los productos y se coordinará el transporte de su pedido.',checks:[['Ofertas comparables','Compare la identidad del proveedor, la adecuación del producto, los elementos incluidos y las condiciones. El precio más bajo no basta.'],['Revisiones vinculadas a su pedido','Acuerde la muestra o especificación y el alcance de la inspección. Documente resultados, fotografías y cuestiones pendientes.'],['Una entrega al transporte bien definida','Relacione cantidades, registros de embalaje y alcance del transporte. DDNZ gestiona las compras; HB coordina el transporte internacional.']],
 caseTitle:'Una decisión de embalaje que cambió un envío.',caseBody:'En nuestro caso de altavoces Guangzhou–Abiyán, DDNZ y los ingenieros de fábrica planificaron el envío de piezas para montaje local. Para el primer modelo, un 40HQ pasó de 637 altavoces completos a 740 juegos de piezas.',caseLink:'Ver el caso del envío de altavoces',process:'Cómo trabajamos',services:'Servicios de compras',freight:'Servicios de transporte',contact:'Cuéntenos qué necesita comprar',final:'Díganos qué quiere comprar y cuál es el destino.',
 },
 fr: {
 nav:'À propos',title:'À propos de DDNZ Global | Achats et transport en Chine',description:'Découvrez DDNZ et HB : sourcing en Chine, coordination des exportations et fret international. Consultez les registres des sociétés et nos activités sur le terrain.',
 heading:'Votre équipe de sourcing et de transport en Chine.',intro:'Depuis Guangzhou, DDNZ accompagne les acheteurs internationaux dans le sourcing, la coordination de production et la préparation des exportations. HB coordonne le fret international. Deux générations relient les décisions d’achat à la planification des expéditions.',history:'Notre parcours',years:['Début de l’expérience de l’équipe dans le transport.','La société HB est constituée à Guangzhou.','La société DDNZ est constituée à Guangzhou.'],
 evidence:'Notre travail sur le terrain.',visit:'Dans le showroom du fournisseur',visitBody:'Échanges sur des enceintes avec les acheteurs et les représentants du fournisseur. Les discussions et visites permettent de préciser les besoins.',loading:'Lors de la remise au transport',loadingBody:'Une photo prise lors d’une expédition d’accessoires mobiles : vérification de la porte et du scellé du conteneur lors de la remise.',
 trust:'Comment choisir un partenaire de sourcing fiable en Chine',trustIntro:'La présentation d’une entreprise est un point de départ. Demandez comment seront traités le choix du fournisseur, les contrôles produits et la remise au transport pour votre commande.',checks:[['Des offres comparables','Comparez l’identité du fournisseur, l’adéquation du produit, les éléments inclus et les conditions. Le prix seul ne suffit pas.'],['Des contrôles liés à votre commande','Convenez de l’échantillon ou des spécifications et du périmètre de contrôle. Consignez les résultats, photos et points non résolus.'],['Une remise au transport définie','Reliez quantités, relevés d’emballage et périmètre du transport. DDNZ gère le sourcing ; HB coordonne le fret international.']],
 caseTitle:'Un choix d’emballage qui a changé une expédition.',caseBody:'Dans notre cas d’enceintes Guangzhou–Abidjan, DDNZ et les ingénieurs de l’usine ont organisé un envoi en pièces pour assemblage local. Pour le premier modèle, un 40HQ est passé de 637 enceintes complètes à 740 ensembles de pièces.',caseLink:'Voir le cas d’expédition d’enceintes',process:'Notre méthode de travail',services:'Services de sourcing',freight:'Services de fret',contact:'Parlons de vos achats',final:'Dites-nous ce que vous achetez et où la marchandise doit arriver.',
 },
 pt: {
 nav:'Sobre nós',title:'Sobre a DDNZ Global | Compras e transporte na China',description:'Conheça a DDNZ e a HB: sourcing na China, coordenação de exportações e transporte internacional. Veja registros das empresas e trabalho em campo.',
 heading:'Sua equipe de sourcing e transporte na China.',intro:'De Guangzhou, a DDNZ apoia compradores internacionais no sourcing, na coordenação da produção e na preparação das exportações. A HB coordena o transporte internacional. Duas gerações conectam decisões de compra ao planejamento dos embarques.',history:'Nossa trajetória',years:['Começa a experiência da equipe em transporte.','A empresa HB é constituída em Guangzhou.','A empresa DDNZ é constituída em Guangzhou.'],
 evidence:'Nosso trabalho em campo.',visit:'No showroom do fornecedor',visitBody:'Conversas sobre caixas de som com compradores e representantes do fornecedor. Visitas e contato direto ajudam a definir os requisitos.',loading:'Na entrega para transporte',loadingBody:'Registro de um embarque de acessórios para celular: verificação da porta e do lacre do contêiner durante a entrega.',
 trust:'O que procurar em um parceiro de sourcing confiável na China',trustIntro:'A apresentação da empresa é um ponto de partida. Pergunte como serão conduzidas a escolha do fornecedor, as verificações dos produtos e a entrega ao transporte do seu pedido.',checks:[['Propostas comparáveis','Compare a identidade do fornecedor, a adequação do produto, os itens incluídos e as condições. O menor preço não basta.'],['Verificações ligadas ao seu pedido','Defina a amostra ou especificação e o escopo da inspeção. Registre resultados, fotos e questões pendentes.'],['Uma entrega ao transporte bem definida','Relacione quantidades, registros de embalagem e escopo do transporte. A DDNZ cuida do sourcing; a HB coordena o frete internacional.']],
 caseTitle:'Uma decisão de embalagem que mudou um embarque.',caseBody:'No caso de caixas de som Guangzhou–Abidjan, a DDNZ e os engenheiros da fábrica planejaram o envio de peças para montagem local. Para o primeiro modelo, um 40HQ passou de 637 unidades completas a 740 conjuntos de peças.',caseLink:'Ver o caso do embarque de caixas de som',process:'Como trabalhamos',services:'Serviços de sourcing',freight:'Serviços de transporte',contact:'Fale conosco sobre suas compras',final:'Conte o que deseja comprar e qual é o destino.',
 },
 ru: {
 nav:'О нас',title:'О DDNZ Global | Закупки и перевозки из Китая',description:'Познакомьтесь с DDNZ и HB: закупки в Китае, координация экспорта и международные перевозки. Регистрационные сведения и реальные рабочие материалы.',
 heading:'В Китае мы связываем закупки и перевозки.',intro:'Из Гуанчжоу DDNZ помогает зарубежным покупателям с закупками, координацией производства и подготовкой экспорта. HB координирует международные перевозки. Два поколения связывают решения о закупках с планированием отправки.',history:'Наша история',years:['Начало работы команды в грузоперевозках.','Компания HB зарегистрирована в Гуанчжоу.','Компания DDNZ зарегистрирована в Гуанчжоу.'],
 evidence:'Наша работа на местах.',visit:'В шоуруме поставщика',visitBody:'Обсуждение акустических систем с покупателями и представителями поставщика. Личные встречи и осмотр помогают уточнить требования.',loading:'При передаче груза',loadingBody:'Рабочий материал по отправке аксессуаров для телефонов: проверка двери и пломбы контейнера при передаче.',
 trust:'Как выбрать надёжного партнёра по закупкам в Китае',trustIntro:'Знакомство с компанией — первый шаг. Уточните, как для вашего заказа будут выбирать поставщика, проверять продукцию и передавать груз в перевозку.',checks:[['Сопоставимые предложения','Сравнивайте данные поставщика, соответствие продукции, комплектацию и условия. Низкая цена сама по себе не определяет выбор.'],['Проверки под ваш заказ','Согласуйте образец или спецификацию и объём инспекции. Фиксируйте результаты, фотографии и нерешённые вопросы.'],['Понятная передача груза','Сопоставляйте количество мест, упаковочные записи и условия перевозки. DDNZ ведёт закупки, HB координирует международную доставку.']],
 caseTitle:'Упаковочное решение, изменившее загрузку.',caseBody:'В кейсе поставки акустики Гуанчжоу–Абиджан DDNZ и инженеры фабрики спланировали отправку деталей для местной сборки. Для первой модели в 40HQ разместили 740 комплектов деталей вместо 637 готовых колонок.',caseLink:'Посмотреть кейс поставки акустики',process:'Как мы работаем',services:'Услуги по закупкам',freight:'Услуги перевозок',contact:'Обсудить закупку',final:'Расскажите, что вы закупаете и куда нужно доставить груз.',
 },
 tr: {
 nav:'Hakkımızda',title:'DDNZ Global Hakkında | Çin Tedarik ve Taşımacılık Ekibi',description:'DDNZ ve HB’yi tanıyın: Çin’de ürün tedariki, ihracat koordinasyonu ve uluslararası taşımacılık. Şirket kayıtlarını ve saha çalışmalarını inceleyin.',
 heading:'Çin’deki tedarik ve taşımacılık ekibiniz.',intro:'DDNZ, Guangzhou’dan uluslararası alıcılara ürün tedariki, üretim koordinasyonu ve ihracat hazırlığında destek verir. HB uluslararası taşımacılığı koordine eder. İki nesil, satın alma kararlarını sevkiyat planlarına bağlar.',history:'Geçmişimiz',years:['Ekibin taşımacılık deneyimi başlar.','HB şirketi Guangzhou’da kurulur.','DDNZ şirketi Guangzhou’da kurulur.'],
 evidence:'Sahadaki çalışmalarımız.',visit:'Tedarikçinin showroom’unda',visitBody:'Alıcılar ve tedarikçi temsilcileriyle hoparlör ürünlerinin görüşülmesi. Doğrudan iletişim ve yerinde inceleme, ihtiyaçları netleştirir.',loading:'Yükün tesliminde',loadingBody:'Telefon aksesuarları sevkiyatından bir saha kaydı: teslim sırasında konteyner kapısının ve mührünün kontrolü.',
 trust:'Çin’de güvenilir bir tedarik ortağı seçerken nelere bakılmalı?',trustIntro:'Şirketi tanımak ilk adımdır. Siparişiniz için tedarikçi seçiminin, ürün kontrollerinin ve taşımacıya teslimin nasıl yapılacağını sorun.',checks:[['Karşılaştırılabilir teklifler','Tedarikçi kimliğini, ürün uygunluğunu, dahil olan parçaları ve koşulları birlikte değerlendirin. Düşük fiyat tek başına yeterli değildir.'],['Siparişinize bağlı kontroller','Numuneyi veya teknik özellikleri ve denetim kapsamını belirleyin. Sonuçları, fotoğrafları ve açık konuları kaydedin.'],['Taşımacıya açık ve düzenli teslim','Koli adetlerini, ambalaj kayıtlarını ve taşıma kapsamını eşleştirin. DDNZ tedariki, HB uluslararası taşımacılığı koordine eder.']],
 caseTitle:'Bir sevkiyatı değiştiren ambalaj kararı.',caseBody:'Guangzhou–Abidjan hoparlör örneğimizde DDNZ ve fabrika mühendisleri, yerel montaj için parça sevkiyatı planladı. İlk modelde bir 40HQ, 637 tamamlanmış hoparlör yerine 740 hoparlörün montajı için parça setleri taşıdı.',caseLink:'Hoparlör sevkiyatı örneğini inceleyin',process:'Nasıl çalışıyoruz?',services:'Tedarik hizmetleri',freight:'Taşımacılık hizmetleri',contact:'Tedarik ihtiyacınızı görüşelim',final:'Ne satın almak istediğinizi ve varış noktasını anlatın.',
 },
 ar: {
 nav:'من نحن',title:'عن DDNZ Global | فريق التوريد والشحن من الصين',description:'تعرّف على DDNZ وHB: توريد المنتجات في الصين وتنسيق التصدير والشحن الدولي. اطّلع على سجلات الشركات والعمل الميداني.',
 heading:'في الصين، نربط توريد المنتجات بالشحن.',intro:'تساعد DDNZ من قوانغتشو المشترين الدوليين في توريد المنتجات وتنسيق الإنتاج وتجهيز التصدير. وتنسّق HB الشحن الدولي. يعمل جيلان على ربط قرارات الشراء بخطط الشحن.',history:'مسيرتنا',years:['بداية خبرة الفريق في الشحن.','تأسيس شركة HB في قوانغتشو.','تأسيس شركة DDNZ في قوانغتشو.'],
 evidence:'نظرة على عملنا الميداني.',visit:'في معرض المورّد',visitBody:'مناقشة مكبرات الصوت مع المشترين وممثلي المورّد. تساعد الزيارات والحوار المباشر على تحديد متطلبات المنتجات.',loading:'عند تسليم الشحنة',loadingBody:'سجل ميداني لشحنة ملحقات هواتف: التحقق من باب الحاوية والختم أثناء التسليم.',
 trust:'ما الذي تبحث عنه في شريك توريد موثوق في الصين؟',trustIntro:'التعرّف على الشركة هو البداية. اسأل كيف سيُختار المورّد وكيف ستُفحص المنتجات وتُسلَّم الشحنة للنقل في طلبك.',checks:[['عروض قابلة للمقارنة','قارن هوية المورّد وملاءمة المنتج والمكونات المشمولة والشروط. السعر المنخفض وحده لا يحسم قرار الشراء.'],['فحوص مرتبطة بطلبك','اتفق على العينة أو المواصفات ونطاق الفحص. سجّل النتائج والصور والمسائل غير المحسومة قبل الخطوة التالية.'],['تسليم واضح إلى فريق الشحن','اربط أعداد الطرود وسجلات التعبئة بنطاق النقل المتفق عليه. تتولى DDNZ التوريد وتنسّق HB الشحن الدولي.']],
 caseTitle:'قرار تعبئة غيّر حمولة الشحنة.',caseBody:'في حالة مكبرات الصوت من قوانغتشو إلى أبيدجان، خططت DDNZ مع مهندسي المصنع لشحن الأجزاء للتجميع المحلي. بالنسبة إلى الطراز الأول، استوعبت حاوية 40HQ عددًا من مجموعات الأجزاء يكفي لتجميع 740 مكبر صوت بدلاً من 637 مكبر صوت مكتمل.',caseLink:'اطّلع على حالة شحنة مكبرات الصوت',process:'كيف نعمل',services:'خدمات التوريد',freight:'خدمات الشحن',contact:'ناقش احتياجاتك من التوريد',final:'أخبرنا بما تريد شراءه والوجهة المطلوبة.',
 },
};
export const aboutLanguages = ['en','zh','es','fr','pt','ru','tr','ar'] as const;
const seoTitles: Record<Language,string> = {en:'About Us | China Sourcing & Freight Team',zh:'关于我们 | 中国采购与国际货运团队',es:'Quiénes somos | Compras y transporte en China',fr:'À propos | Achats et transport en Chine',pt:'Sobre nós | Compras e transporte na China',ru:'О нас | Закупки и перевозки из Китая',tr:'Hakkımızda | Çin Tedarik ve Taşımacılık Ekibi',ar:'من نحن | فريق التوريد والشحن من الصين'};
export const aboutMeta = (language: Language) => ({title:seoTitles[language],desc:aboutCopy[language].description,image:'/images/company/office/workspace-1600.webp',keywords:''});
