import React,{useState} from 'react';
import {refrigerationCopy,type RefrigerationLocale} from './copy';
import {foodPrefix} from '../food-processing/localization';
import {overviewCopy} from '../overview/copy';
const images=['upright-dg860l4-sanitized','counter-application-sanitized','display-range-sanitized','ice-maker-sd50f-spec'].map(n=>`/images/product-showcase/refrigeration/${n}.webp`);
const evidenceImages=['ice-maker-packout-source','ice-maker-warehouse-source','high-ambient-airflow-diagram'];
export default function RefrigerationContent({locale}:{locale:RefrigerationLocale}){
 const c=refrigerationCopy[locale],o=overviewCopy[locale],u=o.ui,prefix=foodPrefix(locale),[family,setFamily]=useState(0),[ready,setReady]=useState(false),[form,setForm]=useState({destination:'',temperature:'',capacity:'',cooling:'',stage:'',notes:''});
 const fields=[[u.category,c.families[family][0]],[u.destination,form.destination],[c.labels[0],form.temperature],[c.labels[1],form.capacity],[c.labels[2],form.cooling],[u.stage,form.stage],[u.notes,form.notes]].filter(([,v])=>v);
 const url=`${prefix}/get-a-quote/?`+new URLSearchParams({leadGoal:'Product Sourcing',source:'refrigeration_equipment_product',industry:c.families[family][0],overviewBrief:[c.title,...fields.map(([k,v])=>`${k}: ${v}`)].join('\n'),dest:form.destination,buyingStage:form.stage});
 const change=(k:keyof typeof form,v:string)=>{setForm(f=>({...f,[k]:v}));setReady(false);};
 return <main id="main-content" lang={locale==='zh'?'zh-CN':locale} dir={locale==='ar'?'rtl':'ltr'} className="bg-slate-50 text-slate-900"><div className="mx-auto max-w-7xl space-y-16 px-6 py-12"><header className="grid items-center gap-10 lg:grid-cols-2"><div><a className="text-purple-800 underline" href={`${prefix}/products/`}>{u.categories}</a><h1 className="mt-6 text-4xl font-bold leading-tight md:text-5xl">{c.title}</h1><p className="mt-6 text-lg leading-8">{c.intro}</p><a className="mt-7 inline-block rounded-xl bg-purple-800 px-5 py-3 font-bold text-white" href="#refrigeration-rfq">{u.quote}</a></div><img src={images[0]} alt={c.families[0][0]} width="1200" height="800" className="w-full rounded-2xl"/></header>
 <section id="refrigeration-range"><h2 className="text-3xl font-bold">{u.categories}</h2><div className="mt-7 grid gap-6 md:grid-cols-2">{c.families.map(([name,body],i)=><article className="overflow-hidden rounded-2xl border border-slate-200 bg-white" key={name}><img src={images[i]} alt={name} width="1000" height="1000" loading="lazy" className="aspect-square w-full object-contain"/><div className="space-y-5 p-6"><h3 className="text-xl font-bold">{name}</h3><p className="leading-7">{body}</p><button type="button" aria-pressed={family===i} className="font-bold text-purple-800 underline" onClick={()=>{setFamily(i);setReady(false);document.getElementById('refrigeration-rfq')?.scrollIntoView();}}>{u.scope}</button></div></article>)}</div></section>
 <section id="comparison"><h2 className="text-3xl font-bold">{u.compare}</h2><ol className="mt-7 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{c.checks.map((text,i)=><li className="rounded-xl bg-white p-6 leading-7" key={text}><span className="mb-3 block font-bold text-purple-700">0{i+1}</span>{text}</li>)}</ol></section>
 <section id="sample-control"><h2 className="text-3xl font-bold">{c.labels[4]}</h2><ol className="mt-7 grid gap-5 md:grid-cols-2">{c.steps.map((text,i)=><li className="rounded-xl border border-slate-200 p-6 leading-7" key={text}><span className="font-bold">0{i+1} · </span>{text}</li>)}</ol></section>
 <section id="factory-evidence"><h2 className="text-3xl font-bold">{c.labels[3]}</h2><div className="mt-7 grid gap-6 md:grid-cols-2"><figure className="rounded-xl bg-white p-4"><video controls muted playsInline preload="none" poster="/images/product-showcase/refrigeration/ice-maker-line-source.webp" aria-label={c.evidence[0]} className="aspect-video w-full bg-slate-900"><source src="/media/process/kitchen-production.mp4" type="video/mp4"/></video><figcaption className="mt-4 leading-7">{c.evidence[0]}</figcaption></figure>{evidenceImages.map((name,i)=><figure className="rounded-xl bg-white p-4" key={name}><img src={`/images/product-showcase/refrigeration/${name}.webp`} alt={c.evidence[i+1]} loading="lazy" width="1000" height="750" className="aspect-video w-full object-contain"/><figcaption className="mt-4 leading-7">{c.evidence[i+1]}</figcaption></figure>)}</div></section>
 <section id="refrigeration-rfq" className="scroll-mt-32 rounded-2xl bg-purple-50 p-7"><h2 className="text-3xl font-bold">{u.quote}</h2><p className="mt-4">{u.formIntro}</p>{!ready?<form className="mt-7 grid gap-5 md:grid-cols-2" onSubmit={e=>{e.preventDefault();setReady(true);}}><label>{u.category}<select className="mt-2 block w-full rounded-lg border p-3" name="family" value={family} onChange={e=>setFamily(Number(e.target.value))}>{c.families.map(([name],i)=><option key={name} value={i}>{name}</option>)}</select></label><label>{u.destination} *<input name="destination" className="mt-2 block w-full rounded-lg border p-3" value={form.destination} onChange={e=>change('destination',e.target.value)} required maxLength={160}/></label>{(['temperature','capacity','cooling'] as const).map((key,i)=><label key={key}>{c.labels[i]}<input name={key} className="mt-2 block w-full rounded-lg border p-3" value={form[key]} onChange={e=>change(key,e.target.value)} maxLength={400}/></label>)}<label>{u.stage} *<select name="stage" className="mt-2 block w-full rounded-lg border p-3" required value={form.stage} onChange={e=>change('stage',e.target.value)}><option value="">{u.select}</option>{u.stages.map(text=><option key={text}>{text}</option>)}</select></label><label>{u.notes}<input name="notes" className="mt-2 block w-full rounded-lg border p-3" value={form.notes} onChange={e=>change('notes',e.target.value)} maxLength={1500}/></label><button type="submit" className="rounded-xl bg-purple-800 px-5 py-3 font-bold text-white">{u.prepare}</button></form>:<div className="mt-7 space-y-5" role="status"><h3 className="text-xl font-bold">{u.ready}</h3><dl>{fields.map(([k,v])=><div className="my-4" key={k}><dt className="font-bold">{k}</dt><dd className="whitespace-pre-wrap break-words">{v}</dd></div>)}</dl><a className="inline-block rounded-xl bg-purple-800 px-5 py-3 font-bold text-white" href={url}>{u.continue}</a><button type="button" className="ms-5 text-purple-800 underline" onClick={()=>setReady(false)}>{u.edit}</button></div>}</section>
 <a className="text-purple-800 underline" href={`${prefix}/sourcing/commercial-ice-machines-from-china/`}>{c.families[3][0]}</a><p className="leading-7">{u.freight}</p><a className="text-purple-800 underline" href={`${prefix}/sourcing-services/`}>{u.services}</a></div></main>;
}
