#!/bin/bash
# Creates a small desktop wrapper. The wrapper calls the launcher in this
# repository, so it continues to use the latest committed launcher logic.

set -u

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd -P)"
START_SCRIPT="$SCRIPT_DIR/start-content-ops.sh"
DESKTOP_DIR="$HOME/Desktop"
DESKTOP_LAUNCHER="$DESKTOP_DIR/DDNZ Content Ops.command"

fail() {
  local message="$1"
  message="${message//\\n/$'\n'}"
  printf '\n%s\n\n' "$message" >&2
  /usr/bin/osascript - "DDNZ Content Ops" "$message" <<'APPLESCRIPT' >/dev/null 2>&1 || true
on run argv
  display dialog (item 2 of argv) with title (item 1 of argv) buttons {"OK"} default button "OK" with icon caution
end run
APPLESCRIPT
  if [[ -t 0 ]]; then
    printf 'Press Return to close this window. '
    read -r _unused || true
  fi
  exit 1
}

[[ "$(uname -s)" == "Darwin" ]] || fail "This installer is for macOS."
[[ -f "$PROJECT_DIR/package.json" ]] || fail "Could not locate the DDNZ project folder."
[[ -f "$START_SCRIPT" ]] || fail "The DDNZ launcher script is missing."
[[ -d "$DESKTOP_DIR" ]] || fail "The macOS Desktop folder was not found."

if [[ -e "$DESKTOP_LAUNCHER" ]] && [[ ! -f "$DESKTOP_LAUNCHER" ]]; then
  fail "Cannot install because this desktop item already exists and is not a file:\n$DESKTOP_LAUNCHER"
fi

tmp_launcher="${DESKTOP_LAUNCHER}.tmp.$$"
{
  printf '%s\n' '#!/bin/bash'
  printf '%s\n' '# DDNZ Content Ops desktop launcher — generated by install-desktop-launcher.command.'
  printf 'export DDNZ_CONTENT_OPS_PROJECT_DIR=%q\n' "$PROJECT_DIR"
  printf 'exec %q "$@"\n' "$START_SCRIPT"
} >"$tmp_launcher" || fail "Could not create the desktop launcher."

/bin/chmod 700 "$tmp_launcher" || fail "Could not make the desktop launcher executable."
/bin/mv -f "$tmp_launcher" "$DESKTOP_LAUNCHER" || fail "Could not install the desktop launcher."

printf 'Installed: %s\n\nDouble-click “DDNZ Content Ops.command” on your Desktop to launch the local content workspace.\n' "$DESKTOP_LAUNCHER"
/usr/bin/osascript - "DDNZ Content Ops" "Desktop launcher installed. Double-click DDNZ Content Ops.command on your Desktop to open the local content workspace." <<'APPLESCRIPT' >/dev/null 2>&1 || true
on run argv
  display dialog (item 2 of argv) with title (item 1 of argv) buttons {"OK"} default button "OK" with icon note
end run
APPLESCRIPT
