import { buildQuoteHref } from '../../lib/quoteLinks';
import BrazilPortGallery from './BrazilPortGallery';

export const brazilPortugueseMeta = {
  title: 'Frete da China para o Brasil: marítimo e aéreo | DDNZ',
  desc: 'Planeje frete da China para o Brasil: FCL, LCL, aéreo, consolidação de fornecedores e preparação dos documentos até a entrega acordada.',
  keywords: 'frete da China para o Brasil, frete marítimo China Brasil, carga consolidada da China, agenciamento de cargas China Brasil',
};
export const brazilPortugueseFaqs = [
  ['Quanto custa o frete da China para o Brasil?', 'O valor depende da origem, modalidade, descrição da mercadoria, dimensões, peso, data de disponibilidade e destino final. Peça uma proposta que separe coleta, despesas na China, transporte internacional e serviços no Brasil. Tributos e despesas locais precisam de escopo explícito.'],
  ['Qual é o prazo de transporte da China para o Brasil?', 'Solicite o itinerário e a previsão válidos para a carga e a data de embarque. Diferencie coleta, espera para embarque, trânsito internacional, liberação e entrega. Uma previsão de trânsito não é uma garantia de chegada ao endereço final.'],
  ['Posso consolidar pedidos de vários fornecedores chineses?', 'Sim, a viabilidade deve ser avaliada com a lista de fornecedores, datas, mercadorias e volumes. Confira quantidades e documentos por pedido, compatibilidade das cargas e condições de armazenagem antes de autorizar a consolidação.'],
  ['Preciso de CNPJ e de uma NCM definida para a operação?', 'Identifique o importador e confirme seus dados cadastrais e a classificação fiscal com o responsável pela importação no Brasil. Consulte o tratamento administrativo aplicável no Siscomex; o produto e a operação determinam as verificações necessárias.'],
  ['A cotação inclui desembaraço, impostos e entrega no Brasil?', 'Somente quando esses itens estiverem expressamente incluídos na proposta aceita. Confirme quem responde pela importação, pelo despacho, pelos tributos e pela retirada ou entrega. Não considere uma tarifa de transporte como preço final nacionalizado.'],
  ['Como importar máquinas de processamento de alimentos da China?', 'Antes de comprar, confirme modelo, capacidade, tensão, acessórios, peso e dimensões da embalagem. Alinhe com o importador os requisitos do equipamento e os documentos. Depois compare a coleta na fábrica e as opções FCL, LCL ou aéreas adequadas à carga.'],
];
const modes = [
  ['FCL: contêiner completo', 'Para avaliar um lote que ocupa um contêiner ou exige um plano próprio de carregamento. Informe volumes, peso por palete, acesso para coleta e necessidade de fixação.'],
  ['LCL: carga marítima consolidada', 'Para comparar o envio de lotes menores em espaço compartilhado. Avalie embalagem, manuseio, consolidação, desconsolidação e despesas no destino junto com o frete.'],
  ['Frete aéreo', 'Para peças, amostras e pedidos com maior urgência. A análise considera peso e dimensões, aceitação da mercadoria, documentos e disponibilidade do transporte.'],
];
export default function BrazilPortugueseContent() {
 const quote=buildQuoteHref({intent:'Freight Export',language:'pt',source:'brazil_pt_freight',destination:'Brasil'});
 const card='rounded-2xl border border-slate-200 bg-white p-6';
 return <main id="main-content" lang="pt-BR" className="bg-slate-50 text-slate-900">
  <header className="bg-slate-950 text-white"><div className="mx-auto max-w-7xl px-6 py-16 lg:py-24">
   <nav aria-label="Navegação estrutural" className="mb-8 text-sm text-slate-300"><a href="/pt/">Início</a><span aria-hidden="true"> / </span><a href="/pt/services/sea-freight/">Frete internacional</a><span aria-hidden="true"> / Brasil</span></nav>
   <p className="mb-5 text-sm font-bold tracking-widest text-orange-300">DDNZ GLOBAL · HEAVEN BORN</p>
   <h1 className="max-w-4xl text-4xl font-bold leading-tight md:text-6xl">Frete da China para o Brasil.</h1>
   <p className="mt-6 max-w-3xl text-lg leading-8 text-slate-200">Planeje transporte marítimo ou aéreo, consolidação de fornecedores na China e a entrega no Brasil dentro do escopo acordado. A DDNZ coordena compras e preparação na origem; a Heaven Born coordena o frete internacional.</p>
   <a href={quote} className="mt-8 inline-block rounded-xl bg-orange-700 px-6 py-4 font-bold text-white">Solicitar cotação para o Brasil →</a>
   <p className="mt-5 text-sm text-slate-300">Da coleta no fornecedor ao porto, aeroporto ou endereço combinado com o importador.</p>
  </div></header>
  <div className="mx-auto max-w-7xl space-y-16 px-6 py-16">
   <section aria-labelledby="br-modes"><h2 id="br-modes" className="text-3xl font-bold">Frete marítimo FCL, LCL ou aéreo?</h2><p className="mt-4 max-w-3xl leading-7">A modalidade depende do pedido e da entrega necessária. Compare o custo de toda a operação e as etapas de manuseio.</p><div className="mt-7 grid gap-5 md:grid-cols-3">{modes.map(([h,p])=><article className={card} key={h}><h3 className="text-xl font-bold">{h}</h3><p className="mt-4 leading-7">{p}</p></article>)}</div></section>
   <BrazilPortGallery/>
   <section aria-labelledby="br-route"><h2 id="br-route" className="text-3xl font-bold">Da cidade do fornecedor ao destino brasileiro</h2><div className="mt-7 grid gap-5 md:grid-cols-2"><article className={card}><h3 className="text-xl font-bold">Coleta e consolidação na China</h3><p className="mt-4 leading-7">Informe os endereços dos fornecedores em Guangzhou, Shenzhen, Yiwu ou outras cidades. Compare coleta, recebimento, inspeção e preparação das embalagens antes de escolher o porto de saída.</p><a className="mt-4 inline-block font-bold text-purple-800 underline" href="/pt/sourcing-services/consolidation-export/">Consolidação de pedidos e preparação para exportação →</a></article><article className={card}><h3 className="text-xl font-bold">Santos, São Paulo e o endereço de recebimento</h3><p className="mt-4 leading-7">Use Santos e a região de São Paulo como pontos para discutir o plano de recebimento. Para outro porto, aeroporto ou cidade, envie a localização final. Rota, conexão e transporte interno dependem da carga e da disponibilidade confirmada.</p><p className="mt-4 leading-7">Defina se o serviço termina no terminal, em um armazém ou no endereço do comprador, e quem organiza a retirada.</p></article></div></section>
   <section aria-labelledby="br-documents"><h2 id="br-documents" className="text-3xl font-bold">Documentos e responsabilidades antes do embarque</h2><ol className="mt-7 grid gap-5 md:grid-cols-3">{[
    ['1. Identificar o importador','Confirme razão social, dados cadastrais, CNPJ e responsáveis pela operação e pelo recebimento.'],
    ['2. Conferir mercadorias e documentos','Alinhe descrição, modelo, quantidade e valor na fatura comercial e na lista de volumes. Confirme NCM e eventuais exigências com o importador ou seu representante.'],
    ['3. Aprovar o escopo da entrega','Registre condições de transporte, despesas incluídas, responsabilidades, retirada e entrega antes da reserva.'],
   ].map(([h,p])=><li className={card} key={h}><h3 className="text-xl font-bold">{h}</h3><p className="mt-4 leading-7">{p}</p></li>)}</ol><p className="mt-5 leading-7">Para verificar o tratamento administrativo aplicável, consulte a <a className="font-bold text-purple-800 underline" href="https://www.gov.br/siscomex/pt-br/informacoes/tratamento-administrativos/tratamento-administrativo-na-importacao">orientação oficial do Siscomex</a> com o responsável pela importação.</p></section>
   <section id="country-cargo-planning" aria-labelledby="br-cargo"><h2 id="br-cargo" className="text-3xl font-bold">Comprar na China e organizar o frete para o Brasil</h2><div className="mt-7 grid gap-5 md:grid-cols-2"><article className={card}><h3 className="text-xl font-bold">Máquinas e equipamentos para alimentos</h3><p className="mt-4 leading-7">Confira capacidade, tensão elétrica, acessórios e embalagem antes de liberar a compra. Para transporte, envie peso bruto, dimensões da caixa, pontos de movimentação e instruções de fixação. O preço do equipamento não inclui automaticamente frete, tributos ou instalação.</p><a className="mt-4 inline-block font-bold text-purple-800 underline" href="/sourcing/food-processing-machinery-from-china/" hrefLang="en">Comparar máquinas de processamento de alimentos (catálogo em inglês) →</a></article><article className={card}><h3 className="text-xl font-bold">Pedidos mistos e eletrônicos</h3><p className="mt-4 leading-7">Separe cada modelo e fornecedor na lista de volumes. Declare baterias e outras características relevantes antes de solicitar o transporte. Não presuma que todas as mercadorias podem viajar juntas ou pela mesma modalidade.</p><a className="mt-4 inline-block font-bold text-purple-800 underline" href="/pt/sourcing-services/inspection-quality-control/">Inspeção e controle de qualidade na China →</a></article></div></section>
   <section aria-labelledby="br-faq"><h2 id="br-faq" className="text-3xl font-bold">Perguntas sobre envio da China para o Brasil</h2><div className="mt-7 grid gap-5 md:grid-cols-2">{brazilPortugueseFaqs.map(([q,a])=><article className={card} key={q}><h3 className="text-xl font-bold">{q}</h3><p className="mt-4 leading-7">{a}</p></article>)}</div></section>
   <section className="rounded-2xl bg-slate-900 p-8 text-white" aria-labelledby="br-quote"><h2 id="br-quote" className="text-3xl font-bold">Prepare uma cotação comparável</h2><p className="mt-4 max-w-3xl leading-7">Envie mercadoria e modelo, fornecedores e pontos de coleta, quantidade de volumes, dimensões, peso bruto, data de disponibilidade, destino final e serviços necessários. Se ainda faltarem dados, indique o que precisa ser confirmado.</p><a href={quote} className="mt-6 inline-block rounded-xl bg-orange-700 px-6 py-4 font-bold">Pedir cotação de frete China–Brasil →</a><div className="mt-6 flex flex-wrap gap-6"><a className="underline" href="/pt/services/lcl-shipping-from-china/">Conhecer o serviço LCL</a><a className="underline" href="/pt/how-we-work/">Como funciona o processo</a><a className="underline" href="/pt/sourcing-services/supplier-search/">Busca de fornecedores na China</a></div></section>
  </div>
 </main>;
}
