import { useState } from 'react';
import type { Language } from '../../i18n/translations';
import { CentralAsiaMap } from '../../components/FreightRouteMap';
import { freightPrefix } from './regions';
import OriginDestinationOpportunities from './OriginDestinationOpportunities';

const destinations = [
  { slug: 'kazakhstan', iso: 'KZ' }, { slug: 'uzbekistan', iso: 'UZ' }, { slug: 'kyrgyzstan', iso: 'KG' },
  { slug: 'tajikistan', iso: 'TJ' }, { slug: 'turkmenistan', iso: 'TM' }, { slug: 'russia', iso: 'RU' },
] as const;
type Copy = {
  home: string; freight: string; title: string; intro: string; select: string; country: string; cargo: string; mode: string;
  prompt: string; cargoOptions: string[]; modeOptions: string[]; open: string; quote: string; routes: string; map: string;
  mapNote: string; gateway: string; gatewayBody: string; papers: string; papersBody: string; consignee: string; consigneeBody: string;
  proof: string; proofHeading: string; wheel: string; wheelBody: string; road: string; roadBody: string; scope: string;
};
const content: Record<Language, Copy> = {
  en: { home: 'Home', freight: 'Freight services', title: 'China to Central Asia: choose the shipment, not a default country.', intro: 'Kazakhstan, Uzbekistan and neighboring markets do not share one border, clearance or delivery plan. Select your destination, cargo and mode before asking for a transit estimate.', select: 'BUILD YOUR ROUTE', country: 'Destination country', cargo: 'Cargo type', mode: 'Transport mode', prompt: 'Select a country', cargoOptions: ['General cargo', 'Heavy industrial parts', 'Consolidated multi-supplier cargo'], modeOptions: ['Compare road and rail', 'Cross-border road', 'Rail freight'], open: 'Open country route', quote: 'Request a route-specific quote', routes: 'COUNTRY ROUTES', map: 'Border gateways and destination cities', mapNote: 'The map locates gateways and cities; drawn corridors are illustrative. Border choice and timetable are confirmed against the actual cargo and service.', gateway: 'Border handling', gatewayBody: 'Rail gauge change and transfer capacity can affect the border dwell time. Ask which gateway and whether a fallback is available.', papers: 'Documents before dispatch', papersBody: 'Align product description, invoice, packing list and any required certification before the cargo reaches the border.', consignee: 'Importer and collection', consigneeBody: 'Confirm the local importer, customs party and whether handover ends at station, warehouse pickup or door.', proof: 'CHINA-SIDE FIELD RECORDS', proofHeading: 'Two real loads, two different planning questions.', wheel: 'Wheel hubs: heavy pallets', wheelBody: 'About 54 hubs per pallet, about 1,900 kg gross and 2.02 m³. Requested scope: destination clearance and notice for warehouse pickup in Kazakhstan or Uzbekistan.', road: 'Jiaozhou to Tashkent: road loading', roadBody: 'Cartons were checked, stacked with timber blocking and secured for a Khorgos–Tashkent road journey. These photos show origin loading, not destination arrival.', scope: 'The pictured records stop at China-side loading. Destination customs release and pickup require shipment-specific evidence.' },
  zh: { home: '首页', freight: '货运服务', title: '中国至中亚：先选具体货物和国家，而不是默认哈萨克斯坦。', intro: '哈萨克斯坦、乌兹别克斯坦及周边国家不能套用同一套口岸、清关和交付安排。先选目的国、货物与运输方式，再谈时效。', select: '组合你的路线', country: '目的国家', cargo: '货物类型', mode: '运输方式', prompt: '先选目的国', cargoOptions: ['普货', '重型工业零部件', '多供应商集货'], modeOptions: ['比较汽运与铁路', '跨境汽运', '铁路运输'], open: '查看国家路线', quote: '获取具体路线报价', routes: '国家线路', map: '口岸与目的城市', mapNote: '地图标注口岸与城市；连线仅作走廊示意。最终口岸和班期按具体货物与服务确认。', gateway: '口岸处理', gatewayBody: '铁路轨距换装与车板能力会影响口岸停留。询价时要问清具体口岸与备选方案。', papers: '发车前的单证', papersBody: '品名、发票、箱单和所需认证在货到口岸前核对一致。', consignee: '进口主体与提货', consigneeBody: '确认当地进口主体、清关责任，以及交付终点是车站、仓库自提还是到门。', proof: '中国端现场记录', proofHeading: '两票真实货物，两种不同的规划重点。', wheel: '轮毂：重货托盘', wheelBody: '一托约54件，毛重约1,900kg、体积约2.02m³。需求为哈萨克斯坦或乌兹别克斯坦清关后通知仓库自提。', road: '胶州至塔什干：汽运装车', roadBody: '纸箱装车前核对，木方分层阻挡并加固，经霍尔果斯发往塔什干。照片仅证明中国端装载。', scope: '照片证据止于中国端装车。目的地清关和自提需要具体运单的交接记录。' },
  ru: { home: 'Главная', freight: 'Грузовые услуги', title: 'Китай — Центральная Азия: выберите груз и страну, а не маршрут по умолчанию.', intro: 'Казахстан, Узбекистан и соседние рынки требуют разных переходов, оформления и схем выдачи. Укажите страну, груз и способ перевозки до оценки срока.', select: 'СОБРАТЬ МАРШРУТ', country: 'Страна назначения', cargo: 'Тип груза', mode: 'Вид транспорта', prompt: 'Выберите страну', cargoOptions: ['Обычный груз', 'Тяжёлые промышленные детали', 'Сборный груз поставщиков'], modeOptions: ['Сравнить авто и ЖД', 'Международное авто', 'Железная дорога'], open: 'Открыть маршрут', quote: 'Запросить расчёт', routes: 'МАРШРУТЫ ПО СТРАНАМ', map: 'Переходы и города назначения', mapNote: 'Карта показывает географию; линии — схема возможных коридоров. Переход и график уточняются по грузу.', gateway: 'Пограничная обработка', gatewayBody: 'Перегрузка из-за разной колеи и наличие платформ влияют на ожидание. Уточняйте переход и резервный вариант.', papers: 'Документы до отправки', papersBody: 'Согласуйте описание груза, счёт, упаковочный лист и сертификаты до прибытия к границе.', consignee: 'Импортёр и выдача', consigneeBody: 'Уточните местного импортёра и заканчивается ли услуга на станции, складе или у двери.', proof: 'ЗАПИСИ ПОГРУЗКИ В КИТАЕ', proofHeading: 'Два груза — два разных вопроса планирования.', wheel: 'Ступицы: тяжёлые паллеты', wheelBody: 'Около 54 штук, 1 900 кг брутто и 2,02 м³ на паллету. Запрос: оформление и выдача со склада в Казахстане или Узбекистане.', road: 'Цзяочжоу — Ташкент: автопогрузка', roadBody: 'Коробки проверены и закреплены брусом для перевозки через Хоргос. Фото подтверждают только погрузку в Китае.', scope: 'Фото не подтверждают оформление или выдачу в пункте назначения. Нужны записи по конкретной отправке.' },
  fr: { home: 'Accueil', freight: 'Services de fret', title: 'Chine–Asie centrale : choisissez le fret et le pays, pas une route par défaut.', intro: 'Kazakhstan, Ouzbékistan et marchés voisins n’ont pas les mêmes passages ni modalités de livraison. Précisez pays, fret et mode avant de demander un délai.', select: 'CONSTRUIRE L’ITINÉRAIRE', country: 'Pays de destination', cargo: 'Type de fret', mode: 'Mode de transport', prompt: 'Choisir un pays', cargoOptions: ['Fret général', 'Pièces industrielles lourdes', 'Groupage multi-fournisseurs'], modeOptions: ['Comparer route et rail', 'Route transfrontalière', 'Fret ferroviaire'], open: 'Voir la route pays', quote: 'Demander un devis', routes: 'ROUTES PAR PAYS', map: 'Passages et villes de destination', mapNote: 'La carte situe les points ; les lignes illustrent des corridors possibles. Passage et horaire sont confirmés selon le fret.', gateway: 'Traitement frontalier', gatewayBody: 'Le changement d’écartement et la disponibilité des wagons influent sur l’attente. Vérifier le passage et une option de secours.', papers: 'Documents avant départ', papersBody: 'Aligner désignation, facture, colisage et certifications avant l’arrivée à la frontière.', consignee: 'Importateur et retrait', consigneeBody: 'Confirmer l’importateur local et si la prestation se termine en gare, en entrepôt ou à domicile.', proof: 'DOSSIERS À L’ORIGINE CHINE', proofHeading: 'Deux chargements, deux points de planification.', wheel: 'Moyeux : palettes lourdes', wheelBody: 'Environ 54 unités, 1 900 kg brut et 2,02 m³ par palette. Demande : dédouanement et retrait en entrepôt au Kazakhstan ou en Ouzbékistan.', road: 'Jiaozhou–Tachkent : chargement routier', roadBody: 'Cartons contrôlés, calés par bois et arrimés pour la route via Khorgos. Les photos ne prouvent que le chargement en Chine.', scope: 'Ces photos ne prouvent ni dédouanement ni retrait à destination ; demander les pièces de l’envoi.' },
  es: { home: 'Inicio', freight: 'Servicios de carga', title: 'China–Asia Central: elige la carga y el país, no una ruta predeterminada.', intro: 'Kazajistán, Uzbekistán y mercados vecinos tienen pasos, despachos y entregas distintos. Indica destino, carga y modo antes de estimar el plazo.', select: 'CONFIGURAR RUTA', country: 'País de destino', cargo: 'Tipo de carga', mode: 'Modo de transporte', prompt: 'Elegir país', cargoOptions: ['Carga general', 'Piezas industriales pesadas', 'Consolidación de proveedores'], modeOptions: ['Comparar carretera y tren', 'Carretera transfronteriza', 'Ferrocarril'], open: 'Ver ruta del país', quote: 'Solicitar cotización', routes: 'RUTAS POR PAÍS', map: 'Pasos fronterizos y ciudades', mapNote: 'El mapa ubica nodos; las líneas son corredores ilustrativos. Paso y calendario se confirman por carga.', gateway: 'Operación fronteriza', gatewayBody: 'El cambio de ancho de vía y la disponibilidad de vagones afectan la espera. Pregunta por el paso y la alternativa.', papers: 'Documentos antes de salir', papersBody: 'Acordar descripción, factura, lista de empaque y certificaciones antes de llegar a la frontera.', consignee: 'Importador y retiro', consigneeBody: 'Confirmar el importador local y si termina en estación, almacén o domicilio.', proof: 'REGISTROS EN ORIGEN CHINA', proofHeading: 'Dos cargas, dos preguntas distintas.', wheel: 'Bujes: paletas pesadas', wheelBody: 'Unas 54 piezas, 1.900 kg brutos y 2,02 m³ por paleta. Solicitud: despacho y aviso de retiro en Kazajistán o Uzbekistán.', road: 'Jiaozhou–Taskent: carga vial', roadBody: 'Cajas revisadas, bloqueadas con madera y sujetas para el viaje vía Khorgos. Las fotos solo demuestran la carga en China.', scope: 'Las fotos no prueban despacho ni retiro en destino. Solicita registros del envío concreto.' },
  ar: { home: 'الرئيسية', freight: 'خدمات الشحن', title: 'الصين إلى آسيا الوسطى: اختر البضاعة والبلد، لا مساراً افتراضياً.', intro: 'تختلف كازاخستان وأوزبكستان والأسواق المجاورة في المعابر والتخليص والتسليم. حدد الوجهة والبضاعة والوسيلة قبل تقدير المدة.', select: 'كوّن مسارك', country: 'بلد الوجهة', cargo: 'نوع البضاعة', mode: 'وسيلة النقل', prompt: 'اختر البلد', cargoOptions: ['بضاعة عامة', 'قطع صناعية ثقيلة', 'تجميع موردين'], modeOptions: ['قارن البر والسكك', 'نقل بري عابر للحدود', 'شحن بالسكك'], open: 'افتح مسار البلد', quote: 'اطلب عرض سعر', routes: 'مسارات الدول', map: 'المعابر ومدن الوجهة', mapNote: 'الخريطة تحدد المواقع؛ الخطوط تمثل ممرات توضيحية. يؤكد المعبر والجدول حسب الشحنة.', gateway: 'إجراءات المعبر', gatewayBody: 'تؤثر عملية تغيير عربات القطار وتوافرها في مدة الانتظار. اسأل عن المعبر والبديل.', papers: 'المستندات قبل الشحن', papersBody: 'طابق وصف البضاعة والفاتورة وقائمة التعبئة والشهادات قبل وصولها للحدود.', consignee: 'المستورد والاستلام', consigneeBody: 'حدد المستورد المحلي وما إذا كان التسليم في المحطة أو المستودع أو العنوان.', proof: 'سجلات منشأ الصين', proofHeading: 'شحنتان وسؤالان مختلفان في التخطيط.', wheel: 'محاور العجلات: منصات ثقيلة', wheelBody: 'نحو 54 قطعة و1,900 كغ و2.02 م³ للمنصة. المطلوب التخليص والإخطار للاستلام في كازاخستان أو أوزبكستان.', road: 'جياوجو إلى طشقند: تحميل بري', roadBody: 'فُحصت الصناديق وثُبتت بأخشاب وأحزمة لمسار خورغوس. الصور تثبت التحميل في الصين فقط.', scope: 'الصور لا تثبت التخليص أو الاستلام في الوجهة. اطلب سجلات الشحنة المحددة.' },
  pt: { home: 'Início', freight: 'Serviços de frete', title: 'China–Ásia Central: escolha carga e país, não uma rota padrão.', intro: 'Cazaquistão, Uzbequistão e vizinhos exigem passagens e entregas distintas. Defina destino, carga e modo antes do prazo.', select: 'MONTE SUA ROTA', country: 'País de destino', cargo: 'Tipo de carga', mode: 'Modo de transporte', prompt: 'Escolha um país', cargoOptions: ['Carga geral', 'Peças industriais pesadas', 'Consolidação de fornecedores'], modeOptions: ['Comparar rodovia e ferrovia', 'Rodovia internacional', 'Ferrovia'], open: 'Ver rota do país', quote: 'Solicitar cotação', routes: 'ROTAS POR PAÍS', map: 'Passagens e cidades', mapNote: 'Os pontos são geolocalizados; linhas indicam corredores possíveis. Passagem e horário dependem da carga.', gateway: 'Operação na fronteira', gatewayBody: 'A troca de bitola e a capacidade ferroviária afetam a espera. Verifique a passagem e a alternativa.', papers: 'Documentos antes da partida', papersBody: 'Alinhe descrição, fatura, embalagem e certificados antes da fronteira.', consignee: 'Importador e retirada', consigneeBody: 'Confirme importador local e término no terminal, armazém ou endereço.', proof: 'REGISTROS NA CHINA', proofHeading: 'Duas cargas, duas decisões.', wheel: 'Cubos de roda: paletes pesados', wheelBody: 'Cerca de 54 unidades, 1.900 kg brutos e 2,02 m³ por palete. Escopo solicitado: desembaraço e retirada em armazém.', road: 'Jiaozhou–Tashkent: carregamento rodoviário', roadBody: 'Caixas conferidas, calçadas e amarradas para a rota via Khorgos. Fotos provam apenas o carregamento na China.', scope: 'Fotos não provam desembaraço ou retirada no destino. Peça registros da remessa.' },
  tr: { home: 'Ana sayfa', freight: 'Yük hizmetleri', title: 'Çin–Orta Asya: varsayılan rota değil, yükü ve ülkeyi seçin.', intro: 'Kazakistan, Özbekistan ve komşu pazarların sınır ve teslim planları farklıdır. Süre istemeden önce ülke, yük ve modu belirleyin.', select: 'ROTANIZI OLUŞTURUN', country: 'Varış ülkesi', cargo: 'Yük türü', mode: 'Taşıma türü', prompt: 'Ülke seçin', cargoOptions: ['Genel yük', 'Ağır sanayi parçaları', 'Tedarikçi konsolidasyonu'], modeOptions: ['Kara ve demiryolunu karşılaştır', 'Sınır ötesi karayolu', 'Demiryolu'], open: 'Ülke rotasını açın', quote: 'Teklif isteyin', routes: 'ÜLKE ROTALARI', map: 'Sınır geçitleri ve şehirler', mapNote: 'Konumlar koordinatlıdır; çizgiler olası koridorları gösterir. Geçit ve program yüke göre teyit edilir.', gateway: 'Sınır işlemleri', gatewayBody: 'Hat genişliği değişimi ve vagon kapasitesi beklemeyi etkiler. Geçidi ve alternatifi sorun.', papers: 'Sevk öncesi belgeler', papersBody: 'Ürün tanımı, fatura, koli listesi ve sertifikaları sınırdan önce eşleştirin.', consignee: 'İthalatçı ve teslim alma', consigneeBody: 'Yerel ithalatçıyı ve hizmetin istasyon, depo veya kapıda bitip bitmediğini doğrulayın.', proof: 'ÇİN ÇIKIŞ KAYITLARI', proofHeading: 'İki gerçek yük, iki planlama sorusu.', wheel: 'Tekerlek göbekleri: ağır palet', wheelBody: 'Palet başına yaklaşık 54 parça, 1.900 kg brüt ve 2,02 m³. İstenen kapsam: gümrük ve depodan alma bildirimi.', road: 'Jiaozhou–Taşkent: karayolu yüklemesi', roadBody: 'Kutular kontrol edilip ahşap ve kayışlarla Khorgos güzergâhı için sabitlendi. Fotoğraflar yalnızca Çin yüklemesini kanıtlar.', scope: 'Fotoğraflar varış gümrüğünü veya teslimi kanıtlamaz. Sevkiyata özel kayıtları isteyin.' },
};

const headline: Record<Language, string> = {
  en: 'Shipping from China to Central Asia and Russia.',
  zh: '中国到中亚五国及俄罗斯，按货物设计路线。',
  ru: 'Доставка из Китая в Центральную Азию и Россию.',
  fr: 'Expédier de Chine vers l’Asie centrale et la Russie.',
  es: 'Envíos de China a Asia Central y Rusia.',
  ar: 'الشحن من الصين إلى آسيا الوسطى وروسيا.',
  pt: 'Envio da China para a Ásia Central e Rússia.',
  tr: 'Çin’den Orta Asya ve Rusya’ya yük taşımacılığı.',
};
const overviewLabels: Record<Language, { region: string; preparation: string }> = {
  en: { region: 'Central Asia & Russia', preparation: 'PRE-DISPATCH' },
  zh: { region: '中亚五国及俄罗斯', preparation: '发车前确认' },
  ru: { region: 'Центральная Азия и Россия', preparation: 'ДО ОТПРАВКИ' },
  fr: { region: 'Asie centrale et Russie', preparation: 'AVANT LE DÉPART' },
  es: { region: 'Asia Central y Rusia', preparation: 'ANTES DE SALIR' },
  ar: { region: 'آسيا الوسطى وروسيا', preparation: 'قبل الإرسال' },
  pt: { region: 'Ásia Central e Rússia', preparation: 'ANTES DO ENVIO' },
  tr: { region: 'Orta Asya ve Rusya', preparation: 'SEVK ÖNCESİ' },
};

export function centralAsiaMetadata(locale: Language) {
  const c = content[locale];
  return { title: `${headline[locale]} | DDNZ Global`, desc: c.intro, keywords: '' };
}

export default function CentralAsiaOverviewContent({ locale }: { locale: Language }) {
  const c = content[locale];
  const overview = overviewLabels[locale];
  const prefix = freightPrefix(locale);
  const countryPrefix = prefix;
  const englishGuideLabel = '';
  const [country, setCountry] = useState('');
  const [cargo, setCargo] = useState('0');
  const [mode, setMode] = useState('0');
  const names = new Intl.DisplayNames([locale === 'zh' ? 'zh-CN' : locale], { type: 'region' });
  const quote = `${prefix}/get-a-quote/?leadGoal=Freight+Export&source=central_asia_route_builder&dest=${encodeURIComponent(country ? names.of(destinations.find(item => item.slug === country)?.iso || '') || country : overview.region)}&cargo=${encodeURIComponent(c.cargoOptions[Number(cargo)])}&mode=${encodeURIComponent(c.modeOptions[Number(mode)])}`;
  return <main id="main-content" className="freight-editorial freight-next freight-central-overview">
    <header className="freight-region-intro"><div className="freight-wrap">
      <nav className="freight-region-breadcrumb" aria-label="Breadcrumb"><a href={`${prefix}/`}>{c.home}</a><span>/</span><a href={`${prefix}/services/sea-freight/`}>{c.freight}</a><span>/</span><span aria-current="page">{overview.region}</span></nav>
      <p className="freight-kicker">{overview.region}</p><h1>{headline[locale]}</h1><p className="freight-intro">{c.intro}</p>
    </div></header>
    <section className="freight-wrap freight-section" aria-labelledby="route-builder-heading"><p className="freight-kicker">{c.select}</p><h2 id="route-builder-heading" className="mt-4">{c.select}</h2>
      <div className="freight-central-selector">
        <label>{c.country}<select value={country} onChange={event => setCountry(event.target.value)}><option value="">{c.prompt}</option>{destinations.map(item => <option key={item.slug} value={item.slug}>{names.of(item.iso)}</option>)}</select></label>
        <label>{c.cargo}<select value={cargo} onChange={event => setCargo(event.target.value)}>{c.cargoOptions.map((value, index) => <option key={value} value={index}>{value}</option>)}</select></label>
        <label>{c.mode}<select value={mode} onChange={event => setMode(event.target.value)}>{c.modeOptions.map((value, index) => <option key={value} value={index}>{value}</option>)}</select></label>
      </div><div className="freight-region-actions">{country && <a className="freight-cta" href={`${countryPrefix}/shipping-from-china-to-${country}/`}>{c.open}{englishGuideLabel && ` · ${englishGuideLabel}`} ↗</a>}<a href={quote}>{c.quote} ↗</a></div>
    </section>
    <section className="freight-region-map-section" aria-labelledby="central-map-heading"><div className="freight-wrap">
      <div className="freight-region-section-head"><p className="freight-kicker">01 / {c.map}</p><h2 id="central-map-heading">{c.map}</h2><p>{c.mapNote}</p></div>
      <figure className="freight-regional-map"><CentralAsiaMap language={locale} /></figure>
      <OriginDestinationOpportunities context="central-asia" locale={locale} />
    </div></section>
    <section className="freight-wrap freight-section"><p className="freight-kicker">02 / {c.routes}</p><div className="freight-central-country-grid">{destinations.map(item => <a key={item.slug} href={`${countryPrefix}/shipping-from-china-to-${item.slug}/`}><span>{item.iso}{englishGuideLabel && ` · ${englishGuideLabel}`}</span><h3>{names.of(item.iso)}</h3><span aria-hidden="true">↗</span></a>)}</div></section>
    <section className="freight-central-risk"><div className="freight-wrap freight-section"><p className="freight-kicker">03 / {overview.preparation}</p><div className="freight-steps">{[[c.gateway, c.gatewayBody], [c.papers, c.papersBody], [c.consignee, c.consigneeBody]].map(([title, body]) => <article key={title}><h3>{title}</h3><p>{body}</p></article>)}</div></div></section>
    <section className="freight-wrap freight-section"><p className="freight-kicker">04 / {c.proof}</p><h2 className="mt-4">{c.proofHeading}</h2>
      <div className="freight-central-cases"><article><img src="/images/operations/central-asia-wheel-hub-case-pallet.webp" alt={c.wheel} loading="lazy" /><div><h3>{c.wheel}</h3><p>{c.wheelBody}</p></div></article><article><img src="/images/operations/central-asia-uzbekistan-road-loading-overview.webp" alt={c.road} loading="lazy" /><div><h3>{c.road}</h3><p>{c.roadBody}</p></div></article></div>
      <p className="freight-region-evidence-note">{c.scope}</p><a className="freight-cta mt-8" href={quote}>{c.quote} ↗</a>
    </section>
  </main>;
}
