import type { Language } from '../../i18n/translations';

type OriginCopy = {
  kicker: string; heading: string; intro: string; south: string; east: string; north: string; inland: string;
};

const copy: Record<Language, OriginCopy> = {
  en: { kicker: 'CHINA ORIGIN OPTIONS', heading: 'Where in China is your cargo?', intro: 'The supplier city changes collection cost and the sensible departure port. These are ports to compare for your shipment, not a fixed sailing promise.', south: 'From Guangzhou or Shenzhen, compare Nansha, Yantian and Shekou once cargo details and vessel options are known.', east: 'For factories in Ningbo or Shanghai, compare the nearby terminals. Goods from Yiwu can be consolidated inland before evaluating Ningbo-Zhoushan or Shanghai.', north: 'From Qingdao or Tianjin, compare pickup distance, available service and the cargo-ready date before selecting a port.', inland: 'Yiwu is an inland sourcing and consolidation city, not a seaport.' },
  zh: { kicker: '中国起运选择', heading: '货在中国哪里？', intro: '供应商所在城市会影响提货成本和起运港。以下是按货物与船期进一步比较的港口选项，而非固定船期承诺。', south: '广州、深圳的货，可按货物和船期比较南沙、盐田、蛇口等码头。', east: '宁波、上海工厂可比较就近码头；义乌货先内陆集货，再评估宁波舟山港或上海港。', north: '青岛、天津的货，应比较提货距离、可用航线与货好日期，再确定起运港。', inland: '义乌是内陆采购和集货城市，不是海港。' },
  es: { kicker: 'ORIGEN EN CHINA', heading: '¿Dónde está la carga en China?', intro: 'La ciudad del proveedor afecta la recogida y el puerto conveniente. Compare opciones para cada envío; no es una salida garantizada.', south: 'Desde Guangzhou o Shenzhen, compare Nansha, Yantian y Shekou según la carga y el servicio disponible.', east: 'Desde Ningbo o Shanghái, compare terminales cercanas. La carga de Yiwu puede consolidarse tierra adentro antes de evaluar Ningbo-Zhoushan o Shanghái.', north: 'Desde Qingdao o Tianjin, compare la distancia de recogida, el servicio y la fecha de disponibilidad.', inland: 'Yiwu es una ciudad interior de compras y consolidación, no un puerto marítimo.' },
  ru: { kicker: 'ОТПРАВЛЕНИЕ ИЗ КИТАЯ', heading: 'Где находится груз в Китае?', intro: 'Город поставщика влияет на вывоз и выбор порта. Сравнивайте варианты для конкретного груза; это не гарантия рейса.', south: 'Для груза из Гуанчжоу или Шэньчжэня сравните Наньша, Яньтянь и Шэкоу с учетом груза и доступных рейсов.', east: 'Для Нинбо и Шанхая сравните близлежащие терминалы. Груз из Иу можно собрать внутри страны перед выбором Нинбо-Чжоушань или Шанхая.', north: 'Для Циндао и Тяньцзиня сравните расстояние вывоза, доступный сервис и дату готовности груза.', inland: 'Иу — внутренний центр закупок и консолидации, а не морской порт.' },
  fr: { kicker: 'ORIGINE EN CHINE', heading: 'Où se trouve votre marchandise ?', intro: 'La ville du fournisseur influe sur l’enlèvement et le port adapté. Comparez les options par expédition, sans garantie de départ.', south: 'Depuis Guangzhou ou Shenzhen, comparez Nansha, Yantian et Shekou selon la marchandise et les services disponibles.', east: 'Depuis Ningbo ou Shanghai, comparez les terminaux proches. Les biens d’Yiwu peuvent être groupés à l’intérieur du pays avant d’évaluer Ningbo-Zhoushan ou Shanghai.', north: 'Depuis Qingdao ou Tianjin, comparez la distance d’enlèvement, le service et la date de disponibilité.', inland: 'Yiwu est un centre intérieur d’achat et de groupage, pas un port maritime.' },
  ar: { kicker: 'المنشأ في الصين', heading: 'أين تقع بضاعتك في الصين؟', intro: 'تؤثر مدينة المورد في تكلفة الاستلام واختيار الميناء. قارن الخيارات لكل شحنة؛ فهي ليست وعداً بإبحار محدد.', south: 'للبضائع من قوانغتشو أو شنتشن، قارن نانشا ويانتيان وشيكو حسب نوع البضاعة والخدمة المتاحة.', east: 'لمصانع نينغبو أو شنغهاي، قارن المحطات القريبة. يمكن تجميع بضائع ييوو براً قبل تقييم نينغبو-تشوشان أو شنغهاي.', north: 'من تشينغداو أو تيانجين، قارن مسافة الاستلام والخدمة وتاريخ جاهزية البضاعة.', inland: 'ييوو مدينة داخلية للشراء والتجميع وليست ميناءً بحرياً.' },
  pt: { kicker: 'ORIGEM NA CHINA', heading: 'Onde está a carga na China?', intro: 'A cidade do fornecedor afeta coleta e porto de saída. Compare opções por remessa, sem promessa de escala fixa.', south: 'De Guangzhou ou Shenzhen, compare Nansha, Yantian e Shekou conforme a carga e os serviços disponíveis.', east: 'De Ningbo ou Xangai, compare terminais próximos. A carga de Yiwu pode ser consolidada no interior antes de avaliar Ningbo-Zhoushan ou Xangai.', north: 'De Qingdao ou Tianjin, compare distância de coleta, serviço e data de disponibilidade.', inland: 'Yiwu é um centro interior de compras e consolidação, não um porto marítimo.' },
  tr: { kicker: 'ÇİN ÇIKIŞ SEÇENEKLERİ', heading: 'Yükünüz Çin’in neresinde?', intro: 'Tedarikçinin şehri teslim alma maliyetini ve uygun limanı etkiler. Seçenekleri yük bazında karşılaştırın; bu sabit sefer vaadi değildir.', south: 'Guangzhou veya Shenzhen çıkışında yük ve sefer durumuna göre Nansha, Yantian ve Shekou’yu karşılaştırın.', east: 'Ningbo veya Şanghay’daki fabrikalar için yakın terminalleri karşılaştırın. Yiwu yükü önce iç bölgede konsolide edilip Ningbo-Zhoushan veya Şanghay değerlendirilebilir.', north: 'Qingdao veya Tianjin çıkışında alım mesafesini, mevcut servisi ve yükün hazır tarihini karşılaştırın.', inland: 'Yiwu deniz limanı değil, iç bölgede tedarik ve konsolidasyon merkezidir.' },
};

export default function ChinaOriginGuide({ locale, destination }: { locale: Language; destination: string }) {
  const c = copy[locale];
  const destinationLabel = locale === 'en' ? ` to ${destination}` : '';
  const names = locale === 'zh' ? ['广州 · 深圳', '宁波 · 上海 · 义乌', '青岛 · 天津'] : ['Guangzhou · Shenzhen', 'Ningbo · Shanghai · Yiwu', 'Qingdao · Tianjin'];
  return <div className="freight-china-origins" aria-labelledby="china-origins-heading">
    <div className="freight-china-origins-head"><div><p className="freight-kicker">{c.kicker}</p><h3 id="china-origins-heading">{c.heading}</h3></div><p>{c.intro}</p></div>
    <div className="freight-china-origin-grid">
      <article><span>01 / {{"en": ["SOUTH CHINA", "EAST CHINA", "NORTH CHINA"], "zh": ["华南", "华东", "华北"], "es": ["SUR DE CHINA", "ESTE DE CHINA", "NORTE DE CHINA"], "ar": ["جنوب الصين", "شرق الصين", "شمال الصين"], "ru": ["ЮГ КИТАЯ", "ВОСТОК КИТАЯ", "СЕВЕР КИТАЯ"], "fr": ["SUD DE LA CHINE", "EST DE LA CHINE", "NORD DE LA CHINE"], "pt": ["SUL DA CHINA", "LESTE DA CHINA", "NORTE DA CHINA"], "tr": ["GÜNEY ÇİN", "DOĞU ÇİN", "KUZEY ÇİN"]}[locale][0]}</span><h4>{names[0]}{destinationLabel}</h4><p>{c.south}</p></article>
      <article><span>02 / {{"en": ["SOUTH CHINA", "EAST CHINA", "NORTH CHINA"], "zh": ["华南", "华东", "华北"], "es": ["SUR DE CHINA", "ESTE DE CHINA", "NORTE DE CHINA"], "ar": ["جنوب الصين", "شرق الصين", "شمال الصين"], "ru": ["ЮГ КИТАЯ", "ВОСТОК КИТАЯ", "СЕВЕР КИТАЯ"], "fr": ["SUD DE LA CHINE", "EST DE LA CHINE", "NORD DE LA CHINE"], "pt": ["SUL DA CHINA", "LESTE DA CHINA", "NORTE DA CHINA"], "tr": ["GÜNEY ÇİN", "DOĞU ÇİN", "KUZEY ÇİN"]}[locale][1]}</span><h4>{names[1]}{destinationLabel}</h4><p>{c.east}</p></article>
      <article><span>03 / {{"en": ["SOUTH CHINA", "EAST CHINA", "NORTH CHINA"], "zh": ["华南", "华东", "华北"], "es": ["SUR DE CHINA", "ESTE DE CHINA", "NORTE DE CHINA"], "ar": ["جنوب الصين", "شرق الصين", "شمال الصين"], "ru": ["ЮГ КИТАЯ", "ВОСТОК КИТАЯ", "СЕВЕР КИТАЯ"], "fr": ["SUD DE LA CHINE", "EST DE LA CHINE", "NORD DE LA CHINE"], "pt": ["SUL DA CHINA", "LESTE DA CHINA", "NORTE DA CHINA"], "tr": ["GÜNEY ÇİN", "DOĞU ÇİN", "KUZEY ÇİN"]}[locale][2]}</span><h4>{names[2]}{destinationLabel}</h4><p>{c.north}</p></article>
    </div>
    <p className="freight-china-inland">{c.inland}</p>
  </div>;
}
