import { buildQuoteHref } from '../../lib/quoteLinks';
import { useLanguage } from '../../contexts/LanguageContext';
import { localizedProductPath } from '../../lib/productLocalization.mjs';

const cities: Record<string,string> = {
 'saudi-arabia':'Riyadh / Jeddah',uae:'Dubai / Abu Dhabi',kuwait:'Kuwait City',qatar:'Doha',oman:'Muscat',bahrain:'Manama',
 kazakhstan:'Almaty / Astana',uzbekistan:'Tashkent / Samarkand',kyrgyzstan:'Bishkek / Osh',tajikistan:'Dushanbe',turkmenistan:'Ashgabat',russia:'Moscow / Novosibirsk',
 nigeria:'Lagos / Abuja',ghana:'Accra / Kumasi',mexico:'Mexico City / Guadalajara',brazil:'São Paulo / Santos',argentina:'Buenos Aires',peru:'Lima / Callao',chile:'Santiago / San Antonio',
};
const copy = {
 en: {title:'Equipment, supplier orders and the final delivery address', equipment:(c:string)=>`Shipping food processing machinery from China to ${c}`, equipmentBody:'List each model, quantity, packed dimensions and gross weight. Confirm lifting points, crate protection, included motors and accessories; identify any batteries, liquids or restricted components before a freight review.', rail:'Rail or road freight from China: compare the complete route', sea:'FCL or LCL shipping from China: compare the complete scope', modeBody:'Compare pickup, consolidation, loading, destination handling and final delivery on the same cargo list. Availability and routing require confirmation for the commodity, date and receiving address; a mode name alone is not a delivery commitment.', address:'Port or terminal arrival is different from delivery to your address.', addressBody:'Examples of receiving locations to specify in your request:', addressNote:'Provide the actual address, unloading access and importer details. These examples do not establish a guaranteed route or local delivery coverage.', product:'Compare food processing machinery from China', kitchen:'Compare commercial kitchen equipment', service:'Multi-supplier consolidation and export support', quote:'Request a cargo-specific shipping plan'},
 zh:{title:'设备、多供应商订单与最终收货地址',equipment:(c:string)=>`食品加工机械从中国运输至${c}`,equipmentBody:'逐项提供型号、数量、包装尺寸和毛重。确认吊装位置、木箱防护、电机与随附配件；在货运审核前说明电池、液体或其他受限部件。',rail:'中国始发铁路或公路运输：比较完整路线',sea:'中国始发整柜或拼箱运输：比较完整服务范围',modeBody:'用同一份货物清单比较提货、集货、装载、目的地操作和最终交付。货类、出运时间及收货地址决定可接范围与路线，运输方式名称本身不构成交付承诺。',address:'到港、到站与送至收货地址是不同的服务范围。',addressBody:'询价时可明确的收货城市示例：',addressNote:'请提供实际地址、卸货条件及进口方资料。城市示例不代表已保证的班次或当地派送覆盖。',product:'比较中国食品加工机械',kitchen:'比较商用厨房设备',service:'多供应商集货与出口协同',quote:'按具体货物询运输方案'},
 es:{title:'Equipos, pedidos de proveedores y dirección final',equipment:(c:string)=>`Envío de maquinaria alimentaria desde China a ${c}`,equipmentBody:'Indique modelo, cantidad, dimensiones embaladas y peso bruto. Confirme puntos de elevación, protección, motores y accesorios; declare baterías, líquidos o componentes restringidos antes de revisar el transporte.',rail:'Transporte ferroviario o por carretera desde China: compare la ruta completa',sea:'Envíos FCL o LCL desde China: compare el alcance completo',modeBody:'Compare recogida, consolidación, carga, operaciones en destino y entrega con la misma lista. Disponibilidad y ruta dependen de mercancía, fecha y dirección; nombrar un modo no garantiza la entrega.',address:'Llegar al puerto o terminal no equivale a entregar en su dirección.',addressBody:'Ejemplos de destinos que puede indicar en su solicitud:',addressNote:'Facilite dirección real, acceso para descarga e importador. Los ejemplos no garantizan rutas ni cobertura local.',product:'Compare maquinaria alimentaria de China',kitchen:'Compare equipos de cocina comercial',service:'Consolidación de proveedores y apoyo a la exportación',quote:'Solicite un plan según su carga'},
 fr:{title:'Équipements, commandes fournisseurs et adresse finale',equipment:(c:string)=>`Transport de machines alimentaires depuis la Chine : ${c}`,equipmentBody:'Indiquez modèle, quantité, dimensions emballées et poids brut. Confirmez levage, protection, moteurs et accessoires ; signalez batteries, liquides et composants soumis à restrictions avant étude du fret.',rail:'Rail ou route depuis la Chine : comparer le trajet complet',sea:'Fret FCL ou LCL depuis la Chine : comparer tout le périmètre',modeBody:'Comparez enlèvement, consolidation, chargement, opérations à destination et livraison sur la même liste. Disponibilité et itinéraire dépendent du produit, de la date et de l’adresse ; le mode seul ne garantit pas la livraison.',address:'Une arrivée au port ou terminal ne vaut pas livraison à votre adresse.',addressBody:'Exemples de lieux de réception à préciser :',addressNote:'Indiquez adresse réelle, accès au déchargement et importateur. Ces exemples ne garantissent ni itinéraire ni couverture locale.',product:'Comparer les machines alimentaires de Chine',kitchen:'Comparer les équipements de cuisine professionnelle',service:'Consolidation fournisseurs et coordination export',quote:'Demander un plan adapté au fret'},
 ru:{title:'Оборудование, заказы поставщиков и адрес доставки',equipment:(c:string)=>`Доставка пищевого оборудования из Китая — ${c}`,equipmentBody:'Укажите модель, количество, размеры упаковки и вес брутто. Согласуйте точки подъема, защиту ящиков, двигатели и комплектующие; сообщите о батареях, жидкостях и ограниченных компонентах до проверки груза.',rail:'Железнодорожная или автомобильная доставка из Китая: сравните весь маршрут',sea:'Перевозка FCL или LCL из Китая: сравните полный состав услуги',modeBody:'Сравнивайте забор, консолидацию, погрузку, обработку в пункте назначения и доставку по единому списку груза. Доступность и маршрут подтверждаются по товару, дате и адресу; название транспорта не гарантирует доставку.',address:'Прибытие в порт или на терминал отличается от доставки по адресу.',addressBody:'Примеры городов получения для заявки:',addressNote:'Укажите точный адрес, условия разгрузки и импортера. Примеры не гарантируют маршрут или местную доставку.',product:'Сравнить пищевое оборудование из Китая',kitchen:'Сравнить оборудование для профессиональной кухни',service:'Консолидация заказов и экспортная координация',quote:'Запросить план по вашему грузу'},
 ar:{title:'المعدات وطلبات الموردين وعنوان التسليم النهائي',equipment:(c:string)=>`شحن آلات تجهيز الأغذية من الصين إلى ${c}`,equipmentBody:'حدد الطراز والكمية وأبعاد التغليف والوزن الإجمالي. أكد نقاط الرفع وحماية الصناديق والمحركات والملحقات، واذكر البطاريات والسوائل والمكونات المقيدة قبل مراجعة الشحن.',rail:'الشحن بالسكك أو الطرق من الصين: قارن المسار الكامل',sea:'شحن الحاويات الكاملة أو المشتركة من الصين: قارن النطاق الكامل',modeBody:'قارن الاستلام والتجميع والتحميل والمناولة في الوجهة والتسليم وفق قائمة بضائع واحدة. يتطلب المسار والتوفر تأكيد نوع البضاعة والتاريخ والعنوان؛ اسم الوسيلة وحده ليس التزاماً بالتسليم.',address:'الوصول إلى الميناء أو المحطة يختلف عن التسليم إلى عنوانك.',addressBody:'أمثلة لمواقع الاستلام التي يمكن تحديدها في الطلب:',addressNote:'قدم العنوان الفعلي وشروط التفريغ وبيانات المستورد. لا تضمن الأمثلة مساراً أو تغطية توصيل محلية.',product:'قارن آلات تجهيز الأغذية من الصين',kitchen:'قارن معدات المطابخ التجارية',service:'تجميع طلبات الموردين وتنسيق التصدير',quote:'اطلب خطة شحن حسب بضاعتك'},
};
export default function CountryCargoPlanning({country, countryName}:{country:string;countryName:string}) {
 const {language}=useLanguage(); const lang=language in copy ? language as keyof typeof copy : 'en'; const c=copy[lang];
 const rail=['kazakhstan','uzbekistan','kyrgyzstan','tajikistan','turkmenistan','russia'].includes(country);
 const prefix=language==='en'?'':`/${language==='zh'?'zh-cn':language}`;
 return <section className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8" aria-labelledby="country-cargo-planning" data-country-cargo-planning>
  <h2 id="country-cargo-planning" className="text-2xl font-bold text-slate-900">{c.title}</h2>
  <div className="mt-8 grid gap-8 md:grid-cols-3">
   <article><h3 className="text-lg font-bold">{c.equipment(countryName)}</h3><p className="mt-3 leading-7">{c.equipmentBody}</p><a className="mt-4 block underline" href="/sourcing/food-processing-machinery-from-china/" hrefLang="en">{c.product}</a><a className="mt-3 block underline" href={localizedProductPath('/sourcing/commercial-kitchen-equipment-from-china',language)}>{c.kitchen}</a></article>
   <article><h3 className="text-lg font-bold">{rail?c.rail:c.sea}</h3><p className="mt-3 leading-7">{c.modeBody}</p><a className="mt-4 block underline" href={`${prefix}/sourcing-services/consolidation-export/`}>{c.service}</a></article>
   <article><h3 className="text-lg font-bold">{c.address}</h3><p className="mt-3 leading-7">{c.addressBody} <span dir="ltr">{cities[country]}</span></p><p className="mt-3 leading-7">{c.addressNote}</p><a className="mt-4 block underline" href={buildQuoteHref({intent:'Freight Export',language,source:'country_cargo_planning',destination:countryName})}>{c.quote}</a></article>
  </div>
 </section>;
}
