import { dgInternationalCopy } from './dgInternationalCopy';
import type { LclExtraLocale } from './lclInternationalCopy';
export const internationalDgMetadata = (locale:LclExtraLocale) => ({title:`${dgInternationalCopy[locale].title} | DDNZ Global`,desc:dgInternationalCopy[locale].intro,keywords:''});
const images = ['carton-cargo-net-restraint','lithium-battery-pallet-lashing','dangerous-goods-drums-lashing','equipment-crate-blocking'];
const references = ['https://www.imo.org/en/ourwork/safety/pages/ctu-code.aspx','https://www.imo.org/en/ourwork/safety/pages/dangerousgoods-default.aspx','https://www.iata.org/lithiumbatteries'];
export default function DgInternationalContent({locale}:{locale:LclExtraLocale}) {
 const c = dgInternationalCopy[locale];
 const quote=`/${locale}/get-a-quote/?leadGoal=Freight+Export&source=dangerous_goods_shipping`;
 const base='/media/freight-additions-20260918/';
 return <main id="main-content" className="freight-editorial freight-next freight-dg-page" lang={locale} dir={locale==='ar'?'rtl':'ltr'}>
  <header className="freight-wrap freight-section"><p className="freight-kicker">DDNZ / HEAVEN BORN</p><h1 className="text-4xl font-black leading-tight md:text-6xl">{c.title}</h1><p className="freight-intro">{c.intro}</p><a className="freight-cta" href={quote}>{c.quote} ↗</a></header>
  <section className="freight-dark"><div className="freight-wrap freight-section"><h2 id="dangerous-goods-loading-title">{c.proofTitle}</h2><p className="freight-intro">{c.proofIntro}</p><div className="mt-10 grid gap-6 sm:grid-cols-2 lg:grid-cols-4">{c.cards.map(([title,detail],i)=><figure key={title}><a href={`/images/operations/${images[i]}-anonymized.webp`} target="_blank" rel="noreferrer" aria-label={`${c.open}: ${title}`}><img src={`/images/operations/${images[i]}-anonymized.webp`} alt={title} width={1090} height={1440} loading="lazy"/></a><figcaption><h3 className="text-xl font-bold">{title}</h3><p>{detail}</p></figcaption></figure>)}</div><h3 className="mt-10 text-xl font-bold">{c.noteTitle}</h3><p className="mt-4 leading-8">{c.note}</p><h3 className="mt-10 text-xl font-bold">{c.refs}</h3><p className="mt-4 leading-8">{c.refIntro}</p><ul className="mt-4 space-y-3">{references.map((href,i)=><li key={href}><a className="underline" href={href} target="_blank" rel="noreferrer">{c.refLabels[i]} ↗</a></li>)}</ul></div></section>
  <section id="specialist-field-records" className="freight-wrap freight-section"><h2>{c.records}</h2><div className="freight-drum-gallery">{c.drums.map((caption,i)=><figure key={caption}><a href={`${base}chemical-${i+1}.webp`} target="_blank" rel="noreferrer"><img src={`${base}chemical-${i+1}.webp`} alt={caption} width={1270} height={1700} loading="lazy"/></a><figcaption>{caption}</figcaption></figure>)}</div><div className="freight-arrival-films freight-arrival-three">{c.films.map((caption,i)=><figure key={caption}><video controls playsInline muted preload="none" poster={`${base}lithium-${i+1}.jpg`} src={`${base}lithium-${i+1}.mp4`} aria-label={caption}/><figcaption>{caption}</figcaption></figure>)}</div></section>
  <section id="dg-brief" className="freight-wrap freight-section"><h2>{c.briefTitle}</h2><ul className="mt-6 divide-y border-y border-slate-300">{c.items.map((item,i)=><li className="flex gap-5 py-5" key={item}><span>0{i+1}</span>{item}</li>)}</ul><p className="freight-intro">{c.scope}</p><a className="freight-cta" href={quote}>{c.quote} ↗</a></section>
 </main>;
}
