import type { LclExtraLocale } from './lclInternationalCopy';
type Copy = { title:string; intro:string; quote:string; proofTitle:string; proofIntro:string; cards:[string,string][]; noteTitle:string; note:string; records:string; drums:string[]; films:string[]; briefTitle:string; items:string[]; scope:string; refs:string; refIntro:string; refLabels:string[]; open:string };
export const dgInternationalCopy: Record<LclExtraLocale,Copy> = {
 ru:{
  title:'Перевозка опасных грузов из Китая и крепление в контейнере', intro:'Какие сведения нужны до отправки и как выглядят крепление, распорки и заполнение промежутков при разных видах упаковки: примеры с площадки погрузки.', quote:'Запросить перевозку опасного груза',
  proofTitle:'Крепление, распорки и заполнение промежутков', proofIntro:'Способ крепления зависит от прочности упаковки, распределения массы, свойств груза и маршрута. Прокладки, упоры и крепёж подбирают для конкретной отправки.',
  cards:[['Сетка по ширине дверного проёма','Сплошная удерживающая поверхность у дверей ограничивает смещение коробок в их сторону.'],['Перекрёстное крепление паллет','Сначала стабилизируют грузовую единицу, затем соединяют её с точками крепления контейнера.'],['Распорки и заполнение пустот','Штанги, ремни и заполнители совместно ограничивают продольное и поперечное перемещение.'],['Упоры для ящика с оборудованием','Упоры и боковую амортизацию располагают с учётом основания и центра тяжести.']],
  noteTitle:'Условия приёма опасного груза', note:'Приём зависит от номера UN, надлежащего отгрузочного наименования, класса, упаковки, документов, перевозчика и маршрута. Очерёдность погрузки определяется требованиями разделения, распределением массы и обработкой, а не одним универсальным правилом.',
  records:'От бочек до литиевых батарей: записи погрузки', drums:['Бочки внутри контейнера','Перемещение бочек погрузчиком','Бочки: вид от дверей'], films:['Литиевые батареи: перемещение и погрузка','Литиевые батареи: паллеты у дверей контейнера','Литиевые батареи: крепление и закрытие дверей'],
  briefTitle:'Приложите к запросу', items:['Наименование, назначение, номер UN и имеющийся MSDS','Вид упаковки, количество мест, размеры и масса брутто каждого места','Место отправления, назначение и дата готовности'], scope:'Сведения о грузе и маршрут определяют возможность приёма, варианты перевозки и объём предложения.',
  refs:'Источники по погрузке и опасным грузам', refIntro:'Материалы описывают общие принципы. Условия конкретной отправки проверяются по виду транспорта, свойствам груза и требованиям перевозчика.', refLabels:['Кодекс CTU: IMO / ILO / UNECE','Обзор Кодекса IMDG от IMO','Материалы IATA по перевозке батарей'],open:'Открыть фотографию'
 },
 fr:{
  title:'Transport de marchandises dangereuses depuis la Chine et arrimage', intro:'Consultez les informations nécessaires avant le départ et des photos d’arrimage, de calage et de remplissage des vides pour différents emballages.', quote:'Demander un transport de marchandises dangereuses',
  proofTitle:'Arrimage, calage et remplissage des vides', proofIntro:'La méthode dépend de la résistance de l’emballage, de la répartition du poids, des propriétés de la marchandise et de la route. Calage, blocage et arrimage sont définis pour chaque expédition.',
  cards:[['Filet sur toute la largeur','Une surface de retenue continue près des portes limite le déplacement des cartons vers celles-ci.'],['Palettes avec sangles croisées','Stabiliser chaque unité palettisée avant de la relier aux points d’arrimage du conteneur.'],['Calage et remplissage des vides','Barres, sangles et matériaux de remplissage limitent les mouvements longitudinaux et latéraux.'],['Caisse d’équipement bloquée','Blocage et protection latérale sont disposés selon la base et le centre de gravité.']],
  noteTitle:'Acceptation des marchandises dangereuses', note:'L’acceptation dépend du numéro UN, de la désignation officielle de transport, de la classe, de l’emballage, des documents, du transporteur et de la route. L’ordre de chargement suit les besoins de séparation, de répartition du poids et de manutention, pas une règle universelle.',
  records:'Des fûts aux batteries au lithium : opérations de chargement', drums:['Fûts dans le conteneur','Manutention des fûts au chariot élévateur','Fûts vus depuis les portes'], films:['Batteries au lithium : manutention et chargement','Batteries au lithium : palettes et portes du conteneur','Batteries au lithium : retenue et fermeture des portes'],
  briefTitle:'À joindre à votre demande', items:['Produit, usage, numéro UN et MSDS disponible','Type d’emballage, nombre de colis, dimensions et poids brut par colis','Origine, destination et date de disponibilité'], scope:'Les informations sur la marchandise et la route déterminent l’acceptation, les modes de transport et le périmètre du devis.',
  refs:'Références sur le chargement et les marchandises dangereuses', refIntro:'Ces documents expliquent les principes généraux. Chaque expédition reste soumise au mode de transport, aux propriétés de la marchandise et aux conditions du transporteur.', refLabels:['Code CTU : OMI / OIT / CEE-ONU','Présentation du Code IMDG par l’OMI','Documentation IATA sur les batteries'],open:'Voir la photo complète'
 },
 ar:{
  title:'شحن البضائع الخطرة من الصين وتثبيتها داخل الحاوية', intro:'تعرف على المعلومات المطلوبة قبل الإرسال، وشاهد صور الربط والتدعيم وملء الفراغات لأنواع مختلفة من التغليف.', quote:'اطلب شحن بضائع خطرة',
  proofTitle:'الربط والتدعيم وملء الفراغات', proofIntro:'تختلف طريقة التثبيت حسب قوة التغليف وتوزيع الوزن وخصائص البضاعة والمسار. تحدد الفواصل والدعامات والأربطة لكل شحنة على حدة.',
  cards:[['شبكة بعرض باب الحاوية','سطح تقييد متصل قرب الأبواب يحد من حركة الصناديق نحوها.'],['ربط متقاطع للمنصات','تثبت كل وحدة على المنصة أولاً ثم تربط بنقاط التثبيت داخل الحاوية.'],['تدعيم وملء الفراغات','تعمل القضبان والأربطة ومواد الملء معاً للحد من الحركة الطولية والجانبية.'],['تدعيم صندوق المعدات','توضع الدعامات والحماية الجانبية بحسب القاعدة ومركز الثقل.']],
  noteTitle:'شروط قبول البضائع الخطرة', note:'يعتمد القبول على رقم UN واسم الشحن الصحيح والفئة والتغليف والمستندات والناقل والمسار. ترتيب التحميل يتبع متطلبات الفصل وتوزيع الوزن والمناولة، وليس قاعدة واحدة ثابتة.',
  records:'من البراميل إلى بطاريات الليثيوم: مشاهد التحميل', drums:['البراميل داخل الحاوية','مناولة البراميل بالرافعة الشوكية','البراميل من جهة الباب'], films:['بطاريات الليثيوم: المناولة والتحميل','بطاريات الليثيوم: المنصات وباب الحاوية','بطاريات الليثيوم: التثبيت وإغلاق الأبواب'],
  briefTitle:'أرفق هذه البيانات مع الاستفسار', items:['اسم المنتج واستخدامه ورقم UN وورقة MSDS المتاحة','نوع التغليف وعدد الطرود وأبعاد ووزن كل طرد الإجمالي','المنشأ والوجهة وتاريخ جاهزية البضاعة'], scope:'تحدد بيانات البضاعة والمسار إمكانية القبول وخيارات النقل ونطاق عرض السعر.',
  refs:'مراجع التحميل والبضائع الخطرة', refIntro:'تشرح هذه المراجع المبادئ العامة. يجب تأكيد كل شحنة بحسب وسيلة النقل وخصائص البضاعة وشروط الناقل.', refLabels:['مدونة CTU للمنظمة البحرية ومنظمة العمل ولجنة الأمم المتحدة الاقتصادية لأوروبا','نظرة عامة على مدونة IMDG من المنظمة البحرية الدولية','إرشادات IATA لنقل البطاريات'],open:'عرض الصورة كاملة'
 },
 pt:{
  title:'Transporte de cargas perigosas da China e fixação em contêiner', intro:'Consulte os dados necessários antes do embarque e fotos de amarração, travamento e preenchimento de espaços para diferentes embalagens.', quote:'Consultar transporte de carga perigosa',
  proofTitle:'Amarração, travamento e preenchimento de espaços', proofIntro:'A fixação varia conforme resistência da embalagem, distribuição de peso, propriedades da carga e rota. Apoios, bloqueios e amarrações são definidos para cada embarque.',
  cards:[['Rede em toda a largura','Uma superfície contínua de contenção junto às portas reduz o movimento das caixas nessa direção.'],['Paletes com amarração cruzada','Estabiliza-se cada unidade paletizada antes de conectá-la aos pontos de fixação do contêiner.'],['Travamento e preenchimento','Barras, cintas e materiais de preenchimento limitam movimentos longitudinais e laterais.'],['Caixote de equipamento travado','Bloqueios e proteção lateral são dispostos conforme a base e o centro de gravidade.']],
  noteTitle:'Aceitação de cargas perigosas', note:'A aceitação depende do número UN, nome apropriado para embarque, classe, embalagem, documentos, transportador e rota. A ordem de carregamento segue segregação, distribuição de peso e manuseio, não uma regra universal.',
  records:'De tambores a baterias de lítio: registros de carregamento', drums:['Tambores dentro do contêiner','Movimentação de tambores com empilhadeira','Tambores vistos da porta'], films:['Baterias de lítio: manuseio e carregamento','Baterias de lítio: paletes e porta do contêiner','Baterias de lítio: contenção e fechamento das portas'],
  briefTitle:'Inclua estes dados na consulta', items:['Produto, uso, número UN e MSDS disponível','Embalagem, quantidade de volumes, dimensões e peso bruto por volume','Origem, destino e data de prontidão'], scope:'Os dados da carga e a rota definem aceitação, opções de transporte e escopo da cotação.',
  refs:'Referências de carregamento e cargas perigosas', refIntro:'As fontes explicam princípios gerais. Cada embarque depende da modalidade, das propriedades da carga e das condições do transportador.', refLabels:['Código CTU: IMO / ILO / UNECE','Visão geral do Código IMDG da IMO','Orientações IATA para baterias'],open:'Ver foto completa'
 },
 tr:{
  title:'Çin’den tehlikeli madde taşımacılığı ve konteyner içi sabitleme', intro:'Sevkiyat öncesi gerekli bilgileri inceleyin; farklı ambalajlarda bağlama, destekleme ve boşluk doldurma uygulamalarının saha fotoğraflarını görün.', quote:'Tehlikeli madde taşıma talebi',
  proofTitle:'Bağlama, destekleme ve boşluk doldurma', proofIntro:'Sabitleme yöntemi ambalaj dayanımı, ağırlık dağılımı, yük özellikleri ve rotaya göre değişir. Ara malzemeler, takozlar ve bağlar her sevkiyat için planlanır.',
  cards:[['Tam genişlikte yük ağı','Kapı yakınında kesintisiz bir tutma yüzeyi oluşturarak kolilerin kapıya doğru hareketini sınırlar.'],['Çapraz bağlı paletler','Her palet birimi önce dengelenir, ardından konteynerin sabitleme noktalarına bağlanır.'],['Destekleme ve boşluk doldurma','Çubuklar, kayışlar ve dolgu malzemeleri boyuna ve yanal hareketi birlikte sınırlar.'],['Sabitlenmiş ekipman sandığı','Takozlar ve yan koruma, tabana ve ağırlık merkezine göre yerleştirilir.']],
  noteTitle:'Tehlikeli yük kabul koşulları', note:'Kabul; UN numarası, uygun taşıma adı, sınıf, ambalaj, belgeler, taşıyıcı ve rotaya bağlıdır. Yükleme sırası tek bir kurala değil; ayrıştırma, ağırlık dağılımı ve elleçleme gereksinimlerine göre belirlenir.',
  records:'Varillerden lityum pillere: yükleme kayıtları', drums:['Konteyner içindeki variller','Forklift ile varil taşıma','Kapı tarafından varil görünümü'], films:['Lityum piller: taşıma ve yükleme','Lityum piller: paletler ve konteyner kapısı','Lityum piller: sabitleme ve kapı kapatma'],
  briefTitle:'Talebinize şu bilgileri ekleyin', items:['Ürün adı, kullanım amacı, UN numarası ve mevcut MSDS','Ambalaj, paket adedi, parça ölçüleri ve brüt ağırlık','Çıkış, varış ve yükün hazır olacağı tarih'], scope:'Yük bilgisi ve rota; kabulü, taşıma seçeneklerini ve teklif kapsamını belirler.',
  refs:'Yükleme ve tehlikeli madde kaynakları', refIntro:'Bu kaynaklar genel ilkeleri açıklar. Her sevkiyat; taşıma türü, yük özellikleri ve taşıyıcı koşullarına göre ayrıca teyit edilir.', refLabels:['CTU Kodu: IMO / ILO / UNECE','IMO IMDG Kodu genel bakış','IATA pil taşıma rehberi'],open:'Fotoğrafı tam aç'
 }
};
