import { freightPrefix, words, type FreightLocale } from './regions';

export function ghanaMetadata(locale: FreightLocale) {
  return {
    title: words('中国到加纳货运｜特马海运与阿克拉收货安排 | DDNZ Global','Shipping from China to Ghana | Tema & Accra Delivery | DDNZ Global','Envíos de China a Ghana | Tema y entrega en Acra | DDNZ Global')[locale],
    desc: words('按加纳收货地址安排中国端集货、整柜拼箱及目的地衔接。区分特马到港与阿克拉等城市交付，提前核对进口资料、提货责任和费用范围。','Plan China–Ghana consolidation, FCL and LCL around the receiving address. Distinguish Tema port arrival from delivery in Accra and confirm documents, collection and costs.','Planificar consolidación, FCL y LCL de China a Ghana. Diferenciar llegada a Tema y entrega en Acra; confirmar documentos, recogida y costos.')[locale],
    keywords: 'China Ghana shipping,Tema freight,Accra delivery,FCL,LCL',
  };
}

export default function GhanaContent({locale, preview=false}: {locale:FreightLocale; preview?:boolean}) {
  const t = (zh:string,en:string,es:string)=>words(zh,en,es)[locale];
  const prefix = freightPrefix(locale);
  const quote = `${prefix}/get-a-quote/?leadGoal=Freight+Export&source=ghana_country&dest=Ghana`;
  return <main id="main-content" className="freight-editorial freight-next ghana-page">
    <header className="freight-cover"><div className="freight-cover-copy"><a className="uae-back" href={`${prefix}/shipping-from-china-to-west-africa/`}>← {t('西非货运','West Africa freight','Transporte a África Occidental')}</a><p className="freight-kicker">{t("中国 → 加纳","CHINA → GHANA","CHINA → GHANA")}</p><h1>{t('中国到加纳。','China to Ghana.','De China a Ghana.')}<br/><em>{t('到特马港，\n还是送到收货点？','To Tema port,\nor your receiving address?','¿Hasta Tema\no hasta tu dirección?')}</em></h1><p>{t('把目的港、收货城市和交付范围分开说清楚。中国端集货、海运、目的地提货与配送，按这一票货的实际需要安排。','Separate the port, receiving city and delivery scope. Plan consolidation in China, ocean freight, destination collection and onward delivery around the shipment.','Definir puerto, ciudad y alcance por separado. Coordinar consolidación en China, transporte marítimo, recogida y entrega según el envío.')}</p><div className="freight-cover-actions"><a className="freight-cta" href={quote}>{t('询加纳运价','Request a Ghana quote','Cotizar envío a Ghana')} ↗</a><a href="#ghana-destination">{t('先看收货安排','Plan receiving','Planificar la recepción')} ↓</a></div></div><div className="country-route-board"><p className="freight-kicker">{t("特马 / 阿克拉 / 收货地址","TEMA / ACCRA / YOUR ADDRESS","TEMA / ACCRA / SU DIRECCIÓN")}</p><h2>{t('船到了，\n谁来接下一段？','After arrival,\nwho handles the next leg?','Al llegar,\n¿quién sigue con la entrega?')}</h2><ol>{[t('进口方：资料与申报准备','Importer: documents and declaration','Importador: documentos y declaración'),t('提货方：放行、车辆与预约','Collection: release, vehicle and appointment','Recogida: levante, vehículo y cita'),t('收货方：地址与卸货条件','Receiver: address and unloading facilities','Receptor: dirección y descarga')].map((item,i)=><li key={item}><span>0{i+1}</span>{item}</li>)}</ol></div></header>
    <nav className="freight-chapters" aria-label={t('本页内容','On this page','En esta página')}><a href="#ghana-destination">01 / {t('收货地点','Destination','Destino')}</a><a href="#ghana-preparation">02 / {t('出运准备','Preparation','Preparación')}</a><a href="#ghana-costs">03 / {t('费用与提货','Costs and collection','Costos y recogida')}</a><a href="#ghana-quote">04 / {t('询价资料','Quote details','Cotización')}</a></nav>
    <section className="freight-wrap freight-section" id="ghana-destination"><div className="freight-section-heading"><p className="freight-kicker">{t("01 / 港口并非最终收货地址","01 / PORT IS NOT THE FINAL ADDRESS","01 / EL PUERTO NO ES LA DIRECCIÓN FINAL")}</p><h2>{t('到港的报价，\n不等于送到仓库。','A port quotation\nis not a warehouse delivery.','Cotizar hasta puerto\nno es entregar en almacén.')}</h2><p>{t('收货在特马、阿克拉或其他城市，请提供完整地址和卸货条件。报价应写清海运结束后的操作由谁负责。','For Tema, Accra or another city, share the full address and unloading conditions. The quote should identify who handles each step after ocean transport.','Para Tema, Acra u otra ciudad, facilitar dirección y condiciones de descarga. La cotización debe indicar quién gestiona cada paso tras el transporte marítimo.')}</p></div><div className="uae-scope-list">{[
      [t('特马到港','Arrival at Tema','Llegada a Tema'),t('确认收货人、目的地清关联系人、文件交接与提货安排。将港口操作、清关服务和适用税费分开列明。','Confirm consignee, clearance contact, document handover and collection. Separate port handling, clearance services and applicable taxes.','Confirmar destinatario, contacto de despacho, documentos y recogida. Separar manipulación portuaria, despacho e impuestos.')],
      [t('阿克拉收货','Receiving in Accra','Recepción en Acra'),t('提供仓库、门店或工地地址，确认车辆能否进入、是否需要预约、由谁卸货。需要到门服务时，把这一段明确写入报价。','Share the warehouse, shop or jobsite address and confirm access, appointments and unloading responsibility. Include this leg explicitly when requesting door delivery.','Indicar dirección de almacén, tienda u obra; confirmar acceso, cita y descarga. Incluir expresamente este tramo si se requiere entrega a domicilio.')],
      [t('其他城市或分批收货','Other cities or staged deliveries','Otras ciudades o entregas parciales'),t('分别列出收货点、件数、单件重量与期望收货时间，再确认内陆运输和分批安排。','List each receiving point, package count, unit weight and target date before confirming inland or split delivery.','Listar cada destino, bultos, peso por unidad y fecha antes de confirmar transporte interior o entregas parciales.')],
    ].map(([title,body])=><article key={title}><span>{title}</span><p>{body}</p></article>)}</div><div className="freight-links"><a href="https://ghanaports.gov.gh/page/index/4/ZE4GGQFA/Welcome-to-Port-Of-Tema" target="_blank" rel="noreferrer">{t('特马港官方资料','Official Tema port information','Información oficial del puerto de Tema')} ↗</a></div></section>
    <section className="freight-dark" id="ghana-preparation"><div className="freight-wrap freight-section"><p className="freight-kicker">{t("02 / 货物出发之前","02 / BEFORE THE CARGO LEAVES","02 / ANTES DE QUE SALGA LA CARGA")}</p><h2>{t('货单、包装、进口资料，\n装柜前一起核对。','Cargo list, packing and documents.\nCheck them before loading.','Carga, embalaje y documentos.\nRevisarlos antes de cargar.')}</h2><div className="uae-route-grid"><article><h3>{t('中国端：先齐货单','In China: reconcile the order','En China: conciliar el pedido')}</h3><p>{t('多供应商订单按工厂列出货好时间、包装、件数、尺寸和毛重。整柜或拼箱不仅看总体积，还要确认堆码条件及是否分批出运。','List ready dates, packing, counts, dimensions and gross weights by factory. FCL or LCL planning also depends on stackability and whether cargo ships in batches.','Listar fechas, embalajes, bultos, medidas y pesos por fábrica. La elección FCL/LCL depende también del apilado y de posibles envíos parciales.')}</p><a href={`${prefix}/services/sea-freight/#mixed-loads`}>{t('看集货与装柜实拍','See consolidation and loading','Ver consolidación y carga')} →</a></article><article><h3>{t('加纳端：先明确进口方','In Ghana: identify the importer','En Ghana: definir al importador')}</h3><p>{t('提前确认进口方和清关代理，准备发票、装箱单、运输单据及货物适用的许可资料。申报通过 ICUMS 办理，具体材料由进口方和代理按产品核对。','Identify the importer and clearing agent. Prepare the invoice, packing list, transport documents and applicable permits. Declarations use ICUMS; have the importer and agent confirm product-specific documents.','Definir importador y agente; preparar factura, lista de empaque, documentos de transporte y permisos aplicables. La declaración se tramita en ICUMS; confirmar requisitos por producto.')}</p><a href="https://gra.gov.gh/customs/import-procedures/" target="_blank" rel="noreferrer">GRA · {t('官方进口流程','Official import procedures','Procedimiento oficial de importación')} ↗</a></article></div></div></section>
    <section className="freight-wrap freight-section" id="ghana-costs"><p className="freight-kicker">{t("03 / 确认交付方式","03 / AGREE THE HANDOVER","03 / ACORDAR LA ENTREGA")}</p><h2>{t('提货前，\n把费用和联系人对齐。','Before collection,\nalign costs and contacts.','Antes de recoger,\naclarar costos y contactos.')}</h2><div className="uae-scope-list">{[
      [t('报价包含什么','What is included','Qué está incluido'),t('中国端操作、海运、目的地操作、清关服务、税费和内陆配送逐项列出。比较报价时，确保交付终点一致。','Itemise origin handling, ocean freight, destination handling, clearance, taxes and inland delivery. Compare quotes to the same final point.','Desglosar origen, flete, destino, despacho, impuestos y reparto. Comparar cotizaciones hasta el mismo punto final.')],
      [t('谁负责下一步','Who handles the next step','Quién gestiona el siguiente paso'),t('到港通知发给谁、谁确认可提货、谁预约车辆、谁接货卸货，提前确定联系人。不要等到车辆到场再协调。','Agree who receives arrival notices, confirms collection readiness, books vehicles and receives/unloads the cargo before the vehicle arrives.','Acordar quién recibe avisos, confirma disponibilidad, reserva vehículo y recibe/descarga antes de que llegue el vehículo.')],
      [t('发生等待怎么办','If there is a delay','Si hay una espera'),t('询价时确认报价有效期，以及查验、仓储、等待和额外操作的计费方式及通知流程。具体时效按本票路线和出运安排确认。','Confirm quote validity, charging and notification arrangements for inspection, storage, waiting and extra handling. Confirm timing for the actual shipment and route.','Confirmar vigencia, cobro y aviso de inspección, almacenaje, espera y manipulación adicional. Acordar plazos según el envío y la ruta.')],
    ].map(([title,body])=><article key={title}><span>{title}</span><p>{body}</p></article>)}</div></section>
    {preview && <section className="freight-wrap freight-section" id="ghana-fieldwork"><aside className="uae-material-slot" data-material-slot="ghana-cargo"><span>{t('待补素材 · 仅本地预览','Media needed · local preview only','Material pendiente · solo vista previa')}</span><h3>{t('发往加纳或加纳当地货物实拍','Ghana shipment footage','Imágenes de un envío a Ghana')}</h3><p>{t('中国端发往加纳的装柜，或加纳卸货、入仓照片／短视频，任选一种。注明货物、地点和我们负责的环节；无需交接记录或当地派送视频。','Loading in China for Ghana, or unloading/storage in Ghana: either is useful. Include cargo, location and our role. No handover records or last-mile footage required.','Carga en China para Ghana o descarga/almacenaje en Ghana. Indicar mercancía, lugar y nuestra función. No se requieren actas ni vídeos de reparto final.')}</p></aside></section>}
    <section className="freight-destination-band" id="ghana-quote"><div className="freight-wrap freight-section"><p className="freight-kicker">{t("04 / 从具体货物开始","04 / START WITH YOUR CARGO","04 / EMPEZAR POR SU CARGA")}</p><h2>{t('把货单和加纳收货地址发来。','Send the cargo list\nand Ghana receiving address.','Enviar la lista de carga\ny la dirección en Ghana.')}</h2><ul className="uae-brief">{[t('品名、用途、包装照片、件数、尺寸和毛重','Products, use, packing photos, counts, dimensions and weights','Productos, uso, fotos, bultos, medidas y pesos'),t('中国供应商地点及货好时间','Supplier locations in China and ready dates','Proveedores en China y fechas'),t('加纳收货地址、进口方和清关联系人','Ghana address, importer and clearance contact','Dirección en Ghana, importador y contacto'),t('到港或到门、卸货条件及期望收货时间','Port or door, unloading conditions and target date','Puerto o domicilio, descarga y fecha deseada')].map(item=><li key={item}>{item}</li>)}</ul><a className="freight-cta" href={quote}>{t('提交加纳货运需求','Send your Ghana freight inquiry','Consultar envío a Ghana')} ↗</a></div></section>
  </main>;
}
