import { buildQuoteHref } from '../../lib/quoteLinks';
import { freightLanguagePrefix } from './freightLanguages';

export const internationalCountries: Record<string,{iso:string;cities:string;region:string;land?:boolean}> = {
 'saudi-arabia':{iso:'SA',cities:'Riyadh / Jeddah',region:'middle-east'},uae:{iso:'AE',cities:'Dubai / Abu Dhabi',region:'middle-east'},kuwait:{iso:'KW',cities:'Kuwait City',region:'middle-east'},qatar:{iso:'QA',cities:'Doha',region:'middle-east'},oman:{iso:'OM',cities:'Muscat',region:'middle-east'},bahrain:{iso:'BH',cities:'Manama',region:'middle-east'},
 kazakhstan:{iso:'KZ',cities:'Almaty / Astana',region:'central-asia',land:true},uzbekistan:{iso:'UZ',cities:'Tashkent / Samarkand',region:'central-asia',land:true},kyrgyzstan:{iso:'KG',cities:'Bishkek / Osh',region:'central-asia',land:true},tajikistan:{iso:'TJ',cities:'Dushanbe',region:'central-asia',land:true},turkmenistan:{iso:'TM',cities:'Ashgabat',region:'central-asia',land:true},russia:{iso:'RU',cities:'Moscow / Novosibirsk',region:'central-asia',land:true},
 nigeria:{iso:'NG',cities:'Lagos / Abuja',region:'west-africa'},ghana:{iso:'GH',cities:'Accra / Kumasi',region:'west-africa'},mexico:{iso:'MX',cities:'Mexico City / Guadalajara',region:'latin-america'},brazil:{iso:'BR',cities:'São Paulo / Santos',region:'latin-america'},argentina:{iso:'AR',cities:'Buenos Aires',region:'latin-america'},peru:{iso:'PE',cities:'Lima / Callao',region:'latin-america'},chile:{iso:'CL',cities:'Santiago / San Antonio',region:'latin-america'},
};
type Locale='pt'|'tr';
const text={
 pt:{
  title:(country:string)=>`Frete da China: destino ${country}.`,intro:(country:string)=>`Planeje o transporte da China com destino a ${country}, da coleta no fornecedor à entrega acordada. Compare modalidade, consolidação, documentos e responsabilidades antes de confirmar a remessa.`,home:'Início',overview:'Visão geral da região',quote:'Solicitar cotação para este destino',scope:'DDNZ: compras e preparação na China · Heaven Born: frete internacional',
  modes:'Escolha o transporte conforme a carga',landTitle:'Rodoviário e ferroviário',landBody:'Compare coleta nas fábricas, consolidação, transferência na fronteira e entrega no destino. O trecho ferroviário ou rodoviário deve ser confirmado para a carga e o endereço; a combinação pode exigir transbordo.',seaTitle:'Marítimo FCL e LCL',seaBody:'Compare contêiner completo com carga compartilhada. Inclua coleta, embalagem, carregamento, desconsolidação e despesas locais na análise. A rota e o porto dependem da disponibilidade e do plano de recebimento.',airTitle:'Aéreo para cargas urgentes',airBody:'Envie peso, dimensões, descrição e data de disponibilidade. O peso tarifável, a aceitação pelo transportador e a entrega após a chegada fazem parte da avaliação.',
  arrival:'O endereço final define a última etapa',cityLabel:'Cidades de referência para o planejamento:',arrivalBody:'Informe o endereço real, o contato de recebimento e as condições de descarga. Chegar ao terminal ou porto não equivale a entregar no seu armazém. Os exemplos de cidades não confirmam cobertura ou frequência de transporte.',
  preparation:'Antes de reservar o transporte',checks:[['Mercadoria e importador','Identifique o produto, modelo, finalidade e responsável pela importação. Confirme a classificação e os documentos necessários com o importador antes do embarque.'],['Coerência dos documentos','Compare quantidade, descrição, valor, peso e destinatário na fatura, lista de volumes e instrução de transporte. Registre divergências antes de liberar a carga.'],['Embalagem e manuseio','Informe peso por volume, dimensões, empilhamento e pontos de movimentação. Declare baterias, líquidos e outras características que exijam avaliação do transportador.'],['Escopo e custos','Defina coleta, transporte, documentos, despesas na chegada, desembaraço e entrega. Confirme serviços incluídos, exclusões e base de cobrança por escrito.']],
  equipment:'Máquinas e pedidos de vários fornecedores',equipmentBody:'Para equipamentos de processamento de alimentos, confirme modelo, capacidade, tensão, acessórios e embalagem antes da compra. Envie peso bruto e dimensões embaladas para o cálculo do frete. Se houver vários fornecedores, concilie caixas, quantidades e datas antes de consolidar.',equipmentLink:'Comparar máquinas de processamento de alimentos (em inglês)',consolidation:'Consolidação e preparação para exportação',inspection:'Inspeção antes do embarque',
  faqTitle:'Perguntas para preparar sua remessa',faqs:[['Como calcular o custo de envio?','Use a mesma lista de mercadorias e o mesmo escopo para comparar propostas. Origem, destino, modalidade, peso, dimensões e disponibilidade alteram o custo. O preço do produto não inclui automaticamente o frete.'],['Quando a previsão de chegada pode ser confirmada?','Após revisar a carga, a data de disponibilidade e o itinerário proposto. Separe coleta, espera, transporte internacional, liberação e entrega. Uma estimativa de trânsito não garante a data de entrega final.'],['Posso enviar pedidos de várias fábricas juntos?','A viabilidade depende das mercadorias, embalagens, documentos e datas. Confirme compatibilidade e requisitos de recebimento antes de liberar todos os fornecedores para um único ponto de consolidação.'],['Quem organiza o desembaraço e a entrega local?','A proposta deve identificar os responsáveis e o ponto final do serviço. Confirme com o importador o tratamento aplicável, os tributos e as despesas. Não presuma que uma cotação de transporte inclua todos os serviços locais.']],
  next:'Envie os dados para uma proposta com escopo claro',brief:'Informe fornecedores e pontos de coleta, mercadoria, quantidade de volumes, dimensões, peso bruto, data de disponibilidade, destino e serviços necessários. Indique também as informações ainda pendentes de confirmação.',
 },
 tr:{
  title:(country:string)=>`Çin çıkışlı yük taşımacılığı: ${country}.`,intro:(country:string)=>`Çin’den ${country} varışlı taşımayı, tedarikçiden teslim almadan kararlaştırılan teslim noktasına kadar planlayın. Sevkiyatı teyit etmeden önce taşıma türünü, konsolidasyonu, belgeleri ve sorumlulukları karşılaştırın.`,home:'Ana sayfa',overview:'Bölgeye genel bakış',quote:'Bu varış noktası için teklif isteyin',scope:'DDNZ: Çin’de tedarik ve ihracat hazırlığı · Heaven Born: uluslararası taşıma',
  modes:'Taşıma türünü yüke göre seçin',landTitle:'Karayolu ve demiryolu',landBody:'Fabrikalardan toplama, konsolidasyon, sınırda devir ve varış teslimini karşılaştırın. Demiryolu veya karayolu ayağı yük ve adres için teyit edilmelidir; taşıma kombinasyonu aktarma gerektirebilir.',seaTitle:'FCL ve LCL denizyolu',seaBody:'Tam konteyner ile parsiyel yükü karşılaştırın. Toplama, ambalaj, yükleme, ayrıştırma ve yerel masrafları hesaba katın. Güzergâh ve liman, mevcut seferlere ve teslim alma planına bağlıdır.',airTitle:'Acil yükler için havayolu',airBody:'Ağırlık, ölçüler, ürün tanımı ve hazır olma tarihini iletin. Ücretlendirilebilir ağırlık, taşıyıcı kabulü ve varış sonrasındaki teslim değerlendirmeye dahildir.',
  arrival:'Son adres, son taşıma aşamasını belirler',cityLabel:'Planlamada kullanılabilecek örnek şehirler:',arrivalBody:'Gerçek adresi, teslim alacak kişinin iletişim bilgilerini ve boşaltma koşullarını bildirin. Terminale veya limana varış, deponuza teslim anlamına gelmez. Şehir örnekleri hizmet kapsamını veya sefer sıklığını garanti etmez.',
  preparation:'Taşımayı rezerve etmeden önce',checks:[['Ürün ve ithalatçı','Ürünü, modeli, kullanım amacını ve ithalattan sorumlu tarafı belirleyin. Sevkten önce sınıflandırmayı ve gerekli belgeleri ithalatçıyla teyit edin.'],['Belgelerin tutarlılığı','Fatura, çeki listesi ve taşıma talimatındaki miktar, tanım, değer, ağırlık ve alıcıyı karşılaştırın. Yükü serbest bırakmadan önce farklılıkları kaydedin.'],['Ambalaj ve elleçleme','Paket başına ağırlığı, ölçüleri, istifleme koşullarını ve kaldırma noktalarını bildirin. Batarya, sıvı ve taşıyıcı incelemesi gerektiren diğer özellikleri beyan edin.'],['Kapsam ve maliyet','Toplama, taşıma, belgeler, varış masrafları, gümrükleme ve teslim kapsamını belirleyin. Dahil olan hizmetleri, istisnaları ve ücretlendirme esasını yazılı teyit edin.']],
  equipment:'Makineler ve birden fazla tedarikçinin siparişleri',equipmentBody:'Gıda işleme makinelerinde satın almadan önce modeli, kapasiteyi, voltajı, aksesuarları ve ambalajı teyit edin. Navlun hesabı için brüt ağırlığı ve ambalajlı ölçüleri iletin. Birden fazla tedarikçi varsa konsolidasyondan önce koli, miktar ve tarihleri uzlaştırın.',equipmentLink:'Gıda işleme makinelerini karşılaştırın (İngilizce)',consolidation:'Konsolidasyon ve ihracat hazırlığı',inspection:'Sevkiyat öncesi kontrol',
  faqTitle:'Sevkiyatınızı hazırlarken sorulacak sorular',faqs:[['Gönderim maliyeti nasıl hesaplanır?','Teklifleri aynı ürün listesi ve hizmet kapsamıyla karşılaştırın. Çıkış, varış, taşıma türü, ağırlık, ölçüler ve hazır olma tarihi maliyeti değiştirir. Ürün fiyatı navlunu otomatik olarak kapsamaz.'],['Tahmini varış ne zaman teyit edilebilir?','Yük, hazır olma tarihi ve önerilen güzergâh incelendikten sonra. Toplama, bekleme, uluslararası taşıma, serbest bırakma ve teslim aşamalarını ayırın. Tahmini taşıma süresi, son teslim tarihini garanti etmez.'],['Birden fazla fabrikanın siparişleri birlikte gönderilebilir mi?','Uygunluk ürünlere, ambalajlara, belgelere ve tarihlere bağlıdır. Tüm tedarikçileri tek konsolidasyon noktasına yönlendirmeden önce uyumluluğu ve kabul koşullarını teyit edin.'],['Gümrükleme ve yerel teslimi kim düzenler?','Teklif, sorumlu tarafları ve hizmetin sona erdiği noktayı belirtmelidir. Geçerli işlemleri, vergileri ve masrafları ithalatçıyla teyit edin. Taşıma teklifinin bütün yerel hizmetleri kapsadığını varsaymayın.']],
  next:'Kapsamı açık bir teklif için yük bilgilerini iletin',brief:'Tedarikçileri ve toplama noktalarını, ürünü, paket adedini, ölçüleri, brüt ağırlığı, hazır olma tarihini, varış yerini ve gereken hizmetleri bildirin. Henüz teyit edilmemiş bilgileri de belirtin.',
 }
};
export function internationalCountryName(country:string,locale:Locale){return new Intl.DisplayNames([locale],{type:'region'}).of(internationalCountries[country].iso)!;}
export function internationalCountryMeta(country:string,locale:Locale){const name=internationalCountryName(country,locale);return {title:`${text[locale].title(name)} | DDNZ Global`,desc:text[locale].intro(name),keywords:''};}
export default function InternationalCountryContent({country,locale}:{country:string;locale:Locale}){
 const c=text[locale],profile=internationalCountries[country],name=internationalCountryName(country,locale),prefix=freightLanguagePrefix(locale);
 const quote=buildQuoteHref({intent:'Freight Export',language:locale,source:'international_country',destination:name});
 const card='rounded-2xl border border-slate-200 bg-white p-6';
 return <main id="main-content" lang={locale} className="bg-slate-50 text-slate-900"><header className="bg-slate-950 text-white"><div className="mx-auto max-w-7xl px-6 py-20"><nav aria-label={c.overview} className="mb-8 flex flex-wrap gap-4 text-sm"><a href={`${prefix}/`}>{c.home}</a><a href={`${prefix}/shipping-from-china-to-${profile.region}/`}>{c.overview} →</a></nav><p className="mb-6 text-sm text-orange-300">DDNZ GLOBAL · HEAVEN BORN</p><h1 className="max-w-4xl text-4xl font-bold leading-tight md:text-6xl">{c.title(name)}</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-slate-200">{c.intro(name)}</p><a className="mt-8 inline-block rounded-xl bg-orange-700 px-6 py-4 font-bold" href={quote}>{c.quote} →</a><p className="mt-6 text-sm text-slate-300">{c.scope}</p></div></header><div className="mx-auto max-w-7xl space-y-16 px-6 py-16">
 <section><h2 className="text-3xl font-bold">{c.modes}</h2><div className="mt-7 grid gap-6 md:grid-cols-2"><article className={card}><h3 className="text-xl font-bold">{profile.land?c.landTitle:c.seaTitle}</h3><p className="mt-4 leading-7">{profile.land?c.landBody:c.seaBody}</p></article><article className={card}><h3 className="text-xl font-bold">{c.airTitle}</h3><p className="mt-4 leading-7">{c.airBody}</p></article></div></section>
 <section className={card}><h2 className="text-3xl font-bold">{c.arrival}</h2><p className="mt-5 font-semibold">{c.cityLabel} <bdi>{profile.cities}</bdi></p><p className="mt-4 max-w-4xl leading-7">{c.arrivalBody}</p></section>
 <section><h2 className="text-3xl font-bold">{c.preparation}</h2><div className="mt-7 grid gap-6 md:grid-cols-2">{c.checks.map(([h,p])=><article className={card} key={h}><h3 className="text-xl font-bold">{h}</h3><p className="mt-4 leading-7">{p}</p></article>)}</div></section>
 <section id="country-cargo-planning" className={card}><h2 className="text-3xl font-bold">{c.equipment}</h2><p className="mt-5 max-w-4xl leading-7">{c.equipmentBody}</p><div className="mt-6 flex flex-wrap gap-6 font-semibold text-purple-800 underline"><a href="/sourcing/food-processing-machinery-from-china/" hrefLang="en">{c.equipmentLink}</a><a href={`${prefix}/sourcing-services/consolidation-export/`}>{c.consolidation}</a><a href={`${prefix}/sourcing-services/inspection-quality-control/`}>{c.inspection}</a></div></section>
 <section><h2 className="text-3xl font-bold">{c.faqTitle}</h2><div className="mt-7 grid gap-6 md:grid-cols-2">{c.faqs.map(([q,a])=><article className={card} key={q}><h3 className="text-xl font-bold">{q}</h3><p className="mt-4 leading-7">{a}</p></article>)}</div></section>
 <section className="rounded-2xl bg-slate-900 p-8 text-white"><h2 className="text-3xl font-bold">{c.next}</h2><p className="mt-5 max-w-4xl leading-7">{c.brief}</p><a className="mt-6 inline-block rounded-xl bg-orange-700 px-6 py-4 font-bold" href={quote}>{c.quote} →</a></section>
 </div></main>;
}
