import { freightPrefix, words, type FreightLocale } from './regions';
import ShipmentPreparation from './ShipmentPreparation';
import LclLoadingDetails from './LclLoadingDetails';

export function lclMetadata(locale: FreightLocale) {
  return {
    keywords: 'LCL shipping China, sea freight consolidation, 拼箱, 拼箱费用',
    title: words('中国 LCL 拼箱与集运｜费用、包装与交付 | DDNZ Global', 'LCL Shipping from China | Costs, Packing & Delivery | DDNZ Global', 'Envíos LCL desde China | Costos, embalaje y entrega | DDNZ Global')[locale],
    desc: words('已有货物需要海运拼箱？核对件重尺、包装、截仓时间、目的地费用和提货安排，比较完整出运方案。', 'Plan LCL shipping for ready cargo. Review dimensions, packing, receiving cutoffs, destination charges and collection before booking.', 'Planifica LCL para carga preparada: medidas, embalaje, cierre de recepción, gastos en destino y recogida.')[locale],
  };
}

export default function LclContent({locale, materialPreview}: {locale: FreightLocale; materialPreview?: React.ReactNode}) {
  const t = (zh:string,en:string,es:string) => words(zh,en,es)[locale];
  const prefix = freightPrefix(locale);
  const quote = `${prefix}/get-a-quote/?leadGoal=Freight+Only&source=lcl_shipping`;
  return <main id="main-content" className="freight-editorial freight-next">
    <header className="freight-cover"><div className="freight-cover-copy"><p className="freight-kicker">LCL / FROM CHINA</p><h1>{t('不满一柜，\n也要把每一步算清。', 'Less than a container.\nPlan the whole journey.', 'Menos de un contenedor.\nPlanifica todo el recorrido.')}</h1><p>{t('货已经有了，要发几箱、几托，还是多家供应商一起走？从最终包装和收货地址开始，把拼箱运费、仓库操作和目的地交付放在同一份方案里比较。', 'A few cartons, several pallets or cargo from several suppliers? Start with final packing and the delivery address, then compare freight, warehouse handling and destination delivery together.', '¿Unas cajas, varios palés o varios proveedores? Parte del embalaje final y la dirección; compara flete, almacén y entrega en una misma propuesta.')}</p><a className="freight-cta" href={quote}>{t('提交拼箱货物资料', 'Request an LCL quote', 'Solicitar cotización LCL')} ↗</a></div><div className="country-route-board"><p className="freight-kicker">CARTONS → CFS → DESTINATION</p><h2>{t('看全程，\n不只看海运单价。', 'The full journey.\nNot just the ocean rate.', 'Todo el recorrido.\nNo solo el flete.')}</h2><ol>{[t('多少货：最终件数、尺寸和毛重', 'Cargo: final count, dimensions and gross weight', 'Carga: bultos, medidas y peso bruto finales'),t('怎么收：仓库、门店或自行提货', 'Receiving: warehouse, shop or collection', 'Recepción: almacén, tienda o recogida'),t('谁负责：费用、操作和交付边界', 'Responsibility: charges, handling and delivery scope', 'Responsabilidad: cargos, operaciones y entrega')].map((x,i)=><li key={x}><span>0{i+1}</span>{x}</li>)}</ol></div></header>
    <nav className="freight-chapters" aria-label={t('本页内容','On this page','En esta página')}><a href="#lcl-fit">01 / {t('适不适合','Cargo fit','Carga adecuada')}</a><a href="#lcl-costs">02 / {t('费用比较','Compare costs','Comparar costos')}</a><a href="#lcl-field-record">03 / {t('装柜现场','Loading photos','Fotos de carga')}</a><a href="#lcl-loading-mistakes">04 / {t('错误示范','Incorrect examples','Ejemplos incorrectos')}</a><a href="#lcl-brief">05 / {t('询价资料','Shipment brief','Datos del envío')}</a></nav>
    <section id="lcl-fit" className="freight-wrap freight-section"><p className="freight-kicker">01 / BEFORE BOOKING</p><h2>{t('先确认货物，\n再确认拼箱方案。','Check the cargo.\nThen choose the plan.','Primero la carga.\nDespués el plan.')}</h2><div className="freight-questions">{[
      [t('包装能否堆叠？','Can the packages be stacked?','¿Se puede apilar?'),t('提供单件外尺寸、毛重与包装照片；易碎、超长、超重或不可堆叠要提前说明。带电、液体等货物先确认承运条件。','Provide dimensions, gross weight and packing photos. Declare fragile, oversized, heavy or non-stackable cargo; confirm acceptance for batteries or liquids first.','Facilita medidas, peso y fotos. Indica fragilidad, sobredimensión o restricciones de apilado; confirma aceptación de baterías o líquidos.')],
      [t('能否赶上截仓？','Will cargo meet the receiving cutoff?','¿Llegará antes del cierre?'),t('确认仓库地址、入仓编号、预约与最晚收货时间；货好时间与实际到仓时间分开记录。错过截仓时，重新确认船期和仓储安排。','Confirm warehouse address, reference, appointment and receiving cutoff. Track readiness and warehouse arrival separately; recheck sailing and storage if the cutoff is missed.','Confirma almacén, referencia, cita y cierre. Distingue preparación de llegada; si se pierde el cierre, revisa salida y almacenaje.')],
      [t('到港后谁来提？','Who collects at destination?','¿Quién recoge en destino?'),t('确认目的地拆箱仓、放货条件、提货预约和卸货设备；到港、到仓与到门的报价范围要分别写清。','Confirm deconsolidation warehouse, release conditions, collection appointment and unloading equipment. Define port, warehouse or door scope in writing.','Confirma almacén de desconsolidación, liberación, cita y equipos. Define por escrito el alcance hasta puerto, almacén o domicilio.')],
    ].map(([title,body])=><details key={title}><summary>{title}</summary><p>{body}</p></details>)}</div></section>
    <div id="lcl-costs"><ShipmentPreparation locale={locale} consolidation /></div>
    <ShipmentPreparation locale={locale}/>
    <section className="freight-wrap freight-section" id="lcl-field-record"><p className="freight-kicker">LCL / FIELD RECORDS</p><h2>{t('不同包装，怎么一起装？','Different packages. How do they load together?','¿Cómo cargar juntos distintos embalajes?')}</h2>
      <div className="mt-8 grid gap-8 md:grid-cols-2"><figure><a href="/media/freight-20260918/mixed-cargo-loading.jpg" target="_blank" rel="noreferrer"><img src="/media/freight-20260918/mixed-cargo-loading.jpg" alt={t('不同包装混合装柜的现场', 'Different packaging types in a mixed load', 'Distintos embalajes en una carga mixta')} loading="lazy" /></a><figcaption>01 / {t('不同包装同柜：先确认尺寸与堆叠条件。', 'Mixed packaging: confirm dimensions and stacking constraints.', 'Embalajes mixtos: confirmar medidas y apilamiento.')}</figcaption></figure><figure><a href="/media/lcl-20260920/loading-in-progress.webp" target="_blank" rel="noreferrer"><img src="/media/lcl-20260920/loading-in-progress.webp" width={1200} height={1547} alt={t('木箱、托盘与成组货物的 LCL 装柜过程', 'LCL loading in progress with crates, pallets and bundled cargo', 'Carga LCL de cajones, palés y mercancía agrupada')} loading="lazy" /></a><figcaption>02 / {t('木箱与托盘装柜过程 · 点击查看完整图片。', 'Crates and pallets during loading · View full image.', 'Cajones y palés durante la carga · Ver imagen completa.')}</figcaption></figure></div>
    </section>
    <LclLoadingDetails locale={locale} />
    {materialPreview}
    <section className="freight-wrap freight-section"><h2>{t('供应商订单还没理顺？','Still coordinating supplier orders?','¿Aún coordinando pedidos?')}</h2><p className="freight-intro">{t('供应商交期、订单数量与异常处理属于采购交接准备。需要这部分协助，可查看集货与出口交付服务。','Supplier dates, order quantities and exceptions belong to sourcing preparation. Explore our consolidation and export handoff service for that support.','Fechas, cantidades e incidencias de proveedores forman parte de la preparación de compras. Consulta el servicio de consolidación y entrega para exportación.')}</p><a href={`${prefix}/sourcing-services/consolidation-export/`}>{t('查看采购端集货与出口交付','Explore sourcing-side consolidation','Ver consolidación de compras')} →</a></section>
    <section id="lcl-brief" className="freight-destination-band"><div className="freight-wrap freight-section"><h2>{t('带上这份货物资料，\n开始比较。','Bring the cargo details.\nCompare on equal terms.','Trae los datos de carga.\nCompara el mismo alcance.')}</h2><p className="freight-intro">{t('品名与用途、包装照片、件数、外尺寸、毛重、中国提货地址、货好日期、目的地地址，以及希望到港还是到门。报价时确认起运地、海运、目的地操作、税费及配送分别包含哪些项目。','Send product and use, packing photos, count, dimensions, gross weight, China pickup address, ready date, destination and port or door scope. Confirm inclusions for origin, ocean, destination handling, taxes and delivery.','Envía producto y uso, fotos, bultos, medidas, peso, recogida en China, fecha, destino y alcance. Confirma inclusiones de origen, flete, destino, impuestos y entrega.')}</p><a className="freight-cta" href={quote}>{t('询 LCL 拼箱方案','Request an LCL plan','Consultar un plan LCL')} ↗</a></div></section>
  </main>;
}
