export type LclExtraLocale = 'ru' | 'fr' | 'ar' | 'pt' | 'tr';
type Copy = {
  title: string; intro: string; quote: string; nav: string[];
  fitTitle: string; fit: [string,string][]; costsTitle: string; costsIntro: string; costs: [string,string][];
  questionsTitle: string; questions: [string,string][];
  photosTitle: string; photosIntro: string; photos: [string,string][];
  errorsTitle: string; errorsIntro: string; errorLabel: string; errors: [string,string][];
  open: string; sourcingTitle: string; sourcingBody: string; sourcingLink: string;
  briefTitle: string; brief: string; scope: string;
};
export const lclInternationalCopy: Record<LclExtraLocale, Copy> = {
  ru: {
    title:'Сборные морские грузы из Китая: планируйте весь путь',
    intro:'Несколько коробок, паллет или заказы от разных поставщиков? Начните с окончательной упаковки и адреса получателя. Сравнивайте морской фрахт, складские операции и выдачу груза в одной смете.',
    quote:'Запросить расчёт LCL', nav:['Подходит ли LCL','Сравнение затрат','Фото погрузки','Ошибки погрузки','Данные для расчёта'],
    fitTitle:'Сначала груз — затем план перевозки.',
    fit:[['Можно ли штабелировать груз?','Укажите габариты и массу брутто каждого места, приложите фотографии упаковки. Заранее сообщите о хрупком, длинномерном, тяжёлом или нештабелируемом грузе. Приём батарей и жидкостей согласуется отдельно.'],['Успеет ли груз на склад?','Уточните адрес склада, номер приёмки, запись и крайний срок поступления. Готовность на фабрике и прибытие на склад — разные даты. При опоздании заново согласуйте отправление и хранение.'],['Кто забирает груз в пункте назначения?','Уточните склад расформирования, условия выдачи, запись на получение и разгрузочное оборудование. Разделяйте доставку до порта, склада и адреса получателя.']],
    costsTitle:'Когда объединение грузов даёт экономию?', costsIntro:'Запросите варианты для одного состава груза и одного адреса. Сравнивайте полные расходы, а не только ставку морского фрахта.',
    costs:[['Минимальные сборы за отправку','При отдельных отправках проверьте минимальные сборы в стране отправления и назначения для каждой партии. При объединении — приёмку, консолидацию и дополнительные перегрузки.'],['Ожидание и хранение','Уточните, начинается ли бесплатный период с каждой приёмки или после поступления всего груза. Согласуйте даты поставок и сравните ожидание с раздельными отправками.'],['Окончательный расчётный объём','Размеры до паллетирования не заменяют размеры готовой упаковки. Пересчитайте места, массу, габариты, упаковочные работы, расформирование и выдачу груза в пункте назначения.']],
    questionsTitle:'Что согласовать до отправки',
    questions:[['Один поставщик задерживается: ждать или разделить?','Составьте график поступления от всех поставщиков. Сравните сроки и стоимость двух вариантов, начало платного хранения и порядок согласования частичной отправки. Не назначайте отправление только по дате самой ранней готовности.'],['Изменится ли расчёт после паллетирования?','Передайте исходные размеры, массу и ограничения по штабелированию. Стоимость паллетирования или переупаковки согласуйте отдельно; перевозку пересчитайте по готовым местам.'],['Как подтвердить состав отправки?','Сверьте маркировку, количество мест и упаковку по поставщикам. Отдельно укажите недостачу и незавершённые проверки. До отправки утвердите список; заранее оговорите фото, паллетную ведомость и передачу назначенному экспедитору.'],['У получателя нет погрузчика?','Сообщите тип адреса: склад, магазин, жилой дом или стройплощадка, наличие рампы и ограничения для машин. Согласуйте гидроборт, рабочих, запись и ожидание. Доставка до двери сама по себе не включает занос внутрь.'],['Что проверить при самостоятельном получении?','Адрес, разрешение на выдачу, запись и сборы; затем габариты упаковки, массу, вместимость машины и способ погрузки. Учтите свой транспорт, работников и время.']],
    photosTitle:'Разная упаковка в одном контейнере', photosIntro:'Фотографии помогают объяснить форму груза и условия обработки. Наличие свободного места не заменяет проверку упаковки и допустимой нагрузки.',
    photos:[['Смешанный груз','Коробки, мешки и обёрнутые грузовые места. До погрузки уточните габариты и ограничения по штабелированию.'],['Погрузка ящиков и паллет','Деревянные ящики, паллеты и связки груза в процессе загрузки контейнера.'],['Ящики и паллеты по высоте','Над деревянными ящиками размещён паллетированный груз. Укажите конструкцию упаковки и допустимые условия штабелирования.'],['Мешки и коробки слоями','Между частью слоёв виден прокладочный материал. Возможность размещения сверху проверяют по фактической массе и прочности упаковки.']],
    errorsTitle:'Помещается — не значит, что так можно грузить.', errorsIntro:'Два примера неправильной укладки. Обратите внимание на деформацию коробок, смещение рядов и промежутки между местами.', errorLabel:'Неправильный пример',
    errors:[['Неровная укладка и деформированные коробки','Проверьте углы, сдавленные участки и промежутки между мешками и коробками. Сначала осмотрите упаковку и груз, затем решайте вопрос переупаковки, перестановки или дополнительных опор.'],['Наклонённые и смещённые ряды','Часть коробок заметно изогнута. Не добавляйте груз только потому, что осталось место. Сначала проверьте массу коробок, ограничения по штабелированию и состояние упаковки.']],
    open:'Открыть фотографию', sourcingTitle:'Ещё согласовываете заказы поставщиков?', sourcingBody:'Сроки фабрик, количество по заказам и устранение расхождений относятся к подготовке закупки. Для этой задачи предусмотрена отдельная услуга консолидации и передачи на экспорт.', sourcingLink:'Консолидация заказов и экспорт',
    briefTitle:'Данные для сопоставимого расчёта', brief:'Наименование и назначение товара, фото упаковки, количество мест, наружные размеры, масса брутто, адрес забора в Китае, дата готовности, адрес назначения и доставка до порта или двери.', scope:'Уточните, что входит в расходы в стране отправления, морской фрахт, операции в пункте назначения, налоги и доставку.'
  },
  fr: {
    title:'Groupage maritime depuis la Chine : prévoir tout le trajet',
    intro:'Quelques cartons, plusieurs palettes ou des commandes de plusieurs fournisseurs ? Partez de l’emballage final et de l’adresse de réception. Comparez le fret, les opérations d’entrepôt et la remise à destination dans un même devis.',
    quote:'Demander un devis LCL', nav:['Adéquation du fret','Comparer les coûts','Photos de chargement','Erreurs de chargement','Données du devis'],
    fitTitle:'Vérifier la marchandise, puis choisir le transport.',
    fit:[['Les colis sont-ils gerbables ?','Indiquez les dimensions et le poids brut de chaque colis, avec des photos. Signalez les marchandises fragiles, longues, lourdes ou non gerbables. Confirmez séparément l’acceptation des batteries et liquides.'],['La marchandise arrivera-t-elle avant la clôture ?','Confirmez l’adresse, la référence d’entrée, le rendez-vous et la date limite de réception. Distinguez disponibilité en usine et arrivée à l’entrepôt. En cas de retard, revoyez le départ et le stockage.'],['Qui récupère la marchandise à destination ?','Confirmez l’entrepôt de dégroupage, les conditions de mise à disposition, le rendez-vous et le matériel de déchargement. Distinguez un devis jusqu’au port, à l’entrepôt ou à l’adresse finale.']],
    costsTitle:'Où le regroupement peut-il réduire les coûts ?', costsIntro:'Demandez les deux options pour les mêmes marchandises et la même adresse. Comparez l’ensemble des frais, pas seulement le taux de fret maritime.',
    costs:[['Minimums par expédition','Envois séparés : vérifiez les minimums à l’origine et à destination pour chaque lot. Envoi groupé : vérifiez la réception, le regroupement et les manutentions supplémentaires.'],['Attente et stockage','Confirmez si la franchise démarre à chaque réception ou à l’arrivée du dernier lot. Planifiez les livraisons des fournisseurs et comparez attente et départs séparés.'],['Volume final facturable','Le volume avant palettisation ne remplace pas les dimensions finales. Revoyez emballage, nombre de colis, poids, dimensions, dégroupage et retrait à destination.']],
    questionsTitle:'Les points à régler avant le départ',
    questions:[['Un fournisseur est en retard : attendre ou fractionner ?','Listez les dates d’arrivée prévues. Comparez coûts et délais des deux options, le début du stockage payant et la personne qui autorise un départ partiel. Ne réservez pas uniquement selon la première usine prête.'],['La palettisation change-t-elle le devis ?','Fournissez dimensions, poids et limites de gerbage initiaux. Convenez séparément du prix de palettisation ou de réemballage, puis recalculez le transport sur les colis terminés.'],['Comment confirmer le contenu de l’envoi ?','Rapprochez marques, quantités et état des emballages par fournisseur. Isolez les manquants et contrôles en attente. Validez la liste avant départ et précisez les photos, listes de palettes ou remises à un transitaire désigné.'],['Pas de chariot élévateur chez le destinataire ?','Précisez entrepôt, magasin, domicile ou chantier, accès au quai et restrictions des véhicules. Confirmez hayon, personnel, rendez-vous et attente. Une livraison à l’adresse ne définit pas à elle seule la manutention à l’intérieur.'],['Que vérifier pour un retrait par vos soins ?','Adresse, avis de mise à disposition, rendez-vous et frais ; puis dimensions finales, poids, capacité du véhicule et chargement. Incluez votre transport, votre personnel et votre temps.']],
    photosTitle:'Plusieurs emballages dans un conteneur', photosIntro:'Les photos rendent visibles les formes de colis et les besoins de manutention. L’espace disponible ne remplace pas la vérification des emballages et charges admises.',
    photos:[['Chargement mixte','Cartons, sacs et colis filmés : confirmer les dimensions et contraintes de gerbage avant chargement.'],['Caisses et palettes en cours de chargement','Caisses en bois, palettes et marchandises regroupées pendant le chargement.'],['Caisses et palettes superposées','Des palettes sont placées au-dessus de caisses en bois. Précisez la structure de l’emballage et les conditions de gerbage autorisées.'],['Sacs et cartons par couches','Des intercalaires sont visibles entre certaines couches. Vérifiez les poids réels et la résistance des emballages avant de décider quoi poser au-dessus.']],
    errorsTitle:'Ce qui rentre n’est pas forcément bien chargé.', errorsIntro:'Deux exemples incorrects : regardez les cartons déformés, les couches décalées et les vides entre colis.', errorLabel:'Exemple incorrect',
    errors:[['Piles inégales et cartons déformés','Vérifiez les angles, les zones comprimées et les vides entre sacs et cartons. Examinez emballage et marchandise avant de décider d’un réemballage, d’une réorganisation ou de supports supplémentaires.'],['Cartons inclinés et couches décalées','Certaines boîtes sont visiblement courbées. Ne rajoutez pas de fret au seul motif qu’il reste de la place. Vérifiez poids, limites de gerbage et état de l’emballage.']],
    open:'Voir la photo complète', sourcingTitle:'Vous coordonnez encore les commandes ?', sourcingBody:'Délais des usines, quantités commandées et écarts relèvent de la préparation des achats. Consultez le service distinct de consolidation et de remise pour exportation.', sourcingLink:'Consolidation des achats et export',
    briefTitle:'Les données pour comparer les devis', brief:'Produit et usage, photos d’emballage, nombre de colis, dimensions extérieures, poids brut, adresse d’enlèvement en Chine, date de disponibilité, adresse finale et périmètre jusqu’au port ou à l’adresse.', scope:'Confirmez les inclusions : origine, fret maritime, opérations à destination, taxes et livraison.'
  },
  ar: {
    title:'الشحن البحري الجزئي من الصين: خطط للرحلة كاملة',
    intro:'بضع صناديق أم عدة منصات أم طلبات من موردين مختلفين؟ ابدأ بالتغليف النهائي وعنوان الاستلام. قارن أجرة البحر وعمليات المستودع والتسليم ضمن عرض واحد.',
    quote:'اطلب عرض شحن جزئي', nav:['ملاءمة الشحنة','مقارنة التكاليف','صور التحميل','أمثلة خاطئة','بيانات التسعير'],
    fitTitle:'تأكد من البضاعة أولاً، ثم اختر خطة الشحن.',
    fit:[['هل يمكن تكديس الطرود؟','قدم الأبعاد والوزن الإجمالي لكل طرد وصور التغليف. وضح مسبقاً إن كانت البضاعة هشة أو طويلة أو ثقيلة أو لا تقبل التكديس. يجب تأكيد قبول البطاريات والسوائل بشكل منفصل.'],['هل تصل قبل إغلاق الاستلام؟','أكد عنوان المستودع ورقم الإدخال والموعد وآخر وقت للاستلام. جاهزية المصنع ليست تاريخ وصول المستودع. عند التأخير، أعد تأكيد موعد الإبحار والتخزين.'],['من يستلم في الوجهة؟','حدد مستودع تفريغ الشحنة المجمعة وشروط الإفراج وموعد الاستلام ومعدات التفريغ. ميز بين العرض حتى الميناء أو المستودع أو العنوان النهائي.']],
    costsTitle:'متى يوفر تجميع الشحنات؟', costsIntro:'اطلب الخيارين للبضاعة نفسها والعنوان نفسه. قارن التكلفة الكاملة، وليس أجرة البحر وحدها.',
    costs:[['الحد الأدنى لرسوم كل شحنة','للشحن المنفصل: راجع الحد الأدنى في المنشأ والوجهة لكل دفعة. للشحن المجمع: راجع رسوم الاستلام والتجميع والمناولة الإضافية.'],['الانتظار والتخزين','أكد هل تبدأ الفترة المجانية عند استلام كل دفعة أم عند اكتمال البضاعة. نظم مواعيد الموردين وقارن الانتظار بالإرسال على دفعات.'],['الحجم النهائي المحتسب','الحجم قبل وضع البضاعة على المنصات لا يعوض الأبعاد النهائية. راجع رسوم التغليف وعدد الطرود وأوزانها وأبعادها ورسوم فك التجميع والاستلام في الوجهة.']],
    questionsTitle:'ما الذي يجب الاتفاق عليه قبل الإرسال؟',
    questions:[['تأخر مورد: ننتظر أم نقسم الشحنة؟','سجل موعد الوصول المتوقع لكل مورد. قارن تكلفة ومدة الخيارين، وبداية رسوم التخزين، ومن يوافق على الإرسال الجزئي. لا تحجز اعتماداً على أول مصنع يجهز فقط.'],['هل يتغير السعر بعد تجهيز المنصات؟','قدم أبعاد الصناديق وأوزانها وحدود التكديس. اتفق على رسوم المنصات أو إعادة التغليف منفصلة، ثم أعد حساب النقل وفق الطرود النهائية.'],['كيف نؤكد ما سيخرج في هذه الشحنة؟','طابق العلامات وعدد الطرود وحالة التغليف حسب المورد. افصل النواقص والفحوص المعلقة. اعتمد القائمة قبل الإرسال وحدد مسبقاً طلب الصور أو قائمة المنصات أو التسليم لوكيل تختاره.'],['لا توجد رافعة شوكية عند المستلم؟','حدد إن كان العنوان مستودعاً أو متجراً أو منزلاً أو موقع عمل، مع الرصيف والمعدات وقيود المركبات. أكد الحاجة إلى منصة رفع وعمال وموعد وانتظار. الوصول إلى العنوان لا يعني تلقائياً نقل البضاعة إلى الداخل.'],['ماذا أراجع إذا استلمت بنفسي؟','العنوان وإشعار الإفراج والموعد والرسوم، ثم الأبعاد النهائية والوزن وسعة المركبة وطريقة التحميل. احسب مركبتك والعمالة والوقت ضمن المقارنة.']],
    photosTitle:'عبوات مختلفة داخل حاوية واحدة', photosIntro:'توضح الصور شكل الطرود واحتياجات المناولة. المساحة المتاحة لا تغني عن فحص التغليف والأحمال المسموح بها.',
    photos:[['حمولة مختلطة','صناديق وأكياس وطرود مغلفة: أكد الأبعاد وحدود التكديس قبل التحميل.'],['تحميل الصناديق والمنصات','صناديق خشبية ومنصات وبضائع مربوطة معاً أثناء التحميل.'],['منصات فوق صناديق خشبية','تظهر منصات محملة فوق صناديق خشبية. وضح بنية التغليف وشروط التكديس المسموح بها.'],['أكياس وصناديق على طبقات','تظهر فواصل بين بعض الطبقات. يجب مراجعة الوزن الفعلي وقوة التغليف قبل تحديد ما يوضع فوقها.']],
    errorsTitle:'وجود مساحة لا يعني أن التحميل مناسب.', errorsIntro:'الصورتان مثالان خاطئان. انتبه لتشوه الصناديق وانزياح الصفوف والفراغات بين الطرود.', errorLabel:'مثال خاطئ',
    errors:[['تكديس غير متساوٍ وصناديق متشوهة','افحص الزوايا والأماكن المضغوطة والفراغات بين الأكياس والصناديق. افحص التغليف والبضاعة أولاً، ثم قرر إعادة التغليف أو الترتيب أو إضافة الدعم.'],['صناديق مائلة وصفوف منزاحة','بعض الصناديق منحنية بوضوح. لا تضف بضاعة لمجرد وجود فراغ؛ راجع وزن الطرد وحدود التكديس وحالة التغليف أولاً.']],
    open:'عرض الصورة كاملة', sourcingTitle:'ما زلت تنسق طلبات الموردين؟', sourcingBody:'مواعيد المصانع وكميات الطلبات ومعالجة الفروق جزء من إعداد المشتريات. لهذه المهمة خدمة مستقلة لتجميع الطلبات وتسليمها للتصدير.', sourcingLink:'تجميع المشتريات والتصدير',
    briefTitle:'بيانات تساعد على مقارنة العروض', brief:'اسم المنتج واستخدامه وصور التغليف وعدد الطرود والأبعاد الخارجية والوزن الإجمالي وعنوان الاستلام في الصين وتاريخ الجاهزية وعنوان الوجهة والتسليم إلى الميناء أو الباب.', scope:'أكد ما يشمله العرض من رسوم المنشأ وأجرة البحر وعمليات الوجهة والضرائب والتوصيل.'
  },
  pt: {
    title:'Carga marítima LCL da China: planeje todo o percurso',
    intro:'Algumas caixas, vários paletes ou pedidos de fornecedores diferentes? Comece pela embalagem final e pelo endereço de recebimento. Compare frete, operações de armazém e entrega no mesmo orçamento.',
    quote:'Solicitar cotação LCL', nav:['Adequação da carga','Comparar custos','Fotos de carregamento','Exemplos incorretos','Dados para cotação'],
    fitTitle:'Primeiro a carga, depois o plano de transporte.',
    fit:[['Os volumes podem ser empilhados?','Informe dimensões e peso bruto por volume, com fotos da embalagem. Avise sobre itens frágeis, compridos, pesados ou não empilháveis. Confirme separadamente a aceitação de baterias e líquidos.'],['A carga chega antes do encerramento da recepção?','Confirme endereço, referência de entrada, agendamento e prazo final. Prontidão na fábrica e chegada ao armazém são datas diferentes. Em caso de atraso, reveja a saída e a armazenagem.'],['Quem retira no destino?','Confirme armazém de desconsolidação, condições de liberação, agendamento e equipamentos de descarga. Diferencie cotação até o porto, armazém ou endereço final.']],
    costsTitle:'Onde a consolidação pode economizar?', costsIntro:'Peça as duas opções para a mesma carga e endereço. Compare os custos completos, não apenas o frete marítimo.',
    costs:[['Cobranças mínimas por embarque','Separados: verifique mínimos na origem e no destino para cada lote. Consolidados: confira recebimento, consolidação e manuseios extras.'],['Espera e armazenagem','Confirme se o período livre começa em cada recebimento ou após chegar toda a carga. Agende os fornecedores e compare espera com embarques separados.'],['Volume final faturável','O volume antes da paletização não substitui as dimensões finais. Revise embalagem, quantidade, peso e medidas, além de desconsolidação e retirada no destino.']],
    questionsTitle:'O que combinar antes do embarque',
    questions:[['Um fornecedor atrasou: esperar ou dividir?','Liste a chegada prevista de cada fornecedor. Compare custo e prazo das opções, início da armazenagem paga e quem autoriza o embarque parcial. Não reserve apenas pela primeira fábrica pronta.'],['Paletizar altera a cotação?','Envie medidas, peso e limites de empilhamento originais. Combine paletização ou reembalagem separadamente e recalcule o transporte com os volumes finais.'],['Como confirmar o que será enviado?','Confira marcas, quantidades e embalagem por fornecedor. Separe faltantes e inspeções pendentes. Aprove a lista antes da saída e informe requisitos de fotos, relação de paletes ou entrega a um agente indicado.'],['Não há empilhadeira no recebimento?','Informe se é armazém, loja, residência ou obra, com doca e restrições de veículos. Confirme plataforma elevatória, pessoal, agendamento e espera. Entrega no endereço não define, por si só, a colocação dentro do imóvel.'],['O que conferir para retirar por conta própria?','Endereço, aviso de liberação, agendamento e taxas; depois medidas finais, peso, capacidade do veículo e carregamento. Inclua veículo, mão de obra e tempo próprios na comparação.']],
    photosTitle:'Embalagens diferentes no mesmo contêiner', photosIntro:'As fotos mostram formatos e necessidades de manuseio. Espaço disponível não substitui a conferência da embalagem e das cargas permitidas.',
    photos:[['Carga mista','Caixas, sacos e volumes envolvidos em filme: confirme medidas e limites de empilhamento antes do carregamento.'],['Caixotes e paletes durante o carregamento','Caixotes de madeira, paletes e carga agrupada durante a operação.'],['Paletes sobre caixotes','Há carga paletizada acima dos caixotes de madeira. Informe a estrutura da embalagem e as condições de empilhamento permitidas.'],['Sacos e caixas em camadas','Há material separador visível entre algumas camadas. Confira pesos reais e resistência da embalagem antes de decidir o que colocar acima.']],
    errorsTitle:'Caber não significa estar bem carregado.', errorsIntro:'Duas fotos de exemplos incorretos. Observe caixas deformadas, camadas deslocadas e espaços entre volumes.', errorLabel:'Exemplo incorreto',
    errors:[['Pilhas desiguais e caixas deformadas','Verifique cantos, áreas comprimidas e espaços entre sacos e caixas. Inspecione embalagem e mercadoria antes de decidir por reembalagem, rearranjo ou apoios adicionais.'],['Caixas inclinadas e camadas deslocadas','Algumas caixas estão visivelmente curvadas. Não acrescente carga só porque sobrou espaço: confira peso por caixa, limites de empilhamento e estado da embalagem.']],
    open:'Ver foto completa', sourcingTitle:'Ainda coordenando os pedidos?', sourcingBody:'Prazos das fábricas, quantidades e divergências fazem parte da preparação das compras. Consulte o serviço separado de consolidação e entrega para exportação.', sourcingLink:'Consolidação de compras e exportação',
    briefTitle:'Dados para comparar as cotações', brief:'Produto e uso, fotos da embalagem, quantidade de volumes, dimensões externas, peso bruto, endereço de coleta na China, data de prontidão, endereço final e escopo até o porto ou a porta.', scope:'Confirme o que está incluído na origem, frete marítimo, operações no destino, tributos e entrega.'
  },
  tr: {
    title:'Çin’den parsiyel denizyolu taşımacılığı: tüm süreci planlayın',
    intro:'Birkaç koli, birkaç palet veya farklı tedarikçilerin siparişleri mi? Son ambalaj ve teslimat adresiyle başlayın. Navlun, depo işlemleri ve varış teslimini tek teklifte karşılaştırın.',
    quote:'LCL teklifi isteyin', nav:['Yük uygunluğu','Maliyet karşılaştırma','Yükleme fotoğrafları','Hatalı örnekler','Teklif bilgileri'],
    fitTitle:'Önce yükü netleştirin, sonra taşıma planını.',
    fit:[['Ambalajlar istiflenebilir mi?','Her parçanın ölçülerini, brüt ağırlığını ve ambalaj fotoğraflarını paylaşın. Kırılgan, uzun, ağır veya istiflenemeyen yükü önceden belirtin. Pil ve sıvı kabulünü ayrıca teyit edin.'],['Depo kabul kapanışına yetişir mi?','Depo adresini, giriş referansını, randevuyu ve son kabul zamanını doğrulayın. Fabrikada hazır olma ve depoya varış farklı tarihlerdir. Gecikmede seferi ve depolamayı yeniden görüşün.'],['Varışta yükü kim teslim alır?','Ayrıştırma deposunu, serbest bırakma koşullarını, teslim alma randevusunu ve boşaltma ekipmanını teyit edin. Liman, depo ve son adrese teslim kapsamlarını ayırın.']],
    costsTitle:'Konsolidasyon nerede tasarruf sağlayabilir?', costsIntro:'Aynı yük ve teslimat adresi için iki seçeneği de isteyin. Yalnızca deniz navlununu değil, toplam masrafı karşılaştırın.',
    costs:[['Sevkiyat başına asgari ücretler','Ayrı gönderilerde her parti için çıkış ve varış asgari ücretlerini kontrol edin. Birleştirmede kabul, konsolidasyon ve ilave elleçleme ücretlerini inceleyin.'],['Bekleme ve depolama','Ücretsiz sürenin her kabulde mi yoksa tüm yük tamamlandığında mı başladığını teyit edin. Tedarikçi teslimlerini planlayıp bekleme ile ayrı gönderileri karşılaştırın.'],['Nihai ücretlendirilen hacim','Palet öncesi hacim, bitmiş ambalaj ölçülerinin yerine geçmez. Ambalaj ücreti, nihai adet, ağırlık ve ölçülerle varış ayrıştırma ve teslim alma masraflarını gözden geçirin.']],
    questionsTitle:'Sevkiyattan önce kararlaştırılacaklar',
    questions:[['Bir tedarikçi gecikti: beklemeli mi, bölmeli mi?','Her tedarikçinin beklenen geliş tarihini listeleyin. İki seçeneğin maliyet ve süresini, ücretli depolamanın başlangıcını ve kısmi sevkiyatı kimin onaylayacağını karşılaştırın. Yalnızca ilk hazır fabrikaya göre rezervasyon yapmayın.'],['Paletleme teklifi değiştirir mi?','İlk koli ölçülerini, ağırlığını ve istif sınırlarını verin. Paletleme veya yeniden ambalajlama ücretini ayrı kararlaştırın; taşımayı nihai paketler üzerinden yeniden hesaplayın.'],['Bu sevkiyatın içeriği nasıl onaylanır?','Tedarikçi bazında işaretleri, adetleri ve ambalajı kontrol edin. Eksikleri ve bekleyen kontrolleri ayırın. Çıkıştan önce listeyi onaylayın; fotoğraf, palet listesi veya belirlenen nakliyeciye teslim gereksinimlerini önceden bildirin.'],['Teslimat yerinde forklift yoksa?','Depo, mağaza, konut veya şantiye olduğunu; rampa ve araç kısıtlarını belirtin. Liftli araç, işçi, randevu ve bekleme ihtiyacını teyit edin. Adrese teslim, tek başına bina içine taşımayı kapsamaz.'],['Yükü kendim alacaksam neyi kontrol etmeliyim?','Adres, teslim izni, randevu ve ücretler; ardından nihai ölçü, ağırlık, araç kapasitesi ve yükleme düzeni. Kendi araç, işçilik ve zaman maliyetinizi de karşılaştırmaya katın.']],
    photosTitle:'Aynı konteynerde farklı ambalajlar', photosIntro:'Fotoğraflar paket biçimini ve elleçleme ihtiyacını gösterir. Boş alan, ambalaj ve izin verilen yüklerin kontrolünün yerine geçmez.',
    photos:[['Karma yük','Koliler, çuvallar ve streçli yükler: yüklemeden önce ölçü ve istif sınırlarını teyit edin.'],['Sandık ve palet yükleme süreci','Yükleme sırasında ahşap sandıklar, paletler ve gruplanmış mallar.'],['Sandıkların üzerinde paletler','Ahşap sandıkların üzerinde paletli yük görülüyor. Ambalaj yapısını ve izin verilen istif koşullarını belirtin.'],['Çuval ve koli katmanları','Bazı katmanlar arasında ayırıcı malzeme görülüyor. Üste ne konacağını belirlemeden önce gerçek ağırlığı ve ambalaj dayanımını kontrol edin.']],
    errorsTitle:'Sığması, doğru yüklendiği anlamına gelmez.', errorsIntro:'Bu iki fotoğraf hatalı örneklerdir. Deforme kolilere, kaymış katmanlara ve paket aralarındaki boşluklara bakın.', errorLabel:'Hatalı örnek',
    errors:[['Düzensiz istif ve deforme koliler','Köşeleri, ezilmiş alanları ve çuval-koli boşluklarını kontrol edin. Yeniden ambalajlama, yer değiştirme veya ek destek kararından önce ambalajı ve ürünü inceleyin.'],['Eğilmiş koliler ve kaymış katmanlar','Bazı koliler belirgin biçimde bükülmüş. Sırf boşluk kaldı diye yük eklemeyin; önce koli ağırlığı, istif sınırı ve ambalaj durumunu kontrol edin.']],
    open:'Fotoğrafı tam aç', sourcingTitle:'Tedarikçi siparişlerini hâlâ koordine ediyor musunuz?', sourcingBody:'Fabrika tarihleri, sipariş adetleri ve uyuşmazlıklar satın alma hazırlığının parçasıdır. Bunun için ayrı sipariş konsolidasyonu ve ihracata teslim hizmetini inceleyin.', sourcingLink:'Satın alma konsolidasyonu ve ihracat',
    briefTitle:'Karşılaştırılabilir teklif için bilgiler', brief:'Ürün ve kullanım amacı, ambalaj fotoğrafları, paket adedi, dış ölçüler, brüt ağırlık, Çin’de alım adresi, hazır olma tarihi, varış adresi ve limana ya da kapıya teslim kapsamı.', scope:'Çıkış masrafları, deniz navlunu, varış işlemleri, vergiler ve teslimatta nelerin dahil olduğunu teyit edin.'
  },
};
