import { freightPrefix, words, type FreightLocale } from './regions';
import ImportOrderPlanning from './ImportOrderPlanning';

export function mexicoMetadata(locale: FreightLocale) {
  return {
    title: words('中国到墨西哥货运｜海运、进口准备与内陆交付 | DDNZ Global','Shipping from China to Mexico | Sea Freight & Delivery | DDNZ Global','Envíos de China a México | Transporte marítimo y entrega | DDNZ Global')[locale],
    desc: words('按墨西哥收货城市、货物和交付范围规划整柜拼箱。核对进口方、产品资料、目的地费用及内陆配送安排，再比较完整运输方案。','Plan China–Mexico FCL and LCL around the receiving city, cargo and delivery scope. Review importer details, product documentation, destination charges and inland delivery.','Planificar FCL y LCL de China a México según carga, ciudad y alcance. Revisar importador, documentación, gastos en destino y entrega interior.')[locale],
    keywords: 'China Mexico shipping, FCL, LCL, Mexico freight, envíos China México',
  };
}

export default function MexicoContent({locale}: {locale: FreightLocale}) {
  const t = (zh:string,en:string,es:string) => words(zh,en,es)[locale];
  const prefix = freightPrefix(locale);
  const quote = `${prefix}/get-a-quote/?leadGoal=Freight+Export&source=mexico_country&dest=Mexico`;
  const costs = [
    [t('中国端','Origin in China','Origen en China'),t('提货、集货、包装处理、装柜和出口操作。','Pickup, consolidation, packing work, loading and export handling.','Recogida, consolidación, embalaje, carga y gestión de exportación.')],
    [t('国际运输','International freight','Transporte internacional'),t('整柜或拼箱运费，以及报价列明的附加费。','FCL or LCL freight and the surcharges listed in the quotation.','Flete FCL o LCL y recargos especificados en la cotización.')],
    [t('墨西哥目的地','Destination in Mexico','Destino en México'),t('目的地操作、清关服务及适用税费，分别列明包含范围和付款方。','Destination handling, clearance services and applicable taxes, with inclusions and payer specified separately.','Manipulación en destino, despacho e impuestos aplicables, indicando lo incluido y quién paga.')],
    [t('内陆与额外费用','Inland and additional costs','Entrega interior y gastos adicionales'),t('车辆配送、卸货，以及查验、等待、仓储等可能发生的费用。','Vehicle delivery, unloading and potential inspection, waiting or storage charges.','Reparto, descarga y posibles gastos de inspección, espera o almacenaje.')],
  ];
  return <main id="main-content" className="freight-editorial freight-next mexico-page">
    <header className="freight-cover"><div className="freight-cover-copy"><a className="uae-back" href={`${prefix}/shipping-from-china-to-latin-america/`}>← {t('拉美货运','Latin America freight','Transporte a Latinoamérica')}</a><p className="freight-kicker">CHINA → MÉXICO</p><h1>{t('中国到墨西哥。','China to Mexico.','De China a México.')}<br/><em>{t('到港之后，\n还要走多远？','Beyond the port,\nwhere next?','Después del puerto,\n¿hasta dónde?')}</em></h1><p>{t('收货在墨西哥城、瓜达拉哈拉，还是蒙特雷？先明确最终地址、进口方和卸货条件，再把海运与内陆配送放进同一份方案。','Mexico City, Guadalajara or Monterrey? Start with the final address, importer and unloading conditions, then plan the ocean and inland legs together.','¿Ciudad de México, Guadalajara o Monterrey? Primero, dirección final, importador y condiciones de descarga; después, coordinar transporte marítimo e interior.')}</p><div className="freight-cover-actions"><a className="freight-cta" href={quote}>{t('询墨西哥运价','Request a Mexico quote','Cotizar envío a México')} ↗</a><a href="#mexico-scope">{t('先看报价范围','Compare quotation scope','Comparar el alcance')} ↓</a></div></div><div className="country-route-board"><p className="freight-kicker">PORT / IMPORTER / FINAL ADDRESS</p><h2>{t('同一个目的国，\n不同的交付终点。','One country.\nDifferent delivery points.','Un país.\nDistintos puntos de entrega.')}</h2><ol>{[t('到港：谁接后面的清关与提货？','To port: who handles clearance and collection?','Hasta puerto: ¿quién despacha y recoge?'),t('到仓：地址、预约和卸货怎么安排？','To warehouse: address, appointment and unloading?','Hasta almacén: ¿dirección, cita y descarga?'),t('分批：哪些货先走，哪些一起走？','Split shipments: what moves now or together?','Por lotes: ¿qué sale primero o junto?')].map((item,i)=><li key={item}><span>0{i+1}</span>{item}</li>)}</ol></div></header>
    <nav className="freight-chapters" aria-label={t('本页内容','On this page','En esta página')}><a href="#mexico-scope">01 / {t('交付范围','Delivery scope','Alcance')}</a><a href="#mexico-import">02 / {t('进口准备','Import preparation','Preparación')}</a><a href="#mexico-costs">03 / {t('费用拆分','Cost breakdown','Costos')}</a><a href="#mexico-quote">04 / {t('询价资料','Quote details','Cotización')}</a></nav>
    <section className="freight-wrap freight-section" id="mexico-scope"><div className="freight-section-heading"><p className="freight-kicker">01 / START WITH THE DESTINATION</p><h2>{t('先定收货点，\n再讨论路线。','Start with the address.\nThen compare routes.','Primero la dirección.\nDespués la ruta.')}</h2><p>{t('城市名称还不够。到港、到仓或到门对应不同的责任和费用，具体路线应结合可用船期、目的地操作和内陆段一起确认。','A city name is not enough. Port, warehouse and door delivery have different responsibilities and costs. Compare routes using available sailings, destination handling and inland transport.','La ciudad no basta. Puerto, almacén y domicilio implican responsabilidades y costos distintos. Comparar rutas según salidas disponibles, gestión en destino y transporte interior.')}</p></div><div className="uae-scope-list">{[
      [t('墨西哥城与周边','Mexico City and surroundings','Ciudad de México y alrededores'),t('提供完整地址及邮编，说明是商业仓库、门店还是工地；确认车辆通行、预约收货和卸货设备。','Provide the address and postcode, and identify warehouse, shop or jobsite delivery. Confirm vehicle access, appointments and unloading equipment.','Facilitar dirección y código postal; indicar almacén, tienda u obra. Confirmar acceso, cita y medios de descarga.')],
      [t('瓜达拉哈拉、蒙特雷等城市','Guadalajara, Monterrey and other cities','Guadalajara, Monterrey y otras ciudades'),t('不要把“到墨西哥”当成到任何城市的同一价格。将目的港至收货点的内陆段单列，核对货物重量、体积和收货时间。','Do not treat a Mexico rate as a price to every city. Quote the inland leg separately and confirm weight, volume and receiving hours.','Una tarifa a México no equivale a entrega en cualquier ciudad. Separar el tramo interior y confirmar peso, volumen y horario.')],
      [t('整柜与拼箱','FCL and LCL','FCL y LCL'),t('按货量、单件尺寸、包装及货好时间比较；多供应商订单先列清货单，再决定合并还是分批。','Compare volume, package dimensions, packing and ready dates. Reconcile multi-supplier orders before combining or splitting shipments.','Comparar volumen, medidas, embalaje y fechas. Conciliar pedidos de varios proveedores antes de consolidar o dividir.')],
    ].map(([title,body])=><article key={title}><span>{title}</span><p>{body}</p></article>)}</div><div className="freight-links"><a href={`${prefix}/services/sea-freight/#mixed-loads`}>{t('看中国端集货与装柜实拍','See consolidation and loading in China','Ver consolidación y carga en China')} →</a></div></section>
    <section className="freight-dark" id="mexico-import"><div className="freight-wrap freight-section"><p className="freight-kicker">02 / BEFORE THE BOOKING</p><h2>{t('进口资料，\n订舱前先核对。','Review import details\nbefore booking.','Revisar la importación\nantes de reservar.')}</h2><div className="uae-route-grid"><article><h3>{t('先明确进口方','Identify the importer','Identificar al importador')}</h3><p>{t('确认墨西哥进口主体及清关联系人，由其核对 RFC、进口商名录及适用的行业登记要求。不要等货到港后才开始找进口方。','Identify the Mexican importer and clearance contact. Have them check RFC, importer registration and applicable sector requirements before dispatch.','Definir importador y contacto de despacho en México. Solicitar la revisión del RFC, padrón de importadores y requisitos sectoriales aplicables antes del envío.')}</p><a href="https://www.sat.gob.mx/minisitio/PadronImportadoresExportadores/pi_inscripcion.html" target="_blank" rel="noreferrer">SAT · {t('进口商登记','Importer registration','Padrón de importadores')} ↗</a></article><article><h3>{t('按具体产品核对 NOM','Check NOM requirements by product','Revisar las NOM por producto')}</h3><p>{t('提供用途、型号、技术参数和标签照片，由进口方或报关代理结合税则归类核对适用的 NOM、认证及标签要求。不同产品不能照搬同一套文件。','Provide intended use, model, specifications and label photos. Ask the importer or customs broker to check applicable NOM, certification and labelling requirements against tariff classification.','Facilitar uso, modelo, especificaciones y fotos de etiquetas. El importador o agente aduanal debe revisar NOM, certificación y etiquetado según la clasificación arancelaria.')}</p><a href="https://www.snice.gob.mx/cs/avi/snice/seguridad.normatividad.html" target="_blank" rel="noreferrer">SNICE · {t('NOM 官方资料','Official NOM information','Normatividad NOM')} ↗</a></article></div><p className="uae-routing-note">{t('品名、数量、型号、金额及收发货信息应在发票、装箱单和运输文件中保持一致；具体申报材料由进口方和报关代理按货物确认。','Keep descriptions, quantities, models, values and parties consistent across invoice, packing list and transport documents. Confirm shipment-specific filing requirements with the importer and broker.','Mantener descripción, cantidades, modelos, valores y partes coherentes en factura, lista de empaque y documentos de transporte. Confirmar requisitos específicos con importador y agente aduanal.')}</p></div></section>
    <section className="freight-wrap freight-section" id="mexico-costs"><p className="freight-kicker">03 / COMPARE THE WHOLE SHIPMENT</p><h2>{t('比较的不是一个运价，\n是同一段服务。','Compare the same scope,\nnot just a freight rate.','Comparar el mismo alcance,\nno solo el flete.')}</h2><div className="mexico-cost-list">{costs.map(([title,body],i)=><article key={title}><span>0{i+1}</span><h3>{title}</h3><p>{body}</p></article>)}</div><p className="freight-intro">{t('询价时直接问：哪些已包含，哪些按实际发生，哪些由收货方支付？同时确认报价有效期和异常费用的通知方式。','Ask what is included, charged as incurred or paid by the consignee. Confirm quote validity and how additional charges will be communicated.','Preguntar qué está incluido, qué se cobra según lo ocurrido y qué paga el destinatario. Confirmar vigencia y comunicación de cargos adicionales.')}</p></section>
    <section className="freight-wrap freight-section" id="mexico-fieldwork"><p className="freight-kicker">MEXICO / AT THE WAREHOUSE</p><h2>{t('货柜到仓，\n看现场怎么卸货。','At the warehouse,\nsee the cargo being unloaded.','En el almacén,\nasí se descarga la mercancía.')}</h2><div className="country-field-films">{[
      ['5',t('墨西哥 · 车辆到仓与托盘搬运','Mexico · Arrival and pallet handling','México · Llegada y manejo de palés')],
      ['1',t('墨西哥 · 开柜现场','Mexico · Opening the container','México · Apertura del contenedor')],
      ['3',t('墨西哥 · 货物搬运入仓','Mexico · Moving cargo into the warehouse','México · Entrada de mercancías al almacén')],
    ].map(([id,title])=><figure key={id}><video controls playsInline muted preload="none" src={`/media/freight-20260919/mexico-${id}.mp4`} poster={`/media/freight-20260919/mexico-${id}.jpg`} aria-label={title}/><figcaption>{title}</figcaption></figure>)}</div></section>
    <ImportOrderPlanning locale={locale} market="mexico" />
    <section className="freight-destination-band" id="mexico-quote"><div className="freight-wrap freight-section"><p className="freight-kicker">04 / YOUR SHIPMENT BRIEF</p><h2>{t('货物、地址、进口方。\n从这三项开始。','Cargo. Address. Importer.\nStart here.','Carga, dirección e importador.\nEmpecemos por ahí.')}</h2><ul className="uae-brief">{[t('品名、用途、型号及包装照片','Product, use, model and packing photos','Producto, uso, modelo y fotos'),t('件数、单件尺寸、毛重与总货量','Package count, dimensions, gross weights and total volume','Bultos, medidas, pesos y volumen total'),t('中国提货地点、货好时间与供应商数量','China pickup locations, ready dates and supplier count','Recogida en China, fechas y número de proveedores'),t('墨西哥收货地址、邮编、进口方与清关联系人','Mexico address, postcode, importer and clearance contact','Dirección, código postal, importador y contacto de despacho'),t('到港还是到门、卸货条件与期望收货时间','Port or door scope, unloading conditions and target receiving date','Puerto o domicilio, descarga y fecha prevista')].map(item=><li key={item}>{item}</li>)}</ul><a className="freight-cta" href={quote}>{t('提交墨西哥货运需求','Send your Mexico freight inquiry','Consultar envío a México')} ↗</a></div></section>
  </main>;
}
