import { freightPrefix, words, type FreightLocale } from './regions';
import NigeriaInventory from './NigeriaInventory';

export function nigeriaMetadata(locale: FreightLocale) {
  return {
    title: words('中国到尼日利亚货运｜集货、海运与收货规划 | DDNZ Global', 'Shipping from China to Nigeria | Consolidation & Sea Freight | DDNZ Global', 'Envíos de China a Nigeria | Consolidación y transporte marítimo | DDNZ Global')[locale],
    desc: words('从中国多供应商集货，到尼日利亚到港、内陆收货与库存规划。按货物、收货城市和交付范围确认整柜拼箱及询价资料。', 'Plan supplier consolidation in China, sea freight to Nigeria and inland receiving. Align cargo, destination city, delivery scope and stock planning before requesting a quote.', 'Planificar consolidación en China, transporte marítimo a Nigeria y recepción interior. Aclarar carga, ciudad, alcance e inventario antes de cotizar.')[locale],
    keywords: 'China Nigeria shipping, Nigeria sea freight, supplier consolidation, FCL, LCL',
  };
}

export default function NigeriaContent({locale}: {locale: FreightLocale}) {
  const t = (zh: string, en: string, es: string) => words(zh,en,es)[locale];
  const prefix = freightPrefix(locale);
  const quote = `${prefix}/get-a-quote/?leadGoal=Freight+Export&source=nigeria_country&dest=Nigeria`;
  return <main id="main-content" className="freight-editorial freight-next nigeria-page">
    <header className="freight-cover">
      <div className="freight-cover-copy">
        <a className="uae-back" href={`${prefix}/shipping-from-china-to-west-africa/`}>← {t('西非货运', 'West Africa freight', 'Transporte a África Occidental')}</a>
        <p className="freight-kicker">CHINA → NIGERIA</p>
        <h1>{t('中国到尼日利亚。', 'China to Nigeria.', 'De China a Nigeria.')}<br/><em>{t('几家工厂的货，\n一起安排。', 'Several suppliers.\nOne shipment plan.', 'Varios proveedores.\nUn plan de envío.')}</em></h1>
        <p>{t('采购不只一家，收货也不一定在港口。从供应商交货、集货装柜，到拉各斯或内陆城市收货，先把每一段接起来。', 'Buying from several factories? Receiving beyond the port? Connect supplier pickup, consolidation and loading with receiving in Lagos or an inland city.', '¿Varios proveedores y recepción lejos del puerto? Coordinar recogida, consolidación y carga con la recepción en Lagos o el interior.')}</p>
        <div className="freight-cover-actions"><a className="freight-cta" href={quote}>{t('询尼日利亚运价', 'Request a Nigeria quote', 'Cotizar envío a Nigeria')} ↗</a><a href="#nigeria-consolidation">{t('先看集货怎么安排', 'Plan consolidation', 'Planificar la consolidación')} ↓</a></div>
      </div>
      <div className="country-route-board"><p className="freight-kicker">ORIGIN / DESTINATION / STOCK</p><h2>{t('报价前，\n先对齐这三件事。', 'Before the quote,\nalign three things.', 'Antes de cotizar,\naclarar tres puntos.')}</h2><ol>{[
        t('货在哪：供应商地点与货好时间', 'Origin: supplier locations and ready dates', 'Origen: proveedores y fechas'),
        t('送到哪：收货城市与具体地址', 'Destination: receiving city and address', 'Destino: ciudad y dirección'),
        t('怎么收：整批入仓或分批配送', 'Receiving: one intake or staged deliveries', 'Recepción: un lote o entregas parciales'),
      ].map((item,i)=><li key={item}><span>0{i+1}</span>{item}</li>)}</ol><a href="#inventory-planning">{t('看库存与补货安排', 'Stock and replenishment planning', 'Inventario y reposición')} ↓</a></div>
    </header>
    <nav className="freight-chapters" aria-label={t('本页内容','On this page','En esta página')}><a href="#nigeria-consolidation">01 / {t('中国集货','Consolidation','Consolidación')}</a><a href="#nigeria-receiving">02 / {t('收货城市','Receiving city','Ciudad de recepción')}</a><a href="#inventory-planning">03 / {t('库存安排','Stock planning','Inventario')}</a><a href="#nigeria-documents">04 / {t('出运准备','Before shipment','Antes del envío')}</a></nav>
    <section className="freight-wrap freight-section" id="nigeria-consolidation"><div className="freight-section-heading"><p className="freight-kicker">01 / BEFORE THE CONTAINER</p><h2>{t('先把货单理清，\n再决定怎么装。','Reconcile the cargo.\nThen plan the load.','Conciliar la carga.\nDespués, planificar.')}</h2><p>{t('同一批采购里，纸箱、木箱和托盘可能来自不同工厂。把包装和到货时间一起核对，才能判断整柜、拼箱或分批出运。','Cartons, crates and pallets may arrive from different factories. Compare packaging and ready dates before choosing FCL, LCL or separate shipments.','Cajas y palés pueden proceder de fábricas distintas. Comparar embalajes y fechas antes de elegir FCL, LCL o envíos separados.')}</p></div>
      <div className="uae-scope-list">{[
        [t('多供应商集货','Supplier consolidation','Consolidación'),t('按供应商列出品名、件数、毛重、尺寸和货好时间。还没齐的货，要明确等货还是先发；混装前核对包装承重和堆码条件。','List products, counts, gross weights, dimensions and ready dates by supplier. Decide whether to wait for late cargo or ship separately; check packaging strength and stacking before loading.','Listar productos, bultos, pesos, medidas y fechas por proveedor. Decidir si esperar o separar los envíos; comprobar resistencia y apilado.')],
        [t('整柜还是拼箱','FCL or LCL','FCL o LCL'),t('不要只比较海运费。把中国端集货与操作费、目的地处理、提货和最终配送放进同一份费用清单，标出各自包含的范围。','Compare more than ocean freight. Put origin consolidation, handling, destination charges, collection and final delivery in one cost breakdown with clear inclusions.','Comparar también consolidación, manipulación, gastos en destino, recogida y reparto final, indicando lo incluido en cada partida.')],
      ].map(([title,body])=><article key={title}><span>{title}</span><p>{body}</p></article>)}</div>
      <div className="freight-links"><a href={`${prefix}/services/sea-freight/#mixed-loads`}>{t('看中国端集货与装柜实拍','See origin consolidation and loading','Ver consolidación y carga en origen')} →</a></div>
    </section>
    <section className="freight-dark" id="nigeria-receiving"><div className="freight-wrap freight-section"><p className="freight-kicker">02 / BEYOND THE PORT</p><h2>{t('到拉各斯，\n还是继续往内陆？','Receiving in Lagos,\nor moving inland?','¿Recepción en Lagos\no traslado al interior?')}</h2><div className="uae-route-grid"><article><h3>{t('拉各斯收货','Receiving in Lagos','Recepción en Lagos')}</h3><p>{t('先确认具体提货点和收货地址。谁负责清关、港口提货、车辆预约和卸货，应在报价前逐项明确。','Confirm the collection point and receiving address. Agree who handles clearance, port collection, vehicle booking and unloading before quoting.','Confirmar recogida y dirección. Acordar quién gestiona despacho, retirada, vehículo y descarga antes de cotizar.')}</p></article><article><h3>{t('奥尼查、卡诺等内陆城市','Onitsha, Kano and inland cities','Onitsha, Kano y otras ciudades')}</h3><p>{t('把海运段和内陆段分开看。提供收货城市、地址、单件重量、卸货条件与可收货时段，再讨论转运车辆和费用。','Separate the ocean and inland legs. Share the city, address, package weights, unloading facilities and receiving hours to discuss vehicles and costs.','Separar tramo marítimo e interior. Facilitar ciudad, dirección, pesos, medios de descarga y horario para evaluar vehículo y costo.')}</p></article></div></div></section>
    <NigeriaInventory locale={locale}/>
    <section className="freight-destination-band" id="nigeria-documents"><div className="freight-wrap freight-section"><p className="freight-kicker">04 / CHECK BEFORE DISPATCH</p><h2>{t('文件准备，\n别等到装柜之后。','Check the paperwork\nbefore loading.','Revisar documentos\nantes de cargar.')}</h2><ul className="country-document-list">
      <li><h3>{t('产品与包装','Product and packing','Producto y embalaje')}</h3><p>{t('品名、用途、型号、数量、包装尺寸和重量先对齐。货单、发票与产品资料中的描述应一致。','Align descriptions, intended use, models, quantities, dimensions and weights across the packing list, invoice and product information.','Alinear descripción, uso, modelo, cantidades, medidas y pesos en lista de empaque, factura y ficha de producto.')}</p></li>
      <li><h3>{t('进口方与文件','Importer and documents','Importador y documentos')}</h3><p>{t('明确尼日利亚进口方和清关联系人，出运前核对 Form M、PAAR 及产品适用的监管文件安排。SONCAP 针对其监管范围内的产品，不能把所有货物都按同一套材料处理。','Identify the Nigerian importer and clearance contact. Review Form M, PAAR and applicable product documents before dispatch. SONCAP applies to regulated products; requirements should be checked by product.','Identificar importador y contacto de despacho. Revisar Form M, PAAR y documentos aplicables antes de enviar. SONCAP corresponde a productos regulados; comprobar según el producto.')}</p></li>
      <li><h3>{t('费用与责任','Costs and responsibilities','Costos y responsabilidades')}</h3><p>{t('逐项确认报价包含的操作、税费与配送范围，以及查验、等待、仓储等额外费用由谁承担。','Confirm included handling, taxes and delivery, plus responsibility for additional inspection, waiting and storage costs.','Confirmar manipulación, impuestos y reparto incluidos, y quién asume inspección, espera o almacenaje adicionales.')}</p></li>
    </ul><div className="freight-links"><a href="https://son.gov.ng/soncap-faq/" target="_blank" rel="noreferrer">SONCAP · {t('官方说明','Official guidance','Guía oficial')} ↗</a><a href="https://customs.gov.ng/wp-content/uploads/2025/06/Import-and-Export-Procedure-Corrected_Final.pdf" target="_blank" rel="noreferrer">{t('尼日利亚海关 · 进出口流程','Nigeria Customs · Import procedures','Aduana de Nigeria · Procedimientos')} ↗</a></div></div></section>
    <section className="freight-wrap freight-section" id="nigeria-fieldwork"><p className="freight-kicker">LAGOS / ON THE GROUND</p><h2>{t('从拆柜入仓，\n到现场提货。','From container unloading\nto collection.','De la descarga\na la recogida.')}</h2><div className="country-field-films">{[
      ['lagos-unloading',t('拉各斯 · 拆柜入仓','Lagos · Unloading into storage','Lagos · Descarga y almacenaje')],
      ['lagos-transfer',t('拉各斯 · 仓库货物转运','Lagos · Cargo transfer','Lagos · Traslado de mercancías')],
      ['lagos-collection',t('拉各斯 · 客户提货登记','Lagos · Customer collection registration','Lagos · Registro de recogida')],
    ].map(([asset,title])=><figure key={asset}><video controls playsInline muted preload="none" src={`/media/freight-20260919/${asset}.mp4`} poster={`/media/freight-20260919/${asset}.jpg`} aria-label={title}/><figcaption>{title}</figcaption></figure>)}</div></section>
    <section className="freight-wrap freight-section" id="nigeria-quote"><p className="freight-kicker">NEXT / YOUR SHIPMENT</p><h2>{t('把货单和收货城市发来。','Send the cargo list\nand receiving city.','Enviar la lista de carga\ny la ciudad de recepción.')}</h2><ul className="uae-brief">{[t('品名、件数、尺寸、毛重与包装照片','Products, counts, dimensions, gross weights and packing photos','Productos, bultos, medidas, pesos y fotos'),t('每家供应商地点与货好时间','Location and ready date for each supplier','Ubicación y fecha de cada proveedor'),t('尼日利亚收货地址与进口联系人','Nigerian receiving address and importer contact','Dirección en Nigeria y contacto importador'),t('到港或到门、期望收货时间、是否分批','Port or door, target receiving date and split-shipment needs','Puerto o domicilio, fecha y necesidad de envíos parciales')].map(item=><li key={item}>{item}</li>)}</ul><a className="freight-cta" href={quote}>{t('提交尼日利亚货运需求','Send your Nigeria freight inquiry','Consultar envío a Nigeria')} ↗</a></section>
  </main>;
}
