import { words, type FreightLocale } from './regions';

export default function NigeriaInventory({ locale, sectionNumber = '03' }: { locale: FreightLocale; sectionNumber?: string }) {
  const t = (zh: string, en: string, es: string) => words(zh, en, es)[locale];
  const items = [
    [t('订单还分散：先保留调配余地', 'Scattered orders: keep stock flexible', 'Pedidos dispersos: mantener flexibilidad'), t('先整理已付款订单的城市、SKU、数量与配送成本。如果客户分布还在变化，不宜只因某地仓租便宜就分散库存。', 'Map paid orders by city, SKU, quantity and delivery cost. If demand is still changing, lower rent alone is not a reason to split stock.', 'Registrar ciudad, SKU, cantidad y costo de entrega de pedidos pagados. Un alquiler menor no basta para repartir inventario.')],
    [t('有稳定复购：小批量测试前置库存', 'Repeat orders: test a small forward stock', 'Compras recurrentes: probar un stock pequeño'), t('当奥尼查等地区已有稳定整箱复购，可比较从拉各斯逐单配送与小批量补货的成本。先试一轮，不急于整批搬仓。', 'With stable repeat orders around markets such as Onitsha, compare delivery from Lagos with small replenishment batches. Test before moving the full inventory.', 'Con compras recurrentes en mercados como Onitsha, comparar reparto desde Lagos y reposición en lotes pequeños. Probar antes de trasladar todo.')],
    [t('内陆交付：先算补货周期', 'Inland delivery: work out the replenishment cycle', 'Entrega interior: calcular la reposición'), t('面向卡诺等内陆客户时，把干线运输、收货时间、库存查询和退货安排一起核算。库存离客户近，不代表整条链路一定更省。', 'For inland customers in markets such as Kano, assess linehaul, receiving time, stock visibility and returns together. Closer stock does not automatically lower total cost.', 'Para clientes interiores, como en Kano, evaluar transporte, recepción, visibilidad y devoluciones. La cercanía no garantiza menor costo total.')],
  ];
  return <section className="freight-editorial" id="inventory-planning"><div className="freight-wrap freight-section"><p className="freight-kicker">{sectionNumber} / STOCK & REPLENISHMENT</p><h2 className="mt-4">{t('库存跟着订单走，\n不先跟着仓租走。', 'Let orders guide\nstock placement.', 'Que los pedidos guíen\nel inventario.')}</h2><p className="freight-intro mt-5">{t('第一批货放在哪里，先看订单来自哪些城市、哪些产品卖得快，以及下一批货什么时候能补上。', 'Decide where to stock the first shipment by looking at order locations, fast-selling products and when the next batch can arrive.', 'Decidir dónde almacenar según las ciudades de los pedidos, los productos de mayor salida y la llegada del siguiente lote.')}</p><div className="freight-steps">{items.map(([title, body]) => <article key={title}><h3>{title}</h3><p>{body}</p></article>)}</div><p className="mt-8 border-t border-slate-200 pt-5 text-sm text-slate-500">{t('询价时可附：收货城市、每月订单量、热销 SKU、现有库存与配送要求。仓储地点、费用和执行方按具体需求确认。', 'Share delivery cities, monthly orders, leading SKUs, current inventory and delivery needs. Confirm storage location, cost and operator for the specific shipment.', 'Compartir ciudades, pedidos mensuales, SKU principales, inventario y necesidades. Confirmar ubicación, costo y operador para cada envío.')}</p></div></section>;
}
