import { useEffect } from 'react';
import type { Language } from '../../i18n/translations';
import './freight.css';

type EvidenceCopy = {
  kicker: string; receivingTitle: string; loadingTitle: string; receivingVideo: string; receivingCaption: string;
  loadingAlt: string; loadingCaption: string; seaLink: string; consolidationLink: string;
  receiving: string[][]; loading: string[][];
};

const prefix: Record<Language, string> = { en: '', zh: '/zh-cn', ru: '/ru', fr: '/fr', es: '/es', ar: '/ar', pt: '/pt', tr: '/tr' };
const copy: Record<Language, EvidenceCopy> = {
  en: { kicker: 'China-origin operations', receivingTitle: 'Receiving starts with the carton marks.', loadingTitle: 'A shipment is more than the space it fills.', receivingVideo: 'Receiving and label checks, silent video', receivingCaption: 'Receiving · Carton marks and label checks', loadingAlt: 'Mixed cartons, bags and pallets inside a container', loadingCaption: 'Mixed loading · Cartons, bags and pallets', seaLink: 'Explore sea freight', consolidationLink: 'Explore consolidation and handover', receiving: [['Match the receiving list','Match supplier, order, carton marks and package counts. Record discrepancies separately.'],['Separate receiving from inspection','Counting and label checks are not an unpacking or functional inspection. Agree any extra inspection or repacking scope.'],['Confirm the handover after reconciliation','Reconcile shortages, packing differences and open items; confirm which goods ship now or later.']], loading: [['Look beyond cubic metres','Cartons, bags, pallets and crates have different stacking constraints. Share package dimensions, gross weights and packing photos.'],['Keep the plan and field record distinct','A loading simulation supports planning; photographs record actual condition. Different inputs are not a before-and-after comparison.'],['Make the quotation scope explicit','Confirm pickup, storage, repacking, loading, origin and destination charges. Port and door quotes cover different scopes.']] },
  zh: { kicker: '中国端操作记录', receivingTitle: '收货时，把箱号与数量对上。', loadingTitle: '一柜货，不只是装得下。', receivingVideo: '收货核标现场，无声视频', receivingCaption: '收货现场 · 箱号与标签核对', loadingAlt: '柜内纸箱、袋装货与托盘的混合装载现场', loadingCaption: '拼柜现场 · 纸箱、袋装货与托盘', seaLink: '查看海运安排', consolidationLink: '查看集货与出口交接', receiving: [['对照到货清单','把供应商、订单、箱号与到货件数对应起来；差异单独列出。'],['区分收货与验货','点数和核标不等于开箱或功能检查，额外范围需另行确认。'],['齐货后再确认交接','汇总缺货、包装差异与待确认事项，明确本票或下一票出运。']], loading: [['先看包装，不只看立方数','纸箱、袋装、托盘和木箱的堆叠条件不同，需提供尺寸、毛重和包装照片。'],['把方案与现场分开记录','模拟图用于规划，现场照片记录实际状态；不同输入不能直接比较。'],['把报价范围写清楚','逐项确认提货、仓储、重包装、装柜及目的地费用。']] },
  ru: { kicker: 'Операции в Китае', receivingTitle: 'Приемка начинается с маркировки коробок.', loadingTitle: 'Отправка — это больше, чем занятый объем.', receivingVideo: 'Приемка и проверка маркировки, видео без звука', receivingCaption: 'Приемка · Маркировка и этикетки', loadingAlt: 'Смешанный груз из коробок, мешков и паллет в контейнере', loadingCaption: 'Смешанная загрузка · Коробки, мешки и паллеты', seaLink: 'Морские перевозки', consolidationLink: 'Консолидация и передача', receiving: [['Сверить список приемки','Сопоставьте поставщика, заказ, маркировку и количество; расхождения запишите отдельно.'],['Отделить приемку от инспекции','Подсчет и этикетки не заменяют вскрытие или функциональную проверку.'],['Подтвердить передачу','Сверьте недостачу, упаковку и открытые вопросы; определите текущую и следующую отправку.']], loading: [['Учитывать не только объем','У коробок, мешков, паллет и ящиков разные ограничения по штабелированию.'],['Разделять план и факт','Симуляция поддерживает планирование, фотографии фиксируют фактическое состояние.'],['Зафиксировать объем котировки','Подтвердите забор, хранение, переупаковку, погрузку и расходы назначения.']] },
  fr: { kicker: 'Opérations en Chine', receivingTitle: 'La réception commence par les marques des cartons.', loadingTitle: 'Un envoi ne se résume pas au volume occupé.', receivingVideo: 'Réception et contrôle des étiquettes, vidéo muette', receivingCaption: 'Réception · Marques et étiquettes', loadingAlt: 'Cartons, sacs et palettes mélangés dans un conteneur', loadingCaption: 'Chargement mixte · Cartons, sacs et palettes', seaLink: 'Voir le fret maritime', consolidationLink: 'Voir consolidation et transmission', receiving: [['Rapprocher la liste','Associer fournisseur, commande, marques et colis ; isoler les écarts.'],['Distinguer réception et inspection','Le comptage et les étiquettes ne remplacent ni ouverture ni test fonctionnel.'],['Confirmer la transmission','Rapprocher manquants, emballages et points ouverts ; confirmer ce qui part maintenant.']], loading: [['Voir au-delà du volume','Cartons, sacs, palettes et caisses ont des contraintes d’empilage différentes.'],['Séparer plan et constat','La simulation sert au plan ; les photos enregistrent l’état réel.'],['Préciser le périmètre du devis','Confirmer enlèvement, stockage, reconditionnement, chargement et frais de destination.']] },
  es: { kicker: 'Operaciones en China', receivingTitle: 'La recepción empieza por las marcas de los bultos.', loadingTitle: 'Un envío es más que el espacio que ocupa.', receivingVideo: 'Recepción y etiquetas, video sin sonido', receivingCaption: 'Recepción · Marcas y etiquetas', loadingAlt: 'Cajas, sacos y palés en un contenedor', loadingCaption: 'Carga mixta · Cajas, sacos y palés', seaLink: 'Ver transporte marítimo', consolidationLink: 'Ver consolidación y entrega', receiving: [['Comparar con la lista','Relacionar proveedor, pedido, marcas y bultos; registrar diferencias por separado.'],['Distinguir recepción e inspección','Contar y revisar etiquetas no equivale a abrir o probar el producto.'],['Confirmar la entrega','Conciliar faltantes, embalaje y pendientes; confirmar qué sale ahora.']], loading: [['No mirar solo los metros cúbicos','Cajas, sacos, palés y cajones tienen distintas limitaciones.'],['Separar plan y registro','La simulación planifica; las fotos registran el estado real.'],['Definir el alcance de la cotización','Confirmar recogida, almacenaje, reembalaje, carga y gastos en destino.']] },
  ar: { kicker: 'عمليات المنشأ في الصين', receivingTitle: 'يبدأ الاستلام من علامات الكراتين.', loadingTitle: 'الشحنة أكبر من المساحة التي تشغلها.', receivingVideo: 'الاستلام وفحص الملصقات، فيديو صامت', receivingCaption: 'الاستلام · علامات الكراتين والملصقات', loadingAlt: 'كراتين وأكياس ومنصات داخل الحاوية', loadingCaption: 'تحميل مختلط · كراتين وأكياس ومنصات', seaLink: 'استكشف الشحن البحري', consolidationLink: 'استكشف التجميع والتسليم', receiving: [['مطابقة قائمة الاستلام','طابق المورد والطلب والعلامات والعدد، وسجل الفروقات منفصلة.'],['فصل الاستلام عن الفحص','العد وفحص الملصقات لا يساوي فتح المنتج أو اختبار الوظائف.'],['تأكيد التسليم بعد المطابقة','راجع النقص واختلاف التعبئة وحدد ما يشحن الآن أو لاحقاً.']], loading: [['تجاوز حساب الحجم','للكراتين والأكياس والمنصات والصناديق قيود تكديس مختلفة.'],['افصل الخطة عن السجل','المحاكاة للتخطيط والصور لتوثيق الحالة الفعلية.'],['حدد نطاق العرض','أكد الاستلام والتخزين وإعادة التعبئة والتحميل ورسوم الوجهة.']] },
  pt: { kicker: 'Operações na origem na China', receivingTitle: 'O recebimento começa pelas marcas das caixas.', loadingTitle: 'Um embarque é mais que o espaço ocupado.', receivingVideo: 'Recebimento e etiquetas, vídeo sem som', receivingCaption: 'Recebimento · Marcas e etiquetas', loadingAlt: 'Caixas, sacos e paletes dentro do contêiner', loadingCaption: 'Carga mista · Caixas, sacos e paletes', seaLink: 'Explorar frete marítimo', consolidationLink: 'Explorar consolidação e entrega', receiving: [['Conferir a lista','Relacione fornecedor, pedido, marcas e volumes; registre diferenças separadamente.'],['Separar recebimento de inspeção','Contagem e etiquetas não substituem abertura ou teste funcional.'],['Confirmar a entrega','Concilie faltas, embalagem e pendências; confirme o que embarca agora.']], loading: [['Olhar além do volume','Caixas, sacos, paletes e engradados têm limites diferentes.'],['Separar plano e registro','A simulação planeja; as fotos registram a condição real.'],['Definir o escopo da cotação','Confirme coleta, armazenagem, reembalagem, carga e despesas no destino.']] },
  tr: { kicker: 'Çin çıkış operasyonları', receivingTitle: 'Teslim alma koli işaretleriyle başlar.', loadingTitle: 'Bir sevkiyat kapladığı hacimden fazlasıdır.', receivingVideo: 'Teslim alma ve etiket kontrolü, sessiz video', receivingCaption: 'Teslim alma · Koli işaretleri ve etiketler', loadingAlt: 'Konteyner içinde karışık koli, çuval ve paletler', loadingCaption: 'Karışık yükleme · Koli, çuval ve palet', seaLink: 'Denizyolu taşımacılığını inceleyin', consolidationLink: 'Konsolidasyon ve teslimi inceleyin', receiving: [['Teslim listesini eşleştir','Tedarikçi, sipariş, koli işareti ve sayıyı eşleştirin; farkları ayrı kaydedin.'],['Teslim alma ile kontrolü ayır','Sayım ve etiket kontrolü ürün açma veya işlev testinin yerine geçmez.'],['Teslimi onayla','Eksik, ambalaj farkı ve açık konuları uzlaştırın; şimdi sevk edilecekleri belirleyin.']], loading: [['Hacmin ötesine bak','Koli, çuval, palet ve sandıkların istif koşulları farklıdır.'],['Plan ile kaydı ayır','Simülasyon planlar; fotoğraf gerçek durumu kaydeder.'],['Teklif kapsamını netleştir','Alım, depolama, yeniden paketleme, yükleme ve varış ücretlerini doğrulayın.']] },
};

export default function OperationsEvidence({ locale = 'en', receiving = false }: { locale?: Language; receiving?: boolean }) {
  const sectionId = receiving ? 'receiving-record' : 'loading-proof-title';
  useEffect(() => {
    if (window.location.hash !== `#${sectionId}`) return;
    const frame = requestAnimationFrame(() => document.getElementById(sectionId)?.scrollIntoView({ block: 'start' }));
    return () => cancelAnimationFrame(frame);
  }, [sectionId]);
  const t = copy[locale];
  const steps = receiving ? t.receiving : t.loading;
  return <section className="freight-editorial freight-evidence" id={sectionId} lang={locale === 'zh' ? 'zh-CN' : locale} dir={locale === 'ar' ? 'rtl' : 'ltr'}>
    <div className="freight-wrap freight-section">
      <p className="freight-kicker">{t.kicker}</p>
      <h2 className="mt-4 mb-8">{receiving ? t.receivingTitle : t.loadingTitle}</h2>
      <div className="freight-media">
        <figure>
          {receiving ? <video controls playsInline preload="none" poster="/media/freight-20260918/receiving-poster.jpg" muted className="mx-auto max-h-[580px] w-full rounded-xl bg-slate-950" aria-label={t.receivingVideo} src="/media/freight-20260918/receiving-silent.mp4" /> : <img src="/media/freight-20260918/mixed-cargo-loading.jpg" alt={t.loadingAlt} loading="lazy" decoding="async" />}
          <figcaption>{receiving ? t.receivingCaption : t.loadingCaption}</figcaption>
        </figure>
        <div>{steps.map(([title, body], i) => <article className="freight-check" key={title}><span>0{i + 1}</span><div><h3>{title}</h3><p>{body}</p></div></article>)}
          <div className="freight-links"><a href={`${prefix[locale]}/${receiving ? 'services/sea-freight/' : 'sourcing-services/consolidation-export/'}`}>{receiving ? t.seaLink : t.consolidationLink} →</a></div>
        </div>
      </div>
    </div>
  </section>;
}
