import { freightPrefix, regions, words, type FreightLocale, type RegionId } from './regions';

/** Shared by the browser and static HTML renderer; keep this free of router hooks. */
export default function RegionContent({ region, locale }: { region: RegionId; locale: FreightLocale }) {
  const data = regions[region];
  const prefix = freightPrefix(locale);
  const t = (zh: string, en: string, es: string) => words(zh, en, es)[locale];
  const quote = `${prefix}/get-a-quote/?leadGoal=Freight+Export&source=freight_region_${region}&dest=${encodeURIComponent(data.name[locale])}`;
  return <main id="main-content" className="freight-editorial freight-next freight-region-stage">
    <header className="freight-hero"><div className="freight-wrap">
      <nav aria-label={t('面包屑', 'Breadcrumb', 'Ruta de navegación')} className="mb-8 text-sm text-slate-500"><a href={`${prefix}/`}>{t('首页', 'Home', 'Inicio')}</a><span aria-hidden="true"> / </span><a href={`${prefix}/services/sea-freight/`}>{t('货运服务', 'Freight services', 'Servicios de carga')}</a><span aria-hidden="true"> / </span><span aria-current="page">{data.name[locale]}</span></nav>
      <div className="freight-split"><div><p className="freight-kicker">{t('货运目的地', 'Freight destinations', 'Destinos de carga')} / {data.name.en}</p>
        <h1>{t(`从中国，到${data.name.zh}。`, `From China to ${data.name.en}.`, `De China a ${data.name.es}.`)}</h1>
        <p className="freight-intro">{data.intro[locale]}</p>
        <div className="mt-7 flex flex-wrap items-center gap-6"><a className="freight-cta" href="#country-routes">{t('选择目的国', 'Choose your destination', 'Elegir destino')} ↓</a><a href={quote} className="font-bold underline underline-offset-4">{t('提交货运需求', 'Discuss your shipment', 'Consultar un envío')}</a></div>
        <p className="mt-6 text-sm text-slate-500">{t('DDNZ 协调采购与出口衔接 · 国际货运由华正邦泰执行', 'DDNZ coordinates sourcing and export handover · Freight executed by Heaven Born', 'DDNZ coordina compras y entrega para exportación · Transporte ejecutado por Heaven Born')}</p>
      </div><figure><img src="/media/freight-20260918/factory-container.jpg" alt={t('中国端工厂装柜现场', 'Factory container loading at origin', 'Carga de contenedor en fábrica de origen')} width="1290" height="1700" fetchPriority="high" /><figcaption>{t('中国端 · 工厂装柜现场', 'China origin · Factory loading', 'China · Carga en fábrica')}</figcaption></figure></div>
    </div></header>
    <section id="country-routes" className="freight-wrap freight-section"><p className="freight-kicker">01 / {t('按国家查看', 'Country routes', 'Rutas por país')}</p><h2 className="mt-4">{t('同一个地区，不同的交付安排。', 'One region. Different delivery plans.', 'Una región. Distintos planes de entrega.')}</h2>
      <div className="mt-8 border-t border-[#dedde1]">{data.countries.map((country, i) => <a className="freight-country" key={country.slug} href={`${prefix}/shipping-from-china-to-${country.slug}/`}><span className="font-mono text-[#8c7398]">0{i + 1}</span><h3>{country.name[locale]}</h3><p>{country.focus[locale]}</p><span className="freight-arrow" aria-hidden="true">↗</span></a>)}</div>
    </section>
    <section className="freight-region-proof"><figure><img src="/media/freight-20260918/mixed-cargo-loading.jpg" alt={t('中国端混合包装装柜现场', 'Mixed cargo loading at origin in China', 'Carga mixta en origen en China')} loading="lazy" /></figure><div><p className="freight-kicker">FIELD RECORDS / CHINA ORIGIN</p><h2>{t('出海之前，\n先看柜子里面。', 'Before it sails,\nlook inside.', 'Antes de zarpar,\nmira dentro.')}</h2><p>{t('收货核标、纸箱入柜、不同包装的装载细节。查看中国端现场视频和装载模拟，了解一票货出运前要确认什么。', 'Receiving checks, carton loading and mixed packaging. Watch origin operations and explore loading plans before arranging your shipment.', 'Recepción, carga y embalajes mixtos. Ver operaciones en China y planes de carga antes de organizar el envío.')}</p><a href={`${prefix}/services/sea-freight/#loading-proof-title`}>{t('查看装柜视频与配载记录', 'Watch loading and planning records', 'Ver carga y planificación')} ↗</a></div></section>
    <section className="bg-[#f2eff4]"><div className="freight-wrap freight-section"><p className="freight-kicker">02 / {t('运输方案', 'Shipment planning', 'Planificación')}</p><h2 className="mt-4">{t('比较报价前，先对齐这三件事。', 'Align three things before comparing quotes.', 'Acordar tres puntos antes de comparar precios.')}</h2><div className="freight-steps">
      {[
        [t('货物与包装', 'Cargo and packaging', 'Carga y embalaje'), t('品名、件数、尺寸、毛重、包装照片与货好时间。多家供应商的货，需要分别列出提货地点。', 'Product, package count, dimensions, gross weight, packing photos and ready date. List pickup locations for each supplier.', 'Producto, bultos, medidas, peso bruto, fotos y fecha disponible. Indicar recogida para cada proveedor.')],
        [t('进口与交付分工', 'Import and delivery responsibilities', 'Responsabilidades de importación y entrega'), t('确认进口主体、文件提供方和最终收货地址。到港、到仓、到门分别说明，不默认包含所有费用。', 'Confirm the importer, document owner and final address. Define port, warehouse or door scope without assuming all charges are included.', 'Confirmar importador, responsable documental y dirección final. Definir puerto, almacén o domicilio y gastos incluidos.')],
        [t('时效的起点与终点', 'Start and end of the transit estimate', 'Inicio y fin del plazo estimado'), t('船期、海上运输和门到门时效不是一个概念。核对是否包含集货、清关、提货与末端配送。', 'A sailing schedule, port-to-port transit and door-to-door timing are different. Check consolidation, clearance, collection and delivery.', 'Itinerario marítimo y plazo puerta a puerta no son lo mismo. Revisar consolidación, despacho, retiro y reparto.')],
      ].map(([title, body]) => <article key={title}><h3>{title}</h3><p>{body}</p></article>)}
      </div></div></section>
    <section className="freight-wrap freight-section"><div className="freight-split"><div><p className="freight-kicker">03 / {t('从中国端开始', 'Start at origin', 'Empezar en origen')}</p><h2 className="mt-4">{t('先把货物交接清楚，\n再衔接国际运输。', 'Reconcile the cargo before it moves.', 'Conciliar la carga antes de transportarla.')}</h2><p className="freight-intro mt-5">{t('多个供应商、不同包装、分批到仓。把点数、核标、包装要求和装柜安排逐项确认，减少出运时来回补信息。', 'Multiple suppliers, different packaging and staggered arrivals: confirm counts, labels, packing requirements and loading arrangements before dispatch.', 'Varios proveedores, embalajes distintos y llegadas por lotes: confirmar cantidades, etiquetas y carga antes de salir.')}</p><div className="freight-links"><a href={`${prefix}/sourcing-services/consolidation-export/#receiving-record`}>{t('收货与集货记录', 'Receiving and consolidation', 'Recepción y consolidación')} →</a><a href={`${prefix}/services/sea-freight/#loading-proof-title`}>{t('查看装柜现场', 'Loading records', 'Registros de carga')} →</a></div></div><div className="border-l-2 border-[#b99bc7] pl-7"><h3>{t('询价不需要先填一张完美的表。', 'Start with the details you have.', 'Empieza con la información disponible.')}</h3><p className="mt-4 text-slate-600">{t('先发货物清单、供应商所在地和目的地。缺哪些信息，我们再逐项确认。', 'Send your cargo list, supplier locations and destination. We can identify the missing details together.', 'Envía la lista de carga, ubicaciones de proveedores y destino. Revisaremos lo que falta.')}</p><a href={quote} className="freight-cta mt-6">{t('讨论这票货', 'Discuss this shipment', 'Consultar este envío')}</a></div></div></section>
    {region === 'middle-east' && <section className="freight-wrap freight-section"><p className="freight-kicker">UAE / {t('目的地现场', 'AT DESTINATION', 'EN DESTINO')}</p><h2 className="mt-4">{t('阿联酋拆柜之后，怎么交接？', 'What happens after unloading in the UAE?', '¿Qué ocurre después de descargar en EAU?')}</h2><div className="freight-links"><a href={`${prefix}/shipping-from-china-to-uae/`}>{t('查看现场视频与交付安排', 'See the footage and delivery scope', 'Ver video y alcance de entrega')} ↗</a></div></section>}
  </main>;
}
