import { words, type FreightLocale } from './regions';

/** Buyer questions shared by sourcing and freight, without promising unconfirmed services. */
export default function ShipmentPreparation({ locale, consolidation = false }: { locale: FreightLocale; consolidation?: boolean }) {
  const t = (zh: string, en: string, es: string) => words(zh, en, es)[locale];
  const items = consolidation ? [
    [t('有一家工厂还没交货，要等吗？', 'One supplier is late. Wait or split the shipment?', '¿Esperar al proveedor que falta o dividir el envío?'), t('把每家供应商的预计到货日列出来，再比较等齐与分批出运的费用和交期。确认仓储从哪天计费、是否有免费期，以及谁来批准分批；不要只按最早完工的一家订出运时间。', 'List each supplier’s expected arrival date, then compare the cost and timing of waiting versus separate shipments. Confirm when storage charges start, whether a free period applies and who approves a split before booking.', 'Anota la llegada prevista de cada proveedor y compara costos y plazos de esperar o dividir el envío. Confirma desde cuándo se cobra almacenaje, si hay días libres y quién autoriza la salida parcial antes de reservar.')],
    [t('打托以后，还按原来的立方数报价吗？', 'Will palletizing change the quoted volume?', '¿Paletizar cambia el volumen cotizado?'), t('先提供原箱尺寸、重量和能否堆叠。需要打托或重包装时，分别确认操作费，再用包装完成后的外尺寸和毛重复核运输报价。', 'Provide carton dimensions, weight and stacking limits. If palletizing or repacking is needed, agree handling charges separately and recheck the freight quote using the finished package dimensions and gross weight.', 'Facilita medidas, peso y límites de apilamiento. Si hace falta paletizar o reembalar, acuerda los cargos de manipulación y revisa la cotización con las medidas exteriores y el peso bruto finales.')],
    [t('怎么确认这次究竟发哪些货？', 'How do we agree what goes in this shipment?', '¿Cómo confirmar qué mercancía sale?'), t('按供应商核对到货箱号、件数与包装情况，将未到、短少或待检查的货单列。发运前确认本票清单；需要照片、打托清单或交给指定货代时，提前说明要求。', 'Reconcile carton marks, counts and packing by supplier, with missing cargo or pending checks listed separately. Approve the shipment list before dispatch and specify any photo, pallet-list or nominated-forwarder requirements in advance.', 'Revisa marcas, bultos y embalaje por proveedor; separa faltantes y revisiones pendientes. Confirma la lista antes de salir e indica con antelación si necesitas fotos, lista de palés o entrega a un transitario designado.')],
  ] : [
    [t('收货现场没有叉车，怎么办？', 'No forklift at the receiving address?', '¿No hay montacargas en destino?'), t('询价时说明是仓库、门店、住宅还是工地，有没有月台、叉车及车辆通行限制。尾板、卸货人员、预约和等待时间需提前确认，不要默认“到门”已经包含搬入室内。', 'Tell us whether delivery is to a warehouse, shop, residence or jobsite, with dock access, equipment and vehicle restrictions. Confirm liftgate needs, unloading labour, appointments and waiting time; door delivery does not by itself define indoor placement.', 'Indica si la entrega es en almacén, tienda, vivienda u obra, con acceso, muelle y equipos disponibles. Confirma plataforma elevadora, personal de descarga, cita y espera; la entrega a domicilio no define por sí sola la colocación en el interior.')],
    [t('自己去仓库提货，先确认什么？', 'What should I check before collecting cargo?', '¿Qué confirmar antes de recoger la carga?'), t('确认提货地址、放货通知、预约要求和收费项目，再核对包装后的尺寸重量、车辆容量及装车方式。将自提的车辆、人工与时间成本一起算入比较。', 'Confirm the collection address, release notice, appointment requirements and charges. Check final dimensions, weight, vehicle capacity and loading arrangements, including your own vehicle, labour and time in the comparison.', 'Confirma dirección, aviso de liberación, cita y cargos. Revisa medidas y peso finales, capacidad del vehículo y forma de carga; incluye vehículo, personal y tiempo propios al comparar opciones.')],
  ];
  return <section className="mx-auto max-w-7xl px-6 py-16" aria-label={t('出运前确认', 'Before booking', 'Antes de reservar')}>
    {consolidation && <div className="mb-14" id="consolidation-cost-comparison">
      <h2 className="mb-6 text-3xl font-bold">{t('合在一起发，究竟省在哪？', 'Where can consolidation save costs?', '¿Dónde puede ahorrar la consolidación?')}</h2>
      <p className="mb-6 max-w-4xl leading-8">{t('请货代按同一批货、同一个交付地址分别报价。把下面三项放进比较，不用单一海运单价判断哪种更便宜。', 'Request both options for the same cargo and delivery address. Compare these three items rather than a single ocean rate.', 'Solicita ambas opciones para la misma carga y dirección. Compara estos tres puntos, no solo la tarifa marítima.')}</p>
      <dl className="divide-y border-y border-slate-300">{[
        [t('每票最低收费', 'Minimum charges per shipment', 'Cargos mínimos por envío'), t('分开发：核对每票起运地及目的地最低收费。集中发：核对收货、合单与再次装卸是否另收费。', 'Separate: check origin and destination minimums for each shipment. Consolidated: check receiving, consolidation and extra handling charges.', 'Por separado: revisa mínimos en origen y destino por envío. Consolidado: revisa recepción, consolidación y manipulación adicional.')],
        [t('等待与仓储', 'Waiting and storage', 'Espera y almacenaje'), t('确认免费期从每批到仓还是整票到齐开始计算。让供应商按预约送货，再比较等齐与分批的仓储和交期。', 'Confirm whether free storage starts at each receipt or after all cargo arrives. Schedule supplier deliveries and compare storage and timing for waiting versus splitting.', 'Confirma si el plazo libre empieza con cada recepción o con toda la carga. Programa entregas y compara almacenaje y plazos al esperar o dividir.')],
        [t('最终计费货量', 'Final billable cargo', 'Carga facturable final'), t('打托前的体积不能代替打托后尺寸。把包装操作费、完成后的件重尺，以及目的地拆箱和提货费用一起复核。', 'Pre-pallet volume is not a substitute for finished dimensions. Review packing charges, final counts, weights and dimensions, plus destination deconsolidation and collection charges.', 'El volumen previo no sustituye las medidas paletizadas. Revisa embalaje, bultos, pesos y medidas finales, más desconsolidación y recogida en destino.')],
      ].map(([title, body]) => <div key={title} className="py-6 md:grid md:grid-cols-[14rem_1fr] md:gap-8"><dt className="text-xl font-bold">{title}</dt><dd className="mt-3 leading-8 md:mt-0">{body}</dd></div>)}</dl>
    </div>}
    <h2 className="mb-8 text-3xl font-bold">{consolidation ? t('几家工厂的货，先把这三件事说清。', 'Several suppliers. Three decisions before dispatch.', 'Varios proveedores: tres decisiones antes de salir.') : t('报到门之前，先看怎么收货。', 'Before a door quote, check the receiving setup.', 'Antes de cotizar a domicilio, revisa la recepción.')}</h2>
    <div className="divide-y divide-slate-200">{items.map(([title, body]) => <details key={title} className="py-5"><summary className="cursor-pointer text-lg font-semibold">{title}</summary><p className="mt-4 max-w-4xl leading-8">{body}</p></details>)}</div>
  </section>;
}
