import { freightPrefix, words, type FreightLocale } from './regions';

export function uaeMetadata(locale: FreightLocale) {
  return {
    title: words('中国到阿联酋货运｜海运、拆柜与交付安排 | DDNZ Global', 'Shipping from China to UAE | Sea Freight & Delivery | DDNZ Global', 'Envíos de China a EAU | Transporte y entrega | DDNZ Global')[locale],
    desc: words('根据收货城市、货物包装与交付范围安排中国到阿联酋货运。查看阿联酋拆柜实拍，确认整柜拼箱、目的地费用与收货准备。', 'Plan China–UAE freight around cargo, receiving location and delivery scope. See unloading footage and clarify FCL, LCL and destination arrangements.', 'Planificar envíos China–EAU según carga, ubicación y alcance. Ver la descarga y confirmar FCL, LCL y entrega en destino.')[locale],
    keywords: 'China UAE freight,FCL,LCL,shipping to UAE',
  };
}

export default function UaeContent({locale}: {locale: FreightLocale}) {
  const t = (zh: string, en: string, es: string) => words(zh,en,es)[locale];
  const prefix = freightPrefix(locale);
  const quote = `${prefix}/get-a-quote/?leadGoal=Freight+Export&source=uae_country&dest=UAE`;
  const steps = [
    [t('到港', 'Arrival', 'Llegada'), t('确认船期、到港通知与提货联系人。', 'Confirm the schedule, arrival notice and collection contact.', 'Confirmar itinerario, aviso de llegada y contacto.')],
    [t('拆柜', 'Unloading', 'Descarga'), t('明确拆柜地点、件数核对与异常记录。', 'Agree the unloading point, count checks and discrepancy records.', 'Acordar lugar de descarga, recuento y registro de diferencias.')],
    [t('转运', 'Transfer', 'Traslado'), t('根据货物尺寸与收货条件确认车辆和装卸。', 'Match vehicles and handling to cargo dimensions and receiving conditions.', 'Ajustar vehículo y manipulación a medidas y condiciones de recepción.')],
    [t('交付', 'Delivery', 'Entrega'), t('确认预约、卸货责任及交接记录。', 'Confirm appointments, unloading responsibilities and handover records.', 'Confirmar cita, responsabilidad de descarga y registro de entrega.')],
  ];
  return <main id="main-content" className="freight-editorial freight-next uae-page">
    <header className="freight-cover uae-cover"><div className="freight-cover-copy">
      <a className="uae-back" href={`${prefix}/shipping-from-china-to-middle-east/`}>← {t('中东货运', 'Middle East freight', 'Transporte a Oriente Medio')}</a>
      <p className="freight-kicker">CHINA → UNITED ARAB EMIRATES</p>
      <h1>{t('中国到阿联酋。', 'China to UAE.', 'De China a EAU.')}<br /><em>{t('把到港之后，\n也安排清楚。', 'Plan beyond\nthe port.', 'Planificar más allá\ndel puerto.')}</em></h1>
      <p>{t('货是送到迪拜、阿布扎比，还是其他收货点？整柜或拼箱、到港或到门，先把收货地址和责任范围放进同一份方案。', 'Dubai, Abu Dhabi or another receiving point? Plan full or shared containers around the actual address, with port or door responsibilities clearly defined.', '¿Dubái, Abu Dabi u otro destino? Planificar contenedor completo o consolidado según la dirección y las responsabilidades de entrega.')}</p>
      <div className="freight-cover-actions"><a className="freight-cta" href={quote}>{t('询阿联酋运价', 'Request a UAE quote', 'Cotizar envío a EAU')} ↗</a><a href="#delivery-scope">{t('先看交付范围', 'Compare delivery scope', 'Comparar alcance')} ↓</a></div>
    </div><div className="country-route-board"><p className="freight-kicker">CHINA → UAE</p><h2>{t('从哪里提货，\n送到哪个地址？', 'Where do we collect?\nWhere do you receive?', '¿Dónde recoger?\n¿Dónde entregar?')}</h2><ol>{[t('中国供应商 · 集货与装柜', 'China suppliers · consolidation and loading', 'Proveedores en China · consolidación'),t('海运 · 整柜或拼箱', 'Sea freight · FCL or LCL', 'Transporte marítimo · FCL o LCL'),t('阿联酋 · 到港或到门', 'UAE · port or door', 'EAU · puerto o domicilio')].map((item,i)=><li key={item}><span>0{i+1}</span>{item}</li>)}</ol><a href="#arrival-handover">{t('看阿联酋拆柜卸货现场', 'Watch unloading in the UAE', 'Ver la descarga en EAU')} ↓</a></div></header>
    <nav className="freight-chapters" aria-label={t('本页内容', 'On this page', 'En esta página')}><a href="#delivery-scope">01 / {t('交付范围', 'Delivery scope', 'Alcance')}</a><a href="#uae-routing">02 / {t('收货地点', 'Receiving location', 'Destino')}</a><a href="#arrival-handover">03 / {t('到货衔接', 'Arrival handover', 'Llegada')}</a><a href="#uae-quote">04 / {t('询价准备', 'Quote details', 'Cotización')}</a></nav>
    <section className="freight-wrap freight-section" id="delivery-scope"><div className="freight-section-heading"><p className="freight-kicker">01 / SCOPE BEFORE PRICE</p><h2>{t('同样到阿联酋，\n报价可能不是同一件事。', 'Same country.\nDifferent quotation scopes.', 'Mismo país.\nDistintos alcances.')}</h2><p>{t('比较总价之前，先把提货、起运端操作、海运、目的地处理和派送逐项对齐。', 'Before comparing totals, align pickup, origin handling, sea freight, destination handling and delivery.', 'Antes de comparar totales, aclarar recogida, gestión en origen, transporte y entrega.')}</p></div>
      <div className="uae-scope-list">{[
        [t('到港', 'To port', 'Hasta puerto'), t('谁接目的地这一段？', 'Who handles the destination leg?', '¿Quién gestiona el destino?'), t('确认目的港费用、文件交接、清关与提货责任。报价中写明已包含和由收货方承担的项目。', 'Clarify destination charges, document handover, clearance and collection responsibilities. State included and consignee-paid items.', 'Aclarar gastos, documentos, despacho y recogida. Separar lo incluido de lo pagado por el receptor.')],
        [t('到仓／到门', 'To warehouse / door', 'Hasta almacén / domicilio'), t('地址之外，还要看收货条件。', 'An address is only the start.', 'La dirección es solo el inicio.'), t('提供完整地址、联系人、预约要求，以及是否具备叉车或卸货平台。卸货、等待和特殊车辆需求单独确认。', 'Share the full address, contact, appointment requirements and forklift or dock availability. Clarify unloading, waiting and special vehicles.', 'Facilitar dirección, contacto, cita y disponibilidad de carretilla o muelle. Acordar descarga, espera y vehículos especiales.')],
        [t('多供应商集货', 'Multiple suppliers', 'Varios proveedores'), t('先齐货，再决定哪一票走。', 'Reconcile the cargo before dispatch.', 'Conciliar la carga antes de salir.'), t('分开列出供应商地点、货好时间、件数和包装。对未齐货、重包装及额外检查安排单独确认。', 'List locations, ready dates, counts and packaging by supplier. Agree incomplete orders, repacking and inspection separately.', 'Listar ubicación, fechas, cantidades y embalaje por proveedor. Acordar faltantes, reembalaje e inspección.')],
      ].map(([label,title,body]) => <article key={label}><span>{label}</span><div><h3>{title}</h3><p>{body}</p></div></article>)}</div>
    </section>
    <section className="freight-dark" id="uae-routing"><div className="freight-wrap freight-section"><p className="freight-kicker">02 / START WITH THE ADDRESS</p><h2>{t('港口是节点。\n收货地址才是终点。', 'The port is a waypoint.\nWhere does the cargo need to go?', 'El puerto es una etapa.\n¿Dónde debe llegar la carga?')}</h2><div className="uae-route-grid"><article><h3>Dubai / Jebel Ali</h3><p>{t('目的地在迪拜？把实际收货地址、到港后的交付安排与杰贝阿里港方案一起讨论。', 'Receiving in Dubai? Discuss the actual address and onward delivery alongside a Jebel Ali routing option.', '¿Recepción en Dubái? Revisar dirección y entrega posterior junto con la opción de Jebel Ali.')}</p><a href="https://www.dpworld.com/en/ports-terminals/uae/jebel-ali-port" target="_blank" rel="noreferrer">{t('杰贝阿里港官方资料', 'Jebel Ali port information', 'Información oficial de Jebel Ali')} ↗</a></article><article><h3>Abu Dhabi / Khalifa</h3><p>{t('目的地在阿布扎比？将哈利法港作为讨论入口，结合可用船期、目的地操作和最终地址确认路线。', 'Receiving in Abu Dhabi? Discuss Khalifa Port alongside available sailings, destination handling and the final address.', '¿Recepción en Abu Dabi? Revisar Khalifa Port, itinerarios disponibles, gestión en destino y dirección final.')}</p><a href="https://www.adports.ae/" target="_blank" rel="noreferrer">{t('阿布扎比港口官方资料', 'Abu Dhabi Ports information', 'Información oficial de Abu Dhabi Ports')} ↗</a></article></div><p className="uae-routing-note">{t('其他城市、自由区收货或后续转运，请在询价时说明地址和用途，再确认路线与执行范围。', 'For other cities, free-zone receiving or onward transfer, share the address and purpose so routing and responsibilities can be confirmed.', 'Para otras ciudades, zonas francas o traslado posterior, indicar dirección y finalidad para confirmar ruta y alcance.')}</p></div></section>
    <section className="freight-wrap freight-section" id="arrival-handover"><p className="freight-kicker">03 / ARRIVAL TO HANDOVER</p><h2>{t('拆柜之后，\n还有这些事要对上。', 'After unloading,\nkeep the handover clear.', 'Tras descargar,\naclarar la entrega.')}</h2><ol className="uae-handover">{steps.map(([title,body],i)=><li key={title}><span>0{i+1}</span><h3>{title}</h3><p>{body}</p></li>)}</ol>
      <figure className="uae-arrival-film" id="destination-records"><div className="freight-film-top"><span>{t('阿联酋 · 拆柜卸货现场', 'UAE · Container unloading', 'EAU · Descarga del contenedor')}</span><span>00:43</span></div><video controls playsInline muted preload="none" poster="/media/freight-additions-20260918/uae.jpg" src="/media/freight-additions-20260918/uae.mp4" aria-label={t('阿联酋拆柜卸货视频', 'UAE container unloading video', 'Descarga del contenedor en EAU')} /><figcaption>{t('阿联酋拆柜卸货实拍。', 'Container unloading in the UAE.', 'Descarga del contenedor en EAU.')}</figcaption></figure>
      <div className="country-field-feature"><div><p className="freight-kicker">KITCHEN EQUIPMENT / UAE</p><h3>{t('餐厨设备，拆柜入仓。','Kitchen equipment, unloaded into storage.','Equipos de cocina: descarga y almacenaje.')}</h3><p>{t('从柜内卸货，到包装设备入仓，查看这一批餐厨设备的现场作业。','Follow the handling of this kitchen equipment shipment, from the container to warehouse storage.','Ver la manipulación de este envío de equipos de cocina, del contenedor al almacén.')}</p></div><figure><video controls playsInline muted preload="none" src="/media/freight-20260919/uae-kitchen-unloading.mp4" poster="/media/freight-20260919/uae-kitchen-unloading.jpg" aria-label={t('阿联酋餐厨设备拆柜入仓','Kitchen equipment unloading in the UAE','Descarga de equipos de cocina en EAU')}/><figcaption>{t('阿联酋 · 餐厨设备拆柜入仓','UAE · Kitchen equipment unloading','EAU · Descarga de equipos de cocina')}</figcaption></figure></div>
    </section>
    <section className="freight-destination-band" id="uae-quote"><div className="freight-wrap freight-section"><p className="freight-kicker">04 / BRING THE CARGO DETAILS</p><h2>{t('先发这些，\n就能开始讨论。', 'Start with\nthese details.', 'Empezar con\nestos datos.')}</h2><ul className="uae-brief"><li>{t('品名、用途、包装照片', 'Product, intended use and packing photos', 'Producto, uso y fotos del embalaje')}</li><li>{t('件数、单件尺寸、毛重', 'Package count, dimensions and gross weight', 'Bultos, medidas y peso bruto')}</li><li>{t('供应商地点、货好时间', 'Supplier locations and cargo-ready dates', 'Proveedores y fechas de disponibilidad')}</li><li>{t('阿联酋收货地址、进口及收货联系人', 'UAE receiving address, importer and receiving contact', 'Dirección en EAU, importador y contacto')}</li><li>{t('到港还是到门、期望收货时间', 'Port or door scope and target receiving date', 'Puerto o domicilio y fecha deseada')}</li></ul><a className="freight-cta" href={quote}>{t('提交阿联酋货运需求', 'Send your UAE freight inquiry', 'Consultar envío a EAU')} ↗</a><div className="freight-links"><a href={`${prefix}/services/sea-freight/`}>{t('查看中国端装柜与海运', 'Origin loading and sea freight', 'Carga en origen y transporte marítimo')} →</a><a href={`${prefix}/services/dangerous-goods-shipping-from-china/`}>{t('危险品与锂电池专项运输', 'Dangerous goods and lithium cargo', 'Mercancías peligrosas y litio')} →</a></div></div></section>
  </main>;
}
